Set derivative extrapolation to zero
scipy/scipy pull request #10220
Opened 2019-05-26 12:44 UTC by Bharat123rox

Resolve #10195 by setting the extrapolation of the derivative to zero instead of `const` in `fitpack2.py`

2019-05-26 17:58 UTC, ev-br requested changes
Also needs a test, which can be adapted from the original bug report.

2019-05-26 17:58 UTC, ev-br commented on scipy/interpolate/fitpack2.py
> +        return UnivariateSpline._from_tck(tck, ext=0)
This is not right. First, `ext=0` means "extrapolate", not "zeros". Second, the extrapolation mode should be set to `zeros` if and only if the original extrapolation mode was `const`.

2019-05-27 04:13 UTC, Bharat123rox commented
@ev-br where should I add tests for this? In `test_fitpack2.py` or `test_fitpack.py`? Also, since arguments are evaluated from `splder()` and then changed, I'm still unclear on which method this test should be added.

2019-05-27 07:17 UTC, ev-br commented
test_fitpack2::TestUnivariateSpline looks like a right place for this test. Please also mention it's a regression test for gh-10195 in a comment

2019-06-15 17:15 UTC, ev-br commented
Superseded by https://github.com/scipy/scipy/pull/10310

2019-06-18 17:07 UTC, closed without merging