scipy.spatial enhancement request
scipy/scipy pull request #10314
Opened 2019-06-16 19:05 UTC by rtshort

I would like to add an element to the qhull interface - I would like the class to keep track of whether Voronoi diagrams and Delaunay triangulations were created as nearest site or furthest site diagrams.

Some of my applications are getting fairly large, and it is cumbersome and error-prone to pass the furthest_site argument around.  As an example, I modified voronoi_plot_2d to do furthest site plots as well as the default nearest site diagrams.  Since my plotting routines are in a different module, it was much simpler to have the plotting routine get the information directly from the Voronoi class.

2019-06-18 17:00 UTC, pv requested changes
The change itself looks ok, but there are some small things to correct.

2019-06-19 12:22 UTC, rtshort commented on scipy/spatial/tests/test_qhull.py
> +        assert_equal(vor.furthest_site==False)
Ok.  I think I got all these.

2019-06-19 16:18 UTC, pv commented on scipy/spatial/qhull.pyx
> +        .. versionadded:: x.y.z
It should also read `versionadded:: 1.4.0` not `x.y.z`

2019-06-20 12:15 UTC, rtshort commented on scipy/spatial/qhull.pyx
> +        .. versionadded:: x.y.z
Done.  Thanks.

2019-06-20 18:31 UTC, merged