[DOC] Add an example for _binned_statistic_dd
scipy/scipy pull request #10392
Opened 2019-07-04 11:01 UTC by makbigc

- follow up #10113

2019-07-05 16:52 UTC, tylerjereddy commented on scipy/stats/_binned_statistic.py
> +    >>> import numpy as np
If I'm not mistaken, I think our documentation testing machinery will automatically provide `np`, so we don't need this.

2019-07-10 14:19 UTC, makbigc commented
@tylerjereddy Anything else to implement? Please tell me.

2019-07-10 17:15 UTC, tylerjereddy reviewed
Made a few more minor suggestions. The new docstring example [looks quite nice in the CI render](https://13836-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.stats.binned_statistic_dd.html#scipy.stats.binned_statistic_dd).

Would be good if a resident stats expert takes a quick look (it is not really my domain).

2019-07-10 17:15 UTC, tylerjereddy commented on scipy/stats/_binned_statistic.py
> +    Create bins and count how many arrays falls in each bin:
`falls` -> `fall`, I think

2019-07-10 17:15 UTC, tylerjereddy commented on scipy/stats/_binned_statistic.py
> +    Set the volumn and the location of bars:
Should `volumn` be `volume`?

2019-07-14 14:51 UTC, rgommers requested changes
Thanks @makbigc, nice example. A few minor comments, if you can address those then I'll merge this PR.

2019-07-14 14:51 UTC, rgommers commented on scipy/stats/_binned_statistic.py
> +    >>> Sigma = np.array([[1., -0.5],[-0.5, 1.5]])
minor: could you use lowercase variable names? `N` is fine, but `sigma`, `x`, `y` would be nice. And `F` --> `multinormal` (or similar, a bit more descriptive).

2019-07-14 14:51 UTC, rgommers commented on scipy/stats/_binned_statistic.py
> +    Take 600 2-D arrays as an example. `binned_statistic_dd` can handle arrays
This is phrased a bit unusually. The shape here is `(600, 2)`, which would be good to show at the end:
```
>>> data.shape
(600, 2)
```
And for phrasing maybe _"Take an array of 600 (x, y) coordinates as an example"_?

2019-07-14 14:51 UTC, rgommers commented on scipy/stats/_binned_statistic.py
> +    >>> dz = ret.statistic
I'd call `dz` something like "bincounts" for clarity.

2019-07-16 16:00 UTC, makbigc commented
@rgommers  Amended. Please tell me if you have anything else to implement.

2019-07-16 21:52 UTC, rgommers approved these changes

2019-07-16 21:53 UTC, merged

2019-07-16 21:56 UTC, rgommers commented
Merged, thanks @makbigc!  

> Please tell me if you have anything else to implement.

there's lots, happy to get more of your help:) for example, this issue is similar: https://github.com/scipy/scipy/issues/9947