BUG: Allow integer input data in scipy.stats.yeojohnson
scipy/scipy pull request #10435
Opened 2019-07-10 07:04 UTC by johannfaouzi

Fixes #10421 

This small PR allows the use of integer data for [scipy.stats.yeojohnson](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.yeojohnson.html): the input data is converted into `np.float64` dtype. I am not very knowledgeable about memory use, so it might not be ideal for extremely large arrays, but I think that it can be expected to have the data converted into float type when doing this kind of transformation.

A small test is added in the YeoJohnson class.

2019-07-24 03:03 UTC, tylerjereddy reviewed
Looks sensible at first glance -- if this wasn't intended behavior then there should be documentation specifying the type limitation.

I think if you rebase on the latest master branch the CI failure will go away since we removed pypy3 from our CI--it was too much of a maintenance burden.

I see that no resident stats expert has commented either on the cognate issue or here--would be good if they did briefly.

2019-07-24 03:07 UTC, tylerjereddy commented on scipy/stats/morestats.py
> +    x = np.asarray(x, dtype=np.float64)
As you note in the issue, some consideration for passing through smaller dtypes might be warranted. Would people typically call this function with a smaller float type and expect the return to be of the same type? The promotion logic for doing that and supporting integers might be a little messy maybe.

2019-07-25 07:26 UTC, johannfaouzi commented
I don't really have a preference regarding the solution (converting the data to float type, possibly with a warning, versus raising an error), but the current behavior could be improved (the error message is not very clear).

Do you think that adding something like this would be better?
```python
if np.issubdtype(x.dtype, np.integer):
    raise ValueError("Yeo-Johnson transformation cannot be performed on integers. "
                     "Convert your data type to float.)
```

2019-07-25 08:02 UTC, johannfaouzi commented
Currently the transformation works for complex numbers, which may not be the expected behavior. The following code might be more appropriate: 

```python
if not np.issubdtype(x.dtype, np.floating):
    raise ValueError("Yeo-Johnson transformation must be performed on floats. "
                     "Convert your data type to float.)
```

2019-07-27 13:52 UTC, rlucas7 commented
>I see that no resident stats expert has commented either on the cognate issue or here--would be good if they did briefly.

Not sure if I qualify as resident or a stats expert and I'll comment regardless. 

I agree with @tylerjereddy that we want to be careful with not accidentally promoting to float64 if the input was a float32 (for example). Probably want some kind of logic for that in the PR even though it *might* be messy. Overarching goal should be to maintain the types that are inputs unless they cause errors. 

On the complex number comment of @johannfaouzi 

>Currently the transformation works for complex numbers, which may not be the expected behavior.

I'm not sure if there are tests for `yeojohnson` gradients in the testing suite, do all unit tests pass if you add in the lines you suggest? 

There are routines in the unit tests which use complex numbers where applicable to get gradients. For example see the function here:

https://github.com/scipy/scipy/blob/8dba340293fe20e62e173bdf2c10ae208286692f/scipy/optimize/_numdiff.py#L204

I agree that the yeojohnson was likely intended primarily for real valued inputs but if there are cases where a gradient is needed it might be better to leave the capability in the function. Unless of course, you have found some undesirable behavior or results for complex invalued inputs.

2019-07-29 12:52 UTC, johannfaouzi commented
The current implementation of the Yeo-Johnson log-likelihood works for real-valued and complex numbers:
https://github.com/scipy/scipy/blob/e1e44d12637997606b1bcc0c6de232349e11eee0/scipy/stats/morestats.py#L1463-L1466

The log-likelihood is always a real-valued number (it might be a complex with a null imaginary part when the input array consists of complex numbers), and the Brent optimization works. Looking briefly at the Wikipedia page, it seems to be a gradient-free optimization algorithm.

Given the implementation of the log-likelihood function, the imaginary parts have an impact on the transformation:
```python
>>> import numpy as np
>>> from scipy.stats import yeojohnson
>>> x = np.arange(10)
>>> yeojohnson(x + 1j)

(array([0.03287148+0.98935685j, 0.98844173+0.94568291j,
        1.91584736+0.91855106j, 2.82231669+0.89925149j,
        3.71267304+0.88439277j, 4.59007808+0.87236522j,
        5.45671414+0.86229017j, 6.31416326+0.85363873j,
        7.163619  +0.84606906j, 8.00601107+0.83934805j]),
 (0.9240010903270425+0j))
```

```python
>>> yeojohnson(x.astype(float))

(array([0.        , 0.89952677, 1.67649209, 2.38322961, 3.04195185,
        3.66477639, 4.25925107, 4.83048762, 5.38215489, 5.91700119]),
 0.7219640406219725)
```
I can't comment on the expected results here (and I'm definitively not a stats expert).

I am going to try to raise a ValueError if the input data type is not float and see how the tests react.

2019-07-29 14:32 UTC, johannfaouzi commented
I don't understand why only one check failed. If someone can shed some light on this issue for me, it would be appreciated.

When the final solution will be accepted (not necessarily the current version obviously), I think that it could be applied to all the functions related to the Yeo-Johnson transformation:
* [scipy.stats.yeojohnson](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.yeojohnson.html)
* [scipy.stats.yeojohnson_llf](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.yeojohnson_llf.html)
* [scipy.stats.yeojohnson_normmax](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.yeojohnson_normmax.html)
* [scipy.stats.yeojohnson_normplot](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.yeojohnson_normplot.html)
* [scipy.stats._yeojohnson_transform](https://github.com/scipy/scipy/blob/e1e44d12637997606b1bcc0c6de232349e11eee0/scipy/stats/morestats.py#L1353-L1372)

2019-07-30 19:08 UTC, rlucas7 requested changes
Left a comment about the complex number type and raising an error. I don't think we want to raise an error or exception in that case. Instead you could write a unit test that confirms the gradients from passing a complex number if you want.

2019-07-30 19:08 UTC, rlucas7 commented on scipy/stats/morestats.py
> +    if not np.issubdtype(x.dtype, np.floating):
There are methods used in scipy where gradients are calculated from complex inputs. If you'd like to instead write a unit test that confirms those values that would be helpful. I don't think it is necessary to restrict to only float types here.

2019-11-12 05:18 UTC, rgommers commented
I don't think raising an error for integer input is correct. The transformation is well-defined for any real number, so users will expect it to work. The reason it's broken now:
```
~/Code/scipy/scipy/stats/morestats.py in _yeojohnson_transform(x, lmbda)

-> 1370         out[pos] = (np.power(x[pos] + 1, lmbda) - 1) / lmbda

ValueError: Integers to negative integer powers are not allowed.
```
is just due to an implementation detail and a missing test. 

You already have the check for if the input is an integer array. If so, just cast to `float64`. Then we can merge this. 

`complex` input on the other hand may raise an error I'd say, since we don't know what the right answer is.

2019-11-12 11:00 UTC, johannfaouzi commented
I made the following changes:
* An error is raised if data type is complex;
* Data type is converted to `float64` if it is integer.

I added small tests for both additions.

The failing test is a crashed worker (I don't know if running it over is worth it).

2019-11-12 22:33 UTC, merged

2019-11-12 22:34 UTC, rgommers commented
LGTM now, merged. Thanks @johannfaouzi