MAINT: signal: malloc fail check
scipy/scipy pull request #10451
Opened 2019-07-12 16:52 UTC by clementkng

Added malloc checks for unchecked malloc calls in `sigtoolsmodule.c`

2019-07-12 23:45 UTC, peterbell10 reviewed
You will also have to edit the code after the `fail:` label since it doesn't `free` the `malloc`ed memory.

2019-07-13 00:19 UTC, clementkng commented
@peterbell10 The easiest way to do that would be to just check each `malloc`ed variable equals `NULL` and if not, then free it right?

2019-07-13 00:55 UTC, peterbell10 commented
>The easiest way to do that would be to just check each malloced variable equals NULL and if not, then free it right?

Yes, except `free(NULL)` is a legal noop so I would just make sure the variables are initialised to NULL at the declaration and unconditionally `free`.

2019-07-14 19:57 UTC, pv requested changes

2019-07-14 19:57 UTC, pv commented on scipy/signal/sigtoolsmodule.c
> +	if (sort_buffer) free(sort_buffer);
The variables need to be explicitly initialized to NULL in the declarations at the beginning.

2019-07-15 09:56 UTC, peterbell10 approved these changes

2019-07-15 09:58 UTC, merged