DOC: special: Add documentation for `beta` function
scipy/scipy pull request #10679
Opened 2019-08-17 20:19 UTC by lhilt

#### Reference issue
None.

#### What does this implement/fix?
Adds a definition, a parameter description, a reference, and some examples of `special.beta` satisfying some known properties. 

#### Additional information
None.

2019-08-18 14:47 UTC, pvanmulbregt requested changes
Thanks for the addition.

2019-08-18 14:47 UTC, pvanmulbregt commented on scipy/special/add_newdocs.py
> +
Suggest adding a "See also:" section referencing betainc, betaln, Gamma.

2019-08-18 17:22 UTC, lhilt commented on scipy/special/add_newdocs.py
> +
Ok, done!

2019-08-20 00:15 UTC, pvanmulbregt approved these changes

2019-08-20 05:47 UTC, merged