DOC: Added examples to maximum_position in ndimage
scipy/scipy pull request #11071
Opened 2019-11-17 00:12 UTC by nwjenkins

#### Reference issue
Example: Partially Closes issue #7168

#### What does this implement/fix?
Added a few examples to maximum_position in ndimage where there were none before

#### Additional information
This is my first pull request, so I am just learning the process. Please let me know if there is anything I should be doing better in the future (or now!). Thanks!

2019-11-17 08:53 UTC, rgommers requested changes
Thanks @nwjenkins, this looks good module two minor comments.

2019-11-17 08:53 UTC, rgommers commented on scipy/ndimage/measurements.py
> +    >>> import numpy as np
this import can be removed, it's implicit in all SciPy examples

2019-11-17 08:53 UTC, rgommers commented on scipy/ndimage/measurements.py
> +    >>> lbl = np.matlib.repmat([0,1,2,3],4,1)
I'd prefer an explicit use of `np.array` here, like a few lines above. Clearer to the reader, and `np.matlib.repmat` is a function that's best avoided.

2019-11-18 01:12 UTC, rgommers commented
One of the CI failures is actually real:
```
scipy.ndimage.maximum_position
------------------------------
File "build/testenv/lib/python3.6/site-packages/scipy/ndimage/measurements.py", line 1225, in maximum_position
Failed example:
    ndimage.maximum_position(a, lbl, 1)
Expected:
    (3, 1)
Got:
    (1, 1)
```
Could you look into that? Perhaps the algorithm is not deterministic with exact duplicates?

2019-11-18 18:33 UTC, nwjenkins commented
I believe I must have made a typo in transcribing the example. It is deterministic for the case of degenerate maxima returning the first of the degenerate maxima.

2019-11-18 20:17 UTC, nwjenkins commented
I see that there is still a CI failure, how am I able to see what this is as you did above?

2019-11-18 20:24 UTC, rgommers commented
> I see that there is still a CI failure, how am I able to see what this is as you did above?

You click on "Details" next to the failed CI run:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/98330/69090978-36906f80-09fe-11ea-8ea8-bba58d8aacda.png">

In this case, it was an unrelated failure on PowerPC, you're all good.

2019-11-18 20:24 UTC, rgommers approved these changes

2019-11-18 20:24 UTC, merged

2019-11-18 20:25 UTC, rgommers commented
Merged, thanks @nwjenkins!

> This is my first pull request, so I am just learning the process. Please let me know if there is anything I should be doing better in the future (or now!). Thanks!

You did it all correctly:)

2019-11-19 13:05 UTC, mdhaber commented
Thanks @nwjenkins. Would you like your name to be added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt)? If so, please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).