correction in error message (%d->%g format)
scipy/scipy pull request #11395
Opened 2020-01-20 22:18 UTC by slayoo

There seem to be no reason to assume that the root-finding interval boundaries are integer-valued

2020-01-21 20:20 UTC, andyfaff requested changes
Thank you @slayoo. Could you change this to:
```
        raise ValueError("a and b are not an interval [{}, {}]".format(a, b))
```
It doesn't matter immensely, but it means we don't have to worry about the numerical types of a and b.

2020-01-21 20:30 UTC, slayoo commented
here you are :)

2020-01-21 20:31 UTC, andyfaff commented
Thank you. I can't wait until we can use f-strings

2020-01-21 21:50 UTC, andyfaff approved these changes

2020-01-21 23:08 UTC, merged

2020-01-21 23:08 UTC, andyfaff commented
Thank you @slayoo. Please feel free to add yourself to THANKS.txt in recognition of your contribution.

2020-01-25 06:51 UTC, mdhaber commented
@slayoo An easy way to add your name to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt) is to make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

2020-01-25 08:12 UTC, slayoo commented
no need, thanks