[WIP] ENH: Add a `plan` argument to FFT functions in `scipy.fft`
scipy/scipy pull request #11408
Opened 2020-01-23 18:39 UTC by leofang

#### Reference issue

Closes #10302.

#### What does this implement/fix?

As discussed, a keyword-only argument `plan` is reserved and added to all FFT functions in `scipy.fft` for possible extensions by 3rd party FFT vendors. DST and DCT functions are not touched, as it seems neither FFTW nor cuFFT supports them.

#### Additional information

I have two questions:
1. Do we want to document this argument given that it's not usable in SciPy itself? If we do, is the following description OK?
```python
'''
plan: object, optional
    This argument is reserved for passing in a precomputed plan provided by downstream
    FFT vendors. It is currently not used in SciPy.
'''
```
2. Do we want to test it? If so, where should I add the test?

Thanks!

cc: @peterbell10 @larsoner @grlee77

2020-01-23 20:01 UTC, larsoner commented
> is the following docstring OK?

Looks good

> Do we want to test it? If so, where should I add the test?

Yes, I would do a:
```
with pytest.raises(ValueError, match='must be None'):
    fft(x, plan='foo')
```
or so. Maybe in https://github.com/scipy/scipy/blob/master/scipy/fft/tests/test_backend.py ?

Also maybe add a smoke test that you can mock a backend that *does* take a `plan` argument and that it does *not* raise.

2020-01-23 20:25 UTC, peterbell10 requested changes
This file is not specific to scipy's FFT backend so your exceptions will be raised by the `cupy` backend as well. Instead you will need to put the `raise` in `_pocketfft`:
https://github.com/scipy/scipy/blob/master/scipy/fft/_pocketfft/basic.py

2020-01-23 20:27 UTC, peterbell10 commented
Also, regarding tests, I test that a backend can accept a `plan` argument in `fft/tests/test_backend.py` but would put the exception test in `fft/_pocketfft/test/test_basic.py` since it is specific to the `_pocketfft` backend.

2020-01-23 21:08 UTC, leofang commented
Thanks, Eric & Peter, for quick feedbacks! One quick questions while I'm figuring out how backends and uarray works: Can I just add a `plan` to `fft/tests/mock_backend.py`, or I should create a separate backend for this purpose?

2020-01-23 21:25 UTC, peterbell10 commented
You should be able to use `MockFunction.last_args` to test for `plan` in the kwargs.

2020-01-24 16:26 UTC, leofang commented
@peterbell10 @larsoner Changes are made with tests added. PTAL, thanks!

Note that I have both the exception and no-raise tests done in the same test class, as it seems to be the easiest thing to do. Peter, please let me know if you still prefer the former to be done in `fft/_pocketfft/test/test_basic.py`.

Also, @grlee77 I would like to have one last confirmation from you that this PR will not interfere with pyFFTW. Thanks 🙂

2020-01-24 16:27 UTC, leofang commented
One more thing: There's one test on Travis that has been failing two days in a row...Is it relevant to this PR?

2020-01-24 17:06 UTC, larsoner commented
No, that is happening on all PRs.

@peterbell10 I'll let you take a look first since you have the clearest picture of what should be needed

2020-01-24 17:13 UTC, peterbell10 approved these changes
LGTM

2020-01-24 17:55 UTC, larsoner reviewed
LGTM other than needing `versionadded` directives

2020-01-24 17:55 UTC, larsoner commented on scipy/fft/_basic.py
> +        by downstream FFT vendors. It is currently not used in SciPy.
```suggestion
        by downstream FFT vendors. It is currently not used in SciPy.

        .. versionadded:: 1.5.0
```

2020-01-24 17:55 UTC, larsoner commented on scipy/fft/_basic.py
> +        by downstream FFT vendors. It is currently not used in SciPy.
```suggestion
        by downstream FFT vendors. It is currently not used in SciPy.

        .. versionadded:: 1.5.0
```

2020-01-24 17:55 UTC, larsoner commented on scipy/fft/_basic.py
> +        by downstream FFT vendors. It is currently not used in SciPy.
etc.

2020-01-24 20:00 UTC, larsoner commented
Thanks @leofang

2020-01-24 20:00 UTC, merged

2020-01-25 06:52 UTC, mdhaber commented
Thanks @leofang! Could you add this contribution to the 1.5.0 [release notes](https://github.com/scipy/scipy/wiki/*Release-note-entries-for-SciPy-1.5.0*)? Also, if you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

2020-01-25 20:38 UTC, leofang commented
@mdhaber Ah, thanks for the instruction. I just edited the two wiki pages.

2020-01-26 03:06 UTC, mdhaber commented
Thanks @leofang. It might help readers if you could give maybe one sentence more detail about the intent of the argument.

2020-01-26 03:46 UTC, leofang commented
@mdhaber I edited it. It looks like the argument's docstring now 😅