Update integrate.quad documentation
scipy/scipy pull request #11469
Opened 2020-02-04 16:50 UTC by caos21

DOC: Updated epsrel and epsabs documentation entries.

#### Reference issue
#11450

#### What does this implement/fix?
Extended documentation for epsrel and epsabs

#### Additional information
Minor correction in an error message: errabs changed to epsabs

2020-02-05 19:08 UTC, rgommers requested changes
Thanks @caos21. I noticed that other functions in this file (e.g. `dblquad`) have the same parameters, so would be good to keep the descriptions in sync.

2020-02-05 19:08 UTC, rgommers commented on scipy/integrate/quadpack.py
> +        an accuracy of `abs(i-result) <= max(epsabs, epsrel*abs(i))`
A note on reST formatting: typesetting as code requires double backticks (single backticks means "create a link to this function/object").

2020-02-05 19:08 UTC, rgommers commented on scipy/integrate/quadpack.py
> +        where `i` = integral of `func` from `a` to `b`, and `result` is the
same here, `i` is code (a/b/func are parameters, there single backticks are fine)

2020-02-05 19:08 UTC, rgommers commented on scipy/integrate/quadpack.py
> +        If `epsabs <=0`, `epsrel` must be greater than both 5e-29
double backticks for `epsabs <=0` (and space after `=`)

2020-02-05 19:08 UTC, rgommers commented on scipy/integrate/quadpack.py
> +        and 50*(machine epsilon). See `epsabs` above.
`50*(machine epsilon)` -> double backticks and spaces around `*`

2020-02-05 19:46 UTC, caos21 commented
@rgommers Thanks for the feedback. I hope this commit fix the typos. Also, I hinted at the `dblquad` documentation. If it is OK, I can propagate the fix to the similar functions.

2020-02-13 06:39 UTC, ev-br commented
Looks like a nice addition, so let's merge it. Further improvements welcome in a next PR. Thanks @caos21, Ralf.

2020-02-13 06:42 UTC, merged

2020-02-15 17:52 UTC, mdhaber commented
Thanks @caos21! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).