FIX: unnecesary IF block in cdfchn.f gives bad results
scipy/scipy pull request #11477
Opened 2020-02-06 20:00 UTC by caos21

- Removed `IF` block `tent4`. The removed `IF` block produces the wrong results.
- Expanded search range for `X` and `DF` (as in `CDFLIB`).

#### Reference issue
#11474 and possibly solves #8665

#### What does this implement/fix?
Fixes at least the calculation of the `skellam.cdf` as described in #11474

#### Additional information
The revised code is virtually identical to the `CDFLIB`.

2020-02-07 08:32 UTC, caos21 commented
`pnonc` is now bounded by `tent9 = 1e9`. 
This is a new attempt to solve #11474 and #8665 without breaking the tests.

2020-02-09 03:01 UTC, tylerjereddy commented
> The revised code is virtually identical to the CDFLIB

Just to clarify: you're saying there's a newer `CDFLIB` implementation somewhere that this code adjustment mimics?

I believe `CDFLIB` is vendored Fortran code, so taking on responsibility for adjusting/maintaining that code may requite a little discussion perhaps?

2020-02-09 07:10 UTC, caos21 commented
- In my first commit I deleted the `IF` block that does not appears in the `CDFLIB` implementation, and I did 3 minor changes. In that way, the two codes are the same.

- These changes broke an unit test. I restore the conditional but I raised the value for the search in `pnonc`. This fix solves the two issues and pass the test.

I agree that it merits its own discussion. I diffed the two dirs of `CDFLIB` (scipy vs NETLIB) and got some differences.

2020-02-12 04:00 UTC, pvanmulbregt commented
The Fortran code in cdfchn.f caps `pnonc` at 10000 and documents the reason as needed to bound the computation.  (This cap also affects gh-9836.)
Computers are faster than they were 20 years ago so raising the limit may be appropriate. What is the change in computation time in the worst case with this PR?

2020-02-12 15:12 UTC, caos21 commented
You are right, I checked it
```
from scipy.stats import rice
print(rice.cdf(np.arange(10, 150, 10), np.arange(10, 150, 10)))

[0.48002781 0.49002332 0.49335004 0.49501283 0.49601038 0.49667537
 0.49715034 0.49750656 0.49778362 0.49800526 0.49818661 0.49833773
 0.4984656  0.4985752 ]
```
In these tests the elapsed time is almost the same. Maybe we need to
consider a time-consuming test.
I see other errors coming from the difference between implementations and restrictions like this.

It is worth noting that the original implementation does not have these lines:
```
      IF (pnonc.GT.tent4) THEN
          pnonc = tent4
      END IF
```
But it has the search truncated to `tent4`. It seems to be a fix, but it will give the wrong
value for `pnonc` if the condition is met. I think the wrapper for this function should raise an error without changing the logic of the `fortran` code, and this should be reflected in the docs also. The fix proposed only change the value of the search.

2020-12-07 23:07 UTC, mdhaber commented
Closes gh-12731
Checking gh-2158, gh-9836, and gh-8665

2020-12-08 02:10 UTC, mdhaber commented
Looking very good. I'll put together a speed test and compare with master.

2020-12-08 04:26 UTC, mdhaber commented
Starting with 1000 percent points from 0.0001 to 0.9999, I used `chndtrix` to compute the quantiles, and then I used `chndtr` to compute the percent points from the quantiles. I measured the execution time and L2 norm of the error (between given and calculated percentile points) for a range of noncentrality parameter values and degrees of freedom.

The execution time of `chndtr` increases with the square root of the noncentrality parameter (dashed blue line) and is nearly independent of the number of degrees of freedom.

![image](https://user-images.githubusercontent.com/6570539/101438686-c9c96b00-38c7-11eb-8aa1-28043d644747.png)

The execution time of `chndtrix` also increases with the square root of the noncentrality parameter (dashed blue line) and is nearly independent of the number of degrees of freedom, too.

![image](https://user-images.githubusercontent.com/6570539/101438750-e9609380-38c7-11eb-931e-69a737f0a05d.png)

There is an interesting relationship between the "round trip error", the noncentrality parameter, and the number of degrees of freedom. I leave interpretation up to the reader.

![image](https://user-images.githubusercontent.com/6570539/101439064-95a27a00-38c8-11eb-8ac8-e2d16f442585.png)

The total computing time was 138 seconds on the PR branch. I'll try again on master and I'll edit this post based on the comparison.

2020-12-08 05:56 UTC, mdhaber commented
Here we go:

![image](https://user-images.githubusercontent.com/6570539/101445100-b9b88800-38d5-11eb-961e-27f48edf0e53.png)

![image](https://user-images.githubusercontent.com/6570539/101445188-e2408200-38d5-11eb-9b5b-0a8ab9a76fad.png)

The extra accuracy is not free, but since:

- the execution time only increases when additional computation is required for accuracy (e.g. for low noncentrality parameter, execution time is the same; only when `master` loses accuracy does `chndtr_fix` start taking more time) and
- the execution time only increases with the square root of the noncentrality parameter,

I think it's worth it. 

Ideally, perhaps these limits would be exposed to the user? But I'd suggest merging this PR as-is

2020-12-08 06:12 UTC, mdhaber commented
@pvanmulbregt Thanks for finding the relationship between this PR and all those issues! I think I've addressed your question about the change in computation time in the plots above, and I've also added tests demonstrating that this PR fixes those issues. I'd appreciate your review when you have a chance!

@caos21 Thanks very much for this PR! It's surprising how much code these constants affect, and it makes me wonder how many other special function issues we can solve like this.

2020-12-08 15:49 UTC, caos21 commented
@mdhaber @pvanmulbregt  Thank you, I am sorry I didn't have the time to dig more and doing the performance tests. At that time, I was looking for everything that broke with this implementation, and I don't remember finding anything else. In any case, I will remain more attentive next time :-)

2020-12-11 12:38 UTC, WarrenWeckesser commented
@mdhaber's investigation and unit tests demonstrate pretty clearly that this is an improvement to the code.  I've spot checked some values with large `nc` using Wolfram Alpha and `mpsci` and confirmed that this PR is a big improvement. For example,

                         CDF
    x          df   nc   Wolfram & mpsci       This PR              SciPy 1.5.2
    1000001    1    1e6  0.5001994710820217    0.5001994709731743   1.000000000003714
    100000001  1    1e8  0.5000199471139619    0.5000198922867907   1.000000000003714
    100000001  1e3  1e8  0.48010103866913795   0.4801009855849495   1.000000000003714

For `chndtrix`, this computes the equivalent of `chndtrix(p, df, nc)` using `mpmath`:
```
import mpmath
from mpsci.distributions import ncx2

mpmath.mp.dps = 90

df = 100
nc = 1e8
p = 0.46875

x = mpmath.findroot(lambda x: ncx2.cdf(x, df, nc) - p, nc)
print(float(x))
```
It prints `99998530.75750586`, and with this PR, `chndtrix(p, df, nc)` returns `99998530.78259979`, while in SciPy 1.5.2 we get `10083.286532476992` (i.e. garbage).

I'll do a line-by-line persnickety code review, but +1 for the fix and for @mdhaber's unit tests.

2020-12-11 12:51 UTC, WarrenWeckesser requested changes
I requested a few small changes in-line.  Otherwise, this looks good.

2020-12-11 12:51 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +
Only one blank line before `def`s in a class.
```suggestion
```

2020-12-11 12:51 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
Ditto.
```suggestion
```

2020-12-11 12:51 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +         # Generated in R
```suggestion
        # Generated in R
```

2020-12-11 12:51 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +    nc = 10**np.arange(5,10)
```suggestion
    nc = 10**np.arange(5, 10)
```

2020-12-11 12:51 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +    assert_allclose(stats.ncx2.cdf(1e4, df=1, nc=nc), 0)
The true values are so small that the only possible correct answer when using 64 bit floating point is 0, so this should be `assert_equal`.
```suggestion
    assert_equal(stats.ncx2.cdf(1e4, df=1, nc=nc), 0)
```

2020-12-13 05:42 UTC, caos21 commented
Love it. thank you @mdhaber

2020-12-13 13:08 UTC, WarrenWeckesser approved these changes
Thanks @caos21 and @mdhaber, looks good.

2020-12-15 21:39 UTC, WarrenWeckesser commented
I'd like to merge the PR this Friday.  Any more comments or questions?  @pv or @person142, what do you think?

2020-12-20 19:38 UTC, merged

2020-12-20 19:39 UTC, WarrenWeckesser commented
Thanks @caos21 and @mdhaber, merged.  Always nice to close a bunch of issues with one PR!