[WIP] DOC: Improve documentation of scipy.signal.signaltools.wiener
scipy/scipy pull request #11499
Opened 2020-02-11 22:59 UTC by grapheo12

#### Reference issue

Closes #11415 

#### What does this implement/fix?

- Docstring of the wiener function has been updated to show the source and equivalent Matlab/Octave function
#### Additional information

TODO: Adding the information to the documentation.

2020-02-11 23:01 UTC, grapheo12 commented
Am I proceeding in the right direction? Or do I need to add something more to the docstring?
Should I proceed with the documentation? @pv @ilayn

2020-02-11 23:31 UTC, ilayn requested changes
Thanks @grapheo12 for taking the time to submit a PR. If you don't mind could you please add some basic examples too while we are at it? I've placed some boilerplate structure in the comments.

2020-02-11 23:31 UTC, ilayn commented on scipy/signal/signaltools.py
>      Apply a Wiener filter to the N-dimensional array `im`.
Put the explanation under this line.

2020-02-11 23:31 UTC, ilayn commented on scipy/signal/signaltools.py
> +    It is similar to wiener2 in Matlab/Octave.
Could make this a bit more expressive via putting it in the Notes section

```
.... some existing text ...

    Returns
    -------
    out : ndarray
        Wiener filtered result with the same shape as `im`.

    Examples
    --------
    ... some examples would be really appreciated see other
        functions in the same file for examples

    Notes
    -----
    This implementation is similar to Matlab/Octave's `wiener2` function. 
    For more details see [1]_

    References
    ------------
    .. [1] Lim, Jae S., Two-Dimensional Signal and Image Processing,
           Englewood Cliffs, NJ, Prentice Hall, 1990, p. 548.

    """
```

2020-02-12 16:16 UTC, grapheo12 commented
@ilayn Please review.

2020-02-13 15:09 UTC, grapheo12 commented
Please suggest what should I do:
I intend to show 2 images side by side using `plt.subplots`. It is working fine in a notebook or from shell. But when the docs are compiled by Sphinx, only one image is shown.

2020-02-13 16:36 UTC, ilayn commented on scipy/signal/signaltools.py
> +    >>> plt.figure()
This creates a figure that you don't use. In the line below you get `f` as the figure anyways so creates a dummy output.

2020-02-13 16:36 UTC, ilayn commented on scipy/signal/signaltools.py
>      >>> from pylab import *
We don't need this line anymore right? That's unnecessary import of the whole namespace

2020-02-13 16:36 UTC, ilayn commented on scipy/signal/signaltools.py
> +    >>> img = np.random.random((40,40))    #Create a random image
We can be a bit more economic here

```python
>>> img = np.random.random((40,40))  # Create a random image
>>> filtered_img = wiener(img, (5, 5))  # Filter the image
....
```

2020-02-13 16:36 UTC, ilayn commented on scipy/signal/signaltools.py
> +    >>> f, arr = plt.subplots(1, 2)
You can also add figure size to control the whitespace if the default is too big. See the example here https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.fourier_gaussian.html

2020-02-14 12:47 UTC, grapheo12 commented
I have made the changes as requested. Thanks for being patient with me.

2020-02-14 12:49 UTC, ilayn approved these changes

2020-02-14 12:49 UTC, ilayn commented
My pleasure, thank you for your efforts @grapheo12 !

2020-02-14 12:50 UTC, merged

2020-02-15 17:57 UTC, mdhaber commented
Thanks @grapheo12! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).