FIX: Allow non-native byte order inputs to scipy.fft
scipy/scipy pull request #11534
Opened 2020-02-17 17:43 UTC by peterbell10

#### Reference issue
Fixes https://github.com/scipy/scipy/issues/10422#issuecomment-587040183

#### What does this implement/fix?
`_pocketfft` transforms now accept inputs in non-native byte-order by copying the data to native byte-order first.

2020-02-17 18:51 UTC, grlee77 requested changes
there is one duplicate test function name, but otherwise looks good to me

2020-02-17 18:51 UTC, grlee77 commented on scipy/fft/_pocketfft/tests/test_basic.py
> +def test_swapped_byte_order_complex(func):
```suggestion
def test_swapped_byte_order_real(func):
```

2020-02-17 18:53 UTC, grlee77 commented
There is also one error on Travis that appears to be a tolerance issue. 
https://travis-ci.org/scipy/scipy/jobs/651622854#L1379-L1390

2020-02-17 19:45 UTC, peterbell10 commented
Weird, the test failures are in `long double` which is only tested to the same precision as `double`.

2020-02-17 21:05 UTC, grlee77 approved these changes
looks like the failure was not reproduced after your commit renaming the test function

2020-02-24 03:42 UTC, tylerjereddy commented
CI is all green, there's a +1 expert review, and it looks to me like there's some pretty thorough additional testing added here, so in it goes, thanks @peterbell10 & @grlee77

2020-02-24 03:42 UTC, merged