Add examples
scipy/scipy pull request #11633
Opened 2020-03-05 23:31 UTC by gholdman1

DOC: Add examples to various functions in `scipy.special`, namely `assoc_laguerre`, `jvp`, and yvp`. Fixes #7168 for these functions.

2020-03-06 13:20 UTC, ilayn requested changes
Thank you for the effort @gholdman1 ! I've added very minor comments.

2020-03-06 13:20 UTC, ilayn commented on scipy/special/_basic.py
> +    >>> result = special.jvp(v,z)
nitpick pep8 commas

2020-03-06 13:20 UTC, ilayn commented on scipy/special/_basic.py
> +    >>> special.jv(v-1,z)-special.jv(v+1,z)
pep8 space after comma

2020-03-06 13:20 UTC, ilayn commented on scipy/special/_basic.py
> +    >>> result = special.yvp(v,z)
You don't need the intermediate `result` variables. You can directly print the result just as you did with `assoc_laguerre`

2020-03-06 13:20 UTC, ilayn commented on scipy/special/_basic.py
> +    >>> assoc_laguerre(1,2)
pep8 comma

2020-03-06 13:20 UTC, ilayn commented on scipy/special/_basic.py
> +    >>> assoc_laguerre(1,2,3)
PEP8 commas

2020-03-06 16:17 UTC, gholdman1 commented
Thank you! I've made the changes. Please let me know if you find anything else.

I'll be adding more examples in this branch soon. Will I need to open a new PR?

2020-03-07 19:47 UTC, gholdman1 commented
Hello! I tried fixing some errors given by the tests. In the process, I may have messed up the commit history and may not be able to push to `origin/add-examples`. I'll be making a new branch and opening a new PR.

2020-03-07 19:47 UTC, closed without merging