Add domain option for resample.
scipy/scipy pull request #11776
Opened 2020-04-01 21:33 UTC by luigifreitas

The original `scipy.signal.resample` function converts the input time-domain signal into frequency-domain to perform the resampling. This pull request proposes to add an option `domain` to pass a signal already in the frequency-domain. This would reduce the computational load of workloads that require several resamples of the same input signal. Here, the `domain` option is passed to the function with `time` for time-domain (Default) or `freq` for frequency-domain.

2020-04-02 09:24 UTC, miladsade96 requested changes
@luigifreitas Please add tests related to your feature into **/scipy/signal/tests/test_signaltools.py**

2020-04-07 14:46 UTC, EverLookNeverSee commented on scipy/signal/signaltools.py
> +
```suggestion
```

2020-04-07 14:47 UTC, EverLookNeverSee commented on scipy/signal/signaltools.py
> +
remove this blank line

2020-04-07 14:51 UTC, miladsade96 requested changes

2020-04-07 14:51 UTC, EverLookNeverSee commented on scipy/signal/signaltools.py
> +           Consider the input `x` as frequency-domain.
```suggestion
        ``time`` Consider the input `x` as time-domain (Default),
        ``freq`` Consider the input `x` as frequency-domain.
```

2020-04-07 15:51 UTC, e-q commented
I see the logic in wanting to spare redundant DFT calculations, but the keyword argument approach seems a little awkward to me. One alternative could be to factor out some of the inner logic of `resample` into a `resample_dft` function that takes in the user's DFT and returns the `Y` currently calculated in `resample`. Then, `resample` could call that within itself and handle the fft/ifft calculations.

2020-04-08 19:14 UTC, ilayn requested changes

2020-04-13 00:00 UTC, luigifreitas commented on scipy/signal/signaltools.py
> +        raise NotImplementedError("domain should be 'time' or 'freq'")
Domain ValueError validation added as requested.

2020-04-18 11:30 UTC, ilayn requested changes
Only minor comments

2020-04-18 11:30 UTC, ilayn commented on scipy/signal/tests/test_signaltools.py
> +from scipy import fftpack
Just import `scipy.fft`

2020-04-18 11:30 UTC, ilayn commented on scipy/signal/signaltools.py
> +    elif domain == 'freq':
Now it is just `else`. You can write 

```python
    else:  # domain == 'freq'
```
Note double whitespace before `#` for PEP8

2020-04-18 20:42 UTC, merged

2020-04-18 20:42 UTC, ilayn commented
Thank you @luigifreitas for your time!