Add simplify_output parameter to scipy.io.loadmat
scipy/scipy pull request #11798
Opened 2020-04-05 13:16 UTC by cbrnr

Fixes #7895.

This adds a new parameter `simplify_output` to `scipy.io.loadmat`, which if `True` returns the output dict in a simpler format. People have been using workarounds for a long time, and this PR finally integrates one particular workaround.

Open questions/issues:

- [ ] Is the parameter named appropriately (if not please suggest a better alternative)?
- [ ] Is everyone attributed appropriately (@jcbsv as well as https://stackoverflow.com/a/29126361/572908 which currently is not mentioned)?
- [ ] Currently this is only implemented for `mio5` - I don't know if it's even possible for `mio4`, but if so this would require additional work. Also, the code by @jcbsv is `mio5` only.
- [ ] If `simplify_output=True`, this requires `squeeze_me=True` and `struct_as_record=False` (both non-default values). Currently, I warn about this, but I'm sure users would like to turn off these warnings when just calling `loadmat` with `simplify_output=True`. Any suggestions?
- [ ] A test is missing. Will work on that.

2020-04-05 20:17 UTC, rgommers commented
> Is the parameter named appropriately (if not please suggest a better alternative)?

Since this only affects cell arrays, a more specific name would be better (similar to `struct_as_record`). How about `squeeze_cells` or `simplify_cells`?

> Is everyone attributed appropriately

The commit message would be a good place to do the attribution in a more complete way.

>     * If `simplify_output=True`, this requires `squeeze_me=True` and `struct_as_record=False` (both non-default values). Currently, I warn about this, but I'm sure users would like to turn off these warnings when just calling `loadmat` with `simplify_output=True`. Any suggestions?

Unfortunately that is starting to look like a mess. Using a `matlab_compatible` boolean for setting a combination of those other keywords is unfortunate. Ideally that would look like `method='default'` that would also take `'matlab_compatible'` and `'simplified'`. As it is now, I'm not sure there's a better option.

2020-04-05 20:32 UTC, cbrnr commented
I like `simplify_cells`!

I know that the current solution isn't ideal, but it is the least invasive. We could also not warn and just document the behavior.

2020-04-06 11:51 UTC, cbrnr commented
Regarding a what's new entry, in which document should I include this?

2020-04-06 12:21 UTC, rgommers commented
Thanks for asking, please add a note to https://github.com/scipy/scipy/wiki/*Release-note-entries-for-SciPy-1.5.0*

2020-04-06 12:21 UTC, rgommers commented
Sorry that link is messed up because of the `*`, one sec I'll remove those

2020-04-06 12:22 UTC, rgommers commented
https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.5.0

2020-04-06 12:25 UTC, cbrnr commented
Thanks, I'll add an entry in the "scipy.io improvements" section once this is merged.

2020-04-21 07:30 UTC, cbrnr commented
Does anyone else have time to review this PR? Any other things that I should add/change?

2020-04-21 07:31 UTC, cbrnr commented
@jcbsv or @prisae do you have any comments?

2020-04-21 07:38 UTC, jcbsv commented
It's great work!

2020-04-21 11:10 UTC, prisae commented
Great, thanks so much for the PR. LGTM.

2020-05-06 07:19 UTC, cbrnr commented
@rgommers would it be possible to include this in the upcoming 1.5 release?

2020-05-06 08:01 UTC, ilayn requested changes
Some minor comments and it is good to go I think. And yes we can make it into 1.5.0

2020-05-06 08:41 UTC, cbrnr commented on scipy/io/matlab/mio5.py
> +def _check_keys(d):
Yes, is `_matstruct_to_dict` OK?

2020-05-06 08:42 UTC, cbrnr commented on scipy/io/matlab/mio5.py
> +def _check_keys(d):
Wait, I meant `_todict` -> `_matstruct_to_dict`.

2020-05-06 08:42 UTC, cbrnr commented on scipy/io/matlab/mio5.py
> +    """Construct nested dicts from mat_struct objects."""
OK!

2020-05-06 08:44 UTC, cbrnr commented on scipy/io/matlab/mio5.py
> +def _tolist(ndarray):
OK!

2020-05-06 08:46 UTC, cbrnr commented on scipy/io/matlab/mio5.py
> +def _check_keys(d):
To avoid confusion with `_matstruct_to_dict`, what about naming this function `_simplify_cells`?

2020-05-06 08:47 UTC, cbrnr commented on scipy/io/matlab/miobase.py
> +import warnings
Done!

2020-05-06 10:27 UTC, cbrnr commented
The errors on Travis are unrelated I think.

2020-05-20 08:08 UTC, cbrnr commented
@ilayn are you happy with the name changes?

2020-05-20 22:34 UTC, tylerjereddy commented
> Some minor comments and it is good to go I think. And yes we can make it into 1.5.0

@ilayn Are you happy with this PR now? Based on your last review this should be close.

2020-05-21 00:24 UTC, ilayn commented
Oh my! So sorry about the delay and thanks for your efforts @cbrnr

2020-05-21 00:24 UTC, merged

2020-05-21 00:28 UTC, ilayn commented
Do you mind adding a few words to the release notes @cbrnr ? https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.5.0

2020-05-21 08:20 UTC, thomasaarholt commented
Hi, thanks for doing this. Just wondering if there's also been added references to this in the documentation? It seems likely that users would prefer using this new approach. 

https://docs.scipy.org/doc/scipy/reference/tutorial/io.html

2020-05-21 08:53 UTC, cbrnr commented
No, we haven't added anything to the tutorial, but I agree it would be nice to demonstrate the new parameter. I can create a new PR where I add a short section using the example you provided in #7895 - would that be OK?

2020-06-21 13:03 UTC, cbrnr commented
I'm a bit 😢 to see that I'm not on the list of contributors for 1.19. Did I forget to add myself to a manually maintained list? Or if authors are determined automatically, there seems to be something wrong with the way it's currently done.

2020-06-21 13:06 UTC, prisae commented
I think you refer to numpy 1.19, but your PR will be in scipy 1.5 I think....?

2020-06-21 13:08 UTC, prisae commented
And for scipy 1.5 you are on the list: https://github.com/scipy/scipy/releases/tag/v1.5.0rc2

2020-06-21 13:08 UTC, thomasaarholt commented
You are there, for the scipy 1.5 release candidate: [release notes](https://github.com/scipy/scipy/releases). (ctrl + F "Clemens")

2020-06-21 13:17 UTC, cbrnr commented
🤦🤦🤦 thanks!