DOC: add Returns and Examples for scipy.ndimage.correlate() docstring
scipy/scipy pull request #11883
Opened 2020-04-18 11:55 UTC by AtsushiSakai

#### Reference issue
To fix a part of #7168

#### What does this implement/fix?
add Returns and Examples for scipy.ndimage.correlate() docstring

2020-04-18 16:26 UTC, rgommers commented
Thanks @AtsushiSakai. Still failing, `unexpected indentation` on TravisCI.

2020-04-19 02:14 UTC, AtsushiSakai commented
@rgommers I’m sorry. From the next time, i will use draft when my PR is not ready for review. I fix it. PATL.

2020-04-19 10:43 UTC, rgommers commented
> @rgommers I’m sorry. From the next time, i will use draft when my PR is not ready for review.

No worries. If you expected it to pass CI it was perfectly fine as it was (I do the same), if you know it's not ready you can indeed use draft mode or title it WIP: ....

2020-04-19 10:47 UTC, rgommers requested changes
Thanks @AtsushiSakai, nice example. Just a couple of formatting issues.

2020-04-19 10:47 UTC, rgommers commented on scipy/ndimage/filters.py
> +    as kernel over the image and computing the sum of products at each location.
This needs a blank line here to render correctly.

2020-04-19 10:47 UTC, rgommers commented on scipy/ndimage/filters.py
> +    For example, element [2,2] is 7 + 11 + 12 + 13 + 17 = 60
Could you use double backticks around `[2,2]` and the `7 + ...` expression? Will look nicer in the rendered html.

2020-04-19 12:02 UTC, rgommers commented
Okay this was definitely fixed, so better not to switch to draft mode. I want to push the green button but can't right now.

2020-04-19 12:05 UTC, AtsushiSakai commented
@rgommers Sorry, go ahead.

2020-04-19 12:05 UTC, ilayn commented
Ralf you can get it out of draft mode by clicking the button "Ready for review"

2020-04-19 12:06 UTC, rgommers commented
> Ralf you can get it out of draft mode by clicking the button "Ready for review"

ah thanks, never done that before

2020-04-19 12:07 UTC, merged

2020-04-19 12:07 UTC, rgommers commented
Merged, thanks @AtsushiSakai