DOC, MAINT: mailmap update
scipy/scipy pull request #11934
Opened 2020-04-25 23:53 UTC by tylerjereddy

* update mailmap early to reduce last-minute
burden for `1.5.0` release

I made an effort to click through GitHub profiles and webpages linked therein to find full names, but in some cases I couldn't quite track the info down; pinging for those I couldn't find full names for in case they'd prefer their full name in release notes vs. username:

- [ ] @reidarkind
- [ ] @mckib2
- [ ] @Mazay0
- [ ] @Maltimore
- [ ] @Konrad0
- [ ] @janvle
- [ ] @hakeemo
- [ ] @dankleeman
- [ ] @caos21
- [ ] @ananyashreyjain

2020-04-26 05:54 UTC, EverLookNeverSee commented on .mailmap
> +Milad Sadeghi <EverLookNeverSee@Protonmail.ch> ELNS <57490926+EverLookNeverSee@users.noreply.github.com>
```suggestion
Milad Sadeghi DM  <EverLookNeverSee@Protonmail.ch> ELNS <57490926+EverLookNeverSee@users.noreply.github.com>
```

2020-04-26 05:58 UTC, miladsade96 requested changes

2020-04-26 05:58 UTC, EverLookNeverSee commented on .mailmap
> +Milad Sadeghi <EverLookNeverSee@Protonmail.ch> ELNS <57490926+EverLookNeverSee@users.noreply.github.com>
There should DM at the end of my name.

2020-04-26 08:39 UTC, reidarkind commented
My name is Reidar Kind :)

2020-04-26 08:54 UTC, Maltimore commented
I guess for me the line should be:

```Malte Esders <git@maltimore.info> Maltimore <git@maltimore.info>```

2020-04-26 13:11 UTC, ilayn commented
Wow, here we go officially for 1.5.0 then 😃

2020-04-26 13:41 UTC, caos21 commented
Is it too late for me? Benjamin Santos @caos21

2020-04-26 17:37 UTC, janvle commented
Jan Vleeshouwers @janvle

2020-04-26 17:56 UTC, ananyashreyjain commented
Anany Shrey Jain @ananyashreyjain

2020-04-26 19:26 UTC, mckib2 commented
Nicholas McKibben

2020-04-26 22:08 UTC, tylerjereddy commented
I've applied all the revisions suggested so far, thanks.

2020-04-27 05:50 UTC, miladsade96 approved these changes
LGTM! Thanks @tylerjereddy

2020-04-30 00:48 UTC, tylerjereddy commented
Ok, simple `.mailmap` update and the CI issue is not related, so merging.

I'll do another pass eventually if others pinged on the list respond at some point.

2020-04-30 00:48 UTC, merged