DOC: add Examples and fix docstring for special.airye
scipy/scipy pull request #11969
Opened 2020-04-29 10:04 UTC by AtsushiSakai

#### Reference issue
fix a part of #7168

#### What does this implement/fix?
add Examples and fix docstring for special.airye()

2020-04-29 13:41 UTC, ilayn commented
You might want to use the OOP style as matplotlib fols recommend its usage

```python
from scipy.special import airye
import matplotlib.pyplot as plt
z = np.linspace(40, 200)
eAi, eAip, eBi, eBip = airye(x)
f, ax = plt.subplots(2, 1, sharex=True)
for ind, data in enumerate([[eAi, eBi, ["eAi", "eBi"]],
                            [eAip, eBip, ["eAip", "eBip"]]]):
    ax[ind].plot(z, data[0], "-r", z, data[1], "-b")
    ax[ind].legend(data[2])
    ax[ind].grid()
```

2020-04-29 13:54 UTC, person142 requested changes
The interesting thing about these functions is the “exponentially scaled” bit, so for an example I would want to see something that compares them to the normal Airy functions so that you can see what they are exponentially scaled compared to.

2020-04-29 14:23 UTC, pv commented
And maybe some example where the usual non-scaled functions under/overflow whereas the exponentially scaled ones do not, so that the reason for the existence of these functions becomes clearer.

2020-04-30 02:14 UTC, AtsushiSakai commented
Thank you guys for reviewing and comments. I updated it based on your feedbacks. PTAL.

2020-05-01 23:37 UTC, AtsushiSakai commented
Close and reopen to rerun CI

2020-05-04 21:47 UTC, pv commented on scipy/special/add_newdocs.py
> +    >>> plt.show()
Probably clearer to show this in code than as plots:
```suggestion
>>> airy(200)
(0.0, 0.0, nan, nan)
>>> airye(200)
(0.07501041684381093, -1.0609012305109042, 0.15003188417418148, 2.1215836725571093)
```

2020-05-06 21:28 UTC, ilayn commented
This is quite nice now. Thanks @AtsushiSakai @pv

2020-05-06 21:28 UTC, merged