DOC: fix docstrings of `query_ball_tree` and `query_pairs` of `spatial.KDTree` and `spatial.cKDTree`
scipy/scipy pull request #12327
Opened 2020-06-08 13:52 UTC by AtsushiSakai

#### What does this implement/fix?
I found some minor doc issues of `spatial.KDTree` and `spatial.cKDTree`.

I think current docstrings of `query_ball_tree` and `query_pairs` of `spatial.KDTree` and `spatial.cKDTree` are not good at below points:
1. docstrings are not consistent between `spatial.KDTree` and `spatial.cKDTree`.
2. `query_ball_tree` returns indexes of data, but docstring says that it find pairs of data.

So, I fixed docstrings of `query_ball_tree` and `query_pairs` of `spatial.KDTree` and `spatial.cKDTree`.

2020-06-08 14:03 UTC, peterbell10 requested changes

2020-06-10 11:33 UTC, AtsushiSakai commented on scipy/spatial/ckdtree.pyx
> +        Find all indexes of points whose distance is at most r
Thank you for your comment. I got it. I updated docsting based on your comment. PTAL.

2020-06-11 10:59 UTC, AtsushiSakai commented on scipy/spatial/ckdtree.pyx
> +        Find all pairs of points between `self` tree and `other` tree whose distance is at most r
OK. I fixed it. PTAL.

2020-06-11 11:13 UTC, peterbell10 approved these changes
LGTM, seems like a useful distinction.

2020-06-11 11:55 UTC, AtsushiSakai commented
Thank you. If you have time, could you please review this PR also #12341 ? I think these functions should have Examples to understand its functionalities easily.

2020-06-14 06:43 UTC, AtsushiSakai commented
[TODO] After merging this PR and #12341, we should answer this question:
python - Scipy cKDTree query_pairs versus query_ball_tree - Stack Overflow https://stackoverflow.com/questions/47763534/scipy-ckdtree-query-pairs-versus-query-ball-tree

2020-06-15 23:49 UTC, merged

2020-06-15 23:50 UTC, peterbell10 commented
Thanks @AtsushiSakai