MAINT: Minor cleanup of (c)KDTree tests
scipy/scipy pull request #12372
Opened 2020-06-16 16:49 UTC by peterbell10

#### What does this implement/fix?
In gh-8923 @sturlamolden mentions that we can't remove `KDTree` completely because it's used in the tests for `cKDTree`. In fact, I could only see it used as a reference in one test for `sparse_distance_matrix`, so switch that test to compare against `distance_matrix` instead.

Also noticed some copy-paste tests that only differ by using `cKDTree` instead of `KDTree` so used `pytest.mark.parametrize` to clean these up.

2020-06-16 17:25 UTC, sturlamolden commented
We could remove it, but we would have to rewrite the tests to use brute force search (which is ok, as long as the data sets are small). Another option is to move the module to ```scipy/spatial/tests``` and use it as a test class by relative import.

2020-06-16 17:53 UTC, peterbell10 commented
For this test case, brute force is actually 3 orders of magnitude faster than `KDTree`. 74 us vs 29 ms.

2020-06-16 18:40 UTC, sturlamolden commented
Yes, and that is why cKDTree has a parameter ```leafsize``` that determines when the queries will switch to brute force. We still have the overhead of building the kd-tree, though, so there will always be a data size below which brute force is faster (at least if it is written in Cython).

2020-06-16 18:43 UTC, peterbell10 commented
What I meant is that keeping the python version of `KDTree` around for correctness tests doesn't make sense when brute force is faster and easier to verify anyway.

2020-06-16 18:48 UTC, sturlamolden commented
> What I meant is that keeping the python version of `KDTree` around for correctness tests doesn't make sense when brute force is faster and easier to verify anyway.

Yes.

2020-06-18 19:36 UTC, peterbell10 commented
Slightly tacked onto this PR, I've expanded the tests for `KDTree.query`'s `query_all_neighbors` mode. The current tests only test the shape of the return types, but doesn't test that it gives the right answer...

2020-06-24 15:31 UTC, peterbell10 commented
@sturlamolden, @rainwoodman would you mind taking a look at this?

2020-06-25 01:38 UTC, sturlamolden commented on scipy/spatial/tests/test_kdtree.py
> +        assert isinstance(d, list)
Use underscore: assert_

2020-06-25 01:49 UTC, sturlamolden commented
- Use assert_ function instrad of assert statement
- Rebase on scipy/master to make sure all checks are green

2020-06-25 01:49 UTC, sturlamolden requested changes

2020-06-25 01:49 UTC, sturlamolden commented on scipy/spatial/tests/test_kdtree.py
> +        assert isinstance(i, list)
assert_(isinstance(d, list))
assert_(isinstance(i, list))

2020-06-25 01:49 UTC, sturlamolden commented on scipy/spatial/tests/test_kdtree.py
> +        assert all(a <= b for a, b in zip(d, d[1:]))
assert_(all(a <= b for a, b in zip(d, d[1:])))

2020-06-25 01:55 UTC, larsoner commented
I think we as a package should prefer bare assert statements over assert_ for simple built-in comparisons now that we use pytest. Pytest gives nice information for built-in types when it fails.

2020-06-25 02:13 UTC, sturlamolden commented
I thought the reason for assert_ was that Python does not generate bytecode for assert statements when executing code with -O flag.

2020-06-25 03:00 UTC, tylerjereddy commented
> I thought the reason for assert_ was that Python does not generate bytecode for assert statements when executing code with -O flag.

True, but `pytest` wraps around this so using plain `assert` is fine now that we don't use `nose`. I think this discussion came up a few times and there was rough agreement to use plain `assert` moving forward, but not to be super aggressive about replacing the old `assert_`.

2020-06-25 03:47 UTC, sturlamolden commented
I see. I guess plain assert is fine then.

2020-06-25 10:04 UTC, peterbell10 commented
`pytest` rewrites the python AST to replace `assert`s with its own generated code. So, as long as the assert is actually inside of a test function, it will still work even with `-O`. This package shows roughly what it's doing:
https://pypi.org/project/pytest-ast-back-to-python/

From the readme:
```python
def test_simple():
    a = 1
    b = 2
    assert a + b == 3
```
is transformed into 

```python
def test_simple():
    a = 1
    b = 2
    @py_assert2 = a + b
    @py_assert4 = 3
    @py_assert3 = @py_assert2 == @py_assert4
    if @py_assert3 is None:
        from _pytest.warning_types import PytestAssertRewriteWarning
        from warnings import warn_explicit
        warn_explicit(PytestAssertRewriteWarning('asserting the value None, please use "assert is None"'), category=None, filename='/home/tom/.virtualenvs/tmp-483cf04ecc31dda8/test_thing.py', lineno=4)
    if not @py_assert3:
        @py_format6 = @pytest_ar._call_reprcompare(('==',), (@py_assert3,), ('(%(py0)s + %(py1)s) == %(py5)s',), (@py_assert2, @py_assert4)) % {'py0': @pytest_ar._saferepr(a) if 'a' in @py_builtins.locals() or @pytest_ar._should_repr_global_name(a) else 'a', 'py1': @pytest_ar._saferepr(b) if 'b' in @py_builtins.locals() or @pytest_ar._should_repr_global_name(b) else 'b', 'py5': @pytest_ar._saferepr(@py_assert4)}
        @py_format8 = ('' + 'assert %(py7)s') % {'py7': @py_format6}
        raise AssertionError(@pytest_ar._format_explanation(@py_format8))
    @py_assert2 = @py_assert3 = @py_assert4 = None
```

2020-06-25 10:32 UTC, sturlamolden commented
Interesting... Using AST hacks in a testsuite... 🧐😅

2020-06-28 18:10 UTC, rainwoodman commented
I hope the AST hack eventually finds its way into mainline python.

The PR looks good to me.

2020-07-07 20:05 UTC, peterbell10 commented
I'd like to get this merged in order to unblock #12382. From the discussion I think @sturlamolden and @rainwoodman are happy, so I will merge tomorrow if there are no more comments.

2020-07-08 00:23 UTC, merged

2020-07-08 00:23 UTC, larsoner commented
Thanks @peterbell10