Small update to scipy FFT docs
scipy/scipy pull request #12599
Opened 2020-07-22 06:30 UTC by mreineck

Apart from removing a note in the `scipy` FFT tutorial which is probably no longer necessary, this updates the docs to mention that `scipy.fft` has support for DCT/DST type IV.

The documentation for DCTs and DSTs seems a bit inconsistent, so I wasn't entirely sure which one I should adopt. Maybe some more extensive rework would be useful here, but unfortunately I don't have the time.

2020-07-22 11:20 UTC, mreineck commented
CI errors seem unrelated.

2020-07-22 13:34 UTC, peterbell10 requested changes

2020-07-22 14:02 UTC, mreineck commented on doc/source/tutorial/fft.rst
> +    y[k] = \sum_{n=0}^{N-1} x[n] \cos\left({\pi (2n+1)(2k+1) \over 2N}\right)
Sorry, that's a mixup of two independent errors ... should be fixed now.
I also changed 2N to 4N in the normalized expression, the factor in front of the sum should be OK though.

2020-07-22 14:02 UTC, mreineck commented on doc/source/tutorial/fft.rst
> +    y[k] = \sum_{n=0}^{N-1} x[n] \sin\left({\pi (2n+1)(2k+1) \over 2N}\right)
Fixed, see above.

2020-07-22 14:46 UTC, peterbell10 approved these changes

2020-07-22 16:18 UTC, merged

2020-07-22 16:19 UTC, peterbell10 commented
CI failures unrelated again so merged. Thanks @mreineck.

2020-10-30 10:37 UTC, hgomersall commented
I appreciate I'm rather late to the boat on this, but I'm curious as to the reason why the link to `pyfftw` was removed (though the link _was_ to the wrong site)?

2020-10-30 10:57 UTC, ilayn commented
Probably because we started using pocketFFT covered the speed part good enough and also not used in SciPy so no point on disturbing the tutorial flow.