ENH: use special.sindg in ndimage.rotate
scipy/scipy pull request #12721
Opened 2020-08-14 19:56 UTC by ewmoore

This makes `np.all(a == ndimage.rotate(ndimage.rotate(a, 180), -180))` be `True` when a has integral dtype.

Even if this isn't a perfect fix, there is no reason not to use `sindg` instead of converting to radians.  And getting this case correct is why these functions exist.

fixes gh-12543.

2020-08-14 22:25 UTC, grlee77 commented on scipy/ndimage/tests/test_ndimage.py
> +
```suggestion
    def test_rotate_exact_180(self):
        a = numpy.tile(numpy.arange(5), (5, 1))
        b = ndimage.rotate(ndimage.rotate(a, 180), -180)
        assert_equal(a, b)
```

2020-08-14 22:30 UTC, grlee77 requested changes
Thanks @ewmoore. I did not even realize we had a `sindg` function!

I left a couple minor PEP8-related suggestions

2020-08-14 22:30 UTC, grlee77 commented on scipy/ndimage/tests/test_ndimage.py
> +
```suggestion

```

2020-08-14 22:30 UTC, grlee77 commented on scipy/ndimage/tests/test_ndimage.py
> +        assert_equal(a,b)
```suggestion
    def test_rotate_exact_180(self):
        a = numpy.tile(numpy.arange(5), (5, 1))
        b = ndimage.rotate(ndimage.rotate(a, 180), -180)
        assert_equal(a, b)
```

2020-08-14 22:41 UTC, ewmoore commented on scipy/ndimage/tests/test_ndimage.py
> +
extra newline removed.

2020-08-14 22:41 UTC, ewmoore commented on scipy/ndimage/tests/test_ndimage.py
> +        assert_equal(a,b)
spaces added.

2020-08-14 22:42 UTC, ewmoore commented
Comments addressed.

2020-08-15 11:03 UTC, grlee77 approved these changes

2020-08-15 22:51 UTC, ev-br commented
The fix LGTM, the CI errors do not seem related.
I'm surprised this code does not use blas level 1  `drot`, but it"s separate.
Merging, thanks Eric, Gregory

2020-08-15 22:52 UTC, merged

2020-08-15 23:56 UTC, tylerjereddy commented
By the way, is this actually a bug fix vs. enhancement? Reading through the cognate issue it sounds like it may be fixing something?

2020-08-17 13:52 UTC, grlee77 commented
@tylerjereddy: Yes, I would classify this more as a fix rather than enhancement. By removing an intermediate conversion to radians, there is less floating point error of the type shown in the linked issue (causing rotations by +180 or -180 to not be equivalent).