BUG: per #12654 adjusted mudholkar_george method to combine p values
scipy/scipy pull request #12724
Opened 2020-08-15 14:20 UTC by WillTirone

#### Reference issue
Closes #12654: from discussion on issue, "scipy.stats.combine_pvalues seems to work incorrectly with method='mudholkar_george'"

#### What does this implement/fix?
"According to the original article approx_factor should be equal to np.sqrt(nu / (nu - 2)) / scipy.pi * np.sqrt(3 / len(pvalues)), not np.sqrt(nu / (nu - 2))"

p-values are now calculated correctly as described in the [article](https://www.researchgate.net/publication/235117023_The_Logit_Statistic_for_Combining_Probabilities_-_An_Overview)

#### Additional information
I've made a few attempts at contributing in the past but was unsuccessful, so please review carefully. I did the following: 

1. followed the scipy dev guide 
2. removed the old unit test that was comparing an incorrect value and added a new one 
3. All tests pass in test_stats.py 
4. Let me know what I need to do to credit @M1kss for the code - he adjusted the method and I edited / tested; I'm not sure what the usual protocol is here.

2020-08-15 18:29 UTC, WillTirone commented
@rlucas7 I believe you said you wanted to review this one. Thanks!

2020-08-17 01:35 UTC, rlucas7 requested changes
@WillTirone left a couple small comments for changes.

2020-08-17 01:35 UTC, rlucas7 commented on scipy/stats/tests/test_stats.py
> +
suggest remove whitespace

2020-08-17 01:35 UTC, rlucas7 commented on THANKS.txt
> +Will Tirone for contributing to scipy.stats
Can you remove this line?

Reason being that adding to the thanks.txt file is a common cause for git rebase conflicts. 
We've been experimenting with other approaches, for 1.5.0 release we had a wiki page that we asked people to add themselves to you can see it here: 
https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*

I've initiated a discussion on the scipy-dev list and seems there is support for changing the acknowledgments mechanism. We may move the thanks on this file to a separate wiki page (that we add to w/each release) or we may migrate things to this page: https://scipy.org/scipylib/donations.html (still adding on each release)
decision on which is still TBD. 

We'll make sure you're given proper credit though so don't worry about that here.

2020-08-17 03:23 UTC, WillTirone commented
I've made the requested changes - I'm not sure what the preference is on a commit message when I'm fixing something a reviewer has noted. I just undid the changes and added another commit on my local branch and pushed, but let me know if I should have reverted the first commit and made another one. 

Thanks :)

2020-08-17 12:34 UTC, rlucas7 commented
People may have different opinions on this one but I find the commit messages on reviews are usually not fitting into neat boxes like. , DOC, STY etc. so I usually just add a commit message that identifies I’m addressing changes from a review. 

Usually when PR is complete we’ll merge into the master branch as a single commit. This keeps the history clean and allows a second chance to clarify the commit message for changeset.

Sincerely, 

-Lucas Roberts 

> On Aug 16, 2020, at 11:23 PM, WillTirone <notifications@github.com> wrote:
> 
> ﻿
> I've made the requested changes - I'm not sure what the preference is on a commit message when I'm fixing something a reviewer has noted. I just undid the changes and added another commit on my local branch and pushed, but let me know if I should have reverted the first commit and made another one.
> 
> Thanks :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-17 13:33 UTC, WillTirone commented
Got it - so I'm assuming we're done with this PR but let me know if there's anything else I need to do. Thanks again!

2020-08-17 22:57 UTC, rlucas7 commented
> Got it - so I'm assuming we're done with this PR but let me know if there's anything else I need to do. Thanks again!

@WillTirone yeah these changes look fine. 

I'll merge the changeset this weekend to give @M1kss  and others a chance to take a look and comment

2020-08-18 00:20 UTC, WillTirone commented
sounds good!

2020-08-18 14:51 UTC, M1kss commented
@rlucas7 @WillTirone 
I agree with the changes, the testing also looks fine.

P.S. This is also the first time I've opened an issue, so if this is appropriate, I'd be happy to get a credit in any way :)

2020-08-18 23:29 UTC, rlucas7 commented
> On Aug 18, 2020, at 10:52 AM, Alexandr Boytsov <notifications@github.com> wrote:
> 
> ﻿
> @rlucas7 @WillTirone
> I agree with the changes, the testing also looks fine.
> 
> P.S. This is also the first time I've opened an issue, so if this is appropriate, I'd be happy to get a credit in any way :)
> 
Can I interest you in putting together a PR with something to handle the edge cases? 

If not that’s ok too, I can make sure you get added to wherever we move the thanks to once we’ve decided on the specifics for that one.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-19 11:39 UTC, M1kss commented
@rlucas7 
Thanks a lot!

Yeah, that sounds interesting! I suppose a proper way to do this is to introduce a parameter that'd be responsible for ignoring or leaving as is 0s and 1s or smth like that. Do I need to open a separate improvement-issue for this?

2020-08-19 22:58 UTC, rlucas7 commented
> On Aug 19, 2020, at 7:39 AM, Alexandr Boytsov <notifications@github.com> wrote:
> 
> ﻿
> @rlucas7
> Thanks a lot!
> 
> Yeah, that sounds interesting! I suppose a proper way to do this is to introduce a parameter that'd be responsible for ignoring or leaving as is 0s and 1s or smth like that.
> 
Yes that seems a reasonable approach.

> Do I need to open a separate improvement-issue for this?
> 
If you want to discuss specifics further then yes please open a new issue. If you think you’re clear on an approach then you can code up and open a PR directly. 

Of course if you choose the direct PR route but find (as often happens) that you’re not sure about something, opening a PR with WIP (work in progress) is fine too. In fact is usually clearer to discuss options with some posted code. 

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-22 21:00 UTC, rlucas7 approved these changes
LGTM

2020-08-22 21:01 UTC, merged