ENH Adding AUTOSOL file with a package of robust linear equation solvers which detect and handle ill-conditioniong
scipy/scipy pull request #12755
Opened 2020-08-23 02:49 UTC by rejones7

I am pulling a file that contains two routines, Autosolve(A,b) and Autosolve_nonneg(A,b).
These algorithms have been available for C++ for some years, but have been tweaked for slight performance improvement and converted to Python. Autosolve's advantage over scipy's "solve", or "lstsq", or "lsmr" is that its more universal approach, built on the concept of the Discrete Picard Condition (see referenced in the code) handles every case, whether simply square systems, or underdetermined or overdetermined, and whether consistent or inconsistent, automatically, switching to Tikhonov regularization (with automatically determined parameters) when needed. Also, it needs no extra information like error estimates, tolerances, iteration limits, etc, and there are no algorithmic errors to report. Thus it is ideal for new users, or situations where a system of equations may sometimes be well conditioned and sometimes not. More details in short attached file.
I am quite new to GitHub so please tell me if I am nor doing something right.  Ron Jones rejones7@msn.com,
[submit_autosolve.txt](https://github.com/scipy/scipy/files/5113433/submit_autosolve.txt)

2020-09-01 23:28 UTC, rejones7 commented
Ilhan:
I am trying to push (pull??) my new version of autosolve.py, now with test_autosolve.py.
I am so confused with GitHub.
The new code is in my branch:
https://github.com/rejones7/scipy/tree/master/scipy/linalg

But when I try to do a PULL github takes me to the old PULL request, and I don't know how to proceed.

I was a professional mathematician and software developer for decades, and I understand all the code maintence issues, and have taught code development at the university levelm but I just don't understand GitHub and have NO ONE I can get personal help from. I know no one who uses it as a developer.

Can you give an idea what I am supposed to be doing?
Ron Jones
(505)934-8799
[https://avatars1.githubusercontent.com/u/65885180?s=400&v=4]<https://github.com/rejones7/scipy/tree/master/scipy/linalg>
rejones7/scipy<https://github.com/rejones7/scipy/tree/master/scipy/linalg>
Scipy library main repository. Contribute to rejones7/scipy development by creating an account on GitHub.
github.com


________________________________
From: Ilhan Polat <notifications@github.com>
Sent: Sunday, August 23, 2020 6:09 AM
To: scipy/scipy <scipy@noreply.github.com>
Cc: rejones7 <rejones7@msn.com>; Author <author@noreply.github.com>
Subject: Re: [scipy/scipy] ENH Adding AUTOSOL file with two robust lin eq solvers which automatically regularize if needed (#12755)


Hi Rondall, thanks a lot for the feature addition.

We need to get a few things out of the way before we dive into nitty-gritties. First the most obvious one, we need test cases with every bit of code added to the repository. And they have to be covering as much as possible the code branches for maintenance.

The other bit is in the python style side, we actually want informative failures so failures should be an option. I know this is the matlab way with silent exception handling but it is really confusing to understand what happened when something doesn't come out the way expected. Most of us has been bitten by this in our past so that is not quite the desired behavior.

Then, the expensive SVD usage; this is really an overkill for simple linear sets. In my opinion none of this should kick in, if the regular solve manages to solve without warnings or errors. Hence autosol becomes immediately a helper tool because of its cost in production code. But then, we don't have a place for helper tools. Hence it requires a lot of changes as it stands. Note even matlab returns an error if the matrix is exactly singular and does not continue.

On the other hand we might want to enhance the lstsq functions such that we return different solutions for under/overdetermined problems (minimum norm, nonnegative etc). So that we would really want.

I think the best approach here to ask in the Scipy-dev mailing list such that I am not the only person deciding this since there is a larger audience there.

https://scipy.org/scipylib/mailing-lists.html<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fscipy.org%2Fscipylib%2Fmailing-lists.html&data=02%7C01%7C%7C73e13eb9728b403090a608d8475d68ce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637337813794706656&sdata=MrrupBTDU2xr7%2F9OWbKV0eJ0TPdo4R9bmvUIT3i6EfU%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23issuecomment-678766368&data=02%7C01%7C%7C73e13eb9728b403090a608d8475d68ce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637337813794716652&sdata=MjNnbRV0stoL7FX65G6oFqPnWD9WRWDshIYfSpKAz7o%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPWVH7DFZ2CN6QEXS2XJ63LSCEBIBANCNFSM4QINLM6A&data=02%7C01%7C%7C73e13eb9728b403090a608d8475d68ce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637337813794736642&sdata=nhpqx%2BBivbSadJ8CJS%2F9sdLsRQMWrqKPSkqmvbFwG2g%3D&reserved=0>.

2020-09-03 02:50 UTC, rejones7 commented
This is a resubmittal of autosol, which now contains three automatically regularizing routines: 
-autosolve, the primary routine which uses the Picard Condition principle to detect and regularize ill-conditioned (incuding singular) systems. 
-autosolve_nonneg which forces the soltution to be nonnegative;
- autosolve_rising which forces the derivative of the solution to be nonnegative.
Please refer to previous PULL for details, or to http://www.rejones7.net/autorej/index.htm .
A full coverage test is now in the scipy/linalg/tests folder.
A large graphic showing how autosolve compares to lsmr, lstsq, and solve on four test matrices is in scipy/linalg/tests/data. comments invited rejones7@msn.com

2020-09-03 03:15 UTC, rejones7 commented
A question that came up immediately upon the PULL request is whether I could call a cheaper (non-SVD) solver first before doing the SVD to start my analysis, I have illustrated the problem with that in a chart in scipy/linalg/tests/data/autosolve)comparison. Here is the result: typical solvers such a lstsq cannot see that they are producing garbage when the system is poorly conditioned, though the matrix is nowhere near being singular. There is a fundamental problem with traditional solvers which put the blame for ill-conditioned behavior on the Matrix, and its small singular values. But as we learn when study the Picard Condition, it is the vector S+ * Ut * b
(where Ax=b is being solved, as USVt is the SVD) that tells the real story, and that story is that data error in b is the source of the problem. As the diagram shows, lstsq and solve produce horrible oscillatory solution vectors long before the matrix is singular, and they neither know they are doing this are report it. So my algorithms must stand alone... presolving with lstsq, for example, is useless.

2020-09-03 08:18 UTC, ilayn requested changes
I couldn't find too much time and below are very very quick glance review. I'll come back asap I have some time.

2020-09-03 08:18 UTC, ilayn commented on scipy/linalg/autosol.py
> +def two_norm(x):
This is basically a rewrite of `scipy.linalg.norm`

2020-09-03 08:18 UTC, ilayn commented on scipy/linalg/autosol.py
> +def rms(x):
as above you can do `scipy.linalg.norm(a)/len(a)`

2020-09-03 08:18 UTC, ilayn commented on scipy/linalg/autosol.py
> +def compute_mov_sums(g, w, m):
Also here you can use convolution as in `np.convolve(g ,np.ones(w, dtype=int),'valid')` or whichever behavior you prefer (see `numpy.convolve` docstring)

2020-09-03 08:18 UTC, ilayn commented on scipy/linalg/autosol.py
> +    C = A  # working copy
Python doesn't make copies in assignments. You have to make explicit copies via `C = A.copy()`

2020-09-03 08:18 UTC, ilayn commented on scipy/linalg/tests/test_autosolve.py
> +print()
Tests never prints out anything. You can check the other test files for examples for example `linalg/tests/test_basic.py` for inspiration. The results should be asserted and test suite will pickup the success/fail signals automatically.

2020-09-03 08:27 UTC, ilayn commented
> I was a professional mathematician and software developer for decades, and I understand all the code maintence issues, and have taught code development at the university levelm but I just don't understand GitHub and have NO ONE I can get personal help from. I know no one who uses it as a developer.

Welcome to the club :) Git is ... well let's not waste time on complaining. I know exactly how you feel. It is basically a projection of the mindset of its creator. But on its usage, basically everyone uses it and it is truly the industry standard now. So once you get past of its horrific user interface it is indeed a fantastically powerful tool. The only thing we have to keep in mind is that the user interface is an overloading mess. Same command switch behaves differently if there are other switches change state. Thus requires some frustration and time.

> Here is the result: typical solvers such a lstsq cannot see that they are producing garbage when the system is poorly conditioned, though the matrix is nowhere near being singular.

As you know if the system is square, matlab basically doesn't try to switch to QR solvers it basically gives up with a warning/error in the face of singularity or ill-condition cases. For `lstsq` the story is different as you very well know, this is to do with which LAPACK driver we call and with which parameters. Hence the reason why most behave similarly is because they call the same routine including matlab, scipy, mathematica etc. and none rolls out their own solvers due to industry standards/expectations/conventions.

2020-10-13 10:31 UTC, rgommers commented
@ilayn you posted code and a diagram recently for an equivalent function to the Matlab backslash operator. From the description of this PR, `autosol` is most similar to that it seems (right?).

It seems like a similar higher-level diagram for this PR could be very useful.

2020-10-13 18:09 UTC, rejones7 commented
If I can provide a better explanation please let me know.
As I explained in the (overly long) explanation, this package builds successively on itself:

arlsnn()
     |
arlsgt()
    |
arlseq()
    |
  arls()


________________________________
From: Ralf Gommers <notifications@github.com>
Sent: Tuesday, October 13, 2020 4:32 AM
To: scipy/scipy <scipy@noreply.github.com>
Cc: rejones7 <rejones7@msn.com>; Author <author@noreply.github.com>
Subject: Re: [scipy/scipy] ENH Adding AUTOSOL file with a package of robust linear equation solvers which detect and handle ill-conditioniong (#12755)


@ilayn<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Filayn&data=02%7C01%7C%7C65b4bd656aa84109bccf08d86f6340da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637381819357947060&sdata=ZZPjDZOf22TX7smmQeEYOoBmzyn%2F0%2BXjemKyr5RD9Qs%3D&reserved=0> you posted code and a diagram recently for an equivalent function to the Matlab backslash operator. From the description of this PR, autosol is most similar to that it seems (right?).

It seems like a similar higher-level diagram for this PR could be very useful.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23issuecomment-707649452&data=02%7C01%7C%7C65b4bd656aa84109bccf08d86f6340da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637381819357947060&sdata=SrINJC%2FWyMM5znLlaQ%2B1uXgn0qABMmXpcTTqiJGkH6Y%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPWVH7BOIMPJ7K6KLT6S3M3SKQUC5ANCNFSM4QINLM6A&data=02%7C01%7C%7C65b4bd656aa84109bccf08d86f6340da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637381819357947060&sdata=sf4fYuGlvoDv8xQsw0dtQXWQZRX%2FQw%2Fsku1UswcED6Y%3D&reserved=0>.

2020-10-13 22:02 UTC, rejones7 commented
Yes, I agree that some such merge might be best.
I don't mind a name change either.

But I just really don't understand what you mean by "silent exception" in the case of arls().
Arls() is specifically intended to handle ANY degree of ill-behavior, singularity, etc - on the part of A and b, with absolutely no problem.
I have no idea what I would diagnose to the user.

To borrow a title from the mystery writer, Raymond Chandler, "Trouble is My Business!".
"Give arls() your hardest, your most ill-behaved, your most singular problems! Please! Arls() eats them for breakfast!"

I hope you can take a couple of minutes and look at this example I prepared for you managers of scipy...
http://www.rejones7.net/Autosol/DemoArlsVsLsmr/index.htm

Thanks for your interest and time! I know what it is to be overwhelmed at work! (and home)
Take care.
Ron

________________________________
From: Ilhan Polat <notifications@github.com>
Sent: Tuesday, October 13, 2020 3:52 PM
To: scipy/scipy <scipy@noreply.github.com>
Cc: rejones7 <rejones7@msn.com>; Mention <mention@noreply.github.com>
Subject: Re: [scipy/scipy] ENH Adding AUTOSOL file with a package of robust linear equation solvers which detect and handle ill-conditioniong (#12755)


I am indeed trying to find more time to finish #12824<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12824&data=02%7C01%7C%7C9b1f6ead899b426b3ac808d86fc250c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382227645663877&sdata=XsY5kxSNxjtpBmBfV4Hl9kZy1lPQxN1BgKmOeA7%2Ft4A%3D&reserved=0> which implements the backslash then I am hoping to get back to this. Sorry for the delay @rejones7<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frejones7&data=02%7C01%7C%7C9b1f6ead899b426b3ac808d86fc250c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382227645673872&sdata=831v8IjwO4sI1FRfM4%2FtHzQxK6KwJt5Pe%2F3h%2B0GLbL8%3D&reserved=0>, work is keeping me too busy these days. I can't do much other than commenting once in a while.

I am very much in favor of arming lstsq with these functionalities especially the nonnegative solution. I have some reservations about the separate function for two main reasons:

  *   autosol is a very very ambitious name and would signal the user more power than it actually possesses.
  *   As I mentioned some comments ago, an error is much appreciated in Python rather than the criminal "silent exception" behavior of matlab. So at least it should be in the form of an explicit switch such that the user might choose to shoot their own feet.

This is not to say that it is not worth or belittle your contribution but more like adopting into the existing SciPy linalg catalogue. Otherwise, as I said, lstsq() can be armed with these.

If I can ever finish #12824<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12824&data=02%7C01%7C%7C9b1f6ead899b426b3ac808d86fc250c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382227645673872&sdata=4m8Py%2Bwg4A6TeO6iMNWBAqElr5AWpfHjufTIVxQQVYA%3D&reserved=0> we are hoping to get the rectangular system solver inside linalg.solve hence if that unicorn comes to be, then lstsq will attract only specific least squares solution seekers and these extras would fit nicely if we can bring it to production.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23issuecomment-708029562&data=02%7C01%7C%7C9b1f6ead899b426b3ac808d86fc250c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382227645683864&sdata=TXff6fFJkG4v9untM7DGLwF5fV3LmFOW0RCvLiFq6IA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPWVH7HBPBKDKUNWGAXUEA3SKTD2XANCNFSM4QINLM6A&data=02%7C01%7C%7C9b1f6ead899b426b3ac808d86fc250c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637382227645683864&sdata=ZFqCyO9E2T2iJmpueWrGFi5L37UsD9AftReDHzgtCJY%3D&reserved=0>.

2020-10-13 22:20 UTC, ilayn commented
Ah yes, what I mean by silent exception is that things happen without letting user know about it. Moreover, if an error occurs it basically decides internally with no way of knowing what happened. In other words, 

> it knows what difficulties it is dealing with

but we don't. Hence if the user doesn't want this much smartness it shouldn't try to outsmart the user. But of course there is a balance to strike, not everything can be left for user choices to avoid the function becoming a flight cockpit. So I'm exaggerating a bit. 

And probably still under the influence of your early explanation about "never returning error" behavior.

2020-10-16 19:19 UTC, rejones7 commented
A day or two ago I uploaded a later version of autosol, and did not document it here. Sorry.

First, there was objection to the name autosol(), so I changed it to arls(),
meaning Automatically Regularized Least Squares.
(Turns out that was a problem too, which I will address a little later.)

Arls.py responds to requests the arls() give the user some feedback about the solution process, as it was "silent".

Each solver now returns:
-- the tradition numerical rank of A ( I checked other current solvers in scipy to be sure I was doing this in the same exact way)
-- the "usable rank" which involves both A and b, and is the crucial artifact needed to do autoregularization
-- the estimate of the right-hand-side RMS error, sigma.
-- the resulting Tikhonov regularization parameter, lambda

(The in-code comments have been updated.)

And, The test_arls() code has been updated to use one function per test, as best as I understand how to do it at this point

By the way, I am not seeking to REPLACE any current scipy solvers. 
Arls contains new techniques and should only be an additional feature, I think.

Rondall Jones

2020-10-17 06:09 UTC, rejones7 commented
When I switched my package's name from autoreg to arls, I forgot to check it on Google.
So it was pointed out to me that the name "arls" already has a use as a least-squares solver.

Possible names that do NOT have significant collisions on Google include arles, aregls, auregls,
or names like lsmr, including lsar and lsareg. (But "lsa" itself has lots of matches on Google.)

Of all these I think I prefer "arles", as Automatically Regularized LEast Squares. It has no matches except
the town in France where Van Gogh lived.

If there is no particular objection to "arles" I will switch to that.

2020-10-17 12:24 UTC, rlucas7 commented
I like the arles name and I’m not aware of any least squares based algorithm that conflicts. 

-Lucas

> On Oct 17, 2020, at 2:09 AM, rejones7 <notifications@github.com> wrote:
> 
> ﻿
> When I switched my package's name from autoreg to arls, I forgot to check it on Google.
> So it was pointed out to me that the name "arls" already has a use as a least-squares solver.
> 
> Possible names that do NOT have significant collisions on Google include arles, aregls, auregls,
> or names like lsmr, including lsar and lsareg. (But "lsa" itself has lots of matches on Google.)
> 
> Of all these I think I prefer "arles", as Automatically Regularized LEast Squares. It has no matches except
> the town in France where Van Gogh lived.
> 
> If there is no particular objection to "arles" I will switch to that.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-17 19:51 UTC, WarrenWeckesser commented
I can bikeshed with the best of them...

There are several object names in SciPy that include some sort of abbrevation for "least squares" in the name:

```
interpolate.LSQBivariateSpline
interpolate.LSQSphereBivariateSpline
interpolate.LSQUnivariateSpline
interpolate.make_lsq_spline

linalg.lstsq

optimize.least_squares
optimize.leastsq
optimize.lsq_linear
optimize.nnls

signal.firls

sparse.linalg.lsmr
sparse.linalg.lsqr
```
So we already have `least_squares`, `leastsq`, `lstsq`, `lsq` and `ls`.  It would be nice to pick one those rather than introduce another acronym.  (Personally, I would never guess that `les` has anything to do with least squares.)

2023-01-25 21:27 UTC, rejones7 commented
Wow, these comments are from 2 years ago!

I finally just uploaded the final product to the contributed library as arls.
it installs with "pip install arls".
It has been downloaded about once a day (not counting mirrors) since I contributed it in 2021.
There have been no requests for changes, bugs, or enhancements.

If you are interested in upgrading it to scipy I would be interested.

Ron Jones
________________________________
From: Ilhan Polat ***@***.***>
Sent: Thursday, September 3, 2020 2:18 AM
To: scipy/scipy ***@***.***>
Cc: rejones7 ***@***.***>; Author ***@***.***>
Subject: Re: [scipy/scipy] ENH Adding AUTOSOL file with a package of robust linear equation solvers which detect and handle ill-conditioniong (#12755)


@ilayn requested changes on this pull request.

I couldn't find too much time and below are very very quick glance review. I'll come back asap I have some time.

________________________________

In scipy/linalg/autosol.py<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23discussion_r482789674&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385869655&sdata=cJ%2FdXlQ3PNgjxtWB%2F4fH7NW6wLPcivLdNA07L%2BDuvYc%3D&reserved=0>:

> @@ -0,0 +1,405 @@
+from math import sqrt
+import numpy as np
+from numpy import atleast_1d, atleast_2d
+# import scipy.linalg.decomp_svd
+from scipy.linalg.decomp import _asarray_validated
+# from scipy.linalg.misc import LinAlgError, _datacopied, LinAlgWarning
+from scipy.linalg.misc import LinAlgError
+
+# Author : Rondall E. Jones, August 2020
+
+
+def two_norm(x):


This is basically a rewrite of scipy.linalg.norm

________________________________

In scipy/linalg/autosol.py<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23discussion_r482789975&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385879649&sdata=iaHfq2ZfCHEzzbP2tWD%2BIr7iIHaaZNATSqeF53mm9Zk%3D&reserved=0>:

> +def two_norm(x):
+    """ Computes two-norm of 1-D array x without overflow"""
+    ln = len(x)
+    if ln == 0:
+        return 0.0
+    y = abs(x)
+    mx = max(y)
+    if mx == 0.0:
+        return 0.0
+    sm = 0.0
+    for i in range(0, ln):
+        sm += (x[i] / mx) ** 2
+    return mx * sqrt(sm)
+
+
+def rms(x):


as above you can do scipy.linalg.norm(a)/len(a)

________________________________

In scipy/linalg/autosol.py<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23discussion_r482791986&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385879649&sdata=lJitokfUHg4z1YU7tKeYEvs%2Fo3BiEl0n9xB0ZFoujpE%3D&reserved=0>:

> +    mx = max(y)
+    if mx == 0.0:
+        return 0.0
+    sm = 0.0
+    for i in range(0, ln):
+        sm += (x[i] / mx) ** 2
+    return mx * sqrt(sm)
+
+
+def rms(x):
+    """ Computes root-mean-square of 1-D array x without overflow"""
+    s = two_norm(x)
+    return s / sqrt(len(x))
+
+
+def compute_mov_sums(g, w, m):


Also here you can use convolution as in np.convolve(g ,np.ones(w, dtype=int),'valid') or whichever behavior you prefer (see numpy.convolve docstring)

________________________________

In scipy/linalg/autosol.py<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23discussion_r482793569&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385879649&sdata=9fBOvXbRlXGVO8FoiTI6VDjeZwlJSAb4bFzySMsCpho%3D&reserved=0>:

> +    -------
+    Exactly as autosolve above
+    """
+    A = atleast_2d(_asarray_validated(A, check_finite=True))
+    b = atleast_1d(_asarray_validated(b, check_finite=True))
+    m = A.shape[0]
+    n = A.shape[1]
+    if b.shape[0] != m:
+        raise LinAlgError("Inconsistent array sizes.")
+    z = np.zeros(n)
+    if np.count_nonzero(A) == 0:
+        return z, 0, 0.0, 0.0
+    if np.count_nonzero(b) == 0:
+        return z, 0, 0.0, 0.0
+
+    C = A  # working copy


Python doesn't make copies in assignments. You have to make explicit copies via C = A.copy()

________________________________

In scipy/linalg/tests/test_autosolve.py<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23discussion_r482794580&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385889644&sdata=cu1brRZ0PpS2mJl33DmAvBgWSGDTjpDfDTWyf%2Fsx01I%3D&reserved=0>:

> +from autosol import (autosolve, autosolve_nonneg,
+                     autosolve_rising,two_norm)
+# when autosol is online...
+# from scipy.autosol import (autosolve, autosolve_nonneg,
+#                   autosolve_rising, two_norm)
+
+
+# inconsistent arrays .. these crash the run
+# A=np.zeros((3,3))
+# b=np.zeros(5)
+# x=autosolve(A,b)[0]
+# x=autosolve_nonneg(A,b)[0]
+# x=autosolve_rising(A,b)[0]
+
+# 0-D
+print()


Tests never prints out anything. You can check the other test files for examples for example linalg/tests/test_basic.py for inspiration. The results should be asserted and test suite will pickup the success/fail signals automatically.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscipy%2Fscipy%2Fpull%2F12755%23pullrequestreview-481597607&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385889644&sdata=3kdEMx5gEOUtCtd7C%2BlGXC7%2BlXAjyEcmZUenMv9HciQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPWVH7BLGJL6OAVFQ4NUGKTSD5GPDANCNFSM4QINLM6A&data=02%7C01%7C%7C9c39414582154b184dd908d84fe201ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637347179385899638&sdata=n6lscIL%2Bt3q7zhjLId8OaRRD6tlVuw7VGjNi3ot3nf8%3D&reserved=0>.

2024-01-16 14:20 UTC, lucascolley commented
> I finally just uploaded the final product to the contributed library as arls.
it installs with "pip install arls".

Is the source on GitHub somewhere?

2024-01-16 15:50 UTC, rejones7 commented
I haven’t touched done any python for a couple of years. Please explain more about this to me.
Ron
Sent from my iPhone

On Jan 16, 2024, at 7:21 AM, Lucas Colley ***@***.***> wrote:

﻿

I finally just uploaded the final product to the contributed library as arls.
it installs with "pip install arls".

Is the source on GitHub somewhere?

—
Reply to this email directly, view it on GitHub<https://github.com/scipy/scipy/pull/12755#issuecomment-1893841795>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APWVH7CNTORHZHLO44R7JULYO2EEVAVCNFSM4QINLM6KU5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCOBZGM4DIMJXHE2Q>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-01-16 15:54 UTC, rejones7 commented
I finally realized what you were asking.
Yes the source is on Github. But if you install it you get the source, so I don’t understand what you need.
Sent from my iPhone

On Jan 16, 2024, at 8:50 AM, rondall jones ***@***.***> wrote:

﻿ I haven’t touched done any python for a couple of years. Please explain more about this to me.
Ron
Sent from my iPhone

On Jan 16, 2024, at 7:21 AM, Lucas Colley ***@***.***> wrote:

﻿

I finally just uploaded the final product to the contributed library as arls.
it installs with "pip install arls".

Is the source on GitHub somewhere?

—
Reply to this email directly, view it on GitHub<https://github.com/scipy/scipy/pull/12755#issuecomment-1893841795>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APWVH7CNTORHZHLO44R7JULYO2EEVAVCNFSM4QINLM6KU5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCOBZGM4DIMJXHE2Q>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-01-16 16:24 UTC, rejones7 commented
My GitHub account is just "rejones7".
I have forgotten how to use github so I hope that helps.

But actually I would not recommend you look at that version.
After years of revamping this method I was able to develop a much much shorter version which is theoretically and practically better, but it is only on MATLAB right now. Would you be interested in converting it?
I will attach the code.
It uses a lot of vectorized coding, which may be a barrier.
There was a write up about this new method here:
https://blogs.mathworks.com/cleve/2023/06/16/arls-automatically-regularized-least-squares/
[http://blogs.mathworks.com/cleve/files/arls_0.bmp]<https://blogs.mathworks.com/cleve/2023/06/16/arls-automatically-regularized-least-squares/>
ARLS, Automatically Regularized Least Squares<https://blogs.mathworks.com/cleve/2023/06/16/arls-automatically-regularized-least-squares/>
(I have a guest blogger today. Ron Jones worked with me in 1985 for his Ph. D. from the University of New Mexico. He retired recently after nearly 40 years at Sandia National Labs in Albuquerque and now has a chance to return to the problem he studied in his thesis. -- CBM)by Rondall Jones, ***@***.*** interest is
blogs.mathworks.com

________________________________
From: Lucas Colley ***@***.***>
Sent: Tuesday, January 16, 2024 9:01 AM
To: scipy/scipy ***@***.***>
Cc: rejones7 ***@***.***>; Mention ***@***.***>
Subject: Re: [scipy/scipy] ENH Adding AUTOSOL file with a package of robust linear equation solvers which detect and handle ill-conditioniong (#12755)


Above you said "If you are interested in upgrading it to scipy I would be interested."

I took this to mean that you would like someone to review the source for the possibility of including it in SciPy. In which case, a link to the source code (without having to first install from PyPy, e.g. a link to a public GitHub repo), would be helpful.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy/scipy/pull/12755#issuecomment-1894040142>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APWVH7DVIECJ363PV4J3CULYO2P5VAVCNFSM4QINLM6KU5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCOBZGQYDIMBRGQZA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

function x=arls(A,b)
%
% Automatically Regularized Least Squares solution of 
% linear systems of equations.
%
% Copyright (C) 2023, Rondall E. Jones
% Vectorization coded by Cleve B. Moler
% BSD license: http://opensource.org/licenses/BSD-3-Clause
% Date: May 2023
% Contact: ***@***.***
%
% Usage
% x=arls(A,b)
% where A is a matrix of size m by n, where m can be less than,
% or equal to, or more than n, and b is of length m.
% Resulting x is of length n.
%
% Please be sure to check that x is an appropriate solution
% for your situation. 
% In particular check the residual, r = A*x-b.
% Note r can often be used as an estimate of the error in b. 
%
% ARLS is intended for solving ill-conditioned linear 
% systems of any shape or size. 
% By ill-conditioned, we mean that the solution is 
% unacceptably affected by insignificant changes in b.
% Such systems often arise, for example, in inverse problems
% in which the analyst is trying to reverse the effects of 
% natural smoothing processes such as heat dissipation 
% or the effects of indirect sensing.
%
% ARLS generally tolerates singularity (zero or near zero 
% singular values) and other intrinsic difficulties 
% such as linear dependencies between rows.
% If for any reason ARLS' algorithm fails a default
% regularized solution is still returned.
% There are no error exits in ARLS.
%
% Method
% ARLS is a new regularized solution method based on the 
% notion popularized by P C Hansen as the "Picard Condition"
% which suggests that when the solution is represented as an 
% orthogonal expansion, then the coefficients of the
% expansion should decline if a well-behaved solution is to 
% be expected.
% Using the Singular Value Decomposition, A=USV', then
%   USV'x=b   gives   x=V*inv(S)*U'*b,   or x=V*P,
% where P a the set of coefficients of an orthogonal 
% expansion of x in terms of the columns of V.
% ARLS works by finding the smallest Tikhonov regularization
% parameter, lambda, that makes P decline. 
% Due to erratic behavior that generally shows up in P 
% we use a low-degree polynomial fit to P instead of using 
% P directly. And we work with the logarithm of P rather
% than P tself in order to better see the behavior of the 
% smallest elements of P.
%
% Also see ARLSNN(A,b) and ARLSRISE(A,b).
%
% Example: Run this in the Matlab window:
%
% x = [6,5,4,3,2,1,0]'; % ideal solution
% A = hilb(7);          % Hilbert test matrix
% b = A*x + 0.0001*randn(7,1); % add noise to RHS
% A\b                   % simple solution
% arls(A,b)             % autoregularized solution
%
% For reference to this method please mention
% our "Logarithmic Picard Condition Analysis"
%
% initializations
[m,n]=size(A);
mn = min(m,n);
[U,S,V]=svd(A);
if nnz(A)==0 || nnz(b)==0 || nnz(S)==0 || mn==0
    x = zeros(n,1);
    return
end   
s = diag(S);
smax = max(s);
smin = min(s(s>0));
if mn<3 || (smin>smax*0.01)
    Sinv=S';
    for i=1:mn
        if Sinv(i,i)>0.0
            Sinv(i,i)=1.0/Sinv(i,i);
        end
    end
    x = V*Sinv*U'*b;
    return
end
seps = 1.0e-10*smax;      
s(s==0) = seps;
beta = U'*b; % "beta" refers to a transformed "b"
z = (1:mn)'; % parabola axis
beta = beta(z); % resize
beta(beta==0) = seps;

% Phase 1: search for min lambda that makes 
% slope of parabolic fit to PCV negative
g = zeros(mn,1);
gg = g;       % log of scaled version of g
gok = g;      % acceptable value of g
lamb = smax*1.0E-9; % Tikhonov lambda parameter
lambok = 0.0; % acceptable value of lambda
ok = false;
factor1=[10.,2.,1.2,1.05];
for ilamb=1:4
    while lamb<smax
        lambprev = lamb;
        lamb = lamb*factor1(ilamb);
        g = beta.*s./(s.*s + lamb*lamb);
        gref = max([abs(g(1)),abs(g(2)),seps]); 
        gg = log10(max(abs(g/gref),seps));
        % assess slope 
        p=polyfit(z,gg,1);
        ps1=p(1);
        p=polyfit(z,gg,2);
        ps2=0.0;
        for i=1:mn
            % max parab slope
            ps2 = max([ps2, 2.*p(1)*z(i) + p(2)]); 
        end
        ps=min(ps1,ps2);
        if ps<=0.0    
            %lamb is big enough; loop to use finer multiple
            ok = true;
            gok = g;
            lambok = lamb;
            lamb = lambprev; % back up one iteration
            break % while
        end % if
    end % while
end % for

if ~ok  % create default solution
    % use lambda = geometric mean of largest
    % and smallest non-zero singular values.
    "Default Solution"
    ms = min(s(s>0));
    gmean = sqrt(ms*max(s));
    for i=1:mn
        S(i,i) = 1.0/max(S(i,i),gmean);
    end
    x = V*S'*U'*b;
    return
end

% Phase 2: loosen
% trim V for underdetermined systems
if m<n
    V(:,m+1:n) = [];
end
x = V*gok;
resid1 = norm(A*x-b); % starting residual
sref = S(1,1);
lamb = lambok;        % starting lambda
while lamb<sref
    lamb = lamb*1.2;  
    g = beta.*s./(s.*s + lamb*lamb);
    x = V*g;
    resid = norm(A*x-b);
    if resid>2*resid1
        break
    end
end
return

2024-01-16 16:50 UTC, lucascolley commented
Thanks for the explanation. Usually we can't take from MATLAB code due to incompatible licenses, but since your source code has its own 3-clause BSD license, I think it would be fine to include in SciPy (I may be wrong).

I'm not personally interested in converting it, but it sounds like that would be the best thing to do if someone wants to add these features.

In light of what I've said, I think it makes sense to close this PR (which is now outdated) and open an issue, so that anyone who would like to work on this can find your MATLAB code. If that sounds wrong to you, let me know!

---

As an aside, I looked on your `rejones7` GitHub account, but it doesn't have the source for `arls`. The only public repositories are a fork of NumPy and a fork of SciPy.

2024-01-16 16:50 UTC, closed without merging