BUG: fix `scipy.optimize.show_options` for unknown methods. and add *_METHODS list for each solver script and fix show_options doc
scipy/scipy pull request #13054
Opened 2020-11-09 12:29 UTC by AtsushiSakai

#### Reference issue
fix #10782 

#### What does this implement/fix?
I fixed `scipy.optimize.show_options` for unknown methods and added a test for it.
I added a global *_METHODS list for each solver script which is proposed in #10782 
I fixed `show_options` docstring because it is missing `scipy.optimize.root_scalar` doc links.

2020-11-18 19:54 UTC, mdhaber commented on scipy/optimize/optimize.py
> +    `scipy.optimize.root_scalar`
Need to mention this in Parameters:
`Type of optimization solver. One of ‘minimize’, ‘minimize_scalar’, ‘root’, or ‘linprog’.`

2020-11-18 19:58 UTC, mdhaber commented on scipy/optimize/_linprog.py
> +LINPROG_METHODS = ['simplex', 'revised simplex', 'interior-point']
```suggestion
LINPROG_METHODS = ['simplex', 'revised simplex', 'interior-point', 'HiGHS', 'HiGHS-ds', 'HiGHS-ipm']
```

2020-11-18 20:02 UTC, mdhaber commented on scipy/optimize/_linprog.py
> +LINPROG_METHODS = ['simplex', 'revised simplex', 'interior-point']
Can you also add these to show_options?

2020-11-18 20:04 UTC, mdhaber commented
> I fixed scipy.optimize.show_options for unknown methods and added a test for it.

What was wrong with it for unknown methods?

2020-11-19 12:07 UTC, AtsushiSakai commented
@mdhaber I'm sorry this PR is messed up... I will recreate another PR.

2020-11-19 21:26 UTC, mdhaber commented
@AtsushiSakai You can use this one again. All it took was to change the branch this is to be merged into from master to something else and then back again.
![image](https://user-images.githubusercontent.com/6570539/99726064-ddbd4200-2a6a-11eb-87f2-f8b64669e623.png)

2020-11-19 21:44 UTC, mdhaber requested changes
Thanks for this. Nice cleanup. 

You wrote:
> I fixed `scipy.optimize.show_options` for unknown methods and added a test for it

But this was already working correctly:
```
In [3]: show_options(solver='linprog', method='ekki')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-d5a93c37d4fb> in <module>
----> 1 show_options(solver='linprog', method='ekki')

~\Desktop\scipy\scipy\optimize\optimize.py in show_options(solver, method, disp)
   3515             methods = dict(doc_routines[solver])
   3516             if method not in methods:
-> 3517                 raise ValueError("Unknown method %r" % (method,))
   3518             name = methods[method]
   3519

ValueError: Unknown method 'ekki'
```
I don't see any changes to this part of the code, and I don't see a test for unknown methods (only valid solvers and methods). It would help to add tests that the `ValueError` is raised when the solver/method is unknown.

2020-11-19 21:44 UTC, mdhaber commented on scipy/optimize/tests/test_optimize.py
> +            show_options(solver, method)
```suggestion
            # testing that `show_options` works without error
            show_options(solver, method)
            
```
PEP8 newline at the end of file

2020-11-19 21:44 UTC, mdhaber commented on scipy/optimize/tests/test_optimize.py
> +            show_options(solver, method)
Add tests for what happens with unrecognized solver and method.

2020-11-19 21:44 UTC, mdhaber commented on scipy/optimize/_minimize.py
> +MINIMIZE_SCALAR_METHODS = ['Brent', 'Bounded', 'Golden']
```suggestion
MINIMIZE_SCALAR_METHODS = ['brent', 'bounded', 'golden']
```
Not at all important, but this would be more consistent.

2020-11-19 21:45 UTC, mdhaber commented
If you make these changes and we get CI green, I'll merge this so it's fixed for 1.6.

2020-11-20 18:49 UTC, mdhaber requested changes
Thanks for the changes. Besides this, everything else looks good to me! Current failures seem to be intermittent and unrelates, and I don't think the codecov report is correct for this PR, so after this I'll wait for comments from others then squash merge. In the future @AtsushiSakai please review [here](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message) for commit message suggestions. For instance, the commit message might have been:
`MAINT: optimize: update show_options with new solvers/methods and add tests`

2020-11-20 18:49 UTC, mdhaber commented on scipy/optimize/tests/test_optimize.py
> +        assert_raises(ValueError, show_options, solver, method)
```suggestion
        assert_raises(ValueError, show_options, solver, method)
        
```
PEP8 newline.

2020-11-21 06:02 UTC, AtsushiSakai commented
@mdhaber Thank you for reviewing and providing the link. I will review it and follow it from the next PR.

2020-11-27 02:30 UTC, mdhaber commented
Triggered rebuild. I'll merge when it's done.

2020-11-27 03:23 UTC, merged

2020-11-27 04:07 UTC, mdhaber commented
Thanks @AtsushiSakai!