The error message “Domain error in arguments” could be more informative
scipy/scipy pull request #13172
Opened 2020-11-30 03:10 UTC by ZhihuiChen0903

The error message “`Domain error in arguments`” seems too general to be informative.

```
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py in rvs(self, *args, **kwds)
    938         cond = logical_and(self._argcheck(*args), (scale >= 0))
    939         if not np.all(cond):
--> 940             raise ValueError("Domain error in arguments.")
    941 
    942         if np.all(scale == 0):
```

After reading the source, I believe that the expected behavior is that shape parameters should be positive and scale should >=0. Adding this information to the error message should be more user-friendly.

Expected error message:
`Domain error in arguments: shape parameters should be positive and scale should >=0.`

2020-12-01 10:26 UTC, rgommers requested changes
Thanks @ZhihuiChen0903. A better error message would be nice, but unfortunately this change is not correct - distributions define their own `_argcheck` that overrides the default one, so it's not just "must be positive". There's no easy way to get this right I'm afraid.

2020-12-07 06:55 UTC, mdhaber commented on scipy/stats/_distn_infrastructure.py
> +            raise ValueError("Domain error in arguments:shape parameters should be positive and scale should >=0")
```suggestion
            message = ("Domain error in arguments. The `scale` parameter must "
                       "be positive for all distributions; see the distribution "
                       "documentation for other restrictions.")
            raise ValueError(message)
```

2020-12-07 06:56 UTC, mdhaber commented on scipy/stats/_distn_infrastructure.py
> +            raise ValueError("Domain error in arguments:shape parameters should be positive and scale should >=0")
Here's a thought.

2021-01-10 17:24 UTC, mdhaber commented on scipy/stats/_distn_infrastructure.py
> +            raise ValueError("Domain error in arguments:shape parameters should be positive and scale should >=0")
@ZhihuiChen0903 would this be helpful?

2022-02-21 09:01 UTC, mdhaber commented
No need for this to wait. I don't imagine there will be problems, but I'll re-run CI (close and re-open) and merge if it's green.

2022-02-21 17:09 UTC, mdhaber commented on scipy/stats/_distn_infrastructure.py
> +                       "documentation for other restrictions.")
```suggestion
            message = ("Domain error in arguments. The `scale` parameter must "
                       "be positive for all distributions; see the "
                       "distribution documentation for other restrictions.")
```

2022-02-21 17:51 UTC, mdhaber commented
Might be helpful to use an f-string to mention the name of the distribution (e.g. "see `weibull_min` documentation"), and perhaps it should be phrased so that it's more clear that `scale` is not _necessarily_ the problem. But lint passes, and this is more informative than it was, so merging.

Thanks, @ZhihuiChen0903! Next time, please create a feature branch instead of using `master` (now `main`) for PRs, but thanks for submitting this.

2022-02-21 17:52 UTC, merged