Perimosocordiae patch 5
scipy/scipy pull request #13403
Opened 2021-01-19 19:42 UTC by perimosocordiae

#### Reference issue
Fixes gh-13329

#### What does this implement/fix?
Propagates the `dtype` parameter through the intermediate COO format constructor.

2021-01-20 00:07 UTC, tylerjereddy reviewed
@perimosocordiae When I run this feature branch with the original example code in the matching issue I still get a traceback (below). Is there still something off in the original reproducer from @matteodellamico?

```
scipy.__version__: 1.7.0.dev0+7185d00
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    assert v == data[i], (i, data[i], v)
AssertionError: (4, 14115858573662012539, 14115858573662013440)
```

2021-01-20 00:25 UTC, perimosocordiae commented
Did you use the fixed reproducer? The original version could have duplicate entries.

2021-01-20 00:59 UTC, tylerjereddy commented
I thought I did--I believe the author edited the code and I copy-pasted from there.

2021-01-20 03:06 UTC, WarrenWeckesser requested changes
The test passes in the master branch, because `2**63` happens to be a number that survives the round trip through floating point.  The big value used in the test should be changed to, say, `2**63 + 1`.

The test will then fail, because the fix is not complete.  The `dtype` has to be passed to the `array` function that is eventually called at https://github.com/scipy/scipy/blob/01838d2c2ce0fee9bb9e62da1a4f10d63fe9b36f/scipy/sparse/coo.py#L159

2021-01-27 04:53 UTC, perimosocordiae commented
Thanks for the double-checking @tylerjereddy and the explanation @WarrenWeckesser. I learned something new about the way numpy does dtype inference today:

```
In [1]: np.array([2**64 - 1]).dtype                                                                                                      
Out[1]: dtype('uint64')

In [2]: np.array([2**64 - 1] * 5).dtype                                                                                                  
Out[2]: dtype('uint64')

In [3]: np.array([2**64 - 1, 2**32 - 1]).dtype                                                                                           
Out[3]: dtype('float64')
```

With my latest commit, this bug should actually now be fixed.

2021-01-27 07:21 UTC, WarrenWeckesser requested changes
One small PEP-8 change, otherwise looks good.

2021-01-27 07:21 UTC, WarrenWeckesser commented on scipy/sparse/compressed.py
> +                    other = self.__class__(coo_matrix(arg1, shape=shape, dtype=dtype))
PEP-8 line length.
```suggestion
                    other = self.__class__(coo_matrix(arg1, shape=shape,
                                                      dtype=dtype))
```

2021-01-29 01:36 UTC, WarrenWeckesser approved these changes

2021-01-30 14:25 UTC, merged

2021-01-30 14:26 UTC, WarrenWeckesser commented
Merged, thanks @perimosocordiae!