DOC: Added math notation in examples in ltisys.py
scipy/scipy pull request #13513
Opened 2021-02-05 21:56 UTC by nosseb

Added `.. math::` notation to the transfer function in a bunch of examples, as it makes online documentation easier to read.

This commit does not cover State Space notation as I'm unfamiliar with it and current doctring don't provide any baseline.

Also, I don't know how to build the html documentation, but it's basic TeX so shouldn't cause any issue.

2021-02-16 10:23 UTC, rgommers commented
Thanks @nosseb. We try to use LaTeX sparingly to keep things readable in an editor or terminal, but it seems to be appropriate here. Fractions are easier to read rendered.

The doc build timed out due to an unrelated issue, I've rebased on master to get rid of that.

2021-02-16 12:19 UTC, rgommers commented
CI doc build worked, other failures are unrelated. @nosseb do you want to add more changes, or is this ready? If the latter, can you move the PR out of "draft"?

2021-02-16 12:43 UTC, ilayn requested changes
I've placed some minor remarks, you can see the results in the CI artifact https://26703-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.signal.ZerosPolesGain.html#scipy.signal.ZerosPolesGain

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(s) = \frac{5(z - 1)(z - 2)}{(z - 3)(z - 4)}
This should be `H(z)`

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    ..math:: H(s) = \frac{5(s - 1)(s - 2)}{(s - 3)(s - 4)}
These won't render without indentation

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    ..math:: H(s) = \frac{5(s - 1)(s - 2)}{(s - 3)(s - 4)}
Also they can be inline no need for extra lines

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    ..math:: H(s) = \frac{5(z - 1)(z - 2)}{(z - 3)(z - 4)}
Same as above, inline is fine

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(s) = \frac{5(s - 1)(s - 2)}{(s - 3)(s - 4)}
Same issue as above

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(s) = \frac{5(s - 1)(s - 2)}{(s - 3)(s - 4)}
Same issue

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(s) = \frac{5(z - 1)(z - 2)}{(z - 3)(z - 4)}
Same issue

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(s) = \frac{5}{(s-1)^3}
Same issue

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(z) = \frac{1}{z^2 + 2z + 3}
Same issue and missing the dt info

2021-02-16 12:43 UTC, ilayn commented on scipy/signal/ltisys.py
> +    .. math:: H(z) = \frac{1}{z^2 + 2z + 3}
Same issue and missing the dt info

2021-02-16 22:06 UTC, nosseb commented
Thanks @rgommers for explaining the timing-out build. Also I had been unsuccessful in setting-up build pipeline on my machine and thus kinda dropped the whole thing for a moment.

I hope my last few commits should satisfy @ilayn . I took the liberty to apply the inline equation trick to older bits of documentation as well.

I first wanted to add documentation for state space notation as well. As I have to ask a teacher for some help on that, this will have to be implemented in a subsequent pull request.

2021-02-16 22:33 UTC, ilayn approved these changes

2021-02-17 12:40 UTC, rgommers approved these changes
LGTM too now, thanks @nosseb. And thanks @ilayn for reviewing.

2021-02-17 12:40 UTC, merged