DEV: scipy.interpolate b-splines (periodic case)
scipy/scipy pull request #13701
Opened 2021-03-18 19:38 UTC by diana-sukhoverkhova

#### What does this implement/fix?
We developed and implemented an algorithm for computing coefficients for B-splines of degree ``k`` in periodic case.  The algorithm builds a matrix with ``k`` diagonals and upper right and lower left blocks of size ``(k-1)/2 x (k-1)/2`` (for now ``k`` is assumed to be odd). This matrix is stored in a form suitable for ``scipy.linalg.solve_banded``.  Due to the special form of matrix, it is possible to use Woodbury formula to optimize the computations. 

#### Additional information
In periodic case, ordinates and values of the first ``k-1`` derivatives are equal at the ends.

2021-03-23 10:46 UTC, ev-br requested changes
Initial cursory review. Did not check the algorithmic part, also `make_interp_spline` interface. Will do separately.

Full disclosure: Egor and Diana work with me at HSE, so an additional review from someone else would be nice.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    SLE - system of linear equations.
Leftover line? Can go.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    elements will intersect with diagonals.
Should be checked probably.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    is finally computed.
Can probably add the matrix structure in ASCII pseudocode here.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +        V[j, -bs + j] = 1
minor: can be done with fancy indexing, `V[np.arange(bs), np.arange(bs) - bs]` or some such.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +           and Brian P. Flannery, Numerical Recipes, 2007, 2.7.3
Sec 2.7.3 ?

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    corners.
"Solve a cyclic banded linear system with upper right and lower blocks of size `k` using the Woodbury formula" --- is this a fair description of this routine?

Then ASCII pseudocode structure of the matrix would help after the sentence of in the Notes section.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +def _periodic_nodes(x,l=1,r=1):
nit: these are periodic knots, right?

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +def _periodic_nodes(x,l=1,r=1):
space after comma please, here and elsewhere (until the linter CI job is happy)

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +        raise ValueError("n should be greater than k to form system.")
Nit: ... which system? Consider reformulating. E.g., need at least k data point to fit a spline of degree k

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +        A[:,i] = _bspl.evaluate_all_bspl(t, k, x[i], i + k)[:-1][::-1]
[::-1][::-1] looks unusual, is it really needed?

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +        ll[-i, :i] = np.copy(A[offset - i, :i])
certainly need some more docs to follow this part.

Maybe also consider writing explicit loops and move them to cython, like it's done for other boundary conditions.

2021-03-23 10:46 UTC, ev-br commented on scipy/interpolate/tests/test_bsplines.py
> -### XXX: 'periodic' interp spline using full matrices
Why removing this? Maybe better keep this and test your implementation against.
(if this version is buggy, fix it)

2021-03-25 07:50 UTC, ev-br commented
When revising this, please also add tests for the number of points smaller than and equal to k, to catch edge cases similar to k=3 CubicSpline.

2021-04-06 21:32 UTC, diana-sukhoverkhova commented
Now this implementation works with B-splines of even degree ```k```. We changed default knot vector (in Greville-like way) and added dependency on parity to construction of matrices.

2021-04-07 06:20 UTC, ev-br requested changes
It's getting closer. One more review round, algo review still pending.

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    # size of block elements
Consider reformulating

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    ab = ab[-k - (k + 1) % 2:, :]
Why? Consider re formulating (end of the matrix? Before the matrix?)

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +        ll += np.diag(ab[i, -kul - (k % 2): n - 1 + 2 * kul - i], k=-i)
This is due to the special choice of the knot vector, correct?

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    A = ab[:, kul: -k + kul]
Typo: occurE

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +
Identical to what CubcSpline does?

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/tests/test_bsplines.py
> +        # tests for axis=-1
How is this different from what's above?

2021-04-07 06:20 UTC, ev-br commented on scipy/interpolate/tests/test_bsplines.py
> +        assert_raises(ValueError, make_interp_spline, x, y, k, None,
Use 
```
with assert_raises(ValueError) :
    make_interp_spline(...) 
```

2021-05-16 10:01 UTC, ev-br approved these changes
Looks good modulo small nits, which can taken care of in a sequel or not at all. 

Am planning to merge it soon (tm), unless there are more comments --- Would be nice to have a second pair of eyes on this BTW.

2021-05-25 02:35 UTC, tylerjereddy commented
> Looks good modulo small nits, which can taken care of in a sequel or not at all.

Alright, given that the only CI failure is unrelated I'm basically relying on this assessment and my own quick scan through the code for sanity checking and I'm going to merge it. It looks like @ev-br commented on an old test being deleted, but then resolved that conversation, so I'm assuming that is "ok"/approved here.

> Full disclosure: Egor and Diana work with me at HSE, so an additional review from someone else would be nice.

Agreed, but fairly specialized stuff, and we do have folks that appear to work at the same organization merging each others PRs without too much fuss already. Nice when we can get another person to check of course.

2021-05-25 02:35 UTC, merged

2021-05-25 02:35 UTC, tylerjereddy commented
Thanks @diana-sukhoverkhova @ev-br