ENH: stats: add geometric zscore
scipy/scipy pull request #14817
Opened 2021-10-06 09:56 UTC by qbarthelemy

#### Reference issue
Closes issue #14816.

#### What does this implement/fix?
It implements `gzscore`, the geometric version of zscore.

#### Additional information
All details can be found in issue #14816.

2021-10-08 11:56 UTC, tupui requested changes
Thanks @qbarthelemy, a really good start! I have a few comments.

I did not yet look at the tests. They seem complete, but I am not sure yet if we need that much since it's calling `zscore` which is well tested.

2021-10-11 07:18 UTC, tupui reviewed
Thanks for the update.

2021-10-13 07:54 UTC, tupui requested changes

2021-10-28 08:48 UTC, tupui approved these changes
LGTM, you still have a merge conflict before we can merge. @tylerjereddy do you have other comments?

2021-10-28 16:30 UTC, tupui approved these changes
LGTM, thanks @qbarthelemy (CI failures are not related). I will wait a bit in case Tyler or someone else has something to say and merge early next week otherwise.

2021-11-15 18:06 UTC, tupui commented
Close-reopen for CI. I will merge if green

2021-11-15 19:22 UTC, merged

2021-11-15 19:23 UTC, tupui commented
Thanks @qbarthelemy!

2021-12-06 20:47 UTC, mdhaber commented on scipy/stats/mstats.py
> +from scipy.stats import gmean, hmean, zmap, zscore, gzscore, chisquare
I think that was the correct interpretation.