ENH: faster h/vstack for CSR/CSC matrices …
scipy/scipy pull request #14825
Opened 2021-10-08 22:14 UTC by ParticularMiner

#### Reference issue

(None)

#### What does this implement/fix?

Makes functions `hstack` and `vstack` of `scipy.sparse` faster for CSR and CSC matrices respectively, and thus `bmat` by extension.
 

#### Additional information

For CSR/CSC matrices the functions are 2 - 4 times as fast as before.  Here are the benchmarking results:
```python
python3 -u runtests.py --bench-compare origin/master sparse.CsrHstack
``` 

|duration<br>before <br> \[0785d6f4\] <br>  \<master\>|duration<br>after <br>\[3e80e8bc \] <br> \<csr_hstack\>|ratio|  matrix size<br> \[number of rows\] <br> number of columns = 10<sup>5</sup> <br>sparsity = 2 &times; 10<sup>-3</sup> |
|:---:|:---:|:---|---:|
|        517±30ms|          181±4ms|     0.35|  sparse.CsrHstack.time_csr_hstack(50000)|
|       1.12±0.1s|         380±10ms|     0.34|  sparse.CsrHstack.time_csr_hstack(100000)|
|        224±10ms|        74.0±10ms|     0.33|  sparse.CsrHstack.time_csr_hstack(25000)|
|        86.8±4ms|         24.0±2ms|     0.28|  sparse.CsrHstack.time_csr_hstack(10000)|
|         7.79±0s|       1.82±0.06s|     0.23|  sparse.CsrHstack.time_csr_hstack(500000)|

```
SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

2021-10-09 15:56 UTC, ParticularMiner commented
I think the tests that have failed are not due to my added code.  :smiley:.  

If I'm mistaken, let me know.  Thanks!

2021-10-09 23:58 UTC, tylerjereddy commented
> I think the tests that have failed are not due to my added code.

Certainly the MacOS failure should go away the next time the CI gets flushed here because I just merged a fix for that from Ilhan. The 32-bit Linux failure I don't recognize, but maybe I'm just forgetting.

2021-10-14 00:43 UTC, perimosocordiae requested changes

2021-10-14 00:45 UTC, perimosocordiae commented
Thanks for this pull request, @ParticularMiner, this is looking really good!

I left a bunch of comments in my review, but if you disagree or have questions about anything, feel free to push back.

2021-10-25 18:10 UTC, perimosocordiae approved these changes

2021-10-25 18:13 UTC, merged