ENH: add radius to gaussian_filter1d and gaussian_filter
scipy/scipy pull request #15097
Opened 2021-11-24 20:06 UTC by yuanx749

#### Reference issue

Closes #11475
#### What does this implement/fix?

I added an optional `radius` argument to `gaussian_filter1d` and `gaussian_filter`. The default value is None. If `radius` is provided, the value of `truncate` will be ignored, and the kernel size of the filter will be 2*radius+1.

Tests were added to test filters with `radius` specified produce the same results as the filters using `truncate`.
#### Additional information

I agree with #11475 that it would be nice for user to have the option to directly specifiy the radius of the kernel. I have encountered this kind of usecase.

2021-11-25 14:00 UTC, grlee77 requested changes
Thanks @yuanx749, the changes here look good aside from some minor suggestions.

I have in the past had to look up how the kernel radius is determined, so I think this may be nice to have. The counter-argument is that we could keep just truncate, but improve the docstring to make it clearer how this relates to the radius. i.e. Something like the following in a Notes section:

The Gaussian kernel will have size ``2*radius + 1`` where
``radius = math.ceil(truncate * sigma)``.

Strictly speaking the kernel is a rectangle in 2D so it is more a "half width" than a "radius", but I think that the radius usage is common enough in image processing, that it shouldn't be too confusing.

2021-11-25 15:46 UTC, yuanx749 commented on scipy/ndimage/_filters.py
> +        if not isinstance(lw, int) or lw < 0:
@grlee77 Thank you for the review. As you suggested, `radius = math.ceil(truncate * sigma)`. Then do you think it is better to change the original `lw = int(truncate * sd + 0.5)`, which is actually rounding to the nearest integer?

2021-11-25 16:11 UTC, grlee77 commented
No, we should not change the existing behavior. Writing `math.ceil` in stead of `math.round` was a mistake in my suggestion :)

2021-11-25 16:14 UTC, grlee77 commented on scipy/ndimage/_filters.py
> +        if not isinstance(lw, int) or lw < 0:
No, we should not change the existing behavior. Writing `math.ceil` in stead of `math.round` was a mistake in my suggestion :). I think the style of `round(value)` as opposed to `int(value + 0.5)` is just a little easier to parse for the reader of a docstring.

2021-11-25 19:55 UTC, yuanx749 commented
I have applied the changes. Tests passed locally, but there are failings on Azure I cannot figure out why. Could you please take a look? @grlee77

2022-08-22 15:07 UTC, ash-yuen commented
Hi, I would like to use this added feature. I wonder what's the progress of this pull request? It seems ready to be merged. @yuanx749 @grlee77 @rgommers

2022-08-31 09:10 UTC, rgommers approved these changes
Thanks @yuanx749, this LGTM too. The review comments from @grlee77 were addressed, and CI looks good (the one CI failure is `Test_SVDS_PROPACK.test_small_sigma2` - unrelated). So in it goes.

2022-08-31 09:10 UTC, merged