BUG: Handled base case for scipy.integrate.simpson when span along the axis is 0
scipy/scipy pull request #15824
Opened 2022-03-20 14:51 UTC by k-styles

#### Reference issue

Closes #15721 

#### What does this implement/fix?

As described in the issue, the current implementation of `scipy.integrate.simpson` return `NaN` for when the span along the integrable axis is `0`. 
I change the code so that `0` is returned for that situation instead of `NaN`.

2022-03-20 20:04 UTC, k-styles commented
@tupui Let me know, if except the checks, the code will be working fine.

2022-03-21 10:40 UTC, tupui requested changes
Thank you @k-styles for the PR. A lot of tests seem to be broken with the changes. A test is also missing to check the new behaviour.

2022-03-22 05:04 UTC, k-styles commented
@tupui All workflows seems to have passed.

2022-03-22 10:13 UTC, k-styles commented
@tupui Are there any more changes I need to make?

2022-03-22 10:43 UTC, tupui requested changes
@k-styles, as I said before you are missing a test showing that the change is doing what you want. It has to work with different axis, and all other parameters.

2022-03-22 10:49 UTC, k-styles commented
@tupui Oh okay, I wasn't aware I need to add that as well.
I'll do it shortly.

2022-03-22 11:46 UTC, Patol75 commented
Wouldn't it be simpler to directly test `x` when `simpson` is called? Probably something along the lines of
```
if x is not None and np.count_nonzero(np.diff(x, axis=axis)) == 0:
    return 0
```
should work.

2022-03-22 11:56 UTC, tupui commented
> Wouldn't it be simpler to directly test `x` when `simpson` is called? Probably something along the lines of
> 
> ```
> if x is not None and np.count_nonzero(np.diff(x, axis=axis)) == 0:
>     return 0
> ```
> 
> should work.

Ideally, the solution should work for any constant, not just 0. This was discussed in the previous PR or issue AFAIR

2022-03-22 11:59 UTC, Patol75 commented
`count_nonzero` is applied to `diff`, so any constant value should be handled.

2022-03-22 12:00 UTC, tupui commented
> `count_nonzero` is applied to `diff`, so any constant value should be handled.

Yes, but then you don't want to return 0 for all.

2022-03-22 13:36 UTC, k-styles commented
> > `count_nonzero` is applied to `diff`, so any constant value should be handled.
> 
> Yes, but then you don't want to return 0 for all.

@tupui So the change I have made it seems to be okay with you right? On confirmation on this from you, I'll start working on the tests as well.

2022-03-22 13:43 UTC, k-styles commented
> Sorry, I don't really know as it's not my main area (and I am not sure who to ping for scipy.integrate. @ev-br is it you?). Hence without tests it's hard to say. You can work on tests without having any features implemented (test driven development).

Oh okay, Sure, I'll be on it then.

2022-03-22 14:34 UTC, tupui approved these changes
The tests make sense to me, thank you @k-styles. I would like a second pair of eyes before merging but LGTM.

2022-03-22 14:45 UTC, k-styles commented
@tupui 
`Windows Meson tests / Meson Windows tests (pull_request) ` test seems to be failing.
Is it because of the changes made in the code or is it something else?

2022-03-23 03:27 UTC, k-styles commented
@tupui Some workflows have been running for quite a long time. Could you please check on them?

2022-03-23 08:02 UTC, tupui commented
I closed-reopened to re-trigger the CI

2022-03-23 09:04 UTC, tupui approved these changes
LGTM now, thank you @k-styles. I will let this open until April 1st to give time for others to look at it. It there are no comments until then I will merge.

2022-03-23 09:09 UTC, k-styles commented
> LGTM now, thank you @k-styles. I will let this open until April 1st to give time for others to look at it. It there are no comments until then I will merge.

Thanks @tupui !

2022-04-02 05:01 UTC, k-styles commented
@tupui Is it safe to merge this change?

2022-04-02 09:39 UTC, merged

2022-04-02 09:39 UTC, tupui commented
Yes thanks for the ping I forgot yesterday