DEP: remove LAPACK *gegv functions
scipy/scipy pull request #15884
Opened 2022-03-26 21:40 UTC by j-bowhay

#### Reference issue

Closes #15758
#### What does this implement/fix?

Removes deprecated LAPACK functions, have been deprecated for 5+ years so should be ok to remove them
#### Additional information

2022-03-26 22:43 UTC, ilayn commented
Thanks @j-bowhay. Unfortunately, this is slightly trickier than just removing files since we have to bump up the minimum required LAPACK version to 3.6.0 across all platforms which we have to make sure that it is OK to do so.

2022-03-27 02:15 UTC, h-vetinari commented
For reference lapack 3.6.0 was [released](https://github.com/Reference-LAPACK/lapack/releases/tag/v3.6.0) almost 6 years ago. 

Apple Accelerate is outdated but already considered [unsupported](https://scipy.github.io/devdocs/dev/toolchain.html#other-libraries) for a while. From the list quoted in the toolchain roadmap:
> OpenBLAS, ATLAS, MKL, BLIS, and reference Netlib libraries are known to work.

The only one I'm not certain of is ATLAS, the others all support 3.9.0 already. There shouldn't be much in the way of platform support, as I'm 'not aware that any of those implementations has aggressively bump the compiler requirements recently.

2022-03-27 07:53 UTC, ilayn commented
The history for LAPACK is always fun. I've triggered the discussion in #5266 for this

2022-04-18 16:29 UTC, j-bowhay commented
@ilayn I see that the general consensus is to bump the min required version, what are the implications for this PR?

2022-04-18 17:25 UTC, ilayn requested changes
Other than the simple issue this looks like all of it.

2022-04-18 17:25 UTC, ilayn commented on scipy/linalg/_cython_signature_generator.py
>                'dlasq5', 'slasq5',
you can remove all this and below deprecations since we walked past 3.6.0 to 3.7.1 as min version.

2022-04-19 01:38 UTC, h-vetinari commented
Please also reflect the minimum version in the respective section in `doc/source/dev/toolchain.rst` (unless @ilayn would like a separate PR addressing #5266, but I'd say the two things are connected intimately enough to do it in this PR).

2022-04-22 09:35 UTC, ilayn commented
Looks good. Thanks @j-bowhay @h-vetinari . Could you maybe add a line about this to the end of this document https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.9.0?

2022-04-22 09:36 UTC, merged

2022-04-25 03:18 UTC, h-vetinari commented
Thanks both; I updated the release notes to also mention the new LAPACK lower bound.