[BUG] make p-values consistent with the literature
scipy/scipy pull request #15894
Opened 2022-03-29 11:51 UTC by sampan501

#### Reference issue

Closes #15009

#### What does this implement/fix?

The implementation of p-value computation via a permutation test in `scipy.stats.multiscale_graphcorr` was inconsistent with how they are computed in the literature. This PR fixes that.

#### Additional information

2022-03-29 11:52 UTC, sampan501 commented
@mdhaber Just opened a PR

2022-03-29 13:14 UTC, sampan501 commented
It seems like the failures in the tests are unrelated to my code

2022-03-29 14:10 UTC, tupui requested changes
Thank you for the PR @sampan501. Please add a test to verify your changes.

2022-03-29 15:18 UTC, mdhaber commented
It would be OK to check that the p-value is divisible by 1/(n+1) but not 1/n.

2022-03-29 23:08 UTC, sampan501 commented
@tupui added. @mdhaber this test basically does that. In previous tests it returns 1/1000 but this checks if it returns 1/1001

2022-03-29 23:12 UTC, mdhaber commented on scipy/stats/tests/test_stats.py
> +        assert_approx_equal(pvalue, 0.000999000999000999, significant=4)
```suggestion
        assert_allclose(pvalue, 1/1001)
```
![image](https://user-images.githubusercontent.com/6570539/160721380-02b97eaf-3b49-4228-afae-6ae484a89cd1.png)

2022-03-30 03:25 UTC, mdhaber commented
Thanks @sampan501@tupui !

2022-03-30 03:26 UTC, merged