BUG: Allow `spsolve_triangular` to work with matrices with zeros in the diagonal.
scipy/scipy pull request #16026
Opened 2022-04-21 18:02 UTC by v0dro

#### Reference issue
Closes https://github.com/scipy/scipy/issues/15199

#### What does this implement/fix?

Fixes `spsolve_triangular` to work with matrices that have zeros in the diagonals when specifying `unit_diagonal=True`.

2022-04-22 13:20 UTC, tupui requested changes
Hi @v0dro thanks for the PR. A few suggestions for me.

2022-04-22 13:20 UTC, tupui commented on scipy/sparse/linalg/_dsolve/tests/test_linsolve.py
> +        assert_array_almost_equal(A.dot(x), b)
We should not use anymore `assert_array_almost_equal` (cf NumPy's doc)
```suggestion
        assert_allclose(A.dot(x), b)
```

2022-04-22 13:20 UTC, tupui commented on scipy/sparse/linalg/_dsolve/tests/test_linsolve.py
> +        A = np.random.randn(n, n)
Use the new/recommended `Generator` interface
```suggestion
        rng = np.random.default_rng(43876432987)
        A = rng.standard_normal((n, n))
```

2022-04-25 23:09 UTC, v0dro commented
@tupui can you review this again?

2022-04-26 07:44 UTC, tupui approved these changes
LGTM, not my area so putting a marker for the release to get some attention before merging.

2022-04-26 07:52 UTC, ilayn commented
Can you also please add the example from #15199 as a test?

2022-04-26 21:42 UTC, rgommers approved these changes
LGTM too. Thanks @v0dro, all.

> Can you also please add the example from #15199 as a test?

Good catch, added.

2022-04-26 21:43 UTC, merged