BUG: signal: Fix calculation of extended image indices in convolve2d.
scipy/scipy pull request #16134
Opened 2022-05-07 00:03 UTC by WarrenWeckesser

To handle the `boundary` arguments "wrap" and "symm", the `convolve2d`
code computes indices into the first argument that might be negative or
larger than the size of the image.  The code adjusts negative or big
values so that the adjusted index refers to the correct data element
within the array.  The problem was that this adjustment code assumed
that it would only require that the data be extended *once*. E.g. if
an axis had length 100, it assumed that the extended index would be
in [-100, 200].  This is not true in general; the kernel (i.e. the
second argument of `convolve2d`) can be any size, and so the required
extension could be any size.  If the kernel was too big, the adjusted
indices might still be negative or too big, resulting in attempts to
access memory outside of input array's data.  That could result in
reading garbage, or a segmentation fault.

The fix is to use a couple helper functions that can handle arbitrarily
large kernel dimensions when computing the extended data.

Closes gh-8684.
Closes gh-8814.

#### Reference issue

#### What does this implement/fix?

#### Additional information

2022-05-07 05:25 UTC, WarrenWeckesser commented
This also closes gh-12686.  I pushed another commit containing a couple more tests based on the examples in @coderforlife's comments in that issue.

2022-05-09 12:29 UTC, larsoner approved these changes
Looks pretty straghtforward to me, +1 for merge from my end.

@WarrenWeckesser anyone else you think we should ping before merge? If not, feel free to merge in a couple of days if nobody else says anything

2022-05-09 13:06 UTC, WarrenWeckesser commented
Thanks @larsoner.

> anyone else you think we should ping...

@endolith is involved with `scipy.signal`, though admittedly `convolve2d` is more of an image processing function than a DSP function.
 
@coderforlife, you did a deep dive into the C code and correctly analyzed the problem in https://github.com/scipy/scipy/issues/12686 (back in 2020!), so you might be interested in taking a look now that the problem is finally being fixed.

2022-05-09 20:08 UTC, endolith commented on scipy/signal/_firfilter.c
>  	    else if (ind1 >= Ns[1]) {
and this removed too

2022-05-09 20:30 UTC, endolith commented on scipy/signal/_firfilter.c
>  	}
```suggestion
	if ((ind0 < 0) || (ind0 >= Ns[0])) {
	  if (boundary == REFLECT) ind0 = reflect_symm_index(ind0, Ns[0]);
	  else if (boundary == CIRCULAR) ind0 = circular_wrap_index(ind0, Ns[0]);
	  else bounds_pad_flag = true;
	}
```

2022-05-09 20:31 UTC, endolith commented on scipy/signal/_firfilter.c
>  	}
Suggestion feature doesn't seem to be working

2022-05-09 20:35 UTC, endolith requested changes
Looks good otherwise

2022-05-10 02:35 UTC, coderforlife commented
I did look it over and it looked good. Sorry, I couldn't make a PR myself, I discovered the problem while working on cupy's implementation of these functions.

2022-05-10 06:37 UTC, WarrenWeckesser commented on scipy/signal/_firfilter.c
> +{
Done.

2022-05-10 06:37 UTC, WarrenWeckesser commented on scipy/signal/_firfilter.c
>  	else if (ind0 >= Ns[0]) {
Done.  I made the suggested changes locally instead of using the github "suggested changes" UI.

2022-05-10 06:38 UTC, WarrenWeckesser commented on scipy/signal/_firfilter.c
>  	    else if (ind1 >= Ns[1]) {
Done.

2022-05-10 06:40 UTC, WarrenWeckesser commented
Thanks @endolith, all good suggestions that I've implemented.

And thanks for taking a look, @coderforlife.  No need to apologize for not submitting a PR.  Reporting and analyzing a problem does not obligate you to fix it!

2022-05-10 06:47 UTC, WarrenWeckesser commented
By the way, the horrible code alignment and mix of tabs and spaces in `_firfilter.c` makes reading that code more challenging than necessary.  I don't want to mix a big reformatting job with this PR, but perhaps in a separate maintenance PR this file (and several other C files here and in scipy.special) can be cleaned up with clang-format or some other formatter.

2022-05-10 12:06 UTC, ilayn commented
If you deem necessary, then we can review it by hiding whitespace changes. Usually I agree it is a mess to have these changes but C files don't see too much change over time hence I think we can do it for this one occasion.

2022-05-10 15:22 UTC, endolith approved these changes
Code all looks good to me now, comments are great.  Not sure about the test failures

2022-05-10 16:21 UTC, WarrenWeckesser commented
The test failures are not related to this PR.  They are result of changes in NumPy; see https://github.com/scipy/scipy/pull/16152.

2022-05-10 16:26 UTC, WarrenWeckesser commented
@ilayn, I won't reformat the file in this PR.  That can be done in a separate PR, after we've decided the extent to which we want to clean up our C and C++ files, and which style to use when we do it.

2022-05-10 16:38 UTC, larsoner commented
> @ilayn, I won't reformat the file in this PR. That can be done in a separate PR, after we've decided the extent to which we want to clean up our C and C++ files, and which style to use when we do it.

Agreed this should be a separate PR, and that we should probably do it. @WarrenWeckesser want to get the ball rolling maybe with a post suggesting your preferred solution/formatter to the scipy-dev list? If nobody objects we can do it and add the commit to `.git-blame-ignore-revs` like we're looking at doing for NumpyDoc: https://github.com/numpy/numpydoc/pull/391#issue-1228777252

As noted by @WarrenWeckesser the failures are unrelated and it looks like all comments have been addressed, so I'll merge in a couple of days unless others ask for more changes or time to look!

2022-05-10 19:18 UTC, stefanv approved these changes

2022-05-10 19:35 UTC, ilayn commented
> after we've decided the extent to which we want to clean up our C and C++ files, and which style to use when we do it.

That shed would not be painted very soon, hence my comment 😃 But no problem, I don't see it as a blocker anyways. +1 from me too.

2022-05-13 17:06 UTC, merged

2022-05-13 17:06 UTC, larsoner commented
Thanks @WarrenWeckesser !