CI: Test NumPy main branch also with Python 3.11
scipy/scipy pull request #16206
Opened 2022-05-18 09:03 UTC by EwoutH

Add a Python 3.11 job to the NumPy main branch test configuration.

Python 3.11 is [now in beta](https://blog.python.org/2022/05/python-3110b1-is-now-available.html) and feature stable. By adding a Python 3.11 test run we can catch errors and bugs before Python 3.11 will become stable, and packages dependent on SciPy can start working on their Python 3.11 support. SciPy is one of the most used packages and a package on which many other packages depend, so early support will help speed up Python 3.11 adoption.

Python 3.11 is expected to be released as stable in October 2022, with many new features including:

> - [PEP 657](https://www.python.org/dev/peps/pep-0657/) -- Include Fine-Grained Error Locations in Tracebacks
> - [PEP 654](https://www.python.org/dev/peps/pep-0654/) -- Exception Groups and except*
> - [PEP 673](https://www.python.org/dev/peps/pep-0673/) -- Self Type
> - [PEP 646](https://www.python.org/dev/peps/pep-0646/)-- Variadic Generics
> - [PEP 680](https://www.python.org/dev/peps/pep-0680/)-- tomllib: Support for Parsing TOML in the Standard Library
> - [PEP 675](https://www.python.org/dev/peps/pep-0675/)-- Arbitrary Literal String Type
> - [PEP 655](https://www.python.org/dev/peps/pep-0655/)-- Marking individual TypedDict items as required or potentially-missing
> - [bpo-46752](https://bugs.python.org/issue46752)-- Introduce task groups to asyncio
> - The [Faster Cpython Project](https://github.com/faster-cpython) is already yielding some exciting results: this version of CPython 3.11 is ~ 19% faster on the geometric mean of the [PyPerformance benchmarks](https://speed.python.org/), compared to 3.10.0.

2022-05-18 09:26 UTC, tupui reviewed
Thank you for the PR @EwoutH. Usually we wait until the RC phase. Let see how it goes.

If there is a need for extra commits. Please add in the message `[skip azp] [skip circle]` to only run GH actions.

2022-05-18 10:16 UTC, tupui commented
CI is happy so I am +1 to do this now. @rgommers what do you think?

2022-05-18 16:54 UTC, jarrodmillman approved these changes

2022-05-19 19:53 UTC, rgommers requested changes
Thanks @EwoutH for working on this. Testing Python 3.11-dev is a good idea. One request: please change `3.10` to `3.11-dev`; there is no need for an extra CI job here for such a small delta, and we already have a very (too) heavy CI setup.

2022-05-19 20:11 UTC, andyfaff commented
I'd like to keep the commented out stuff if possible. It's helpful when working on unreleased versions.

2022-05-19 20:13 UTC, tupui commented
> I'd like to keep the commented out stuff if possible. It's helpful when working on unreleased versions.

I thought about this (reason I left it when I updated this last time), but now GH proposes even alpha. So I don't think we need to keep this anymore.

2022-05-19 22:28 UTC, EwoutH commented
> One request: please change `3.10` to `3.11-dev`; there is no need for an extra CI job here for such a small delta, and we already have a very (too) heavy CI setup.

I'm happy to do so, but since the Numpy main branch is also quite unstable, isn't it interesting to see when it's the Numpy main branch itself that fails and when it's because of Python 3.11?

2022-05-20 09:15 UTC, rgommers commented
> since the Numpy main branch is also quite unstable, isn't it interesting to see when it's the Numpy main branch itself that fails and when it's because of Python 3.11?

NumPy `main` will cause some test failures on occasion, but there's (almost) never a build failure due to it. So we will still get signal here as soon as you look at a CI log. 

If we had infinite CI capacity you'd be right that it would be nicer to have separate signals, but we unfortunately don't have that. The difference is really too minor to justify a separate CI job.

2022-05-20 09:18 UTC, EwoutH commented
Thanks for the explanation, I removed the 3.10 job from the matrix.

Would you like me to squash the two commits or keep them separate? (you can also squash on merge)

2022-05-20 09:29 UTC, rgommers commented
No worries, you can leave it as is - I'll squash on merge.

2022-05-20 09:35 UTC, rgommers commented
> > I'd like to keep the commented out stuff if possible. It's helpful when working on unreleased versions.
> 
> I thought about this (reason I left it when I updated this last time), but now GH proposes even alpha. So I don't think we need to keep this anymore.

I agree, we won't need this again in our CI jobs since GHA is updating very fast. If the snippet is helpful for you @andyfaff, how about just copying it to a new issue with a descriptive title that we immediately close, so that it's easy to search for in case you want to dig it up for Python 3.12?

2022-05-20 10:23 UTC, rgommers approved these changes
LGTM and all green, in it goes. Thanks @EwoutH

2022-05-20 10:24 UTC, merged

2022-05-20 10:36 UTC, EwoutH commented
Thanks for merging!