DEP: add deprecation warning for vertices attribute in qhull
scipy/scipy pull request #16258
Opened 2022-05-23 18:37 UTC by j-bowhay

#### Reference issue

closes #16255
#### What does this implement/fix?

The attribute `vertices` was deprecated in documentation only. This pr adds a deprecation warning and test with details for removal.
#### Additional information

2022-05-23 18:45 UTC, h-vetinari approved these changes
You're amazing - thanks so much for tackling this so quickly! :)

2022-05-24 09:55 UTC, tupui requested changes
Thank you @j-bowhay. CI failure seems related.

@j-bowhay @h-vetinari Thank you both for all the work on deprecations. If you are available tomorrow we have our community meeting. Would be nice to meet you and discuss your efforts 😃

2022-05-24 09:55 UTC, tupui commented on scipy/spatial/_qhull.pyx
> +        "'simplices' and will be removed in Scipy 1.11.0.")
I am surprised that this was not flagged by the linter.
```suggestion
        msg = ("Delaunay attribute 'vertices' is deprecated in favour of "
               "'simplices' and will be removed in Scipy 1.11.0.")
```

2022-05-24 10:13 UTC, h-vetinari commented
> @j-bowhay @h-vetinari Thank you both for all the work on deprecations. If you are available tomorrow we have our community meeting. Would be nice to meet you and discuss your efforts 😃

Thanks for the invite! I'll be in a train at that [time](https://mail.python.org/archives/list/scipy-dev@python.org/message/URJX2TJO2KVRSNVR5YSGMXSLUHE2ALJ7/), but I'll try to join if reception permits.

2022-05-24 10:15 UTC, tupui commented
No worries. You are always welcome to join to these meetings. They are for the whole community.

2022-05-24 20:22 UTC, j-bowhay commented on scipy/spatial/_qhull.pyx
> +        Delaunay attribute `vertices` is deprecated in favour of `simplices`
ahh always screw this up

2022-05-24 20:23 UTC, j-bowhay commented
> @j-bowhay @h-vetinari Thank you both for all the work on deprecations. If you are available tomorrow we have our community meeting. Would be nice to meet you and discuss your efforts smiley

Unfortunately, I have a presentation training course (ugh) tomorrow so wont be able to make it

2022-05-24 21:36 UTC, tupui approved these changes
LGTM now, thanks again.

2022-05-24 21:37 UTC, merged