DEP: add deprecation warning for kwargs nyq / Hz in firwin*
scipy/scipy pull request #16315
Opened 2022-05-30 08:21 UTC by j-bowhay

#### Reference issue

closes gh-16253
#### What does this implement/fix?

Adds deprecation warning to kwargs `nyq` and `Hz` that were previously deprecated in docstring only
#### Additional information

2022-05-30 08:51 UTC, tupui requested changes
Thank @j-bowhay. A few suggestions

2022-05-30 08:51 UTC, tupui commented on scipy/signal/_fir_filter_design.py
> +        will be removed in SciPy 1.11.0.
```suggestion
        .. Deprecated:: 1.0.0
           `firls` keyword argument `nyq` is deprecated in favour of `fs` and
           will be removed in SciPy 1.11.0.
```

2022-05-30 15:28 UTC, j-bowhay commented on scipy/signal/tests/test_fir_filter_design.py
> +            assert_raises(ValueError, firwin, 99, [10, 20, 30], nyq=25)
Lines 255-256 perform the same test using fs so I think this is fine to have as well. Happy to change if you disagree

2022-05-30 16:27 UTC, tupui reviewed
This should fix the CI

2022-05-30 16:27 UTC, tupui commented on scipy/signal/_fir_filter_design.py
> +           will be removed in SciPy 1.11.0.
```suggestion
        .. deprecated:: 1.0.0
           `firwin` keyword argument `nyq` is deprecated in favour of `fs` and
           will be removed in SciPy 1.11.0.
```

2022-05-30 16:27 UTC, tupui commented on scipy/signal/_fir_filter_design.py
> +           will be removed in SciPy 1.11.0.
```suggestion
        .. deprecated:: 1.0.0
           `firwin2` keyword argument `nyq` is deprecated in favour of `fs` and
           will be removed in SciPy 1.11.0.
```

2022-05-30 16:27 UTC, tupui commented on scipy/signal/_fir_filter_design.py
> +           will be removed in SciPy 1.11.0.
```suggestion
        .. deprecated:: 1.0.0
           `remez` keyword argument `Hz` is deprecated in favour of `fs` and
           will be removed in SciPy 1.11.0.
```

2022-05-30 16:27 UTC, tupui commented on scipy/signal/_fir_filter_design.py
> +           will be removed in SciPy 1.11.0.
```suggestion
        .. deprecated:: 1.0.0
           `firls` keyword argument `nyq` is deprecated in favour of `fs` and
           will be removed in SciPy 1.11.0.
```

2022-05-30 19:16 UTC, j-bowhay commented
@tupui thanks for that, I keep messing that formatting up! I realise now that the formatting in #16265 and #16258 is incorrect should I make a flow up pr?

2022-05-30 19:35 UTC, tupui commented
No worries 😃 It's not a priority but feel free. If you do, you could address all occurrences in the doc (not that many).

2022-06-01 16:57 UTC, larsoner commented
@j-bowhay can you merge with `upstream/main` to see if that fixes CIs? It would be nice to be able to verify things are correct in the doc build

2022-06-01 16:57 UTC, larsoner commented on scipy/signal/_fir_filter_design.py
> +        .. Deprecated:: 1.0.0
Looks like these still need to be lower-cased

2022-06-01 18:50 UTC, larsoner commented
According to CircleCI some examples need to be updated
```
/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py:docstring of scipy.signal._fir_filter_design.kaiserord:67: WARNING: Exception occurred in plotting scipy-signal-kaiserord-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.signal.kaiserord.rst:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 36, in <module>
  File "/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py", line 393, in firwin
    nyq = 0.5 * _get_fs(fs, nyq)
  File "/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py", line 31, in _get_fs
    warnings.warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: Keyword argument 'nyq' is deprecated in favour of 'fs' and will be removed in SciPy 1.12.0.
/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py:docstring of scipy.signal._fir_filter_design.minimum_phase:102: WARNING: Exception occurred in plotting scipy-signal-minimum_phase-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.signal.minimum_phase.rst:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 7, in <module>
  File "/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py", line 854, in remez
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: 'remez' keyword argument 'Hz' is deprecated in favour of 'fs' and will be removed in SciPy 1.12.0.
/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py:docstring of scipy.signal._fir_filter_design.remez:97: WARNING: Exception occurred in plotting scipy-signal-remez-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.signal.remez.rst:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 29, in <module>
  File "/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/signal/_fir_filter_design.py", line 854, in remez
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: 'remez' keyword argument 'Hz' is deprecated in favour of 'fs' and will be removed in SciPy 1.12.0.
```

2022-06-01 18:51 UTC, larsoner commented
(or the deprecation warning is not being emitted correctly / under the correct conditions -- not sure which is the case)

2022-06-02 06:17 UTC, j-bowhay commented
@larsoner docs now rendering correctly, CI failings seem unrelated?

2022-06-07 22:03 UTC, larsoner approved these changes
@tupui feel free to merge if you're happy

2022-06-07 23:04 UTC, tupui approved these changes
LGTM, thanks everyone 😃

2022-06-07 23:05 UTC, merged