Update warning to include np.min in accordance with gh-15883
scipy/scipy pull request #16377
Opened 2022-06-09 05:30 UTC by jcampbell

Improves warning message for edge cases, based on potentially incremental strategy identified in gh-15883.

2022-06-09 10:34 UTC, tupui requested changes
Thank you @jcampbell. There are CI failure which relate to this PR. We are matching this warning message in some tests. Hence they have to be updated.

2022-06-11 17:46 UTC, jcampbell commented
Thank you -- updating!

2022-06-11 17:47 UTC, jcampbell commented on scipy/stats/_resampling.py
> +                   "statistic is np.min.")
Thank you -- updated in same commit with the test message change.

2022-06-12 15:39 UTC, tupui commented on scipy/stats/_resampling.py
> +            )
Should fix the linter
```suggestion
            msg = (
                "The BCa confidence interval cannot be calculated."
                " This problem is known to occur when the distribution"
                " is degenerate or the statistic is np.min."
            )
```

2022-06-13 07:25 UTC, tupui reviewed
Is there a reason why you did not go with @mdhaber's suggestion?

> The observed value of the statistic is less than or equal to all values in the bootstrap distribution. This is known to occur when, for example, the data is degenerate or the statistic is np.min. The BCa confidence interval cannot be calculated.

This seems more complete and nuanced (example).

2022-06-13 20:55 UTC, jcampbell commented
I actually modified the suggestion because I was concerned that it is *too* specific. For example, if our sample includes `nan`, we will encounter the same problem when bootstrapping the `mean` statistic, but not for the *exact* reason specified. Since this change is already designed to clarify that there are other situations that can cause this problem, I thought it would be best to lead with the net result and then give examples of why that could happen.

2022-06-13 22:02 UTC, tupui commented
I will let @mdhaber weight in.

2022-06-13 22:08 UTC, mdhaber approved these changes
Yup, this is fine. I agree that it can happen in other cases, and we were too specific before, so let's not make the same mistake. Looks like CI is happy with the changes in this PR, too. Anything else, @tupui?

2022-06-14 08:42 UTC, tupui approved these changes
All good then. Thank you @jcampbell and @mdhaber for the review.

2022-06-14 08:42 UTC, merged