DEP: sharpen deprecation warning for `spmatrix` attributes
scipy/scipy pull request #16405
Opened 2022-06-14 17:27 UTC by j-bowhay

#### Reference issue

#### What does this implement/fix?

Sharpens some preexisting deprecation warning for attributes `A` and `H` of `spmatrix` with a timeline for removal. 
#### Additional information

cc. @h-vetinari another for the list

2022-06-14 21:50 UTC, tupui reviewed
Thanks @j-bowhay, LGTM. @stefanv can you confirm? You added this a few months back. Is the timeline fine here?

2022-06-14 22:11 UTC, stefanv commented
@tupui I am not aware of this being discussed anywhere; perhaps you saw such a discussion?

2022-06-14 22:14 UTC, tupui commented
@stefanv apparently you listed these as deprecated in #14822. I don't know more here 😅

2022-06-14 22:22 UTC, stefanv commented
That's because sparse arrays don't support `.A`, and we'll be switching to those at some as-of-yet-undetermined point in the future.

2022-06-15 06:06 UTC, h-vetinari commented
> and we'll be switching to those at some as-of-yet-undetermined point in the future.

Is there a specific concern that would require an indeterminate amount of time to pass for users to adapt? If there's a warning for a year / 2 releases to move away from an API, that's usually a reasonable amount of time for API changes (and this one's been raising a warning already). Perhaps this particular change needs 3-4 releases, but I don't really see it on the scale of wholesale module removals and other similarly-sized changes that got attached to the still somewhat mythical scipy 2.0.

In general, I'd advocate not pushing off reasonable (and reasonably sized) changes until an unknown point in the future. It just makes that volume of future changes all the harder to pull off.

2022-06-15 07:07 UTC, rgommers requested changes
This does not look like a desired change. There was no code using `.A` to begin with, since it was a warning introduced as part of a new feature. It could have raised an exception straight away. The choice was for a _visible_ warning. Going back now and making the warning less visible and then turning it into an error is weird.

This is a special case, not a regular deprecation. Let's leave this unchanged.

2022-06-15 07:08 UTC, rgommers commented
> and we'll be switching to those at some as-of-yet-undetermined point in the future.

To add: this can be dealt with as part of a plan to switch to sparse arrays. If there's no plan written yet, we shouldn't have churn on small aspects of that transition.

2022-06-15 14:58 UTC, h-vetinari commented
> The choice was for a _visible_ warning. Going back now and making the warning less visible and then turning it into an error is weird.

In fairness, this is the [only use](https://github.com/scipy/scipy/search?q=VisibleDeprecationWarning) of `np.VisibleDeprecationWarning` in all of scipy (verified locally because I don't trust GH code search for completeness). I wasn't aware that this is somehow more visible than regular `DeprecationWarnings`, but the question arises whether this case really is special enough to merit a type of warning that's used nowhere else.

> This is a special case, not a regular deprecation. Let's leave this unchanged.

Fine by me, though I don't really see the downside in following through in such a well-delimited aspect of the code, not least because as you mention it could have been raising an exception right off the bat.

2022-06-19 03:17 UTC, perimosocordiae commented
The confusion here may stem from the position of the sparse array API being not 100% "launched" yet. Right now, we're expecting power users and early adopters to start attempting to transition their code to use sparse arrays, and so warnings like these are in place to help them along.

Once the sparse array API is fully ready, we'll officially deprecate the old spmatrix API. When that happens, we can start the clock on deprecating these transitional affordances as well.

2022-06-19 03:17 UTC, closed without merging