ENH: stats.mood: convert output tuple to Bunch
scipy/scipy pull request #16441
Opened 2022-06-19 22:37 UTC by JozsefKutas

Reference issue

https://github.com/scipy/scipy/issues/16364
https://github.com/scipy/scipy/issues/13118

What does this implement/fix?

https://github.com/scipy/scipy/issues/16364 suggests that all statistical functions that currently return tuples should return Bunch objects. This PR converts the tuple returned by stats.mood to a Bunch.

2022-06-20 13:01 UTC, tupui requested changes
Thank you @JozsefKutas, just a suggestion for me otherwise LGTM. I will still wait for @mdhaber to have a look as well so we are all on the same page on these.

2022-06-20 13:01 UTC, tupui commented on scipy/stats/tests/test_morestats.py
> +        x2 = np.random.randn(15, 1)
We should use the generator interface as this is deprecated.
```suggestion
        rng = np.random.default_rng('265827767938813079281100964083953437622')
        x1 = rng.standard_normal((10, 1))
        x2 = rng.standard_normal((15, 1))
```

2022-06-20 19:07 UTC, JozsefKutas commented
Thanks @tupui. I'm not sure the `default_rng` argument should be in quotes though? This seems to be causing a `TypeError` in some of the CI tests.

2022-06-20 19:08 UTC, tupui commented
> Thanks @tupui. I'm not sure the `default_rng` argument should be in quotes though? This seems to be causing a `TypeError` in some of the CI tests.

Ooops it's a typo yes.

2022-06-20 19:08 UTC, tupui commented on scipy/stats/tests/test_morestats.py
> +        rng = np.random.default_rng('265827767938813079281100964083953437622')
```suggestion
        rng = np.random.default_rng(265827767938813079281100964083953437622)
```

2022-06-21 12:31 UTC, tupui approved these changes

2022-06-21 22:28 UTC, merged

2022-06-21 22:29 UTC, mdhaber commented
Thanks @JozsefKutas @tupui!