ENH: vectorize along samples `stats.ortho_group.rvs` and `stats.unitary_group.rvs`
scipy/scipy pull request #16574
Opened 2022-07-10 09:44 UTC by Gattocrucco

#### Reference issue

#16344

#### What does this implement/fix?

The random matrix generators `stats.ortho_group.rvs` and `stats.unitary_group.rvs`, when requested more than one sample, loop in python over each sample. This is inefficient for small matrices. They use the QR decomposition, which has been vectorized in numpy since version 1.22, so I switch to `np.linalg.qr` from `scipy.linalg.qr` and remove the loop. However scipy must work with numpy 1.19, so I actually leave the loop around and decide to use it conditioned on a cached test which calls `np.linalg.qr` with a 3d array.

#### Additional information

2022-07-10 15:21 UTC, rkern commented
Does the output change depending on which branch is taken? If so, then we should wait until scipy depends on the newer numpy to introduce the vectorized `qr()` call.

2022-07-10 15:52 UTC, ilayn commented
In the meantime, I am completing the suite by making linalg funcs accepting ndarrays so either way this would work out ok at most a version later.

2022-07-10 16:10 UTC, rkern commented
That would be a reasonable thing to wait for.

2022-07-10 17:17 UTC, Gattocrucco commented
> Does the output change depending on which branch is taken?

No:

```python
In [1]: from scipy import stats

In [2]: stats._multivariate._has_vectorized_qr()
Out[2]: True

In [3]: stats.ortho_group.rvs(2, size=3, random_state=123)
Out[3]: 
array([[[-0.96766721, -0.25223038],
        [ 0.25223038, -0.96766721]],

       [[-0.23193138,  0.97273215],
        [-0.97273215, -0.23193138]],

       [[ 0.8812753 , -0.47260326],
        [-0.47260326, -0.8812753 ]]])

In [4]: stats._multivariate._has_vectorized_qr.cache = False

In [5]: stats._multivariate._has_vectorized_qr()
Out[5]: False

In [6]: stats.ortho_group.rvs(2, size=3, random_state=123)
Out[6]: 
array([[[-0.96766721, -0.25223038],
        [ 0.25223038, -0.96766721]],

       [[-0.23193138,  0.97273215],
        [-0.97273215, -0.23193138]],

       [[ 0.8812753 , -0.47260326],
        [-0.47260326, -0.8812753 ]]])
```

2022-07-10 17:31 UTC, rkern commented
Okay, great!

2022-07-15 04:01 UTC, mdhaber requested changes
This looks about ready; I've added some minor suggestions. It would work just fine as-is, but hopefully you agree that these would make it a little easier for others to understand?

`size` already tested by `test_multivariate::test_haar`, so no new tests needed here. (right?)

2022-07-15 10:31 UTC, Gattocrucco commented
> `size` already tested by `test_multivariate::test_haar`, so no new tests needed here. (right?)

Right

2022-07-15 12:26 UTC, Gattocrucco commented
I noticed that the `NumpyVersion` check adds 3us, starting from 8us, to `rvs(2)`. I guess that this kind of inefficiency is not a problem here, but I remember seeing people worried about overheads like this in discussions about numpy, so I say it out.

2022-07-15 13:41 UTC, mdhaber approved these changes
Waiting to re-run a test that failed. I doubt it's related; when I'm sure I'll merge.

2022-07-15 15:29 UTC, merged