DOC: Adding import numpy to several files
scipy/scipy pull request #16615
Opened 2022-07-16 15:35 UTC by njj67229

#### Reference issue
See #13049

#### What does this implement/fix?
Adds import numpy as np to examples where necessary 

#### Additional information
Not closed

2022-07-16 16:07 UTC, njj67229 commented
Theres an issue in the tests for _util.py that I am looking at now

2022-07-16 16:11 UTC, tupui requested changes
Thank you @njj67229! A few suggestions 😃

2022-07-16 16:11 UTC, tupui commented on scipy/cluster/vq.py
> +    ...                      [2.,2.,2.]])
```suggestion
    ...                       [2.,2.,2.]])
```

2022-07-16 16:11 UTC, tupui commented on scipy/cluster/vq.py
> +    ...                      [ 1.0,1.0]])
```suggestion
    ...                       [ 1.5,2.5],
    ...                       [ 0.8,0.6],
    ...                       [ 0.4,1.8],
    ...                       [ 1.0,1.0]])
```

2022-07-16 16:11 UTC, tupui commented on scipy/cluster/vq.py
> +    ...                      [ 1.0,1.0]])
```suggestion
    ...                       [ 1.5,2.5],
    ...                       [ 0.8,0.6],
    ...                       [ 0.4,1.8],
    ...                       [ 0.1,0.1],
    ...                       [ 0.2,1.8],
    ...                       [ 2.0,0.5],
    ...                       [ 0.3,1.5],
    ...                       [ 1.0,1.0]])
```

2022-07-18 06:54 UTC, tupui approved these changes
LGTM, thanks @njj67229 for the PR 🚀

2022-07-18 07:00 UTC, merged