ENH add extrapolate to BSpline.design_matrix
scipy/scipy pull request #16797
Opened 2022-08-06 20:00 UTC by lorentzenchr

#### Reference issue
Continuation of #14344.

#### What does this implement/fix?
This PR adds `extrapolate` to `BSpline.design_matrix` such that is produces equivalent results compared to `BSpline.__call__`.

#### Additional information
This would help [scikit-learn#20998](https://github.com/scikit-learn/scikit-learn/issues/20998) a lot.

2022-08-06 20:15 UTC, ev-br commented
@egorz734 would you be able to review this PR?

2022-08-06 21:40 UTC, ev-br commented on scipy/interpolate/tests/test_bsplines.py
> +        k = order
Minor nit: I belive this is degree not order (as in a cubic has degree 3 and the order 4). Somebody went through the codebase and changed a bunch of orders for degrees a while ago. Maybe best to at least agree on the notation.

2022-08-07 04:47 UTC, egorz734 requested changes

2022-08-07 04:47 UTC, egorz734 commented on scipy/interpolate/_bsplines.py
> +            raise ValueError("Knots should not have nans or infs.")
This check is already done in `_as_float_array` (lines 410-411), so i suggest removing it

2022-08-07 09:01 UTC, egorz734 approved these changes

2022-08-07 13:10 UTC, ev-br commented
LGTM too. Merging, thanks @lorentzenchr and @egorz734 for the review!

2022-08-07 13:13 UTC, merged

2022-08-07 15:31 UTC, lorentzenchr commented
Wow, this might be my fastest "PR get's merged" experience in open source 🎉 
Thanks @ev-br and @egorz734.

2022-08-07 20:58 UTC, ev-br commented
The patch is small and focused; implementation looks good; the premise is clear from the docs and tests; the use case is clear and user demand apparent; the danger of painting ourselves into a corner API-wise is small; if a small detail will need tweaking based on usage, the likelihood of a serious problem feels small; the whole thing is localized and does not seem to affect other parts of the library; the author is responsive and reviewers are in the flow. Why dragging it out?

I personally prefer to avoid reformatting code lines which are not absolutely essential to the core goal of the PR, but that's a judgement call on a small trivial detail which is not worth dragging the PR IMO.

Hope it'll be helpful with the scikit-learn enhancement :-).