WIP: DOC: General bessel docs
scipy/scipy pull request #17003
Opened 2022-09-11 10:09 UTC by dschmitz89

#### What does this implement/fix?
Add examples for [general Bessel functions](https://scipy.github.io/devdocs/reference/special.html#bessel-functions).

Follow-up of #16950

[skip azp] [skip actions]

2022-09-11 16:24 UTC, dschmitz89 commented
Turns out that I am not that knowledgable about the exponentially scaled Bessel functions such as `yve` (only useful for complex arguments), so restricting the PR to 'iv', 'jv' and ''yv/yn'.

2022-09-20 10:57 UTC, tupui requested changes
Thanks @dschmitz89, some small things to tweak.

2022-09-20 10:57 UTC, tupui commented on scipy/special/_add_newdocs.py
> +    provinding a list or numpy array as argument for the `v` parameter:
```suggestion
    providing a list or NumPy array as argument for the `v` parameter:
```

2022-09-20 10:57 UTC, tupui commented on scipy/special/_add_newdocs.py
> +    array([ 0.08825696, -0.78121282, -1.65068261])
```suggestion
    The evaluation for different orders can be carried out in one call by
    providing a list or NumPy array as argument for the `v` parameter:

    >>> yn([0, 1, 2], 1.)
    array([ 0.08825696, -0.78121282, -1.65068261])
```

2022-09-20 10:57 UTC, tupui commented on scipy/special/_add_newdocs.py
> +    >>> yn(0, 1.), yn(1, 1.), yn(2, 1.)
```suggestion
    Evaluate the function at one point for different orders.

    >>> yn(0, 1.), yn(1, 1.), yn(2, 1.)
```

2022-09-20 10:57 UTC, tupui commented on scipy/special/_add_newdocs.py
> +    >>> yv(0, 1.), yv(1, 1.), yv(1.5, 1.)
```suggestion
    Evaluate the function at one point for different orders.

    >>> yv(0, 1.), yv(1, 1.), yv(1.5, 1.)
```

2022-09-20 10:57 UTC, tupui commented on scipy/special/_add_newdocs.py
> +    >>> yv([0, 1, 1.5], 1.)
```suggestion
    providing a list or NumPy array as argument for the `v` parameter:

    >>> yv([0, 1, 1.5], 1.)
```

2022-09-22 16:40 UTC, dschmitz89 commented
@tupui : refguide is passing and all style issues resolved. Anything else missing?

2022-09-22 16:41 UTC, tupui approved these changes
LGTM, thanks again for the PR (and the ping) @dschmitz89

2022-09-22 16:41 UTC, merged