Add examples for integrals of Bessel functions
scipy/scipy pull request #17041
Opened 2022-09-18 11:28 UTC by dschmitz89

#### Reference issue
Example: Towards #7168 

#### What does this implement/fix?
Adds examples to [integrals](https://docs.scipy.org/doc/scipy/reference/special.html#integrals-of-bessel-functions) of Bessel functions.

[skip azp][skip actions]

2022-09-18 20:11 UTC, WarrenWeckesser commented
Thanks @dschmitz89.

Just a "drive-by comment" for the moment: we generally don't put a blank line between the section heading and the first line of content in the section.  You can see this in the [numpydoc guidelines](https://numpydoc.readthedocs.io/en/latest/format.html#examples), and it looks like you already following the recommended convention in gh-17003.

2022-09-19 09:50 UTC, tupui requested changes
Thank you for adding these examples @dschmitz89!

2022-09-19 09:50 UTC, tupui commented on scipy/special/_add_newdocs.py
> +    ...     plt.plot(powers, besselpoly(scale, powers, order),
Can you refactor these to use the OOP version of matplotlib instead? We should follow matplotlib's guidelines here. (I have seen that in other PR's IIRC)

2022-09-19 19:01 UTC, tupui requested changes
Thanks for the update and for caring about the CI! Adding some nitpick so that we can also run with Azure as we need to check the refguide (actions can still be skipped).

2022-09-19 19:30 UTC, dschmitz89 commented
> Thanks for the update and for caring about the CI! Adding some nitpick so that we can also run with Azure as we need to check the refguide (actions can still be skipped).

Would it be possible to add sth like `[ci docs]` to the CI machinery which only executes ref-guide, linter and the doc builder? Otherwise a lot of azure CI resources are used for no reason.

2022-09-19 19:32 UTC, tupui commented
We should totally have better flags there 👍 The distinction with provider instead of tasks makes little sense. I proposed some reflexion but it did not do anything. If you have some concrete proposal we could share this on the mailing list and I would gladly add my +1 😃

2022-09-20 08:59 UTC, tupui approved these changes
LGTM, thanks again @dschmitz89.

2022-09-20 08:59 UTC, merged