DEV: dev.py: separate lint and flake8 tasks
scipy/scipy pull request #17496
Opened 2022-11-27 12:26 UTC by j-bowhay

#### Reference issue

closes #17434, closes https://github.com/scipy/scipy/issues/17394

#### What does this implement/fix?

As per discussion, https://github.com/scipy/scipy/issues/17434#issuecomment-1318566296, separates out the running of `lint_diff.py` and flake8 into separate tasks so that `dev.py lint` will now give the same output as the CI job.

Also very minor tidy up of consistent use of fullstops at the end of task descriptions. 
#### Additional information

2022-11-27 20:48 UTC, rgommers requested changes
@j-bowhay thanks for working on this! After reviewing this, I noticed that there's basically no difference between how the linter is run in this PR and in `main`. So I dug a bit deeper and found the actual reason that people saw issues (different `flake8` version) - see https://github.com/scipy/scipy/issues/17394#issuecomment-1328335872.

I propose to:
- Fix the E275 "missing whitespace after keyword" style issues in the code base,
- Not add a separate `dev.py flake8` command, but instead make `dev.py lint` match what CI does even better (i.e., only add `tools/unicode-check.py` to it)

Does that sound good?

2022-11-27 20:48 UTC, rgommers commented on dev.py
> +    """:dash: run flake8 on the scipy and benchmark directories."""
While we're at it consistency-fixups-wise: could you capitalize the first letter, here and for the `build` command and the `--no-build` option?

2022-11-27 20:54 UTC, j-bowhay commented
Thanks for looking into this @rgommers, yes that sounds like a good plan

2022-11-27 23:04 UTC, j-bowhay commented
@rgommers just to make this more fun the latest version of flake8 has removed `--diff` which breaks `tools/lint_diff.py`. I have opened a separate issue for that (https://github.com/scipy/scipy/issues/17503)

2022-11-28 10:29 UTC, rgommers approved these changes
LGTM now, thanks @j-bowhay!

Note that I added one tweak, fixing the one linter complaint and pinning `flake8` to < 6.0 in `environment.yml`.

2022-11-28 10:30 UTC, merged