ENH: update and extend lobpcg.py docstring info and examples
scipy/scipy pull request #17566
Opened 2022-12-08 17:56 UTC by lobpcg

ENH: update and extend lobpcg.py docstring info and examples

#### Reference issue
N/A

#### What does this implement/fix?
update and extend lobpcg.py docstring info and examples

2022-12-12 15:39 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        Maximum number of iterations.
Already done!

2022-12-12 15:40 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        Maximum number of iterations.
Or maybe I do not understand your request...

2022-12-12 15:51 UTC, melissawm reviewed
Left a couple minor comments, thanks @lobpcg !

2022-12-12 15:51 UTC, melissawm commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    The first mandatory input parameter, in this test is
```suggestion
    The first mandatory input parameter in this test is
```

2022-12-12 15:52 UTC, melissawm commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        Maximum number of iterations.
Maybe it's not necessary but I would add something like 
```suggestion
    maxiter : int, optional. The default is ``maxiter=20``.
        Maximum number of iterations. The actual number of iterations will be ``maxiter+3`` (see Notes section).
```

2022-12-12 16:10 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        Maximum number of iterations.
The extra output in history does not come from iterations, but rather from pre- and post-processing.

2022-12-12 16:46 UTC, melissawm commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        Maximum number of iterations.
Oh, got it. Thanks for clarifying!

2022-12-12 16:51 UTC, melissawm approved these changes
This looks good to me now! I'll leave this for other maintainers to see, if we don't get other feedback I'll merge in a few days.

2022-12-12 23:07 UTC, melissawm commented
Single quotes will create links whenever possible to existing objects (e. g. `np.array` will create a link to the array doc). Double quotes are used for raw formatting. If you use single quotes and a link is not found, the result is left in italics.

2022-12-12 23:42 UTC, lobpcg commented
> Single quotes will create links whenever possible to existing objects (e. g. `np.array` will create a link to the array doc). Double quotes are used for raw formatting. If you use single quotes and a link is not found, the result is left in italics. 

Thanks! I'll make the necessary changes and massage the new example to pass the test soon

2022-12-13 21:52 UTC, lobpcg commented
@melissawm I have added another short example at the end and fixed, I hope, all formatting related to quotes, after your review. 

It's ready to merge.

2022-12-15 10:44 UTC, tupui requested changes
Thanks for the addition @lobpcg 

@melissawm Single quotes are also needed when talking about a parameter of the function/class/method. Like ``` `A` ``` but when using it we need double quotes like ``` ``A=...`` ```.

If you accept the suggestions. Please use the `Files changed` tabs and click on `Add suggestion to batch`. This way it will batch all changes and create a single commit, hence send a single notification. And please in the commit message add `[skip azp] [skip actions] [skip cirrus]`

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        If ``A`` has ``shape=(n,n)`` then ``X`` must have ``shape=(n,k)``.
Parameters also need a single quote.
```suggestion
        Initial approximation to the ``k`` eigenvectors (non-sparse).
        If `A` has ``shape=(n,n)`` then `X` must have ``shape=(n,k)``.
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        of the column-space of ``Y``. ``Y`` must be full rank if present.
```suggestion
        of the column-space of `Y`. `Y` must be full rank if present.
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    largest : bool, optional. The default is ``largest=True``.
This is not conform to numpydoc, see https://numpydoc.readthedocs.io/en/latest/format.html#parameters
```suggestion
    largest : bool, default: True
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        The default is ``False``.
Then we should be consistent
```suggestion
    retLambdaHistory : bool, default: False
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        The default is ``False``.
```suggestion
    retResidualNormsHistory : bool, default: False
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        The history of residual norms, if ``retResidualNormsHistory``
```suggestion
        The eigenvalue history, if `retLambdaHistory` is ``True``.
    ResidualNormsHistory : ndarray, optional.
        The history of residual norms, if `retResidualNormsHistory`
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    by ``A``, ``B``, and ``M`` all presere the ``np.float32`` data type,
```suggestion
    by `A`, `B`, and `M` all preserve the ``np.float32`` data type,
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    If both ``retLambdaHistory`` and ``retResidualNormsHistory`` are ``True``,
```suggestion
    If both `retLambdaHistory` and `retResidualNormsHistory` are ``True``,
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    1. Quality of the initial approximations ``X`` to the seeking eigenvectors.
```suggestion
    1. Quality of the initial approximations `X` to the seeking eigenvectors.
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +       for ``A``, which is easy to code since ``A`` is tridiagonal.
```suggestion
       for `A`, which is easy to code since `A` is tridiagonal.
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    the sparse diagonal matrix ``A``
```suggestion
    the sparse diagonal matrix `A`
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    The second mandatory input parameter ``X`` is a 2D array with the
```suggestion
    The second mandatory input parameter `X` is a 2D array with the
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    ``X`` must have linearly independent columns.
```suggestion
    `X` is an initial guess for targeted eigenvectors.
    `X` must have linearly independent columns.
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    then the matrix itself. Since the matrix ``A`` is diagonal in
```suggestion
    LOBPCG needs only access the matrix product with `A` rather
    then the matrix itself. Since the matrix `A` is diagonal in
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    in the reduced precision ``np.float32`` even though the initial ``X``
```suggestion
    The preconditioner acts as the inverse of `A` in this example, but
    in the reduced precision ``np.float32`` even though the initial `X`
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    Let us now solve the eigenvalue problem for the matrix ``A`` first
```suggestion
    Let us now solve the eigenvalue problem for the matrix `A` first
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    With preconditioning we need only 20 iterations from the same ``X``
```suggestion
    With preconditioning we need only 20 iterations from the same `X`
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    Note that the vectors passed in ``Y`` are the eigenvectors of the 3
```suggestion
    Note that the vectors passed in `Y` are the eigenvectors of the 3
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    Finally, the primary matrix ``A`` may be indefinite, e.g., after shifting
```suggestion
    Finally, the primary matrix `A` may be indefinite, e.g., after shifting
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        By default ``Y = None``.
```suggestion
    Y : ndarray, float32 or float64, default: None
```

2022-12-15 10:44 UTC, tupui commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +        The default is ``maxiter=20``. Maximum number of iterations.
```suggestion
    maxiter : int, default: 20
        Maximum number of iterations.
```

2022-12-15 15:23 UTC, lobpcg commented
@tupui sorry, forgot the commit message add [skip azp] [skip actions] [skip cirrus]...

2022-12-15 16:17 UTC, tupui approved these changes
Thank you for the update @lobpcg (no worries for the CI, next time 😉).

I am merging since there is already another approval from a maintainer.

2022-12-15 16:17 UTC, merged