DOC: Examples for stdtr, stdtrit
scipy/scipy pull request #17625
Opened 2022-12-18 19:38 UTC by dschmitz89

#### Reference issue
gh-7168

#### What does this implement/fix?
Examples for:
* `special.stdtr`
* `special.stdtrit`

2023-01-06 16:41 UTC, dschmitz89 commented
@melissawm friendly ping: any chance that this can be merged? :)

2023-01-06 17:09 UTC, WarrenWeckesser commented
@dschmitz89, I'm taking a look now.

For reviewer's convenience, here are the links to the updated docs:
* [`special.stdtr`](https://output.circle-artifacts.com/output/job/7eea9e94-99fe-44be-be0a-1b8d34bef2c5/artifacts/0/html/reference/generated/scipy.special.stdtr.html)
* [`special.stdtrit`](https://output.circle-artifacts.com/output/job/7eea9e94-99fe-44be-be0a-1b8d34bef2c5/artifacts/0/html/reference/generated/scipy.special.stdtrit.html)
* [`special.stdtridf`](https://output.circle-artifacts.com/output/job/7eea9e94-99fe-44be-be0a-1b8d34bef2c5/artifacts/0/html/reference/generated/scipy.special.stdtridf.html)

2023-01-06 17:35 UTC, WarrenWeckesser requested changes
Looks good!

I made a few inline suggestions.  One more editorial change: let's move the comment about it being "the integral from minus infinity to t of the Student t distribution [sic]" to the notes, and fix the text to something simpler, such as "The function computes the integal: ...", because "the integral of the distribution" isn't quite right.  Also, move any terms in the integrand that do not depend on $t$ out of the integral.

2023-01-06 17:35 UTC, WarrenWeckesser commented on scipy/special/_add_newdocs.py
> +    `stdtrit` directly can improve performance compared to the ``ppdf``
```suggestion
    `stdtrit` directly can improve performance compared to the ``ppf``
```

2023-01-06 17:35 UTC, WarrenWeckesser commented on scipy/special/_add_newdocs.py
> +    >>> df, x = 3, 1
Style nit, here and elsewhere: multiple assignment like this is generally (IME) a bad practice.
```suggestion
    >>> df = 3
    >>> x = 1
```

2023-01-10 12:22 UTC, tupui approved these changes
LGTM and renders good. Thanks @dschmitz89

2023-01-10 12:22 UTC, merged