In Progress :: Bug #17387
scipy/scipy pull request #17699
Opened 2023-01-02 17:57 UTC by tinaoberoi

#### Reference issue

Closes bug #17387 
#### What does this implement/fix?

Fixes the documentation of signal.freqz for multidimentional inputs
#### Additional information

2023-01-02 22:44 UTC, melissawm requested changes
Hello @tinaoberoi ! Thanks for your PR.

I left a couple of comments, nothing major.

As a tip, we try to name PRs with meaningful explanations (for example, in this case it could be "DOC: Clarify that scipy.signal.freqz doesn't accept multidimensional inputs" or something similar.) This makes the PR easier to spot and review. There is also a similar guideline on writing the commit message - see https://docs.scipy.org/doc/scipy/dev/contributor/development_workflow.html#writing-the-commit-message

Thanks and let me know if you need help with moving this forward 😄

2023-01-02 22:44 UTC, melissawm commented on scipy/signal/_filter_design.py
> +        Numerator of a linear filter. Multidimentional inputs are not supported,
```suggestion
        Numerator of a linear filter. Multidimensional inputs are not supported,
```

2023-01-02 22:44 UTC, melissawm commented on scipy/signal/_filter_design.py
> +        b[..., np.newaxis] to adjust the dimension.
I am not really sure what is meant by the `scipy.signal.freqz(np.zeros((128, 10, 1)))` comment, can you clarify?

2023-01-02 22:44 UTC, melissawm commented on scipy/signal/_filter_design.py
> +        a[..., np.newaxis] to adjust the dimension.
Same as above.

2023-04-12 20:39 UTC, j-bowhay commented
Friendly reminder @tinaoberoi some comments here to address if you are still interested

2024-01-29 22:32 UTC, jaypal1-7 commented
Hi @j-bowhay,

Can I work on this as the issue is still open?

2024-02-05 12:15 UTC, melissawm commented
Let's give @tinaoberoi another ping to see if this can be wrapped up - if we don't hear back in, say, 2 weeks, I guess you could take it on @jaypal1-7 😄

2025-05-27 19:33 UTC, closed without merging