Clarify input dimensions for directed_hausdorff method
scipy/scipy pull request #17757
Opened 2023-01-09 20:54 UTC by chrisrapson

The docstring stated that the method accepted 2-D arrays, which (combined with the example) led me to the misunderstanding that the input co-ordinates had to be in two spatial dimensions. Now I see that the input arrays are 2-D even for N-D coordinates. Hopefully the suggested change will help other people avoid having the same misunderstanding.

See #17756

2023-01-09 21:31 UTC, tupui requested changes
Thank you for the PR. Please see the comment on the issue. IMO the fix if need be should be to explain `M, N, O`. Nothing more.

2023-01-09 21:41 UTC, tylerjereddy commented
I agree with Pamphile here, it is just the usual situation of array dimensions vs. space dimensions.

I think some programming languages/fields of math use terms like "the number of ranks," but I find adding more such terms usually just causes more confusion. Best advice is perhaps to read some NumPy docs like: https://numpy.org/doc/stable/reference/arrays.ndarray.html but if you want to do what Pamphile says I suppose that's fine as well. That said, I'd hardly be surprised if other parts of SciPy/the ecosystem assume that "2-D array" means "NumPy 2-D array..."

2023-05-30 14:04 UTC, melissawm commented
Hi @chrisrapson - are you interested in finishing this up? Let us know if you have questions. Cheers!

2023-05-31 04:41 UTC, chrisrapson commented
thanks for the reminder @melissawm, I've updated the PR

2023-08-24 21:04 UTC, j-bowhay approved these changes

2023-08-24 21:06 UTC, merged