ENH: Support multinomial distributions with n=0 trials.
scipy/scipy pull request #17750
Opened 2023-01-08 18:16 UTC by anntzer

With n=0 trials, there is a probability of 1 of observing a full-zero tuple.  In fact the logpmf formula works just fine; we simply needed to loosen the pre-check.

#### Reference issue

#### What does this implement/fix?

#### Additional information

2023-01-08 22:55 UTC, mdhaber commented
This seems sensible, but do you have a reference that considers the multinomial distribution to be defined for $n=0$? The Wikipedia page defines it for $n=0$.
![image](https://user-images.githubusercontent.com/6570539/211223145-5ef89fa4-4e9f-4ebf-ac3b-a180a0315d83.png)

I'd say it would be better to leave out an edge case than to risk incorrect behavior due to some mathematical subtlety.

Currently, it looks like there is only a test of `logpmf`. Please add a test that demonstrates that the behavior of each method is correct with `n=0`.

2023-01-18 18:29 UTC, mdhaber commented
R `rmultinom` and `dmultinom` agree:
```R
rmultinom(10, 0, c(0.1, 0.2, 0.3, 0.4))
```
produces an array of zeros, and
```
dmultinom(c(0, 0, 0, 0), size=0, c(0.1, 0.2, 0.3, 0.4))
```
returns 1.

2023-01-18 18:53 UTC, mdhaber commented
@rkearn do you see any problem implementing `multinomial` pmf/entropy/mean/cov for `n=0` trials?

2023-01-18 19:05 UTC, rkern commented
I don't think there is a problem with extending to `n=0`.

2023-01-18 21:01 UTC, anntzer commented
FWIW I came across this use case as a bug report in hmmlearn (which I maintain), where a user wanted to fit a (multidimensional) time series to a multinomial model but some time points had zero observations.

2023-01-19 08:06 UTC, mdhaber commented
Ok. Currently, it looks like there is only a test of `logpmf` with `n=0`. Please add a test to demonstrates that the behavior of each method is correct with `n=0`, and then we can merge.

2023-01-22 06:05 UTC, mdhaber requested changes
Thanks. Two thoughts for future contributions to `scipy.stats`:
- Please push new commits rather than rebase/force pushing. The latter erases the history, so review needs to start over because the code _could_ be entirely different. We'll squash merge most PRs anyway, so there are no advantages to rebasing after review has started. If there is a very clean way to break up the commits and for that reason you want to rebase, we can take care of that at the end. (I'll check out your branch so I have a copy, and after the rebase I'll verify that nothing has changed.)
- Please use `pytest.mark.parametrize` as I've demonstrated here. The advantages include consistency with other tests (written within the past few years anyway), finer-grained output if a test fails (it shows which parameters the test failed with and which it passed with), and slightly simpler test functions that hide the loops to emphasize the logic of the test.

I'll go ahead and merge if tests pass.

2023-01-22 09:05 UTC, mdhaber commented on scipy/stats/tests/test_multivariate.py
> +        assert vals6 == 0
```suggestion
        assert vals6 == 0

```

2023-01-22 15:49 UTC, mdhaber commented
Great. I've seen the one CI failure in main before, so I think this is ready. Thanks @anntzer! Please see my note above for next time.

2023-01-22 15:54 UTC, merged

2023-01-22 17:02 UTC, anntzer commented
Thanks.  I intentionally did not use parametrize in order to keep the style of the tests as they are currently written in that test module, as I didn't know if you had separate plans to modernize it or not (as in #17752).
I'll keep in mind that you already squash merge as a policy.