BLD: link to libatomic if necessary
scipy/scipy pull request #17777
Opened 2023-01-12 16:02 UTC by mgorny

#### Reference issue
Closes #17670

#### What does this implement/fix?
Add a test (using the check code from Mesa) whether 64-bit atomic builtins work correctly without additional libraries, and link to libatomic if they do not. This fixes creating _highs_wrapper extension that fails to load due to missing symbols, e.g.:

    ImportError: /home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-311-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8

#### Additional information
I have tested it on Gentoo/ppc32 that experienced the same issue as described in the linked bug.

2023-01-17 14:13 UTC, rgommers commented
Thanks @mgorny! I'll plan to review this within the next couple of days.

2023-01-17 14:17 UTC, mgorny commented
Thanks. Feel free to ping me if you have any questions.

2023-01-19 23:37 UTC, rgommers commented
I'll add a reference to the more extensive check in Mesa, because their use of `<atomic>` is optional: https://gitlab.freedesktop.org/mesa/mesa/-/blob/8c0531cf912fc3f8edbc73c679602e169c9ad3f2/meson.build#L1142-1183. 

Also double checked license of Mesa, that's liberal and BSD-3 compatible.

2023-01-19 23:56 UTC, rgommers requested changes
The logic here seems correct for GCC, but does not look portable because `__atomic_load_n` & co are GCC builtins, so MSVC won't understand them. Which means that the `find_library('atomic')` call is going to be triggered unconditionally, and will then fail I think. 

LLVM's build system checks unconditionally don't check for MSVC: https://github.com/microsoft/llvm-1/blob/44486be0a1dfb6e34fdc668998e3b051a57b48d1/cmake/modules/CheckAtomic.cmake#L57-L62. We're going to need some logic along the lines of what LLVM does here.

CI didn't trigger, not sure why. Would you be able to update this for MSVC support @mgorny, or would you prefer if I did that?

2023-01-20 04:49 UTC, mgorny commented
I can do that later today but I won't be able to test it myself.

2023-01-20 15:08 UTC, mgorny commented
Pushed an update that skips the check entirely if CC is msvc.

2023-01-22 22:39 UTC, rgommers commented
I'm trying to clean up CI a bit, so we have less unrelated breakage.

The last change probably needs a tweak, because I think that the Meson DSL doesn't short-circuit for logical expressions.

2023-01-23 06:29 UTC, mgorny commented
> I'm trying to clean up CI a bit, so we have less unrelated breakage.
> 
> The last change probably needs a tweak, because I think that the Meson DSL doesn't short-circuit for logical expressions.

Ok, I've exploded these conditions and rebased against main.

2023-01-23 06:40 UTC, mgorny commented
> scipy.scipy (Main prerelease_deps_coverage_64bit_blas) 

Hmm, this seems to have hit a bug in NumPy.

2023-01-23 09:21 UTC, rgommers commented
Yeah, that's unrelated and we can ignore it. Still trying to fix that one, NumPy `main` has been a bit messy for the past week.

2023-01-23 09:58 UTC, rgommers commented
As I mentioned on gh-17670,  the fix here is GCC-specific (e.g., for Clang on 32-bit platforms, we'd need `compiler-rt`). I think my plan here is:
- push a change to really make this GCC-specific, then merge this PR
- open an issue upstream in HiGHS to avoid the problem of needing `libatomic` to begin with

2023-01-23 11:27 UTC, mgorny commented
Thinking about it, clang is actually more complex than that. If clang is using GCC runtime (i.e. `-rtlib=libgcc`), then it wants libatomic as well. If it's using compiler-rt runtime (`-rtlib=compiler-rt`), then it needs compiler-rt. However, I might be wrong but I think the routines we need here are actually provided as part of the "builtins" library there, and it doesn't need extra `-l` flags.

2023-01-23 15:20 UTC, rgommers commented
Good point that Clang can use the GCC runtime as well @mgorny.
 
> However, I might be wrong but I think the routines we need here are actually provided as part of the "builtins" library there

I think we don't even know which routines we actually need, right? We're probing for something here, but that's just taken over from Mesa. There is quite a bit of usage of atomic ops in `scipy/_lib/highs/`, and we don't have any idea yet what is not mapping properly to machine instructions.

2023-01-23 19:16 UTC, mgorny commented
Yes, we're making a general assumption that some 32-bit architectures can't do atomics on 64-bit integers in general, and testing a subset to determine that.

2023-01-25 15:23 UTC, rgommers commented
I have extended the logic a bit, as well as the doc comment. Please let me know if that looks fine to you @mgorny.

2023-01-25 15:47 UTC, mgorny commented
Thanks. It looks good to me. I don't see much of a point in the "avoid `-latomic` if it didn't seem to fix things" case (I think it would be a really marginal corner case) but I'm not the one to oppose that and it shouldn't affect the problematic systems.

2023-01-25 16:22 UTC, rgommers commented
Thanks!

>  (I think it would be a really marginal corner case)

Unfortunately we do have those. Like folks building on a supercomputer with the Fujitsu compiler that we don't even have access to. I don't think we know what the situation is for atomics is with such compilers, and I don't want to hard-require `libatomic` because it may not exist.

2023-01-25 17:10 UTC, rgommers commented
The macOS arm64 failure is unrelated:
```
FAILED scipy/stats/tests/test_continuous_fit_censored.py::test_nct - RuntimeWarning: overflow encountered in _nct_sf
FAILED scipy/stats/tests/test_continuous_fit_censored.py::test_ncx2 - RuntimeWarning: overflow encountered in _ncx2_sf
= 2 failed, 38278 passed, 2299 skipped, 12353 deselected, 139 xfailed, 9 xpassed in 315.77s (0:05:15) =
```

All else looks good, so in it goes. Thanks again @mgorny.

2023-01-25 17:11 UTC, merged

2023-01-25 17:54 UTC, mgorny commented
Thanks for all the help and review!