BUG: Correct intermediate overflow in KS one asymptotic in SciPy.stats
scipy/scipy pull request #17783
Opened 2023-01-13 12:47 UTC by aherbert

Overflow can occur for 6*n when integer n is large.

Change the use of exp to expm1 when appropriate.

See #17775

#### Reference issue
Closes gh-17775.

#### What does this implement/fix?
Corrects integer overflow in the c implementation when n is large by changing `6*n` to `6.0*n`.

Use exp or expm1 to compute the p-value choosing whichever will be smallest. The opposite p-value is computed by subtraction from 1.

2023-01-13 13:26 UTC, tupui requested changes
Thank you @aherbert, this looks great. I only have some suggestions.

Also linter is failing. You can check locally doing `python dev.py lint`.

2023-01-13 13:26 UTC, tupui commented on scipy/stats/tests/test_continuous_basic.py
> +    # Expected values computed using mpmath to 50 dps and output at 20.
Could you add the mpmath code in comment? We like to do that. You can look for other examples in stats.

2023-01-13 13:26 UTC, tupui commented on scipy/stats/tests/test_continuous_basic.py
> +    npt.assert_almost_equal(pdf, 35946.137394996276407)  # noqa, NOT 74995.50250510222
Please use `assert_allclose` instead as recommended by NumPy's doc https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_almost_equal.html

2023-01-13 15:35 UTC, aherbert commented
`assert_allclose` uses a tolerance relative to the expected. This removed the requirement to use the ulp assertion. I switched to a parameterized test which makes it easier to add more test cases as required. Currently the 3 provided cases all failed with the old C code.

2023-01-13 16:08 UTC, tupui approved these changes
LGTM, let's see if all CI is happy now. Thanks for the quick updates.

2023-01-13 16:49 UTC, tupui commented
CI failure is not related (and now fixed on `main`). Merging. Thanks again @aherbert, it was a great issue and PR 👍

2023-01-13 16:49 UTC, merged

2023-01-13 16:51 UTC, tupui commented
Oh just for next time, try to avoid force pushing without telling first the reviewer. GitHub is not smart enough and links from email notifications are breaking after a force push. But even if, it's simpler for reviewer to know what commit they already reviewed and follow along.

2023-01-13 17:16 UTC, aherbert commented
OK. Next time I will leave the commit history and you can squash them as appropriate.

2023-01-13 17:17 UTC, tupui commented
Yes this is what we do 😃

2023-02-18 22:09 UTC, tylerjereddy commented
Bug fix shortly after `1.10.0` release so tentatively labeling for backport to `1.10.1`