Update distance.py
scipy/scipy pull request #17785
Opened 2023-01-13 18:29 UTC by SoubhagyaKhan

Added examples section to correlation, num_obs_dm and num_obs_y functions as per issue #7168

#### Reference issue

#7168 
#### What does this implement/fix?

Added functions to correlation, num_obs_dm and num_obs_y function
#### Additional information

2023-01-13 20:43 UTC, tupui requested changes
Hi @SoubhagyaKhan, thank you for the PR. There are a few things to adjust like: PEP8, linter and also since these are examples we should describe a bit what we are doing and why.

For the linters you can check locally using `dev.py`. e.g. for the linter:

```
python dev.py lint
```

Please have a look at our contributing guide for more detailed info. Or feel free to ask questions 😃 https://scipy.github.io/devdocs/dev/contributor/development_workflow.html

Also please add the following in your commit message: `[skip actions] [skip cirrus]`

2023-01-14 09:08 UTC, j-bowhay requested changes

2023-01-14 09:08 UTC, j-bowhay commented on scipy/spatial/distance.py
> +    1.4472135954999579
```suggestion
    Examples
    --------
    To find the correlation distance between two arrays (length of each
    array must be same) without weights:
    
    >>> from scipy.spatial import distance
    >>> distance.correlation([1, 0, 1], [2, 3, 1])
    1.8660245037844386
    
    To find the correlation distance between two arrays with weights provided:
    
    >>> distance.correlation([1, 0, 1], [2, 2, 1], [2, 3, 1])
    1.4472135954999579
```

2023-01-14 09:08 UTC, j-bowhay commented on scipy/spatial/distance.py
> +    3
```suggestion
    Examples
    --------
    To compute the number of observations that correspond to a square matrix:
    
    >>> from scipy.spatial import distance
    >>> distance.num_obs_dm([[2, 4, 5], [4, 5, 6], [7, 8, 1]])  # Argument must be a square matrix
    3
```

2023-01-14 09:08 UTC, j-bowhay commented on scipy/spatial/distance.py
> +    3
```suggestion
    Examples
    --------
    To find the number of observations in a condensed distance matrix,
    here a one-dimensional array:
    
    >>> from scipy.spatial import distance
    >>> distance.num_obs_y([1, 2, 3])
    3
```

2023-01-14 11:01 UTC, tupui requested changes
Thank you for updating the PR.

Please test locally the changes. If you accept some suggestions edit the commit message (both to have meaningful messages and also skip CI). Lastly, it's better to accept suggestions in batches you can do that from the file changed tab. This limits the notifications we get.

2023-01-14 11:53 UTC, SoubhagyaKhan commented
Ok,Sir!Thank you for the advice.Will changing from 'weights' to 'weight'
resolve the issue?
On Sat, 14 Jan 2023, 16:31 Pamphile Roy, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thank you for updating the PR.
>
> Please test locally the changes. If you accept some suggestions edit the
> commit message (both to have meaningful messages and also skip CI). Lastly,
> it's better to accept suggestions in batches you can do that from the file
> changed tab. This limits the notifications we get.
> ------------------------------
>
> In scipy/spatial/distance.py
> <https://github.com/scipy/scipy/pull/17785#discussion_r1070249770>:
>
> > @@ -603,6 +603,20 @@ def correlation(u, v, w=None, centered=True):
>      correlation : double
>          The correlation distance between 1-D array `u` and `v`.
>
> +    Examples
> +    --------
> +    To find the correlation distance between two arrays (length of each
> +    array must be same) without weights:
> +
> +    >>> from scipy.spatial import distance
> +    >>> distance.correlation([1, 0, 1], [2, 3, 1])
> +    1.8660245037844386
> +
> +    To find the correlation distance between two arrays with weights provided:
> +
> +    >>> distance.correlation([1, 0, 1], [2, 2, 1], [2, 3, 1])
>
> We should encourage people to use keywords for changing optional
> parameters. Here weight.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy/scipy/pull/17785#pullrequestreview-1248752680>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3SAMO3IRGBMMS2X2X46FVDWSKBPTANCNFSM6AAAAAAT2WHTKE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-15 12:17 UTC, tupui commented on scipy/spatial/distance.py
> +    >>> distance.correlation([1, 0, 1], [2, 2, 1], [2, 3, 1])
Please don't resolve discussions. It helps reviewers to know what they asked.

It's also not resolved as what I asked was to use a the keyword in the code like `w=...`

2023-01-15 12:21 UTC, tupui reviewed
Please try to follow the suggested workflow. I know it's a bit tedious at first but there are good reasons for it 😃 (commit naming, skipping CI, suggestion, local testing)

2023-01-15 19:06 UTC, tupui requested changes
Thank you for the update. It looks close to it in terms of formatting. Though I am still missing the value these examples would bring. I am personally still missing a bit of explanations of the value these functions bring. i.e. just running the function with random inputs is not helping a lot newcomers to understand a function.

2023-01-15 19:45 UTC, j-bowhay commented
> Thank you for the update. It looks close to it in terms of formatting. Though I am still missing the value these examples would bring. I am personally still missing a bit of explanations of the value these functions bring. i.e. just running the function with random inputs is not helping a lot newcomers to understand a function.

For example, for correlation distance demonstrating some of the properties from the [Wikipedia article](https://en.wikipedia.org/wiki/Distance_correlation#Distance_correlation_2) could be nice

2023-01-19 12:07 UTC, SoubhagyaKhan commented
Reviewers @tupui, @j-bowhay any more changes required ?If so, please tell me!

2023-01-19 12:10 UTC, tupui commented
@SoubhagyaKhan I am still missing some explanations on what we are doing in correlation. What are these values, how to interpret the result, etc.

2023-01-22 08:43 UTC, j-bowhay commented
Please have a look at https://numpydoc.readthedocs.io/en/v1.5.0/format.html#sections and the order sections need to go in, thanks!

2023-05-30 14:02 UTC, melissawm commented
Hello @SoubhagyaKhan :wave: would you be willing to address the comments above? Thanks!

2023-09-28 21:03 UTC, j-bowhay commented
Thanks @SoubhagyaKhan for your contribution unfortunately an example has now been added for this function but this is appreciated regardless

2023-09-28 21:03 UTC, closed without merging