Updated hamming to check if size of w does not match the size of u and v
scipy/scipy pull request #17798
Opened 2023-01-16 09:08 UTC by aadya940

#### Reference issue

#### What does this implement/fix?

2023-01-16 10:41 UTC, j-bowhay requested changes
Thanks @aadya940, this will also need a test that checks the error is raised

2023-01-16 10:41 UTC, j-bowhay commented on scipy/spatial/distance.py
> +            raise ValueError('w should have same dimensions as u and v')
The indentation here is not correct

2023-01-16 18:57 UTC, aadya940 commented
> Thanks @aadya940, this will also need a test that checks the error is raised

Hey @j-bowhay ,
I have submitted the code with a test. Please do check it and help me out as I'm new to contributing to Scipy and unit-testing. Thanks.

2023-01-16 21:13 UTC, j-bowhay commented
Please could you test this locally (https://docs.scipy.org/doc/scipy/dev/contributor/development_workflow.html) and fix the syntax errors then I will take a look :)

2023-03-03 16:07 UTC, melissawm commented on scipy/spatial/distance.py
> +       else:
I believe you have an indentation error here?

2023-03-03 16:08 UTC, melissawm commented on scipy/spatial/tests/test_distance.py
> +    assert_raises(ValueError, x, y, w)
It doesn't look like this test is testing anything - maybe you forgot something?

2023-03-31 10:03 UTC, j-bowhay commented
Thanks @aadya940, the original issue has now been closed so I am going to close this. Regardless, thank you for your contribution

2023-03-31 10:03 UTC, closed without merging