TST: Added test suite for dgamma distribution
scipy/scipy pull request #17794
Opened 2023-01-16 00:53 UTC by MatteoRaso

The distribution had absolutely no tests, which runs the risk of letting bad code get passed into the codebase.

#### Reference issue

No reference issue
#### What does this implement/fix?

Adds tests for dgamma, as there weren't any previously.
#### Additional information

2023-01-16 20:06 UTC, mdhaber requested changes
Thanks; just a few simplifications and we can merge.

2023-01-16 20:06 UTC, mdhaber commented on scipy/stats/tests/test_distributions.py
> +
```suggestion
```
Covered by
https://github.com/scipy/scipy/blob/0406594b35bf0b382e06d2d56ed0ac1171fbe645/scipy/stats/tests/test_continuous_basic.py#L556

2023-01-16 20:06 UTC, mdhaber commented on scipy/stats/tests/test_distributions.py
> +
```suggestion
```
Covered by
https://github.com/scipy/scipy/blob/0406594b35bf0b382e06d2d56ed0ac1171fbe645/scipy/stats/tests/test_continuous_basic.py#L563

2023-01-16 20:06 UTC, mdhaber commented on scipy/stats/tests/test_distributions.py
> +        np.isclose(stats.dgamma.isf(0.01, 1.01), y_2, atol = 1e-13)
```suggestion
```
ISF is checked against SF
https://github.com/scipy/scipy/blob/0406594b35bf0b382e06d2d56ed0ac1171fbe645/scipy/stats/tests/test_continuous_basic.py#L563

2023-01-16 20:09 UTC, mdhaber commented on scipy/stats/tests/test_distributions.py
> +        assert_almost_equal(y_3, stats.dgamma.pdf(0.03, 0.01))
Also, we don't use `assert_almost_equal` in new code.

![image](https://user-images.githubusercontent.com/6570539/212758421-07d6ad16-7c24-4f62-805d-cd144efdd1c3.png)

2023-01-17 06:47 UTC, MatteoRaso commented on scipy/stats/tests/test_distributions.py
> +        #the defintion from the Scipy documentation
I implemented the pdf using numpy, and then used that to give me my reference values.

2023-01-17 07:16 UTC, MatteoRaso commented on scipy/stats/tests/test_distributions.py
> +        assert_equal(f.pdf(1.3), stats.dgamma.pdf(1.3, 1.1))
Done.

2023-01-17 21:10 UTC, WarrenWeckesser commented
The relation to the gamma distribution could be used to test the CDF also, with something like

    res = stats.dgamma.cdf(x, a)
    ref = np.where(x < 0, 0.5*stats.gamma.sf(-x, a),
                   0.5 + 0.5*stats.gamma.cdf(x, a))
    assert_allclose(res, ref, rtol=1e-12, atol=8e-15)

where `x` and `a` are generated as in `test_pdf`.  This snippet could be added to `test_pdf`, with the name changed to `test_pdf_cdf` (to save CPU time generating the random input), or it could be a separate test (to separate concerns of the tests and provide more focused results if the test fails).

A few experiments with `dgamma.cdf` and `dgamma.sf` exposed a weakness of the current implementation: precision is lost in the tails as a result of subtractive cancellation.  I'll create a new issue for that.

2023-01-17 21:36 UTC, mdhaber commented
But since the CDF is already tested in test_continuous, let's not pull the author back and forth here. I'll open a separate issue about distribution testing standards. For now, @MatteoRaso, please just fix the lint error.

2023-01-17 21:39 UTC, WarrenWeckesser commented
That's fine.  I'll take a closer look at the tests when I submit a fix for https://github.com/scipy/scipy/issues/17805

2023-01-18 01:20 UTC, mdhaber commented on scipy/stats/tests/test_distributions.py
> +class TestDgamma:
```suggestion

class TestDgamma:
```

2023-01-18 01:22 UTC, mdhaber approved these changes
Hopefully, the most recent commit fixes the lint issue. I'll merge when that passes (since `[skip ci]` doesn't seem to work when the commit is added via GitHub...).

2023-01-18 17:03 UTC, merged

2023-01-18 17:03 UTC, mdhaber commented
Thanks @MatteoRaso!

2023-01-18 20:39 UTC, MatteoRaso commented
No problem.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
On Wednesday, January 18th, 2023 at 12:04 PM, Matt Haberland ***@***.***> wrote:

> Thanks ***@***.***(https://github.com/MatteoRaso)!
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/scipy/scipy/pull/17794#issuecomment-1387418240), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AIDGW6SVYVLORRUAMVB7LB3WTAPAVANCNFSM6AAAAAAT4FNK7Y).
> You are receiving this because you were mentioned.Message ID: ***@***.***>