Non-parametric test, similar to 1-samp ttest
scipy/scipy pull request #17804
Opened 2023-01-17 16:17 UTC by oshin94

#### Reference issue

#17690 

#### What does this implement/fix?

Non-parametric test to check if sample mean is same as a known population mean

#### Additional information

This is a draft PR. The tests for this piece of code have not been written yet.
@mdhaber @tupui @chrisb83 @tirthasheshpatel  Please see if I should add more content and the PR satisfies the checklists..
.
I have not created a separate class/object for the output as in `ttest_1samp`. Using the existing class `TtestResult` was not feasible as the method for computing the pvalues, statistics and confidence intervals are different and changes would have to be made in the methods. So, I avoided doing that for now. Though I think that would be possible, or a similar class can be defined. I am not sure what would have more utility. Please advice.

2023-01-17 16:48 UTC, mdhaber commented
Thanks @oshin94. This is a good start. Go ahead and continue with this. One early suggestion is to refactor such that the returned `statistic` maintains the sign of the difference between means. You can take the `abs` if you need to when computing the confidence interval (which would be a separate method like it is for `ttest_1samp`).

2023-02-14 15:07 UTC, mdhaber commented
@oshin94 no problem, but I'm just curious why you decided against continuing this one?

2023-02-14 18:45 UTC, mdhaber commented
Sounds good. Please do answer https://github.com/scipy/scipy/issues/17690#issuecomment-1396527561 when you can, though.

2023-03-18 19:52 UTC, mdhaber commented
There was no feedback from the [mailing list](https://mail.python.org/archives/list/scipy-dev@python.org/message/HXF6JZMMMWQATWREVCX3MJNYXDTB6NYQ/), and response in gh-17690 was lukewarm. We should probably look a bit further for support before continuing this one.

@raphaelvallat does this test look interesting to you (i.e. do you think it fills a gap)? Interesting enough that you'd want it in Pingouin?

@tupui does this look interesting enough to you that you'd be willing to review it?

2023-03-20 17:49 UTC, tupui requested changes
Thank you for the PR @oshin94, it's a good start!

I left a few suggestions to get you started. These points would be necessary to make the function fit with SciPy's API.

The other very important thing which is missing will be tests. Here testing against reference values you could find in the literature would be preferred. Testing against other implementations you could find in R or elsewhere is also possible.

2023-03-20 17:49 UTC, tupui commented on scipy/stats/_stats_py.py
> +                        axis=0, nan_policy='propagate'):
We have a decorator for the `axis` and `nan_policy`: `_axis_nan_policy_factory`. I would either suggest using it, or ensure all associated tests would pass on this function.

Also optional parameters should be marked as keyword only (`*`).

2023-03-20 17:49 UTC, tupui commented on scipy/stats/_stats_py.py
> +                        axis=0, nan_policy='propagate'):
`confidence_level` should be a method of the return object. See other tests such as `fligner` for e.g.

2023-03-21 07:07 UTC, oshin94 commented on scipy/stats/_stats_py.py
> +                        axis=0, nan_policy='propagate'):
Yeah, `mean_test ` does makes sense.. will make the changes in the next PR..

2023-03-21 09:26 UTC, oshin94 commented on scipy/stats/_stats_py.py
> +                        axis=0, nan_policy='propagate'):
Yes, I did mean commit. sorry for the error.

2023-04-08 18:11 UTC, mdhaber commented
@oshin94 just a reminder that you have a review waiting for you.

2023-04-27 01:14 UTC, mdhaber commented
Hi @oshin94 thought I'd check in again. If I don't hear back in a week or so, I'll go ahead and close this, but you're always welcome to reopen.

2023-05-05 01:02 UTC, closed without merging