ENH: implement _sf and _isf for powernorm distribution
scipy/scipy pull request #17848
Opened 2023-01-23 19:00 UTC by dschmitz89

#### Reference issue
Part of #17832 

#### What does this implement/fix?
Implements `_sf` and `_isf` for the powernorm distribution according to formulas from https://www.itl.nist.gov/div898/handbook/eda/section3/eda366d.htm

#### Additional information
The `powernorm` distribution so far does not have its own tests, so was not sure if they need to be added.

2023-01-23 19:48 UTC, mdhaber commented
> The powernorm distribution so far does not have its own tests, so was not sure if they need to be added.

Should add something for the PDF if there is nothing.

These new methods are equivalent to the default implementation. I don't think there is any reason to add them. To be valuable, they need to avoid some numerical issues in the default implementation (which is SF = 1 - CDF, etc.).

2023-01-23 22:15 UTC, WarrenWeckesser commented
You can reopen this.  In distributions where the support goes to +inf, the default implementation of `_sf` eventually loses precision and starts returning 0 far sooner than it should.  For example, with mpmath we can compute that `powernorm.sf(9, 1)` should be 1.1285884059538405e-19.  In the SciPy main branch, `powernorm.sf(9, 1)` returns 0.  The implementation in this PR returns 1.1285884059538324e-19 :+1: .

The default implementation of `_isf` also has problems that can be fixed with a custom implementation.  The implementation in this PR can be improved to `-_norm_ppf(q**(1/c))`.  Then an input such as `powernorm.isf(1e-17, 1)`, which results in `inf` in the main development branch, returns 8.493793224109599, which is the expected value computed with mpmath.

2023-01-23 22:19 UTC, mdhaber commented
Oops, I misread these.

2023-01-23 22:48 UTC, WarrenWeckesser commented
@mdhaber, will do.

2023-01-26 23:46 UTC, WarrenWeckesser requested changes
I requested a few whitespace/PEP-8 fixes inline.

Other changes to make:

* In the `mpmath` code in the comments above `test_isf`, the expression `q**(1/c)` is evaluated without converting the inputs to `mp.mpf` instances.  Add

      q = mp.mpf(q)
      c = mp.mpf(c)

  at the beginning of the function, and reevaluate the reference values in the unit test.
* Add a couple more tests for `cdf`, `sf` and `isf` using a small `c`, say `c = 0.02`.
* Add `rtol` to the call of `assert_allclose()` in all the new tests.  This should be standard procedure. The default `rtol=1e-07` is too big;  normally we should be able to do much better than that with double precision floating point.  Testing `cdf` and `sf` with a few values of `x` and `c` suggests that `rtol=5e-14` might work.
* <strike>*Optional* (since it is not related to this PR, and anyone could fix it later): there is a mistake in the `powernorm` docstring.  The support is *all real x*, not `x >= 0`.</strike>

2023-01-26 23:46 UTC, WarrenWeckesser commented on scipy/stats/_continuous_distns.py
> +        return - _norm_ppf(q**(1 / c))
Style nit: no space after a unary minus.
```suggestion
        return -_norm_ppf(q**(1 / c))
```

2023-01-26 23:46 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +    #     return float(- mp.sqrt(2) * mp.erfinv(2 * arg -1))
I know it's "just a comment", but...
```suggestion
    #     return float(-mp.sqrt(2) * mp.erfinv(2*arg - 1))
```

2023-01-26 23:46 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +
PEP-8: two blank lines before a class definition.
```suggestion


```

2023-01-26 23:58 UTC, mdhaber commented
> Optional (since it is not related to this PR, and anyone could fix it later): there is a mistake in the powernorm docstring. The support is all real x, not x >= 0.

I'll take care of this separately for this and genlogistic, since I had mentioned the same in gh-17857

2023-03-02 15:33 UTC, WarrenWeckesser requested changes
A couple more small changes to make before merging...

2023-03-02 15:33 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +                              (5e-2, 0.02, 17.089518110222244)])
The tests of `isf` with these value all pass with the default implementation of `_isf`.  We need a test that fails without the changes in this PR, e.g. `q=3e-18`, `c=2`.  `stats.powernorm.isf(3e-18, 2)` returns `inf` with the default implementation. In this PR, we get `5.907940937688639`, and the value computed with mpmath is `5.907940937688638` :+1: .

2023-03-04 16:09 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +                              (1e-50, 5, 6.361340902404057)])
Ah, sorry, in my previous comment I said "We need a test that fails without the changes in this PR", but what I meant was "We need an *additional* test that fails without the changes in this PR".  Including the other tests that you had is fine, and probably preferable. Could you restore those?

2023-03-04 18:11 UTC, WarrenWeckesser approved these changes
Thanks for the updates, @dschmitz89.

2023-03-04 18:42 UTC, merged