BUG: Fix handling on user-supplied filters in `signal.decimate`
scipy/scipy pull request #17881
Opened 2023-01-29 08:04 UTC by roryyorke

#### Reference issue

Fixes gh-17845.

#### What does this implement/fix?

Detect if user-supplied filter is FIR, and handle appropriately.

For complex-coefficient IIR filters, use `lfilter` and `filtfilt`, since `sosfilt` and `sosfiltfilt` don't handle complex coefficients.

#### Additional information

`filtfilt` doesn't handle complex coefficient filters correctly; see gh-17877.  Test added uses `filtfilt` to generate reference, so shouldn't need updating if that's fixed.  We could add an error or warning for this case in `decimate` until that is done.

Test suite passes locally (Ubuntu 20.04, x86_64, numpy 1.23.5, Python 3.10.8).

2023-01-29 08:04 UTC, AriyannaFisher approved these changes

2023-02-02 15:25 UTC, larsoner requested changes
Otherwise LGTM!

2023-02-02 15:25 UTC, larsoner commented on scipy/signal/_signaltools.py
> +        print(system.poles.shape)
Debugging cruft I assume
```suggestion
```

2023-04-10 07:21 UTC, roryyorke commented
For the record, the requested change was implemented; I don't know why Github still says "requested changes".

2023-04-10 12:57 UTC, larsoner commented
> For the record, the requested change was implemented; I don't know why Github still says "requested changes".

"Changes requested" by a reviewer can only be dismissed by a (human usually) reviewer, they aren't automatically removed by GitHub when you change the inline-commented lines. So pinging for another review -- implicitly done here -- is the right move. I'll take a look and probably merge since it looks like I just had one tiny comment last time. Thanks in advance!

2023-04-10 12:57 UTC, larsoner approved these changes

2023-04-10 12:57 UTC, merged