ENH: override halflogistic `sf` and `isf`
scipy/scipy pull request #18002
Opened 2023-02-19 08:04 UTC by dschmitz89

#### Reference issue
#17832

#### What does this implement/fix?
Overrides survival function and inverse survival function for the halflogistic distributions. Using a little algebra we get:
$SF(x)=1-CDF(x)=1-\tanh(x/2)=2/(1+e^x)=2\text{expit}(-x)$
$ISF(q)=-\text{logit}(q/2)$

#### Additional information
The current survival function fails at about $x=38$.

![halflogistic_survival](https://user-images.githubusercontent.com/40656107/219936252-b1c3c213-c81d-4c81-ac51-8f66e65310ec.png)

<details>

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy import special as sc

x = np.linspace(0, 400, 200)
plt.semilogy(x, stats.halflogistic.sf(x), label="main", ls="dashed")
plt.semilogy(x, 2 * sc.expit(-x), label="PR", ls="dotted")
plt.legend()
plt.title("Halflogistic survival function")
plt.show()

</details>

Inverse survival function: greatly improved range for small values.

![halflogistic_inverse_survival](https://user-images.githubusercontent.com/40656107/219936342-5bdbf2b8-614e-4430-8bc3-2c9721cedfa4.png)

<details>

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy import special as sc

x = np.logspace(-40, -10, 200)
plt.semilogx(x, stats.halflogistic.isf(x), label="main", ls="dashed")
plt.semilogx(x, -sc.logit(0.5 * x), label="PR", ls="dotted")
plt.legend()
plt.title("Halflogistic inverse survival function")
plt.show()

</details>

2023-03-03 06:38 UTC, WarrenWeckesser requested changes
The new `_sf` works great, but for `_isf`, it looks like we have to play whack-a-mole on the relative error.  Here's a plot of the relative error of the original version of `isf` and the version in this pull request.  The pull request fixes the large errors near 0, but it has significantly worse relative error than the default for inputs near 1.  If you zoom in, you can see that a good threshold for switching between the versions is right in the middle, p=0.5.

![halflogistic_isf_relerr](https://user-images.githubusercontent.com/321463/222647975-156304b0-3960-4552-9261-102e253c5986.png)

Note: the script uses `mpsci.distribution.half_logistic`, a very recent addition to `mpsci`.

<details>
<summary>script that generates the plot</summary>

```

import numpy as np
from scipy import stats
from scipy.special import logit
from mpmath import mp
from mpsci.distributions import half_logistic
import matplotlib.pyplot as plt


p = np.linspace(1e-5, 1, 10000, endpoint=False)
# x1 = stats.halflogistic.isf(p)
x1 = 2*np.arctanh(1 - p)  # Same as stats.halflogistic.isf(p) in main.
x2 = -logit(0.5*p)

mp.dps = 100
x = np.array([float(half_logistic.invsf(t)) for t in p])

plt.plot(p, np.abs(x1 - x)/x, alpha=0.35, label='original')
plt.plot(p, np.abs(x2 - x)/x, alpha=0.35, label='pull request')
plt.title('half-logistic isf relative error')
plt.xlabel('p')
plt.grid()
plt.legend(framealpha=1, shadow=True)
plt.ylim(-1e-15, 4e-14)
plt.show()
```

</details>

2023-03-03 06:38 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +    #     mp.dps = 50
Delete this--you already set `dps` two lines above.

2023-03-04 10:11 UTC, dschmitz89 commented
Thanks for the suggestions @WarrenWeckesser , the relative error of `isf` is much lower now.

<details>
<summary>Relative error using the new formulation</summary>

```
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy import special as sc

@np.vectorize
def isf_mpmath(x):
    x = mp.mpf(x)
    x = x/mp.mpf(2.)
    return float(-mp.log(x/(mp.one - x)))

def isf_special(x):
    return np.where(x < 0.5, -sc.logit(0.5 * x),
                    2*np.arctanh(1 - x))

x = np.linspace(0, 1, 100000)
mpmath_isf = np.array(isf_mpmath(x), dtype=np.float64)
result_special = isf_special(x)

plt.plot(x, np.abs((result_special - mpmath_isf)/mpmath_isf), label="arctanh")
plt.title("Relative error: halflogistic inv. survival function")
```

</details>


![image](https://user-images.githubusercontent.com/40656107/222893904-81898bb5-82e7-4f2a-9310-ebb76515fca0.png)

2023-03-07 06:26 UTC, WarrenWeckesser approved these changes
Looks good.  I'll make a tiny tweak to a few lines of commented code and merge.

2023-03-07 06:26 UTC, WarrenWeckesser commented on scipy/stats/tests/test_distributions.py
> +    #     return float(-mp.log(x/(mp.one - x)))
Simplify a bit, and avoid changing the value of an argument:
```suggestion
    #     halfx = mp.mpf(x)/2
    #     return float(-mp.log(halfx/(mp.one - halfx)))
```

2023-03-07 06:27 UTC, merged