DOC: add examples for xlog1py
scipy/scipy pull request #18082
Opened 2023-03-02 14:26 UTC by OmarManzoor

#### Reference issue

Relates to gh-7168

#### What does this implement/fix?

- Adds an example for xlog1py

#### Additional information

None

2023-03-02 16:27 UTC, tupui requested changes
Thank you for the PR @OmarManzoor. I have the same suggestions as your other PR. Some comments on the results and params you are taking would help.

2023-03-03 08:49 UTC, j-bowhay commented on scipy/special/_add_newdocs.py
> +    and :math::`k` is the number of trials to get the first success.
```suggestion
    and :math:`k` is the number of trials to get the first success.
```

2023-03-03 09:02 UTC, tupui approved these changes
Thank you for the update @OmarManzoor and for using the CI skip comments.

Note that we need to run at least once the Azure ones because the linters are there. We know it's not optimal and are thinking about ways to change this.

Once linters are green LGTM to merge.

Thanks Jake for having a look as well!

2023-03-03 09:09 UTC, tupui commented
Actually @OmarManzoor would you mind actually fixing this?

```
scipy/special/_add_newdocs.py:11:10: UP006 [*] Use `dict` instead of `Dict` for type annotations
```

It's not linked to this PR, but does not matter much as it's just a one letter change. It's annoying us because we are touching this file.

2023-03-03 09:09 UTC, OmarManzoor commented
> Actually @OmarManzoor would you mind actually fixing this?
> 
> ```
> scipy/special/_add_newdocs.py:11:10: UP006 [*] Use `dict` instead of `Dict` for type annotations
> ```
> 
> It's not linked to this PR, but does not matter much as it's just a one letter change. It's annoying us because we are touching this file.

Sure!

2023-03-03 09:11 UTC, tupui commented
Thanks! Please just wait for the `refguide_asv_check` check to finish before pushing with `[skip ci]`.

2023-03-03 09:15 UTC, OmarManzoor commented
> Thanks! Please just wait for the `refguide_asv_check` check to finish before pushing with `[skip ci]`.
> 
> Seems I was too late 😅 no worries.

Sorry about that. If needed I'll try to push something after these checks complete.

2023-03-03 09:22 UTC, OmarManzoor commented on scipy/special/_add_newdocs.py
> +    taking the exponetial of the log pmf.
```suggestion
    taking the exponential of the log pmf.
```
This can be fixed.

2023-03-03 10:03 UTC, merged