BUG: throw AssertionError for mismatched w dimensions and test for error
scipy/scipy pull request #18199
Opened 2023-03-27 03:10 UTC by scb-school

#### Reference issue
Closes #17725 

#### What does this implement/fix?
Fixes misleading error message in hamming function when dimensions of optional argument w do not match u and v. Also implements new test in test_distance.py that checks for the error.

#### Additional information
N/A

2023-03-27 08:25 UTC, j-bowhay requested changes
Thanks, @scb-school! A couple of suggestions. Also, the lint failure looks related, please could you check (`python dev.py lint`) and fix this.

2023-03-27 08:25 UTC, j-bowhay commented on scipy/spatial/distance.py
> +            raise ValueError('w should have same dimensions as u and v.')
```suggestion
            raise ValueError("'w' should have the same length as 'u' and 'v'.")
```

2023-03-27 08:25 UTC, j-bowhay commented on scipy/spatial/tests/test_distance.py
> +    assert_raises(ValueError, whamming, x, y, z)
```suggestion
    u = [0, 0, 1]
    v = [0, 0, 1]
    w = np.array([1, 0, 1, 0])
    msg = "'w' should have the same length as 'u' and 'v'."
    with assert_raises(ValueError, match=msg):
        whamming(u, v, w)
```

2023-03-27 22:47 UTC, tupui commented on scipy/spatial/tests/test_distance.py
> +def test_hamming_unequal_length_with_w():
This should fix the linter 😃 
```suggestion
    assert_raises(ValueError, whamming, x, y)


def test_hamming_unequal_length_with_w():
```

2023-03-29 08:22 UTC, j-bowhay requested changes
Sorry missed this the first time around but it is important to call `_validate_weights(w)` before performing the check so we don't break compatibility if the user parses a list

2023-03-29 08:22 UTC, j-bowhay commented on scipy/spatial/distance.py
> +            w = _validate_weights(w)
```suggestion
        w = _validate_weights(w)
        if w.shape != u.shape:
            raise ValueError("'w' should have the same length as 'u' and 'v'.")
```

2023-03-29 08:22 UTC, j-bowhay commented on scipy/spatial/tests/test_distance.py
> +    w = np.array([1, 0, 1, 0])
```suggestion
    w = [1, 0, 1, 0]
```

2023-03-31 09:59 UTC, j-bowhay approved these changes
Thanks @scb-school and congratulations on your first contribution to SciPy, keep them coming!

2023-03-31 10:01 UTC, merged