replace isspmatrix with issparse in mmio module
scipy/scipy pull request #18556
Opened 2023-05-26 22:37 UTC by dschult

replace isspmatrix() with issparse() in mmio.py module

2023-05-26 22:45 UTC, rossbar approved these changes
LGTM - the sparse format writer is triggered by whether or no the input is sparse, so I believe `issparse` is the appropriate choice!

2023-05-26 22:50 UTC, perimosocordiae approved these changes

2023-05-27 00:59 UTC, perimosocordiae requested changes

2023-05-27 00:59 UTC, perimosocordiae commented on scipy/optimize/_nonlin.py
> +    elif scipy.sparse.issparse(J):
This should probably be reverted, at least for now: the code below is relying on `J*v` being a matrix-vector product, so a sparse array isn't a viable substitute here.

2023-05-27 00:59 UTC, perimosocordiae commented on scipy/optimize/_nonlin.py
> +                elif scipy.sparse.issparse(m):
Same here. We want the sparse arrays to take the branch just above this one.

2023-05-27 00:59 UTC, perimosocordiae commented on scipy/optimize/_nonlin.py
> +                elif scipy.sparse.issparse(m):
And here, too.

2023-05-29 04:18 UTC, perimosocordiae approved these changes
This is looking good now, thanks! Getting rid of that big block of dead code is quite nice.

2023-05-29 15:32 UTC, rossbar approved these changes
This LGTM as well! In principle the remaining `isspmatrix`es can/should also be updated to use `isinstance(J, spmatrix)` following #18531 , but that can be handled in another PR.

2023-05-29 17:18 UTC, dschult commented
Yes, the `ispmatrix` calls in the optimize subpackage can be replaced by checking `isinstance(..., spmatrix)`. But it might be even better to adapt that code to get them working for either sparray or spmatrix (i.e. by changing from `*` to `@` and perhaps other changes).  So, I agree that changing the optimize code would be better in a separate PR as suggested.

And for future clarity, I'll explain here that the large block of code removed from '_mmio.py` in this PR is impossible to reach and thus no longer needed. Presumably it used to be able to be reached.  The import statement at the top of the module `from scipy.sparse import coo_matrix, ...` ensures that `coo_matrix` is present in scipy. So the local check at line 656 for `coo_matrix` will never result in `coo_matrix is None`.  That allows us to remove the lines for the if clause at line 719.

2023-05-30 10:21 UTC, dschult commented
It'd be good to get this and #18565 merged before the new release so the deprecations in #18565 will be remove in v1.13.

2023-05-30 11:23 UTC, j-bowhay commented
I believe the branch has already happened so these won't make it in until 1.12

2023-05-31 05:10 UTC, rgommers approved these changes
LGTM too. It seems to me like this is also a bug fix, for sparse array (rather than matrix) usage with this `io` functionality. So I'll mark it for backporting to 1.11.x

2023-05-31 05:11 UTC, merged

2023-05-31 05:11 UTC, rgommers commented
Thanks @dschult, all.