In sparse, deprecate isspmatrix and isspmatrix_fmt
scipy/scipy pull request #18565
Opened 2023-05-27 01:01 UTC by dschult

Deprecate `isspmatrix` and `isspmatrix_fmt`

This is unlikely to pass tests before #18556 is merged. So, its in draft PR mode now.

2023-05-27 07:02 UTC, j-bowhay requested changes
A minor nit

2023-05-27 07:02 UTC, j-bowhay commented on doc/source/conf.py
> +warnings.filterwarnings(
can you add this here instead so we are not doing the same thing in multiple places
https://github.com/scipy/scipy/blob/763a25e17379c43529bef5e94f0a7d73ac07969a/doc/source/conf.py#L316-L326

2023-05-31 05:19 UTC, rgommers requested changes
`isspmatrix` is heavily used (e.g., in scikit-learn) and it seems to be like it should not be deprecated separately from `csr_matrix` & co, because it provides useful functionality for those classes.

Why not just leave this alone?

2023-05-31 05:39 UTC, rgommers commented
xref https://github.com/scipy/scipy/pull/18530#issuecomment-1569525471 for the general deprecation plan that is needed.

2023-12-22 21:23 UTC, dschult commented
I’m closing this and will reopen, or do it differently when we get to the point of deprecations.

2023-12-22 21:23 UTC, closed without merging