DOC: Add explicit sidebar for API reference pages
scipy/scipy pull request #18596
Opened 2023-05-31 16:45 UTC by melissawm

[skip cirrus]

#### Reference issue
Addresses #18535

#### What does this implement/fix?
This is a workaround for #18535, and it may be unnecessary if we figure out the definitive source of that error.

#### Additional information
Could be related to #18031

2023-05-31 19:06 UTC, melissawm commented
Ok - this is really weird! The `dev` in the documentation folder is somehow being picked up by the version switcher (which also expects a `dev` version of the docs) so renaming the folder from dev to development works 🤯 

Here's the rendered version after the fix: https://output.circle-artifacts.com/output/job/5d1e2549-03f6-4bbc-a3d6-93277a5b00cf/artifacts/0/html/reference/index.html

2023-05-31 19:15 UTC, tupui commented
oh! good find!! cc @drammock as we discussed this during the summit.

So I suppose we don't need the custom `html_sidebars` anymore?

I am personally ok with renaming this folder, and CI is happy. So not sure there would be any issues does that.

2023-05-31 19:27 UTC, melissawm commented
> So I suppose we don't need the custom html_sidebars anymore?

Probably not - I will clean up and fix other broken links internally, and will ping when this is good to go

2023-05-31 20:34 UTC, melissawm commented
Ok - this should be done! [CircleCI preview looks good](https://output.circle-artifacts.com/output/job/bdf9fcd7-6b29-4a5a-902f-b241a101e05b/artifacts/0/html/reference/index.html), I think I got all the links.

2023-05-31 20:47 UTC, tupui reviewed
Ark I am looking at this again and this will break some links on scipy.org. I would say it could be ok if we promptly fix these there. But maybe we don't want to break these for everyone... What do you think?

Looks like changing the switcher itself would be easier. And yes we would only see the rendering after merging.

2023-05-31 22:09 UTC, tupui requested changes
haha no worries. The changes in the switcher files are ok, but we still need to adjust the `conf.py`

2023-05-31 22:19 UTC, tupui approved these changes
Thanks, I think we are all set now. Let's get this in and try 🤞

2023-05-31 22:19 UTC, merged

2023-05-31 23:04 UTC, melissawm commented
It worked 🎉

2023-05-31 23:07 UTC, tupui commented
yay you rock!!!!!!

![arnold-schwarzenegger-thumbs-up](https://github.com/scipy/scipy/assets/23188539/16a6e4a6-5d9d-4941-83d0-03181716fd9f)

2023-06-01 09:04 UTC, tupui commented
mmm the issue is back! I have no clue what is happening. Will try to inspect this.

2023-06-01 09:21 UTC, tupui commented
ok so right now we have this custom code for the sidebar

```html
<nav class="bd-links" id="bd-docs-nav" aria-label="Main navigation">
  <div class="bd-toc-item active">
    {% if pagename.startswith("reference") %}
    {{ generate_nav_html("sidebar", maxdepth=1, collapse=True, includehidden=True, titles_only=True) }}
    {% else %}
    {{ generate_nav_html("sidebar", maxdepth=2, collapse=True, titles_only=True) }}
    {% endif %}
  </div>
</nav>
```

The key is this `includehidden=True` so seems like something is broken here. We only use this because in the ref section we are using a hidden toctree. Since we refactored this a bit, I will try to remove this and use a normal toctree without relying on showing hidden things. This is also more future proof as with the new version of the theme we don't have this logic anymore. I will make a PR and we see from here.

2023-06-01 10:04 UTC, tupui commented
I did not make a PR yet, but I see now that the doc is rendering just fine. This is really bugging me 😅 There was an update of the doc so maybe when this happens it's flaky?? In any case, I think updating the current logic would be a good thing.