MAINT: backports for 1.11.0rc2
scipy/scipy pull request #18671
Opened 2023-06-13 23:11 UTC by tylerjereddy

Still TODO:

- [ ] need to deal with gh-18595 (that's easy enough)
- [ ] `sparse` release notes likely need a bit of tweaking, or at least for the reversion that happened cc @perimosocordiae @stefanv 
- [ ] good to check with `conda` release manager @h-vetinari if there are any concerns I'm not addressing?

Backports Included here:

1. gh-18659
2. gh-18658
3. gh-18657
4. gh-18636
5. gh-18629
6. gh-18608
7. gh-18598
8. gh-18596
9. gh-18556

2023-06-13 23:43 UTC, h-vetinari commented
> good to check with `conda` release manager @h-vetinari if there are any concerns I'm not addressing?

Would be good to have https://github.com/scipy/scipy/pull/18630. @rgommers marked it as a backport-candidate already (but also milestoned it for 1.12? 🤔 In any case, if it's not backported, I'll have to carry it on the feedstock, at least for ppc; this would also be manageable).

Otherwise there are no PRs that I'm aware of that we need for the conda-forge side, thanks for checking!

2023-06-14 06:21 UTC, rgommers commented
> Would be good to have #18630. @rgommers marked it as a backport-candidate already (but also milestoned it for 1.12? 🤔

Agreed. Merged now, would be good to add to the backports here. That PR is going into 1.12; this backport PR pulls it into 1.11 - the milestones on the respective PRs indicate that; the issue itself is also marked for 1.11.0.

2023-06-14 07:33 UTC, rgommers commented
The pre-release job is failing with `meson.build:57:2: ERROR: Problem encountered: SciPy requires Cython < 3.0`. Let's remove that check again from `meson.build` - for details, see https://github.com/scipy/scipy/pull/18591/files#r1229148530.

2023-06-14 07:40 UTC, rgommers commented
The `musllinux` job is crashing due to pulling in numpy 2.0.0.dev - the `--pre` flag had to be added for the `1.25.0` pre-release wheel, but we shouldn't be tested 2.0 nightlies in the 1.11.x branch. 

I pushed a commit that should fix both of the failing jobs.

2023-06-14 07:45 UTC, h-vetinari commented
> The `musllinux` job is crashing due to pulling in numpy 2.0.0.dev

Speaking of numpy, does the condition `numpy <1.28.0` still make sense now that the main branch targets 2.0? Doesn't have to be changed in this PR (and of course we can backport numpy 2.0 compatibility patches if we want to), but more out of curiosity.

2023-06-14 07:55 UTC, rgommers commented
> Speaking of numpy, does the condition `numpy <1.28.0` still make sense now that the main branch targets 2.0?

Yes it does - the `N+3` condition still holds. A numpy 1.26.0 is planned; it's unlikely that there'll be any more minor releases beyond that, but you never know.

2023-06-14 08:33 UTC, rgommers commented
Hmm, `musllinux` got further but is still crashing in `linalg/tests/test_decomp.py` on `TestSVD_GESDD.test_random_complex`. It passes on `main`, with what looks like the same version of OpenBLAS (0.3.23). That seems to be related to https://github.com/scipy/scipy/issues/17630#issuecomment-1358848203 and commit 5055c7eb.

2023-06-14 14:24 UTC, tupui approved these changes
Thanks Tyler! LGTM from my perspective.

About the release notes, can we do some tweaking here? I had some talk with Matt and we might want to highlight other things in stats and in general.

2023-06-14 15:59 UTC, tylerjereddy commented
> About the release notes, can we do some tweaking here? I had some talk with Matt and we might want to highlight other things in stats and in general.

Yes, please do make release notes suggestions here, or you can even open a PR against my branch or whatever suits. Apart from Matt, I think the feedback on the release notes was pretty light initially, probably the usual reason of folks being busy.

2023-06-14 16:47 UTC, tylerjereddy commented
- the two additional backports have been added in, and the summary comment at the top of this PR has been updated accordingly
- at the time of writing, the only outstanding item is making the release notes "better" + `sparse` relnotes updates probably

2023-06-14 18:02 UTC, tupui commented
@jjerphan is going to help for the sparse part tomorrow 😃 Thanks!!

2023-06-14 18:08 UTC, jjerphan commented
Or later tonight. 🦉

2023-06-14 19:08 UTC, ilayn approved these changes

2023-06-14 21:24 UTC, mdhaber requested changes
Please consider https://github.com/tylerjereddy/scipy/pull/73.

2023-06-14 21:52 UTC, jjerphan commented
I just opened https://github.com/tylerjereddy/scipy/pull/74.

2023-06-15 18:44 UTC, tylerjereddy commented
- I merged the release notes PRs from Matt and Julien, making minor tweaks to the latter
- I noticed we still hadn't removed the reference to `diags_array` in the release notes despite gh-18599, so I removed that mention
- noticed another last-minute PR to backport, gh-18676, and pulled that in
- Updated the author/PR lists again, checked doc build + test suite locally at least
- Updated summary comment above, which appears to have no oustanding items left as far as I can tell

2023-06-15 20:34 UTC, rgommers approved these changes
LGTM and CI is green modulo 3 unrelated failures, so good to go I'd say. I'd recommend either squash-merging this though or (preferably) squashing the ~10 separate commits that tweak the release notes entry for sparse array stuff.

2023-06-16 02:30 UTC, tylerjereddy commented
> squashing the ~10 separate commits that tweak the release notes entry for sparse array stuff.

- I took note of the status of the PR before the interactive rebasing adventure: `27 commits, +169 −158`
- then after doing the squasing/merge conflict resolution the PR now shows: `17 commits, +169 −158`

That looks about right I think, a bit unfortunate that a backport got interwoven or I could have condensed even more, but that's a reduction by 10.

2023-06-16 08:23 UTC, rgommers commented
LGTM now, thanks @tylerjereddy. In it goes. The hang on CirrusCI is unrelated; there's one doc warning which seems to be due to a new version of Matplotlib. That's not blocking for the release, let's deal with that in `main`.

2023-06-16 08:23 UTC, merged