CI: test with Python 3.12-beta
scipy/scipy pull request #18689
Opened 2023-06-16 13:45 UTC by tupui

Python 3.12 beta2 is out today. Probably a good time to add it in our CI.

2023-06-16 13:46 UTC, tupui commented
haha we can't yet: `ModuleNotFoundError: No module named 'distutils'`

2023-06-16 17:49 UTC, rgommers commented
I'm afraid that there is no point doing this until there is a numpy nightly for 3.12. That may take a few more weeks (or, with luck, it lands after this weekend, dunno).

2023-06-19 15:20 UTC, EwoutH commented
NumPy wheels are incoming: https://github.com/numpy/numpy/pull/23991

2023-06-20 12:49 UTC, rgommers commented
@tupui numpy nightlies are up now. If you change this to use `3.12-dev` in the CI job that uses the scientific-python bucket rather than the one you currently modified, it should work.

2023-06-20 23:18 UTC, tupui commented
We can still use `main`. Do we want the wheel instead?

I relaunched and now the error is on our side after successfully having compiled NumPy:

```
Traceback (most recent call last):
  File "/home/runner/work/scipy/scipy/dev.py", line 119, in <module>
    from distutils import dist
ModuleNotFoundError: No module named 'distutils'
```

And indeed we have even wrote something about it (gh-16058):


```python
# distutils is required to infer meson install path
# if this needs to be replaced for Python 3.12 support and there's no
# stdlib alternative, use CmdAction and the hack discussed in gh-16058
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=DeprecationWarning)
    from distutils import dist
    from distutils.command.install import INSTALL_SCHEMES
```

Another question that was raised on other repos... Should we also try to ship wheels for 3.12? Seems like CirrusCI is ready: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip

2023-06-21 06:09 UTC, rgommers commented
> Another question that was raised on other repos... Should we also try to ship wheels for 3.12? Seems like CirrusCI is ready: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip

Yes, we can start building nightlies for 3.12-beta I'd say, that will help other projects like scikit-learn & co. Probably best as a follow-up PR to this one. The GHA and Cirrus CI changes should be the same as in https://github.com/numpy/numpy/pull/23991 I'd expect.

2023-06-27 14:35 UTC, FFY00 commented
> @FFY00 seems like you were involved in some discussions around that topic. Any guidance on the best course of action as of now? Thanks in advance :smiley:

Sorry for the delay! I wasn't able to look at this earlier, but I am finally catching up with my notifications.

For Python 3.12 and forward, Debian seems to now be patching `sysconfig`. The main thing to keep in mind is that thair patching is also present inside virtual environments, so you need to make sure you only use `platlib` from `deb_system` when you aren't in a virtual environment, or similar. This can be achieved by looking at `sysconfig.get_default_scheme()`, which will return `posix_local` when you are on the global environment.

So, you'd change	

https://github.com/scipy/scipy/blob/f05674ac43c7dd2d82f37b7c702ff71366bffefb/dev.py#L335-L348

to

```python
def get_site_packages(self):
    """
    Depending on whether we have debian python or not,
    return dist_packages path or site_packages path.
    """
    if sys.version_info < (3, 12) and 'deb_system' in INSTALL_SCHEMES:
        # debian patched python in use
        install_cmd = dist.Distribution().get_command_obj('install')
        install_cmd.select_scheme('deb_system')
        install_cmd.finalize_options()
        plat_path = Path(install_cmd.install_platlib)
    elif sysconfig.get_default_scheme() == 'posix_prefix':
        # debian patched python in use, and we are on the global environment
        # posix_prefix is the user-installable debian scheme
        plat_path = Path(get_path('platlib', scheme='deb_system'))
    else:
        plat_path = Path(get_path('platlib'))
    return self.installed / plat_path.relative_to(sys.exec_prefix)
```

However, I'd actually respect Debian's patching and install to `posix_local` unless you have a reason not to. I don't know the motivation behind doing `install_cmd.select_scheme('deb_system')` in your current code, but I suspect it might have just been copied from somewhere else.

The adjusted code:

```python
def get_site_packages(self):
    """
    Depending on whether we have debian python or not,
    return dist_packages path or site_packages path.
    """
    if sys.version_info < (3, 12) and 'deb_system' in INSTALL_SCHEMES:
        # debian patched python in use
        install_cmd = dist.Distribution().get_command_obj('install')
        install_cmd.finalize_options()
        plat_path = Path(install_cmd.install_platlib)
    else:
        plat_path = Path(get_path('platlib'))
    return self.installed / plat_path.relative_to(sys.exec_prefix)
```

No special handling is needed for Debian anymore because they now patch `sysconfig`.

That is, unless you actually want to install to the Debian install directory (`/usr/lib/python3.12/dist-packages`), which is usually reserved for Debian packages, instead of the Debian-adjusted user install directory (`/usr/local/lib/python3.12/dist-packages`).

2023-06-27 14:40 UTC, FFY00 commented
It seems this code was introduced in https://github.com/scipy/scipy/commit/9e19577939d8ef10558f9485db84cc74dd2c7710. @AnirudhDagar, do you remember if there was a specific reason behind installing to `deb_system`, or if it was just inherited from the code it was based on?

2023-06-27 15:34 UTC, AnirudhDagar commented
Thanks @FFY00 for sharing the update on Debian Python 3.12 `sysconfig` patch. It was there in the first place because we wanted to mimic the exact behaviour of `mesonbuild` for installation to avoid path inconsistencies. IIRC, meson was using `deb_system`.

> No special handling is needed for Debian anymore because they now patch sysconfig.
> 
> That is, unless you actually want to install to the Debian install directory (/usr/lib/python3.12/dist-packages), which is usually reserved for Debian packages, instead of the Debian-adjusted user install directory (/usr/local/lib/python3.12/dist-packages).

This makes sense, we don't need to specifically install to Debian install directory, as long as we make sure the path behaviour is the same as `mesonbuild`'s.

2023-06-28 23:25 UTC, tupui commented
@AnirudhDagar would you like to handle this?

2023-06-29 08:07 UTC, AnirudhDagar commented
Thanks, happy to take this up. @tupui is it okay if I send a PR early next week?
I'm occupied with a lot of office work this week.

2023-06-29 08:15 UTC, tupui commented
Sure thank you @AnirudhDagar 🙏

2023-07-21 01:09 UTC, andyfaff commented
Reopened this PR. #18924 will enable this PR to go further in CI for cp312, it wasn't a replacement for this PR.

2023-07-21 01:21 UTC, AnirudhDagar requested changes
As [mentioned](https://github.com/scipy/scipy/pull/18924#issue-1814556660), this PR will require installing `setuptools` in the 3.12 CI job since meson has not gotten rid of `distutils` yet (open PR https://github.com/mesonbuild/meson/pull/11133)

2023-07-21 01:21 UTC, AnirudhDagar commented on .github/workflows/linux_meson.yml
>          python -m pip install ninja cython pytest pybind11 pytest-xdist pytest-timeout click rich-click doit pydevtool pooch
```suggestion
        python -m pip install ninja cython pytest pybind11 pytest-xdist pytest-timeout click rich-click doit pydevtool pooch setuptools<67.3
```

2023-07-21 01:29 UTC, AnirudhDagar commented on .github/workflows/linux_meson.yml
>          python -m pip install ninja cython pytest pybind11 pytest-xdist pytest-timeout click rich-click doit pydevtool pooch
Sorry, that should be in double quotes "setuptools<67.3"

2023-07-21 01:30 UTC, andyfaff commented on .github/workflows/linux_meson.yml
> +        python -m pip install ninja cython pytest pybind11 pytest-xdist pytest-timeout click rich-click doit pydevtool pooch setuptools<67.3
```suggestion
        python -m pip install ninja cython pytest pybind11 pytest-xdist pytest-timeout click rich-click doit pydevtool pooch "setuptools<67.3"
```

2023-07-21 02:43 UTC, andyfaff commented
This is looking good. I think the test fail is unrelated?

2023-07-21 06:35 UTC, tupui commented
Yes seems unrelated, thanks both! Let's get this in

2023-07-21 06:36 UTC, merged

2023-07-21 08:07 UTC, lesteve commented
Great timing, for scikit-learn I was interested to add Python 3.12 testing and I found this PR that just got merged!

It would be great to have nightly wheels uploaded as mentioned in https://github.com/scipy/scipy/pull/18689#issuecomment-1600240949.

I am willing to take inspiration from numpy and have a go at a scipy PR, but if someone from Scipy plans to do it it may be quicker, let me know!

2023-07-21 08:22 UTC, andyfaff commented
I'm trying to build nightlies at https://github.com/andyfaff/scipy/actions/runs/5619957108/job/15227994408, but running into issues building numpy within the cibuildwheel context.

2023-07-21 08:39 UTC, rgommers commented
It seems like cibuildwheel has no dedicated option to use another wheelhouse, nor do I see an option to use a pre-release from PyPI. So even when numpy uploads a pre-release wheel in ~10 days when Python 3.12.0rc1 arrives, it needs a custom install I think. Using [CIBW_BEFORE_BUILD](https://cibuildwheel.readthedocs.io/en/stable/options/#before-build) is the way to go I think, for nightlies compatible with numpy nightlies we anyway need to use those numpy nightlies, and not rebuild numpy 1.25.x. So I think putting this in `CIBW_BEFORE_BUILD` is the way to go:
```
pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
```