DEP: Closes #18577
scipy/scipy pull request #18834
Opened 2023-07-06 18:09 UTC by bathongor

#### Reference issue

Closes #18577 

#### What does this implement/fix?
.
Deprecates the positional arguments in sparse.linalg.gmres method.

#### Additional information

2023-07-06 19:32 UTC, bathongor commented
I am a first time contributor to SciPy. Do I need to write some documentation in /doc folder?

2023-07-06 20:48 UTC, j-bowhay commented
Thanks for the contribution! I will let @h-vetinari confirm what he had in mind here, but we cannot do this directly as it is not backwards compatible.

2023-07-07 04:25 UTC, h-vetinari requested changes
Thanks for the PR. Unfortunately, things are not so simple. You can read what needs to be done in https://github.com/scipy/scipy/issues/18703, but I doubt that that's a good first issue to tackle.

Maybe have a look at those issues that are explicitly marked "good first issue"?

PS. Please don't write private emails to people whose email address you found in the commit history. You can request feedback from people directly in GitHub. In any case, it might take some time until they get around to respond. We all get lots of notifications, so expecting an answer within hours is neither realistic nor polite.

2023-07-22 16:48 UTC, j-bowhay commented
Thanks for your contribution @bathongor, in this case, I chose to merge @h-vetinari PR as it tackled all the iterative solvers at once however your contribution is still very much valued even if it didn't end up being merged.

2023-07-22 16:48 UTC, closed without merging