DOC: tab sync based on same tab name using ``sphinx-tabs``
scipy/scipy pull request #18887
Opened 2023-07-15 17:29 UTC by RobPasMue

#### Reference issue
None related.

#### What does this implement/fix?
When selecting an OS tab in the documentation you can also use [``sphinx-tabs``](https://sphinx-tabs.readthedocs.io/en/latest/) to easily sync all tabs related (i.e. with the same name). See the video attached. This implies adding the dependency and some minor modifications.

#### Additional information
None.

2023-07-15 17:30 UTC, RobPasMue commented
Pinging @melissawm since she is attending SciPy Conf '23 as Sprint organizer

2023-07-15 17:49 UTC, RobPasMue commented on doc/source/conf.py
> +    'sphinx_tabs.tabs',
```suggestion
```

2023-07-15 17:49 UTC, RobPasMue commented on doc/source/building/index.rst
> +       ``virtualenv``/``virtualenvwrapper``, ``pyenv``/``pyenv-virtualenv``,
Wrong formatting here. Missing backticks =) That's why it was added

2023-07-15 22:44 UTC, tupui requested changes
Thank you @RobPasMue! That's a good addition 😃

Could you also sync venv/conda on this page?

For the next commit, could you please add in its message the following to skip some of the CI: `[skip actions] [skip cirrus]`. We only need to build the doc for doc only PRs.

2023-07-16 10:42 UTC, rgommers commented
Seems like a good idea to me, thanks @RobPasMue 

> This implies adding the dependency

This works as-is with `sphinx-design` (see https://sphinx-design.readthedocs.io/en/latest/tabs.html) which is already a dependency, so no need to add a new dependency.

2023-07-16 13:19 UTC, RobPasMue commented
> This works as-is with `sphinx-design` (see https://sphinx-design.readthedocs.io/en/latest/tabs.html) which is already a dependency, so no need to add a new dependency.

Thanks @rgommers - indeed, I tried it first with ``sphinx-tabs``. @melissawm here at SciPy Conference mentioned to me that the dependency had been dropped some time ago in favor of ``sphinx-design``. That's when I started investigating how to do it with ``sphinx-design``. I just edited the PR description 😄

2023-07-16 13:20 UTC, RobPasMue commented
> Thank you @RobPasMue! That's a good addition 😃
> 
> Could you also sync venv/conda on this page?
> 
> For the next commit, could you please add in its message the following to skip some of the CI: `[skip actions] [skip cirrus]`. We only need to build the doc for doc only PRs.

Sure, you can count on it @tupui! Working on it right away =)

2023-07-16 15:29 UTC, tupui approved these changes
Thank you for the update @RobPasMue! LGTM now and we can merge 🚀 🙌

2023-07-16 15:30 UTC, merged