BUG: trust-constr status=2 despite constraint
scipy/scipy pull request #18890
Opened 2023-07-15 22:37 UTC by ellieLitwack

#### Reference issue

Fixes #18882.
#### What does this implement/fix?

Previously, trust-constr returned status=2 ("`xtol` termination condition is satisfied.") even if the constraint was not satisfied. Now, trust-constr will continue to iterate if the constraint is not satisfied. Also, this adds a test which checks for this issue in the scenario in #18882.
#### Additional information

2023-07-16 15:50 UTC, ellieLitwack commented
This is also related to #10112.

2023-07-27 13:34 UTC, andyfaff requested changes
@ellieLitwack, thank you for preparing this PR. I think we should take a slightly different approach, as suggested in the original issue.

2023-07-27 13:34 UTC, andyfaff commented on scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py
> +        constraint violation at the solution if an equality constraint is
`constr_violation` is the maximum constraint violation for both inequality and equality constraints.
I don't understand why this last sentence has been added, it's probably not necessary.

2023-07-27 13:34 UTC, andyfaff commented on scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py
> +            elif state.tr_radius < xtol and state.constr_violation < gtol:
By adding this extra stopping condition the docstring for `xtol` becomes incorrect.

The docstring should read something like:

> Tolerance for termination by the change of the independent variable.
        The algorithm will terminate when ``tr_radius < xtol and constr_violation < gtol``, where
        ``tr_radius`` is the radius of the trust region used in the algorithm.
        Default is 1e-8.


In any case, I'm not sure if this is the desired behaviour. I'd prefer to keep the stopping condition unchanged (i.e. revert this line). Instead should we add an extra item to `TERMINATION_MESSAGES`, "constraints are not satisfied", and change L538 to:

```python
if state.constr_violation > gtol:
    result.status = 4    # TERMINATION_MESSAGES[4] = "constraints are not satisfied"
result.success = True if result.status in (1, 2) else False
```

My rationale is that it's no change to the stopping condition, but still informs the user that something has gone wrong. It's relatively common that the constraints are always infeasible, in which case the proposed PR would keep going until maximum iterations had been reached. That's undesirable as it artificially prolongs minimisation.

I don't think adding the extra condition in L442 would actually improve a minimisation anyway. I'm ready to be convinced with evidence though.

2023-07-27 13:34 UTC, andyfaff commented on scipy/optimize/tests/test_minimize_constrained.py
> +        # Test that success is false if the constraint is not met.
this test does not actually test that `res.success is False` if the constraints are not met.
The test is also a lot longer than it needs to be.

2023-11-19 15:12 UTC, lucascolley commented
Hi @ellieLitwack, are you interested in returning to this PR?

2024-05-27 22:32 UTC, tylerjereddy commented
This PR has blocking comments, including at the fundamental design level, and no activity for the past 6 months, so I will bump the release milestone for now.

2024-07-18 17:59 UTC, CarrascoCesar commented
Just wanted to revive the discussion related to this issue.  Should  TERMINATION_MESSAGES be expanded to include a status 4 indicating that the constraints have not been satisfied?

2024-08-16 20:37 UTC, CarrascoCesar commented
Hello @andyfaff do you know if this issue has beed addressed through some other PR?

2024-08-16 20:58 UTC, lucascolley commented
> do you know if this issue has beed addressed through some other PR?

I don't think it has - would you like to take over the PR? Feel free to open a separate PR, and [add any coauthors](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) if you reuse code from this PR.

2024-08-16 22:32 UTC, CarrascoCesar commented
Thanks @lucascolley this will be my first PR but I'm up for it.  Will definitely reference the comments and code in this PR.

2024-08-16 22:35 UTC, lucascolley commented
Great! Our contributor guidance is at https://scipy.github.io/devdocs/dev/index.html, feel free to give me a shout if you need help

2024-08-19 20:27 UTC, CarrascoCesar commented
Hello @lucascolley I created the PR https://github.com/scipy/scipy/pull/21407 but it has failed 2 checks that I think are unrelated to the changes I made.  What should be my next step?  Should I wait for Andy to finish the review?

2024-08-19 22:33 UTC, lucascolley commented
Thanks @CarrascoCesar - please just wait for someone to take a look! I can try to take a preliminary look in the coming days.

2024-10-26 01:44 UTC, j-bowhay commented
Closing as superceded by #21407 but thanks for getting the ball rolling @ellieLitwack

2024-10-26 01:44 UTC, closed without merging