DOC:  adds docstring examples for these functions: qmf, berp_zeros, b…
scipy/scipy pull request #19058
Opened 2023-08-12 19:55 UTC by elleem

…and_stop_obj  Issue #7168

#### Reference issue

#### What does this implement/fix?

#### Additional information

2023-08-12 20:08 UTC, j-bowhay commented
Thanks @elleem! It would be great if you could add some context/motivation in these examples to aid understanding in addition to the execution of the code. Also, I would recommend only touching one module per pr as there isn't much overlap between signal and special maintainers, for example.

Finally, as these are documentation only changes we don't need to run the whole test suite so in future please could you add `[skip actions] [skip cirrus]` to the end of your commit as per https://docs.scipy.org/doc/scipy/dev/contributor/continuous_integration.html#skipping

2023-08-13 01:19 UTC, elleem commented
Thank you so much for helping a beginner! I have tried to improve based on your feedback. :) Thanks again.

2023-08-15 18:26 UTC, dschmitz89 commented on scipy/special/_basic.py
> +    -------
```suggestion
    Examples
    --------
```

2023-08-15 18:42 UTC, dschmitz89 requested changes
Thanks for the contribution @elleem. Some advice from someone who originally started contributing to SciPy also mainly on documentation.

1. You probably noticed the errors in CI: to reproduce these locally, you need to run (for all possible options, check `python dev.py --help`):
`python dev.py refguide-check`

This will help you to correct things locally. Relying fully on CI for testing is not possible for SciPy as we would run out of the free quotas.

2. Your examples are missing the necessary imports from scipy (check suggestions).

3. For SciPy documentation, the order is typically first the "Notes" and then "Examples" section.

4. We typically do not use `print()` in the examples. The examples are meant to resemble an ipython section. There, the output of a function, is directly printed. See for example one example in `special` [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.jv.html#scipy.special.jv):
![image](https://github.com/scipy/scipy/assets/40656107/3259f938-b10a-4bcc-b7b7-79341ccf0783)
Code lines have to start with `>>> `, the printed outputs can directly be inserted.

2023-08-15 18:42 UTC, dschmitz89 commented on scipy/signal/_wavelets.py
> +    array([ 0.12940,  0.22414, -0.8365 ,  0.48296])
```suggestion
    >>> from scipy.signal import qmf
    >>> low_pass_coefficients = [0.48296, 0.8365, 0.22414, -0.12940]
    >>> high_pass_coefficients = qmf(low_pass_coefficients)
    >>> high_pass_coefficients
    array([ 0.12940,  0.22414, -0.8365 ,  0.48296])
```

2023-08-15 18:42 UTC, dschmitz89 commented on scipy/signal/_filter_design.py
> +    aims to estimate the order for an analog band stop filter:
This should be shortened or become part of a `Notes` section.

2023-08-15 18:42 UTC, dschmitz89 commented on scipy/signal/_filter_design.py
> +    print(result)  # Expected: 2.386294361119891
```suggestion
    import numpy as np
    from scipy.signal import band_stop_obj

    >>> wp = 2
    >>> ind = 1
    >>> passb = np.array([1, 3])
    >>> stopb = np.array([0.5, 4])
    >>> gstop = 30
    >>> gpass = 3
    >>> filter_type = 'butter'
    >>> band_stop_obj(wp, ind, passb, stopb, gpass, gstop, filter_type)
```

2023-08-15 18:42 UTC, dschmitz89 commented on scipy/special/_basic.py
> +    print("First 5 zeros of the derivative of ber:", zeros)
```suggestion
    Compute the first 5 zeros of the derivative of the Kelvin function ber:

    >>> import numpy as np
    >>> from scipy.special import berp_zeros
    >>> berp_zeros(5)
    array([ 6.03871081, 10.51364251, 14.96844542, 19.41757493, 23.86430432])
```

2023-08-15 18:42 UTC, dschmitz89 commented on scipy/special/_basic.py
> +    -------
```suggestion
    Examples
    --------
```

2023-10-25 19:02 UTC, dschmitz89 commented
@elleem : friendly ping, are you still interested in finishing this PR?

2023-11-02 18:45 UTC, elleem commented
Yes, I would really love to finish this PR. I got a new job and I have been underwater on my work. If possible, I would really appreciate a little extension and will prioritize getting this done.

2023-11-03 04:43 UTC, dschmitz89 commented
> Yes, I would really love to finish this PR. I got a new job and I have been underwater on my work. If possible, I would really appreciate a little extension and will prioritize getting this done.

Awesome, more time is of course possible. I would recommend to split the PR into one PR per documented function though. That will make review much easier.

2024-09-26 19:44 UTC, mdhaber commented
@elleem Thanks for submitting this. Were you still interested in finishing? I can go ahead and make the requested changes so this makes it into the next version of SciPy, if you'd prefer.

2024-10-04 04:31 UTC, mdhaber commented on scipy/signal/_wavelets.py
> +       Prentice Hall. ISBN: 978-0136057185.
```suggestion
    .. [1] Vaidyanathan, P.P. (1993). "Multirate Systems and Filter Banks".
           Prentice Hall. ISBN: 978-0136057185.
```

2024-10-04 04:33 UTC, mdhaber commented on scipy/signal/_filter_design.py
> +    aims to estimate the order for an analog band stop filter:
```suggestion
    Notes
    -----
    Band-stop filters are used in applications where certain frequency
    components need to be blocked while others are allowed. For instance,
    removing noise at specific frequencies while allowing the desired signal
    to pass through. The order of a filter often determines its complexity and
    accuracy. Determining the right order can be a challenge. This function
    aims to estimate the order for an analog band stop filter.
    
    Examples
    --------
```

2024-10-04 04:34 UTC, mdhaber commented on scipy/signal/_wavelets.py
> +           Prentice Hall. ISBN: 978-0136057185.
```suggestion
    Notes
    -----
    This function takes the coefficients of a low-pass filter `hk` and computes
    the corresponding high-pass filter coefficients using a quadrature mirror
    filter (QMF) technique. The QMF technique is commonly used in filter bank
    design, especially in wavelet transform applications.

    The QMF technique works by reversing the coefficients and alternating the
    signs to create the high-pass filter. This is particularly useful when
    designing filter banks where the low-pass and high-pass filters need to
    have certain relationships for proper signal decomposition and
    reconstruction.

    References
    ----------
    .. [1] Vaidyanathan, P.P. (1993). "Multirate Systems and Filter Banks".
           Prentice Hall. ISBN: 978-0136057185.
           
    Examples
    --------
    >>> from scipy.signal import qmf
    >>> low_pass_coefficients = [0.48296, 0.8365, 0.22414, -0.12940]
    >>> high_pass_coefficients = qmf(low_pass_coefficients)
    >>> high_pass_coefficients
    array([ 0.12940,  0.22414, -0.8365 ,  0.48296])

```

2024-10-04 04:38 UTC, mdhaber commented on scipy/special/_basic.py
> +    Compute the first 5 zeros of the derivative of the Kelvin function ber:
```suggestion
    Notes
    -----
    Understanding the behavior of special functions and their derivatives is
    crucial in various fields of science and engineering. For instance, if
    you're working on problems related to heat conduction, wave propagation,
    or certain types of differential equations, you may come across the Kelvin
    function.

    Examples
    --------
    Compute the first 5 zeros of the derivative of the Kelvin function
    `scipy.special.ber`:
```

2024-10-04 13:18 UTC, j-bowhay commented on scipy/special/_basic.py
> +    function.
Thanks for pushing this on, @mdhaber. I have to admit I find this paragraph slightly too generic. Would you object to removing it?

2024-10-08 08:37 UTC, j-bowhay commented on scipy/special/_basic.py
> +    function.
```suggestion
```

2024-10-08 09:56 UTC, j-bowhay approved these changes

2024-10-08 09:57 UTC, merged