DOC: add comment on args in solve_ivp (#18876)
scipy/scipy pull request #19089
Opened 2023-08-18 12:30 UTC by gertingold

[skip ci]

#### Reference issue

gh-18876

#### What does this implement/fix?

This PR slightly extends the docstring of `solve_ivp`. Specifically, it adds remarks to  `fun`, `events`, and `jac`   that the signature has to be extended by `args` if it is used.

#### Additional information

2023-08-18 20:21 UTC, j-bowhay requested changes
Thanks @gertingold! Rather than saying above/bellow, can you say "see documentation of args argument" so it is clear exactly where to look

2023-08-19 08:14 UTC, gertingold commented
Thanks @j-bowhay for the suggestion. The text is now adapted accordingly.

2023-08-19 09:33 UTC, j-bowhay approved these changes
Thanks @gertingold! I will note that variables should really use single backticks not double however for this change this is fine as it is consistent with the rest of the docs for this function.

2023-08-19 09:33 UTC, merged

2023-08-19 12:00 UTC, gertingold commented
@j-bowhay would you like me to change the backticks consistenly in `ivp.py`?