FIX #7168 Added Examples To `combine_pvalues` and `fhtoffset`
scipy/scipy pull request #19129
Opened 2023-08-25 09:38 UTC by devbijay

Added Examples To `combine_pvalues` and `fhtoffset` docstrings

2023-08-25 09:51 UTC, ilayn commented
Hi @devbijay Thank you for the examples. Two things would make this PR even better; 

- Please refrain from putting issue numbers to commit messages because they bark at the original issue and create a bit too much noise, like the following 
![image](https://github.com/scipy/scipy/assets/1303842/fc4b9465-5082-4fd1-9b74-f9573e9e744c)
it is certainly not a big deal but tiny peace of mind for us : ) 
- And since you are only doing changes to documentation we don't need to run the whole test suite so in future please could you add `[skip actions] [skip cirrus]` to the end of your commit message as per https://docs.scipy.org/doc/scipy/dev/contributor/continuous_integration.html#skipping

2023-08-28 05:03 UTC, mdhaber requested changes
In the future, please submit unrelated changes in separate PRs. Including them together can only slow down review (e.g. the different changes may require different reviewers, so the whole PR is delayed until all reviewers have finished).

Please also include all imports explicitly and ensure that the output matches that produced by SciPy.

2023-08-28 05:03 UTC, mdhaber commented on scipy/fft/_fftlog.py
> +    0.539805138227967
The output needs to match that produced by SciPy.
```suggestion
    0.5454581477676637
```

2023-08-28 05:11 UTC, mdhaber commented on scipy/stats/_stats_py.py
> +    >>> weights = [1, 2, 3, 4]
```suggestion
   When the individual p-values carry different weights, consider Stouffer's
   method.

    >>> weights = [1, 2, 3, 4]
```

2023-08-28 05:14 UTC, mdhaber approved these changes
Will merge if CI passes.

2023-08-28 06:01 UTC, mdhaber commented on scipy/stats/_stats_py.py
> +   method.
```suggestion
    When the individual p-values carry different weights, consider Stouffer's
    method.
```

2023-08-28 07:41 UTC, merged