Fix Issue : #19063
scipy/scipy pull request #19127
Opened 2023-08-24 20:55 UTC by iamdipansh

Fixed typo in documentation 
link of typo
https://github.com/scipy/scipy/blob/881b9fe85eae39015693ea3c83d406c252eebcab/scipy/linalg/_basic.py#L1385C55-L1385C55 https://github.com/scipy/scipy/blob/881b9fe85eae39015693ea3c83d406c252eebcab/scipy/linalg/_basic.py#L1415C9-L1415C9

Reference issue
DOC: typo in scipy.linalg.pinv.html #19063

What does this implement/fix?
Fixed the typo in documentation

2023-08-24 20:57 UTC, j-bowhay requested changes
Thanks @iamdipansh, one comment.

Also since this is a doc only pr please add `[skip actions] [skip cirrus]` to save ci resources

2023-08-24 20:57 UTC, j-bowhay commented on scipy/linalg/_basic.py
> +    matrix inverse, ``A`` does not have to be square matrix and have linearly
Please revert the phrasing and just fix the typo

2023-08-25 06:03 UTC, j-bowhay commented on scipy/linalg/_basic.py
>      independant columns/rows.
```suggestion
    matrix inverse, ``A`` does not have to be a square matrix or have
    linearly independent columns/rows.
```

2023-08-25 06:05 UTC, j-bowhay approved these changes
Thanks @iamdipansh, I made a small tweak but this looks good to go. Congratulations on your first contribution.

2023-08-25 06:06 UTC, merged

2023-08-25 07:20 UTC, iamdipansh commented
Thanks @j-bowhay