Resolve #18881: Enhance lobpcg documentation with updated examples
scipy/scipy pull request #19146
Opened 2023-08-27 18:14 UTC by anudeepadi

- Added examples utilizing `aslinearoperator` and `LinearOperator`

@lobpcg 

#### Reference issue

#### What does this implement/fix?

#### Additional information

2023-08-27 18:25 UTC, lobpcg commented
@anudeepadi Reference https://github.com/scipy/scipy/issues/18881

2023-08-27 18:33 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    does not need to be explicitly constructed.
The matrix does need to be constructed to use `aslinearoperator`

2023-08-27 18:33 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    >>> def matvec(X):
remove. you already have the same function below called matmat

2023-08-27 18:33 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    >>>     return vals[:, np.newaxis] * X
That is probably not a proper format for docstrings and will result in an error, I guess. Look at other examples of multi-line and edit yours accordingly

2023-08-27 18:33 UTC, lobpcg commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    >>> A = LinearOperator((n, n), matvec=matmat, dtype='float64')
You must specify both `matvec=matmat, matmat=matmat` for `lobpcg` to take advantage of `matmat`

2023-08-29 19:00 UTC, lobpcg commented
Look at the docsting text above your insert for duplicates

2023-08-29 20:38 UTC, j-bowhay requested changes

2023-08-29 20:38 UTC, j-bowhay commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    This converts the sparse matrix `A` to a LinearOperator. The matrix `A` needs
```suggestion
    This converts the sparse matrix `A` to a `LinearOperator`. The matrix `A` needs 
```

2023-09-06 07:34 UTC, j-bowhay requested changes
@lobpcg did you have any further feedback?

2023-09-06 07:34 UTC, j-bowhay commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    >>> def matmat(X):
Missing whitespace
```suggestion
    Define matmat for matrix-matrix multiplication (important for LOBPCG performance)
    
    >>> def matmat(X):
```

2023-09-06 07:34 UTC, j-bowhay commented on scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py
> +    to be constructed to use the `aslinearoperator`.
Potentially redundant information
```suggestion
```

2023-09-06 19:17 UTC, lobpcg commented
@anudeepadi could you please add me as a collaborator so that I can also edit the file? I have a few comments, but it would be easier for me to just edit rather than explain.

2023-09-08 01:32 UTC, lobpcg commented
I have better incorporated the new examples into the previous text. LGTM

2023-09-08 07:13 UTC, j-bowhay approved these changes
Thanks both

2023-09-08 07:13 UTC, merged