DOC: Added example for tf2zpk function
scipy/scipy pull request #19179
Opened 2023-09-04 12:38 UTC by tamri

#### Reference issue
DOC: Add "Examples" to docstrings #7168

#### What does this implement/fix?
Added example for tf2zpk function. 
The code can be found in scipy/signal/_filter_design.py 

#### Additional information
Once my work accepted, I will add more examples for next PR.

2023-09-04 17:03 UTC, j-bowhay requested changes
Thanks @tamri, some suggestions

2023-09-04 17:03 UTC, j-bowhay commented on scipy/signal/_filter_design.py
> +        H(s) = 3s^2 / (s^2 + 5s + 13)
for correct rendering
```suggestion
    .. math::
    
        H(s) = \frac{3s^2}{s^2 + 5s + 13}
```

2023-09-04 17:03 UTC, j-bowhay commented on scipy/signal/_filter_design.py
> +    >>> from scipy.signal._filter_design import tf2zpk
The correct public import is
```suggestion
    >>> from scipy.signal import tf2zpk
```

2023-09-05 08:34 UTC, tamri commented on scipy/signal/_filter_design.py
> +    >>> from scipy.signal._filter_design import tf2zpk
Thank you for the feedback

2023-09-05 14:00 UTC, j-bowhay approved these changes
Thanks @tamri, congratulations on your first contribution to SciPy, keep them coming!

2023-09-05 14:01 UTC, merged

2023-09-05 14:03 UTC, j-bowhay commented
> Once my work accepted, I will add more examples for next PR. [skip actions] [skip cirrus]

Ps. Relating to this, please try to keep all the examples in a PR related to similar functions as this makes it easier to review