DEP scipy#18279 improve message for deprecated private API
scipy/scipy pull request #19226
Opened 2023-09-12 06:40 UTC by hoangle96

#### Reference issue

Solving a part of issue gh-18279

#### What does this implement/fix?

Finish #18279 for `sparse`

#### Additional information

2023-09-12 06:59 UTC, j-bowhay requested changes
Thanks @hoangle96 some minor changes required

2023-09-12 06:59 UTC, j-bowhay commented on scipy/_lib/tests/test_public_api.py
> +
```suggestion
```

2023-09-12 06:59 UTC, j-bowhay commented on scipy/sparse/bsr.py
> +                                   attribute=name)
New line at end of file needed

2023-09-12 06:59 UTC, j-bowhay commented on scipy/sparse/data.py
> +                                   attribute=name)
new line at end of file

2023-09-12 06:59 UTC, j-bowhay commented on scipy/sparse/linalg/eigen.py
> +    'eigsh', 'lobpcg', 'svds', 'arpack', 'test'
can you revert the change here please

2023-09-12 06:59 UTC, j-bowhay commented on scipy/sparse/linalg/isolve.py
> +    'test'
and here

2023-09-12 06:59 UTC, j-bowhay commented on scipy/sparse/linalg/matfuncs.py
> +    'ProductOperator'
and here

2023-09-12 06:59 UTC, j-bowhay commented on scipy/sparse/linalg/eigen.py
> +
one too many lines at end of file!

2023-09-13 05:56 UTC, hoangle96 reviewed
Making sure changes are compliant with PEP 8. Removing unnecessary changes

2023-09-13 10:37 UTC, j-bowhay requested changes
Thanks @hoangle96 still a few changes required

2023-09-13 10:37 UTC, j-bowhay commented on scipy/sparse/bsr.py
> +                                   attribute=name)
Still missing an new line

2023-09-13 10:37 UTC, j-bowhay commented on scipy/sparse/linalg/isolve.py
> +    'test'
again please revert this change it makes it harder to tell if anything has been removed

2023-09-14 04:21 UTC, hoangle96 commented
@j-bowhay I have updated the changes to be PEP8 complaint and revert the unnecessary changes.

2023-09-26 18:30 UTC, j-bowhay approved these changes
Thanks @hoangle96! Congratulations on your first contribution to SciPy, if you are interested in doing one of the other modules from the issue that would be greatly appreciated!

2023-09-26 18:31 UTC, merged