DOC: Added examples for correlation, num_obs_dm, num_obs_y functions.
scipy/scipy pull request #19256
Opened 2023-09-18 07:25 UTC by tamri

Reference issue
DOC: Add "Examples" to docstrings https://github.com/scipy/scipy/issues/7168

What does this implement/fix?
Added examples for correlation, num_obs_dm, num_obs_y functions.

Additional information
[skip actions] [skip cirrus]

2023-09-18 07:38 UTC, ilayn commented
Hi @tamri Thanks a lot for your efforts to help us! Could you please add the `[skip actions] [skip cirrus]` identifiers to your commit messages? 

Unfortunately GitHub doesn't read the issue description and needs these identifiers at every commit to skip tests.

2023-09-18 19:17 UTC, dschmitz89 requested changes
Thanks for the PR @tamri . 

The linting issues are currently not caught by the linter infrastructure.

I do not really understand the purpose of `num_obs_dm` and `num_obs_y`, so no comment on those examples itself from my side. For the correlation distance, I find the examples helpful.

2023-09-18 19:17 UTC, dschmitz89 commented on scipy/spatial/distance.py
> +    >>> correlation([1, 0, 1],[1, 1, 0])
```suggestion
    >>> correlation([1, 0, 1], [1, 1, 0])
```

2023-09-18 19:17 UTC, dschmitz89 commented on scipy/spatial/distance.py
> +    >>> correlation([1, 0, 1],[1, 1, 0], [0.9, 0.1, 0.1])
```suggestion
    >>> correlation([1, 0, 1], [1, 1, 0], w=[0.9, 0.1, 0.1])
```

2023-09-19 00:29 UTC, tamri commented
@dschmitz89 thx for checking the linting, will be careful about that next time.
Are you familiar with the linux_aarch64_test? It fails because "Monthly free compute limit exceeded!"

2023-09-19 05:12 UTC, dschmitz89 commented
> @dschmitz89 thx for checking the linting, will be careful about that next time.
> Are you familiar with the linux_aarch64_test? It fails because "Monthly free compute limit exceeded!"
> 

That is unrelated to this PR. CI providers only grant some amount of free computation resources per month. For Cirrus, we run out of them regularly unfortunately now.

2023-09-21 05:31 UTC, tamri commented
Anything else needed for this PR to be merged?

2023-09-21 06:16 UTC, dschmitz89 reviewed
My comments were addressed but this still needs a look from a maintainer.

2023-09-21 10:09 UTC, j-bowhay commented
The examples seem fine however I wondering if they could be adapted to provide more insight beyond just plugging in inputs? If the answer is the answer is no, not easily, that is also fine as this is still an improvement on no example

2023-09-21 19:32 UTC, dschmitz89 commented
There are actually two other (rather stale) PRs looking into the same functions: #18431 and #17785 . This one looks closest to me. When it is merged, the other PRs should be closed. 

Wondering if we should ask people to indicate in #7168 if they are working on a specific function to avoid duplicate work. That's how scikit learn  folks do it on a similar meta issue also: https://github.com/scikit-learn/scikit-learn/issues/27090 . However, I did not see duplicate work happening so often in scipy.

2023-09-22 01:11 UTC, tamri commented
@j-bowhay If you could indicate a golden sample that shows what you mean by more insight I can try to follow it.
During my last PR, I tried to be thorough but ended up adding unnecessary redundancy.
Anyway, I'll wait until you confirm how you would like to move forward.

2023-09-28 20:54 UTC, j-bowhay approved these changes
Sorry this slipped under the radar. On second thought, these are quite simple functions so these examples are probably fine and can always be added to in the future if needed. For a more important function, a good narrative to the example is nice eg: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sobol_indices.html#scipy.stats.sobol_indices

2023-09-28 21:00 UTC, j-bowhay commented on scipy/spatial/distance.py
> +    >>> correlation([1, 0, 1], [1, 1, 0], centered = False)
```suggestion
    >>> correlation([1, 0, 1], [1, 1, 0], centered=False)
```

2023-09-28 21:00 UTC, j-bowhay commented on scipy/spatial/distance.py
> +    >>> d = [[0, 100, 200],[100, 0, 150],[200, 150, 0]]
```suggestion
    >>> d = [[0, 100, 200], [100, 0, 150], [200, 150, 0]]
```

2023-09-28 21:01 UTC, merged