DEP: special: improve deprecation of private modules named without underscore prefix
scipy/scipy pull request #19469
Opened 2023-11-03 12:54 UTC by j-bowhay

#### Reference issue

towards https://github.com/scipy/scipy/issues/18279
#### What does this implement/fix?

Currently, some deprecation warnings for private modules named without underscore prefixes are misleading. For example:
Before this pr:
```
In [1]: from scipy.special.orthogonal import arange
<ipython-input-1-18b058905c34>:1: DeprecationWarning: Please use `arange` from the `scipy.special` namespace, the `scipy.special.orthogonal` namespace is deprecated.
  from scipy.special.orthogonal import arange
```
After:
```
In [4]: from scipy.special.orthogonal import arange
<ipython-input-4-18b058905c34>:1: DeprecationWarning: `scipy.special.orthogonal.arange` is deprecated along with the `scipy.special.orthogonal` namespace. `scipy.special.orthogonal.arange` will be removed in SciPy 1.13.0, and the `scipy.special.orthogonal` namespace will be removed in SciPy 2.0.0.
  from scipy.special.orthogonal import arange
```
#### Additional information

2023-11-06 19:41 UTC, lucascolley commented on scipy/special/orthogonal.py
> +                            attribute=name)
mind the no-new-line here

2023-11-06 19:41 UTC, lucascolley commented on scipy/special/sf_error.py
> +                            attribute=name)
no new line here either

2023-11-06 19:41 UTC, lucascolley commented on scipy/special/basic.py
> +                            attribute=name)
Just a style nit but I think you're fine to indent like this and stay within the 88 char limit. As far as I have looked all of the other uses of `_sub_module_deprecation` have indented like this.
```suggestion
    return _sub_module_deprecation(sub_package="special", module="basic",
                                   private_modules=["_basic", "_ufuncs"], all=__all__,
                                   attribute=name)
```

2023-11-08 11:29 UTC, h-vetinari reviewed
Approved module the style nits that were pointed out (i.e. once those are fixed, consider it good to go). Thanks!

2023-11-08 13:43 UTC, j-bowhay commented on scipy/special/orthogonal.py
> +                            attribute=name)
```suggestion
                            attribute=name)

```

2023-11-08 13:43 UTC, j-bowhay commented on scipy/special/sf_error.py
> +                            attribute=name)
```suggestion
                            attribute=name)

```

2023-11-08 13:46 UTC, lucascolley requested changes
The indentation change can be applied to all of the files, not just the one fixed above. Otherwise LGTM

2023-11-08 13:47 UTC, lucascolley approved these changes

2023-11-08 13:59 UTC, merged