DOC: 1.12.0 release notes
scipy/scipy pull request #19628
Opened 2023-12-03 22:56 UTC by tylerjereddy

* draft release notes for SciPy `1.12.0`, including transcription of the wiki version of the release notes

TODO:

- [x] manually go through the `95` merged PRs with `1.12.0` milestone and `enchancement` label, to fill in several parts of the release notes that were not filled in on the [wiki](https://github.com/scipy/scipy/wiki/*Release-Note-Entries-for-SciPy-1.12.0-(asterisk-makes-this-appear-at-the-top)) (this is normal--`stats` folks usually do a good job of filling in the wiki though)
- [x] fix formatting/build errors in the new release notes; nested bullet lists, indentation, the usual...
- [ ] `.mailmap` fixups to get a cleaner duplication/alias-free author list
- [x] deal with the `20` open PRs with `1.12.0` milestone, update the release notes again if/as needed (many of these will probably be milestone bumps on stagnant or difficult PRs)
- [ ] (after merging this): target the wheel builds back to released NumPy (not `2.x`), a faster-than-normal `1.13.0` is planned for NumPy `2.0` support a few months after this `1.12.0` release
- [ ] decide how much I/we care about having the best possible NumPy `main` support before we branch--I've put substantial effort into dealing with gh-19605, but strictly speaking, I don't think we need to do that, and things could still shift a bit anyway
- [x] decide on which new features/improvements qualify as the release highlights
- [x] add some sensible wording for "in progress, but cool/please test me" type features like array API support in some modules
- [x] progressively turn the CI back on here

[skip cirrus] [skip circle] [skip ci]

2023-12-04 00:56 UTC, lucascolley commented
Some mailmap fixups at tylerjereddy/scipy#75

2023-12-04 01:22 UTC, mdhaber commented
@tylerjereddy I hadn't filled in the wiki yet. Can I still do that or do you want changes to be made here?

2023-12-04 02:13 UTC, tylerjereddy commented
> I hadn't taken a pass on the release notes for a few months. Can I still do that or do you want changes to be made here?

You can edit the wiki if you want, I'll check it again a few times anyway

2023-12-04 19:20 UTC, ev-br commented
For scipy.interpolate:

- New class `NdBSpline` represents tensor-product splines in N dimensions. This class only known how to evaluate a tensor product given coefficients and knot vectors. This way it generalizes BSpline for 1D data to N-D, and parallels NdPPoly (which represents N-D tensor product polynomials). Evaluations exploit the localized nature of b-splines.

- `NeastNDInterpolator.__call__` accepts `**query_options`, which are passed through to the `KDTree.query` call to find nearest neighbors. This allows, for instance, to limit the neighbor search distance and parallelize the query using the `workers`  keyword. 

- `BarycentricInterpolator` now allows computing the derivatives.

2023-12-04 22:28 UTC, j-bowhay commented
Probably worth mentioning #18279 in the deprecation section. Error messages have been made clearer for things that don't exist in the public namespace and warnings sharpened for private attributes that are not supposed to be imported at all

2023-12-05 06:45 UTC, mdhaber commented on doc/source/release/1.12.0-notes.rst
> +  `scipy.stats.lomax`, and `scipy.stats.pareto`.
```suggestion
  `scipy.stats.lomax`, and `scipy.stats.pareto`.
- The following functions now support parameters ``axis``, ``nan_policy``, and ``keep_dims``: `scipy.stats.entropy`, `scipy.stats.differential_entropy`, `scipy.stats.variation`, `scipy.stats.ansari`, `scipy.stats.bartlett`, `scipy.stats.levene`, `scipy.stats.fligner`, `scipy.stats.cirmean, `scipy.stats.circvar`, `scipy.stats.circstd`, `scipy.stats.tmean`, `scipy.stats.tvar`, `scipy.stats.tstd`, `scipy.stats.tmin`, `scipy.stats.tmax`, and `scipy.stats.tsem`.
- The ``logpdf`` and ``fit`` methods of `scipy.stats.skewnorm` have been improved.
- The beta negative binomial distribution is implemented as `scipy.stats.betanbinom`.
- The speed of `scipy.stats.invwishart` ``rvs`` and ``logpdf`` have been improved.
- A source of intermediate overflow in `scipy.stats.boxcox_normmax` with ``method='mle'`` has been eliminated, and the returned value of ``lmbda`` is constrained such that the transformed data will not overflow.
- `scipy.stats.nakagami.stats` is more accurate and reliable.
- A source of intermediate overflow in `scipy.norminvgauss.pdf` has been eliminated.
```

2023-12-05 06:45 UTC, mdhaber commented on doc/source/release/1.12.0-notes.rst
> +  `scipy.stats.fligner`
See combination of these in my other comment.
```suggestion
```

2023-12-06 01:50 UTC, lucascolley commented on doc/source/release/1.12.0-notes.rst
>  ============================
```suggestion
============================
- Experimental support added for the array API standard; PyTorch tensors,
  CuPy arrays and array API compatible array libraries are now accepted
  (GPU support is limited to functions with pure Python implementations).
  CPU arrays which can be converted to and from NumPy are supported
  module-wide and returned arrays will match the input type.
  This behaviour is enabled by setting the ``SCIPY_ARRAY_API`` environment
  variable before importing ``scipy``. This experimental support is still
  under development and likely to contain bugs - testing is very welcome.
```

2023-12-06 07:23 UTC, mdhaber commented on doc/source/release/1.12.0-notes.rst
>  `scipy.interpolate` improvements
```suggestion
  development and likely to contain bugs - testing is very welcome.

`scipy.integrate` improvements
==============================
- Added `scipy.integrate.cumulative_simpson` for cumulative quadrature
  from data using Simpson's 1/3 rule.


`scipy.interpolate` improvements
```

2023-12-06 12:08 UTC, lucascolley commented
Feel free to modify the `fft` and `cluster` array API parts to match what Matt has written for `special` if anything looks like an improvement.

2023-12-07 00:21 UTC, lucascolley commented on doc/source/release/1.12.0-notes.rst
> +  `scipy.special.i0e`, `scipy.special.i1, `scipy.special.i1e`,
```suggestion
  `scipy.special.erf`, `scipy.special.erfc`, `scipy.special.i0`, 
  `scipy.special.i0e`, `scipy.special.i1`, `scipy.special.i1e`, 
```

2023-12-07 03:18 UTC, tylerjereddy commented
Obviously I'm a bit behind schedule, but I don't think we're too bad off, and folks have been helping a lot. So yeah, probably a little bit of a branching delay because end of year stuff made me a little busier, but not too worried I don't think.

2023-12-07 05:29 UTC, dschmitz89 commented on doc/source/release/1.12.0-notes.rst
> +  `scipy.special.gammaln`, `scipy.special.gammainc`, `scipy.special.gammaincc`,
```suggestion
  `scipy.special.gammaln`, `scipy.special.gammainc`, `scipy.special.gammaincc`,
```

2023-12-07 05:42 UTC, dschmitz89 commented on doc/source/release/1.12.0-notes.rst
> +  default) respectively.
```suggestion
  default) respectively.
-  Added `scipy.special.betaincc` for computation of the complementary incomplete Beta function and `scipy.special.betainccinv` for computation of its inverse.
- Improved precision of `scipy.special.betainc` and `scipy.special.betaincinv`
```

PR: https://github.com/scipy/scipy/pull/17697

2023-12-07 15:32 UTC, DietBru commented on doc/source/release/1.12.0-notes.rst
> -
I think, due to its considerable length alone 😁, PR #17408 deserves a mention.  A possible wording could look like this:

```ReST
- The class ``ShortTimeFFT`` provides a new more versatile implementation of the
  short-time Fourier transform (STFT), its inverse (ISTFT) as well as the (cross-)
  spectrogram. It utilizes an improved algorithm for calculating the ISTFT based on
  dual windows and provides more fine-grained control of the parametrization especially
  in regard to scaling and phase-shift. Functionality was implemented to ease
  working with signal and STFT chunks. A section has been added to the "SciPy User Guide"
  providing algorithmic details. The functions ``stft``, ``istft`` and ``spectrogram``
  have been marked as legacy.
```

2023-12-07 17:35 UTC, lucascolley commented on .mailmap
> +Lucas Colley <lucas.colley8@gmail.com> lucascolley <lucas.colley8@gmail.com>
```suggestion
Lucas Colley <lucas.colley8@gmail.com> lucascolley <51488791+lucascolley@users.noreply.github.com>
```

2023-12-08 23:51 UTC, tylerjereddy commented
I checked off the manual comb-through of the enhancement PRs and re-checking of the wiki. I believe there have been some merges since I started doing my pass, but anyway it took me a few days because of various interruptions.

I'll think a bit more about the highlights next, then fixing up the formatting/doc build.

2023-12-10 02:13 UTC, tylerjereddy commented
Doc build is passing locally--let's see if CI agrees (minus cirrus for now).

2023-12-10 07:28 UTC, dschmitz89 requested changes
A few minor things, mostly typos.

2023-12-10 07:28 UTC, dschmitz89 commented on doc/source/release/1.12.0-notes.rst
> +- The ``fit`` methods of `scipy.stats.halcauchy`, `scipy.stats.halflogistic`, and
```suggestion
- The ``fit`` methods of `scipy.stats.halfcauchy`, `scipy.stats.halflogistic`, and
```

2023-12-10 07:28 UTC, dschmitz89 commented on doc/source/release/1.12.0-notes.rst
> +- `scipy.stats.beta` ``entropy`` accuracy has been improved for extreme values of
```suggestion
- ``scipy.stats.beta.entropy`` accuracy has been improved for extreme values of
```

2023-12-10 07:28 UTC, dschmitz89 commented on doc/source/release/1.12.0-notes.rst
> +- ``gausshyper`` ``cdf`` and ``rvs`` methods have improved performance.
```suggestion
```

The PR https://github.com/scipy/scipy/pull/18799 this refers to  is difficult to decipher: in the end it was basically a simplifcation of a formula with no notable impact for users.

2023-12-10 17:52 UTC, tylerjereddy commented
I still see blemishes in the rendered version of the release notes for `1.12.0`, but CI is green (including ARM architectures and doc build) and I'm behind schedule on this release cycle so I'll proceed with (squash) merge and the release notes can continue to be improved during the release process (this happens pretty much every time to be honest).

2023-12-10 17:53 UTC, merged