"ENH: Improve least_squares with Default diag=None for LM Method"
scipy/scipy pull request #19700
Opened 2023-12-17 14:19 UTC by Roshan-Velpula

#### Reference issue
This PR addresses the issue described in #19459 - "BUG: optimize.least_squares giving poor result compared to optimize.leastsq and optimize.curve_fit".

#### What does this implement/fix?
This enhancement modifies the behavior of optimize.least_squares when used with the method='lm' (Levenberg-Marquardt algorithm). Previously, unless x_scale was set to 'jac', the default behavior was to use diag=1.0 for scaling, leading to suboptimal fits in certain scenarios. This change proposes to set the default value of x_scale='jac' when method=='lm', aligning the behavior more closely with that of optimize.leastsq and optimize.curve_fit. This results in improved optimization performance and robustness.
Summary of Changes
Set default x_scale='jac' for least_squares with method='lm'.

#### Additional information

2023-12-17 14:36 UTC, j-bowhay commented
Can you add a unit test demonstrating that the change performs as intended?

2023-12-17 21:17 UTC, Roshan-Velpula commented
> Can you add a unit test demonstrating that the change performs as intended?

Updated the unit test and committed the change. Please review the PR and let me know.

2024-01-06 22:09 UTC, dschmitz89 requested changes
test

2024-01-06 22:09 UTC, dschmitz89 commented on scipy/optimize/_lsq/least_squares.py
> +    if method == 'lm' and x_scale == None:
```suggestion
    if method == 'lm' and x_scale is None:
```

2024-01-06 23:11 UTC, Roshan-Velpula commented
> I cannot find how to remove my review here unfortunately. Will take a closer look in some time.

Thanks for the email and suggested changes, I did them accordingly and committed them. Please let me know if you need any further updates from me :)

2024-01-06 23:13 UTC, lucascolley commented
Hi @Roshan-DSBA , if you do the following the doc build check should work:

```
git fetch --all
git merge upstream/main
git push
```

2024-01-07 18:05 UTC, Roshan-Velpula commented
> Hi @Roshan-Velpula , if you do the following the doc build check should work:
> 
> ```
> git fetch --all
> git merge upstream/main
> git push
> ```

Hi, Thank you for the message! Pushed the changes and doc build check worked. :)

2024-02-09 18:19 UTC, dschmitz89 reviewed
The change itself looks good to me but I do not understand how the test demonstrates its correctness. Maybe I am misunderstanding but it looks like `x_scale=1` does not change the Jacobian at all. What about choosing `xscale >>  1`?

2024-11-08 18:55 UTC, CarrascoCesar commented
Hello @lucascolley is there any interest in updating this PR?  I am interested in revisiting it since it would solve an important issue in my view.

2024-11-08 19:01 UTC, lucascolley commented
Hey @CarrascoCesar ! This isn't my area of expertise, but perhaps you could respond to @dschmitz89's comment above about the purpose of the test?

2024-11-08 21:20 UTC, CarrascoCesar commented
Hello @dschmitz89 would there be interest in revisiting the PR and creating a simpler test that checks for improved behavior when x_scale is not defined and least_squares defaults to parameter scaling?

2024-11-10 06:05 UTC, dschmitz89 commented
@CarrascoCesar : sorry, looking again I think I misunserstood your test. My new interpretation is: you are comparing the new against the old default and the new default has to result in better convergence indicated by a smaller number of function evaluations. Is that correct? In that sense, the test is actually very helpful.

Reading again the complete PR description, it seems that the overall goal is to get the same behaviour as `leastsq` if `least_squares` uses Levenberg Marquardt. Currently this is not the case due to different default arguments. WIth this change, we should get the same results. How about we update the test so that we show that we get the same results for `least_squares(method=lm)` and `leastsq`? This would make the purpose more explicit.

2024-11-10 17:24 UTC, CarrascoCesar commented
Hello @dschmitz89, I agree, comparing least_square to leastsq in the test addresses the original issue more directly. I'll work on it to include your recommendation and see if I can come up with a simpler test problem.

2024-11-14 17:04 UTC, CarrascoCesar commented
Hello @lucascolley, this will be my first time modifying somebody else's PR.  What is the process to checkout the commit for me to make changes and then post?

2024-11-14 17:09 UTC, lucascolley commented
> Hello @lucascolley, this will be my first time modifying somebody else's PR. What is the process to checkout the commit for me to make changes and then post?

hey @CarrascoCesar , personally, I would use GitHub's CLI tool `gh` and do the following:

1. Make sure you are in the directory of your clone of this repo
2. `gh checkout 19700` (to checkout this PR)
3. `git checkout -b LM-changes` (to make a new branch matching this PR)
4. Make your changes and commit as usual
5. Open a new PR from your branch

If you don't want to use `gh`, you can do the same by adding @Roshan-Velpula's fork as a remote.

If @Roshan-Velpula were active and collaborating, you could instead make a PR to their fork, and the changes could stay in this PR. But no harm in just opening a new PR here!

2025-04-03 09:20 UTC, closed without merging

2025-04-03 09:20 UTC, andyfaff commented
Closed in favour of #22790