ENH: sparse: Add min-max 1d support and tests
scipy/scipy pull request #19743
Opened 2023-12-23 02:13 UTC by dschult

This PR adds 1d support in the `_minmax_mixin` class providing min and max functionality. It is implemented in coo_array and is independent of the [PR for dok_array #19715 ](https://github.com/scipy/scipy/pull/19715).

This is much smaller than the coo-1d and dok-1d changes. Indeed, most of the new lines are in the tests.

2023-12-26 02:25 UTC, perimosocordiae approved these changes
Looks great, thanks Dan!

2023-12-26 02:25 UTC, perimosocordiae commented on scipy/sparse/tests/test_minmax1d.py
> +from scipy.sparse import coo_array  # , dok_array
Remove commented code here

2023-12-26 02:25 UTC, perimosocordiae commented on scipy/sparse/tests/test_minmax1d.py
> +formats_for_minmax = [coo_array]  # , dok_array]
and here

2023-12-26 15:59 UTC, j-bowhay requested changes
Can we refactor the `pytest.raises` to use the context manager version and add `match=` statements too

2023-12-27 04:18 UTC, dschult commented
I have changed the comment lines and modernized the tests to use the context manager instead of the style from `test_base.py`. I am working on modernizing the tests in the dok-1d branch #19715 too. But this PR should be ready.
Thanks!

2023-12-27 09:41 UTC, j-bowhay approved these changes
Thanks @dschult

2023-12-28 19:12 UTC, tylerjereddy approved these changes
Two core dev approvals, CI is passing, no old tests modified (just new ones added), seems like this should go in now.

2023-12-28 19:12 UTC, merged