DOC: Docstring and examples for Rotation.concatenate
scipy/scipy pull request #19775
Opened 2023-12-28 20:26 UTC by scottshambaugh

#### Reference issue
Closes https://github.com/scipy/scipy/issues/19774

#### What does this implement/fix?

#### Additional information
Suggested edits to make this more clear welcome!

2023-12-28 20:35 UTC, MichaelBonnet reviewed
this definitely fulfills the requests in my issue #19774. Thanks!

2023-12-28 22:40 UTC, j-bowhay requested changes
Thanks @scottshambaugh for tackling this so quickly! Some minor nits

2023-12-28 22:40 UTC, j-bowhay commented on scipy/spatial/transform/_rotation.pyx
> +        rotations, and need to pack them into a single object to do so.
```suggestion
        This is useful if you want to, for example, take the mean of a set of
        rotations and need to pack them into a single object to do so.
```

2023-12-29 09:13 UTC, j-bowhay approved these changes
Thanks for the quick work @scottshambaugh

2023-12-29 09:13 UTC, merged