DOC: scipy.fft.fht - documentation issue
scipy/scipy pull request #19807
Opened 2024-01-04 08:27 UTC by willtryagain

[docs only]

### Reference issue
Closes https://github.com/scipy/scipy/issues/19573

2024-01-04 08:33 UTC, willtryagain commented
apologies, I forgot to add [docs only] in the commit message.

2024-01-04 09:22 UTC, j-bowhay commented
@ntessore would you be interested in reviewing?

2024-01-04 10:58 UTC, ntessore commented
Sure, no problem.

@willtryagain, I don't think the text I wrote in the other issue is a good fit for the docstring. I think a short acknowledgement of the different definition might work better:

    where :math:`J_\mu` is the Bessel function of order :math:`\mu`.  The index
    :math:`\mu` may be any real number, positive or negative.  Note that the
    numerical Hankel transform uses an integrand of :math:`k dr`, while the
    mathematical Hankel transform is commonly defined using :math:`r dr`.

2024-01-05 11:37 UTC, ntessore requested changes
Thanks @willtryagain, I think this reads better for a compact reference. Could you also add a similar sentence to `ifht`?

2024-01-05 12:36 UTC, ntessore requested changes
Sorry about this further request! I could not find a docs preview anywhere on here. After checking locally, I realised that the spacing in the math didn't look right.

2024-01-05 12:36 UTC, ntessore commented on scipy/fft/_fftlog.py
> +    mathematical Hankel transform is commonly defined using :math:`r dr`.
```suggestion
    numerical Hankel transform uses an integrand of :math:`k \, dr`, while the
    mathematical Hankel transform is commonly defined using :math:`r \, dr`.
```

2024-01-05 12:36 UTC, ntessore commented on scipy/fft/_fftlog.py
> +    mathematical inverse Hankel transform is commonly defined using :math:`k dk`.
```suggestion
    numerical inverse Hankel transform uses an integrand of :math:`r \, dk`, while the
    mathematical inverse Hankel transform is commonly defined using :math:`k \, dk`.
```

2024-01-05 12:56 UTC, lucascolley commented
For future reference, the docs preview is available under the CI job "Check the rendered docs here!"

2024-01-05 14:41 UTC, ntessore approved these changes

2024-01-05 15:18 UTC, lucascolley approved these changes
thanks for the review @ntessore ! 

@willtryagain would you mind editing the title of the PR to something slightly more specific, perhaps "DOC: fft: add note about FHT formulas"? 'Documentation issue' is a little vague. This will make it slightly quicker for whoever squash-merges the PR.

Also, in the future, if you could write commit messages roughly following [the guidance in our docs](http://scipy.github.io/devdocs/dev/contributor/development_workflow.html#writing-the-commit-message), that would be great! This isn't necessary at all for complicated PRs with lots of commits, as they will be squash-merged and the title can be edited, but for simple PRs which might be ready to merge straight away this can help us :)

2024-01-05 15:43 UTC, willtryagain commented
thank you. your patience and guidance is much appreciated. I would follow the guidelines in my next PRs.

2024-01-05 21:32 UTC, j-bowhay approved these changes
Thanks everyone

2024-01-05 21:33 UTC, merged