BUG: optimize: fixed issue 19936
scipy/scipy pull request #19966
Opened 2024-01-25 19:44 UTC by dylduhamel

The fix involves a check within `approx_fprime` to determine if the input size is 1. If so, the output is reshaped to a 2-dimensional array (1x1 matrix). This is the general expectation for Jacobian computation.

2024-01-25 23:48 UTC, andyfaff commented
Before reviewing I think we need to have a deeper discussion. Let's do that in the issue.

2024-01-25 23:49 UTC, andyfaff requested changes
Hold off on merging until we have a discussion.

2024-01-26 09:02 UTC, danik292 reviewed
I think it's ok, but you need to wait for discussion 😉.

2024-01-27 01:10 UTC, andyfaff commented
Closing, because any changes would probably use a keyword argument, and probably the use of something along the lines of:
```python
if mykeywordargument:
    return np.atleast_2d(J)
```

2024-01-27 01:11 UTC, closed without merging