MAINT: sparse: change coo_matrix.indices to coo_matrix.coords
scipy/scipy pull request #20003
Opened 2024-02-01 20:17 UTC by dschult

To avoid confusion between formats, the recently implemented attribute name `indices` for COO format is changed in this PR to `coords`. 

This is a public attribute, but did not exist in 1.12, so merging this before 1.13 will not have any backward compatibility issues. 

The CSR/CSC formats already use the attribute name `indices`. So while the word `indices` is fine for COO, it may cause confusion between compressed and COO especially when working with both, converting etc. The name `coords` is arguably better anyway because it matches the "COO" of the COO format name. Both words seem to mean the same thing in English.

2024-02-02 06:42 UTC, perimosocordiae requested changes
Looks good, except for a few documentation issues where we want to use the full word instead of referring to the variable name.

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +                2. coords[i][:]  the axis-i coords of the data entries
The second usage on this line should still be indices.

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +        Whether the matrix has sorted coords and no duplicates
I'd prefer to spell out "coordinates" here.

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +        - Entries and coords sorted by row, then column.
Spell out here too

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +    >>> # Constructing a sparse array with duplicate coords
And here

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +    >>> # Duplicate coords are maintained until implicitly or explicitly summed
And here

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +                3. j[:]      the column coords of the matrix entries
Indices works fine here

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +        Whether the matrix has sorted coords and no duplicates
I'd keep indices here

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +        - Entries and coords sorted by row, then column.
Coordinates

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +    >>> # Constructing a matrix with duplicate coords
Coordinates

2024-02-02 06:42 UTC, perimosocordiae commented on scipy/sparse/_coo.py
> +    >>> # Duplicate coords are maintained until implicitly or explicitly summed
Coordinates

2024-02-03 18:00 UTC, dschult commented
Good catch -- I didn't think enough about docs and comments. But I suspect that its better that you make those calls anyway. I've made those changes.

2024-02-05 19:34 UTC, merged