MAINT: sparse: Un-deprecate getnnz()
scipy/scipy pull request #20033
Opened 2024-02-05 20:11 UTC by perimosocordiae

We deprecated several methods on sparse array classes in gh-18507, but this PR reverts the deprecation notice for `getnnz()`. This is because we don't currently have a replacement for the `axis=` keyword argument usage, and we don't want to leave users to implement the logic themselves.

When/if we add a better method for finding the number of stored entries beyond a simple scalar count, we can re-deprecate this.

2024-02-05 20:38 UTC, j-bowhay requested changes
Think there is an associated test that also needs removing

2024-02-07 23:26 UTC, tylerjereddy reviewed
Sounds good to me, the small patch below the fold allows the full suite to pass for me locally.

<details>

```diff
--- a/scipy/sparse/tests/test_deprecations.py
+++ b/scipy/sparse/tests/test_deprecations.py
@@ -21,9 +21,6 @@ def test_array_api_deprecations():
     with pytest.deprecated_call(match=msg):
         X.getmaxprint()
 
-    with pytest.deprecated_call(match=msg):
-        X.getnnz()
-
     with pytest.deprecated_call(match=msg):
         X.getH()
```
</details>

2024-02-08 04:53 UTC, perimosocordiae commented
Thanks @j-bowhay and @tylerjereddy, I updated the deprecation test.

2024-02-08 17:36 UTC, merged

2024-02-08 17:37 UTC, tylerjereddy commented
I squash merged it for backporting, thanks.

The doc CI failure is not related, I can reproduce on `main` locally.