BUG: Incorrect variable assignment in optimize._trust_region_exact
scipy/scipy pull request #20272
Opened 2024-03-18 12:46 UTC by mart-mihkel

#### Reference issue
Fixes gh-20244

#### What does this fix?
Result of cholesky factorization in disregarded in `IterativeSubproblem.solve()`.
These changes use the result on successful factorization.

2024-03-23 14:24 UTC, j-bowhay requested changes

2024-03-23 14:24 UTC, j-bowhay commented on scipy/optimize/tests/test_trustregion_exact.py
> +    def test_for_edge_case(self):
```suggestion
    def test_gh20244(self):
```

2024-03-23 14:24 UTC, j-bowhay commented on scipy/optimize/tests/test_trustregion_exact.py
> +        assert_array_almost_equal(p, [-0.77472957,  0.63229272])
```suggestion
        assert_assert_allclose(p, [-0.77472957,  0.63229272])
```

2025-02-07 13:33 UTC, melissawm commented
Hi @mart-mihkel - did you mean to close this?

2025-02-07 13:41 UTC, mart-mihkel commented
> Hi @mart-mihkel - did you mean to close this?

Oops, I was deleting some old things and completely forgot that this was still open, sorry that was an accident.

2025-02-07 14:16 UTC, melissawm commented
No worries, feel free to reopen if you are still interested. Cheers!

2026-03-13 23:14 UTC, j-bowhay approved these changes
Will merge if CI come back green, sorry for the delay......

2026-03-14 07:56 UTC, merged