MAINT: sparse: deprecate conjtransp() method for dok_array/matrix classes
scipy/scipy pull request #20283
Opened 2024-03-18 23:57 UTC by dschult

`A.conjtransp()` returns the conjugate transpose. So does `A.T.conj()`.
But `conjtransp` only exists for sparse DOK format. And it is not tested, is unused anywhere in Scipy, and searching all Github repositories for "language:python '.conjtransp('" reveals one use of this method in all of github. Most people I've talked to about this didn't know the method existed.

I propose that we deprecate `conjtransp` from the DOK classes. The proposed message says:
```
        .. deprecated:: 1.13.0

            `conjtransp` is deprecated and will be removed in v1.15.0.
            Use `.T.conj()` instead.
``` 
But the versions can be changed easily if this can't get into v1.13.

2024-03-19 22:02 UTC, j-bowhay requested changes
1.13 has branched so this will be for 1.14. Not a policy as far as I am aware of but all recent deprecations have used just the standard `DeprecationWarning` but I haven't looked into it enough to have a strong opinion

2024-03-20 01:52 UTC, dschult commented
Thanks!!  I prefer `DeprecationWarning` myself (it seems a mixed treatment in Scipy).
And I bumped the version numbers. I was hoping it would be easy to backport, but I totally understand.

Changes made. Thanks!

2024-03-21 12:49 UTC, perimosocordiae approved these changes

2024-03-21 19:55 UTC, j-bowhay approved these changes
Thanks @dschult

2024-03-21 19:55 UTC, merged