ENH: Allow Akima extrapolation
scipy/scipy pull request #20304
Opened 2024-03-21 13:39 UTC by psmd-iberutaru

#### Reference issue

Minor change. Closes #20247 

#### What does this implement/fix?

We add the extrapolation parameter to the construction; passing it to the parent classes. We keep False as the default as that is the behavior of the function before this change.

#### Additional information

2024-03-21 14:37 UTC, j-bowhay requested changes, later dismissed
Thanks @psmd-iberutaru can you add some test coverage for this new functionality

2024-03-22 05:17 UTC, psmd-iberutaru commented
Apologies @j-bowhay. Added the missing unit test(s). If there is a missing test, please let me know so I may add it.

2024-03-27 00:09 UTC, fancidev commented
I guess the doc of the argument “extrapolate” should read “If bool, …” instead of “If true, …” to be consistent with the doc of CubicHermiteSpline and PPoly. @psmd-iberutaru

2024-05-07 09:40 UTC, psmd-iberutaru commented
Just a follow up ping for review: @ev-br  @j-bowhay

2024-05-07 15:47 UTC, ev-br reviewed
LGTM modulo a couple of tolerances in tests. Generally, it's better to explicitly set e.g. `assert_allclose(x, y, atol=1e-15)` to signal equality in the floating point.

2024-05-07 15:47 UTC, ev-br commented on scipy/interpolate/tests/test_interpolate.py
> +        assert_allclose(ak_false(x_ext), ak_none(x_ext), equal_nan=True)
```suggestion
        assert_allclose(ak_false(x_ext), ak_none(x_ext), equal_nan=True, atol=1e-15)
```

2024-05-07 15:47 UTC, ev-br commented on scipy/interpolate/tests/test_interpolate.py
> +        assert_equal(ak_false(x_ext)[0:4], np.full(4, np.nan))
TIL that `assert_equal(np.nan, np.nan)` is True not False.

2024-05-07 15:47 UTC, ev-br commented on scipy/interpolate/tests/test_interpolate.py
> +        assert_allclose(ak_false(x_ext, extrapolate=True), ak_true(x_ext))
```suggestion
        assert_allclose(ak_false(x_ext, extrapolate=True), ak_true(x_ext), atol=1e-15)
```

2024-05-07 15:47 UTC, ev-br commented on scipy/interpolate/tests/test_interpolate.py
> +        assert_allclose(y_ext, ak_true(x_ext))
```suggestion
        assert_allclose(y_ext, ak_true(x_ext), atol=1e-15)
```

2024-05-07 16:42 UTC, ev-br commented
Jake @j-bowhay , your review is red on GH, is there something you'd like to see in this PR?

2024-05-08 06:50 UTC, merged

2024-05-08 06:52 UTC, ev-br commented
CI is green, review comments are addressed, the patch LGTM and is merged. Thank you @psmd-iberutaru, all. And congrats with your first scipy contribution! Keep them coming :-).