Draft: MAINT: Replace usage of np.prod
scipy/scipy pull request #20326
Opened 2024-03-25 10:02 UTC by eendebakpt

We replace usage of `np.prod` with either a direct call to `array.size` if possible or else use `math.prod`.
Direct usage of the size leads to cleaner code. Both alternatives are significantly faster. For example:
```    
x = [1, 2, 3]

%timeit math.prod(x)
50.7 ns ± 2.24 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

%timeit np.prod(x)
2.53 µs ± 36 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

@ev-br This is similar to #20325. These are all the easy/clear cases I could find.

2024-03-25 10:56 UTC, lucascolley commented on scipy/io/matlab/_mio5.py
> +import math
```suggestion

import math
```

2024-03-25 10:56 UTC, lucascolley commented on scipy/sparse/_data.py
> +import math
```suggestion

import math
```

2024-03-25 12:55 UTC, lucascolley requested changes

2024-03-25 16:10 UTC, lucascolley commented
remaining CI failure unrelated

2024-03-26 19:22 UTC, ev-br commented
LGTM.
Review comments seem to be all addressed, the CI failure is unrelated and has been fixed in main already. Let's land this. Thanks @eendebakpt , all.

2024-03-26 19:23 UTC, merged