DOC: updated preconditioner doc for iterative linear solver
scipy/scipy pull request #20517
Opened 2024-04-18 14:07 UTC by Afleloup

#### Reference issue

    Closes #5818
#### What does this implement/fix?

    The argument M in iterative linear solver
    'bicg', 'bicgstab', 'cg', 'cgs' is not standard notation
    in comparison to the literature. It is the inverse of the
    preconditioner usually denoted M^-1. Their should be a
    precondition on M for the preconditioned conjugate gradient.
    It is now explicited in the documentation and linked
    to relevant references.
#### Additional information

##### References

    .. [1] TREFETHEN, Lloyd N. et BAU, David. Numerical linear algebra. 
           Society for Industrial and Applied Mathematics, 2022.
    .. [2] SAAD, Yousef. Iterative methods for sparse linear systems. 
           Society for Industrial and Applied Mathematics, 2003.
    .. [3] "Conjugate Gradient Method, Wikipedia, 
           https://en.wikipedia.org/wiki/Conjugate_gradient_method
    .. [4] "Preconditioner", 
           Wikipedia, https://en.wikipedia.org/wiki/Preconditioner
    .. [5] KATRUTSA, Alexandr, BOTCHEV, Mike, OVCHINNIKOV, George, et al. 
           How to optimize preconditioners for the conjugate gradient method: 
           a stochastic approach. arXiv preprint arXiv:1806.06045, 2018.
    .. [6] CARABA, Elena. Preconditioned conjugate gradient algorithm. 2008.
    .. [7] "Biconjugate gradient stabilized method", 
           Wikipedia, https://en.wikipedia.org/wiki/Biconjugate_gradient_stabilized_method
    .. [8] "Conjugate gradient squared", Wikipedia,
           https://en.wikipedia.org/wiki/Conjugate_gradient_squared_method
    .. [9] "Biconjugate gradient method", Wikipedia, 
           https://en.wikipedia.org/wiki/Biconjugate_gradient_method

2024-04-18 21:37 UTC, thalassemia requested changes

2024-04-18 21:37 UTC, thalassemia commented on scipy/sparse/linalg/_isolve/iterative.py
> +    The inverse precondtitioner noted ``M`` is not standard notation in the litterature. It is usually denoted ``M^-1``. See [1,2,3,4]
```suggestion
    The inverse preconditioner noted ``M`` is not standard notation in the literature. It is usually denoted ``M^-1``. See [1,2,3,4]
```

2024-04-18 21:37 UTC, thalassemia commented on scipy/sparse/linalg/_isolve/iterative.py
> +    The inverse precondititioner noted ``M`` is not standard notation in the litterature. It is usually denoted ``M^-1``. See [1,2,3]
```suggestion
    The inverse preconditioner noted ``M`` is not standard notation in the literature. It is usually denoted ``M^-1``. See [1,2,3]
```

2024-04-18 21:37 UTC, thalassemia commented on scipy/sparse/linalg/_isolve/iterative.py
> +    The inverse precondtitioner noted ``M`` is not standard notation in the litterature. It is usually denoted ``M^-1``. See [1,2,3]
```suggestion
    The inverse preconditioner noted ``M`` is not standard notation in the literature. It is usually denoted ``M^-1``. See [1,2,3]
```

2024-04-18 21:37 UTC, thalassemia commented on scipy/sparse/linalg/_isolve/iterative.py
> +    Here, ``M`` should be a matrix such that MA has a smaller condition number than ``A``.
```suggestion
    Here, ``M`` should be a matrix such that ``MA`` has a smaller condition number than ``A``.
```

2024-04-18 21:37 UTC, thalassemia commented on scipy/sparse/linalg/_isolve/iterative.py
> +    The inverse precondtitioner noted ``M`` is not standard notation in the litterature. It is usually denoted ``M^-1``. See [1,2,3]
```suggestion
    The inverse preconditioner noted ``M`` is not standard notation in the literature. It is usually denoted ``M^-1``. See [1,2,3]
```

2024-04-18 21:38 UTC, thalassemia commented
These are just typo fixes. Someone familiar with the math still needs to review this.

2024-04-19 08:51 UTC, ilayn commented
Thank you @Afleloup 

I think this is conflating the point here a bit too much. Just because the argument name is `M` is not meant to be that we find a preconditioner and invert it and then pass here. We can correct the docs saying simply $MA$ should improve the conditioning of the problem as an extra sentence, and that should be enough.

The theoretical treatment is irrelevant here since the operator name can be anything. It's utility is important. 

The point of all the inverses attached to M is to emphasize that it kinda sorta inverts A. But in fact it does a more important thing which is, ideally, improves the condition number of the LHS. Hence inverse is a red herring here. The existing docs read correct to me, but can be clarified for the mismatch with the literature. 

Note that the preconditioner definition is all over the place, as noted with the wiki page you added as a reference

>  It is also common to call $T=P^{-1}$ the preconditioner, rather than $\displaystyle P$, since $P$ itself is rarely explicitly available.

2024-04-19 09:17 UTC, Afleloup commented
Thanks, I will change it this way then. I didn't see the sentence you mentioned in the wikipedia article and thought the literature I had was consistent with the other notation.

2024-10-01 09:37 UTC, j-bowhay commented on scipy/sparse/linalg/_isolve/iterative.py
> +    condition number than `A`. See [1]_ for more info.
```suggestion
    condition number than `A`, see [1]_ .
```

2024-10-01 09:37 UTC, j-bowhay commented on scipy/sparse/linalg/_isolve/iterative.py
> +    condition number than `A`, see [1]_ for more info.
```suggestion
    condition number than `A`, see [1]_ .
```

2024-10-01 14:41 UTC, j-bowhay approved these changes
Thanks @Afleloup! I made a few edits to get this merged

2024-10-01 14:43 UTC, merged