fix peak widths zero division error
scipy/scipy pull request #20721
Opened 2024-05-16 05:24 UTC by Jerry-Ma

#### Reference issue

Closes #20720 

#### What does this implement/fix?
Added check to only do interpolation if values are different.

#### Additional information

2024-05-16 10:05 UTC, lucascolley reviewed
thanks @Jerry-Ma, could you add a test which fails before this patch and passes afterwards?

2024-06-03 12:53 UTC, tupui commented
If there is not updates there, we could consider shipping it still. It's pretty clear that the conditions guard from a divide by 0.

2024-07-07 12:53 UTC, j-bowhay commented
Friendly ping @Jerry-Ma it would be really great if you would be able to add a regression test for this

2024-07-07 13:53 UTC, Jerry-Ma commented
> Friendly ping @Jerry-Ma it would be really great if you would be able to add a regression test for this

Sorry I was (and am) traveling and have limited time working on this. I'll try to see what I can do in the next few days.

2024-07-07 13:55 UTC, j-bowhay commented
> > Friendly ping @Jerry-Ma it would be really great if you would be able to add a regression test for this
> 
> Sorry I was (and am) traveling and have limited time working on this. I'll try to see what I can do in the next few days.

No problem, if it is easier to provide an example I can add the test

2024-10-23 02:18 UTC, j-bowhay commented
Friendly ping @Jerry-Ma

2024-12-02 22:47 UTC, tylerjereddy reviewed
Since we still don't have a reproducing example/test, I took a stab at "brute forcing" one using `hypothesis`:

<details>

```diff
--- a/scipy/signal/tests/test_peak_finding.py
+++ b/scipy/signal/tests/test_peak_finding.py
@@ -1,4 +1,5 @@
 import copy
+import warnings
 
 import numpy as np
 import pytest
@@ -19,6 +20,11 @@ from scipy.signal.windows import gaussian
 from scipy.signal._peak_finding_utils import _local_maxima_1d, PeakPropertyWarning
 
 
+from hypothesis import strategies as st
+from hypothesis import given, settings
+from hypothesis.extra import numpy as hynp
+
+
 def _gen_gaussians(center_locs, sigmas, total_length):
     xdata = np.arange(0, total_length).astype(float)
     out_data = np.zeros(total_length, dtype=float)
@@ -444,6 +450,16 @@ class TestPeakProminences:
 
 class TestPeakWidths:
 
+    @given(hynp.arrays(np.float64, (12,), elements=st.floats(0.001, 1), unique=False),
+           st.floats(min_value=0.001, max_value=1),
+           hynp.arrays(np.int64, (5,), elements=st.integers(0, 10), unique=False))
+    @settings(max_examples=10_000)
+    def test_gh_20720(self, x, rel_height, peaks):
+        with warnings.catch_warnings():
+            warnings.simplefilter("ignore", category=PeakPropertyWarning)
+            peak_widths(x, peaks, rel_height=rel_height)
+
+
     def test_empty(self):
```

</details>

but it still passes consistently even at `10_000` examples. Maybe a `signal` regular can tweak it to find the problem, but I'll probably move on.

2024-12-04 04:49 UTC, tylerjereddy commented
I'll bump the milestone following my analysis above--suggestions are still welcome of course.

To be honest, if we don't get a viable reproducer soon I'd be tempted to close the issue to avoid timesinks for other devs.

2024-12-04 19:58 UTC, Jerry-Ma commented
> I'll bump the milestone following my analysis above--suggestions are still welcome of course.
> 
> To be honest, if we don't get a viable reproducer soon I'd be tempted to close the issue to avoid timesinks for other devs.

I am deeply sorry for my long inactivity on this. Thanks a lot for being on top of this issue and trying to produce a test to demonstrate the problem.

I also tried come up with a contrived input that could reproduce the issue, but failed.

However, I was able to find in our production data that have triggered the problem. I made a dump of the data as npz file, which is attached (it has to be unzipped as I cannot upload npz file directly here), and here is the script to reproduce the error using the npz file:

```
from scipy.signal import peak_widths
import numpy as np


if __name__ == '__main__':

    data = np.load("scipy_peak_widths_data.npz")

    peak_width, peak_whs, left_ips, right_ips = peak_widths(
        data["x"],
        data["peaks"],
        rel_height=data["rel_height"],
        prominence_data=(
            data["prominence_data_value"],
            data["prominence_data_base_left"],
            data["prominence_data_base_right"],
        ),
    )

    print(peak_width)
    print(peak_whs)
```

[data.zip](https://github.com/user-attachments/files/18013556/data.zip)


It is possible to isolate the exact peak that caused the issue in the dataset, but that'll take some time and investigation which I might not have the time to do.

I am not sure if it is a good idea to include the entire data in the test, which is a couple hundred KB. But at least this is a starting point to properly address this issue.

2025-05-15 21:10 UTC, tylerjereddy commented
> I am not sure if it is a good idea to include the entire data in the test, which is a couple hundred KB. But at least this is a starting point to properly address this issue.

Thanks, I think we'll need a bit more time to see if we can cut this down to a reasonable minimum viable regression test. I need to focus on other aspects of the release process for the next few days, but I'll keep a milestone on this for the next release, and if we resolve it before then we can always backport it since it is a bug fix.

2025-11-23 19:18 UTC, nickodell commented
Hello, I am looking at this bug fix to see if it can be included into 1.17.0. The deadline for this is fast approaching.

>It is possible to isolate the exact peak that caused the issue in the dataset, but that'll take some time and investigation which I might not have the time to do.

I wrote a program to automatically minimize this test case. It works by trying to remove the first N peaks, then removing the last N peaks, and continuing with larger removals until it cannot reduce it further. It also drops samples randomly as long as it does not stop the reproducer from failing.

Here is the reducer program.

<details>

```
from scipy.signal import peak_widths
import numpy as np
import copy

def still_failing(test_case):
    try:
        peak_widths(
            test_case["x"],
            test_case["peaks"],
            prominence_data=(
                test_case["prominence_data_value"],
                test_case["prominence_data_base_left"],
                test_case["prominence_data_base_right"],
            ),
        )
        return False
    except ZeroDivisionError:
        return True

def reduce_test_case_by_peak_removal():
    data = np.load("scipy_peak_widths_data.npz")
    peaks = data["peaks"]
    x = data["x"]
    prominence_data_value = data["prominence_data_value"]
    prominence_data_base_left = data["prominence_data_base_left"]
    prominence_data_base_right = data["prominence_data_base_right"]
    assert still_failing(data)


    for i in range(len(peaks)):
        try:

            peak_width, peak_whs, left_ips, right_ips = peak_widths(
                x,
                peaks[:i],
                prominence_data=(
                    prominence_data_value[:i],
                    prominence_data_base_left[:i],
                    prominence_data_base_right[:i],
                ),
            )

        except:
            print(f"first bad i: {i}")
            break

    for j in range(i, 0, -1):
        print(f"testing {j=}")
        data = np.load("scipy_peak_widths_data.npz")

        try:

            peak_width, peak_whs, left_ips, right_ips = peak_widths(
                x,
                peaks[j:i],
                prominence_data=(
                    prominence_data_value[j:i],
                    prominence_data_base_left[j:i],
                    prominence_data_base_right[j:i],
                ),
            )

            print(peak_width)
            print(peak_whs)
        except:
            print(f"first bad j: {j}")
            break
    start_idx = (prominence_data_base_left[j:i].min()) - 10
    end_idx = (prominence_data_base_right[j:i].max()) + 10
    # end_idx
    new_prominence_data_base_left = prominence_data_base_left[j:i] - start_idx
    new_prominence_data_base_right = prominence_data_base_right[j:i] - start_idx
    new_prominence_data_value = prominence_data_value[j:i]
    new_x = x[start_idx:end_idx]
    # print(start_idx)
    new_peaks = peaks[j:i] - start_idx
    reduced_test_case = {
        "x": new_x,
        "peaks": new_peaks,
        "prominence_data_value": new_prominence_data_value,
        "prominence_data_base_left": new_prominence_data_base_left,
        "prominence_data_base_right": new_prominence_data_base_right,
    }
    assert still_failing(reduced_test_case)
    return reduced_test_case

def reduce_test_case_by_random_removal(reduced_test_case):
    random_index = np.random.randint(0, len(reduced_test_case['x']))
    new_x = np.delete(reduced_test_case['x'], random_index, axis=0)
    new_peaks = reduced_test_case["peaks"]
    new_prominence_data_value = reduced_test_case["prominence_data_value"]
    new_prominence_data_base_left = reduced_test_case["prominence_data_base_left"]
    new_prominence_data_base_right = reduced_test_case["prominence_data_base_right"]
    # fix up indices
    if random_index <= new_peaks[0]:
        new_peaks = new_peaks - 1
    if random_index <= new_prominence_data_base_left[0]:
        new_prominence_data_base_left = new_prominence_data_base_left - 1
    if random_index <= new_prominence_data_base_right[0]:
        new_prominence_data_base_right = new_prominence_data_base_right - 1
    
    new_test_case = {
        "x": new_x,
        "peaks": new_peaks,
        "prominence_data_value": new_prominence_data_value,
        "prominence_data_base_left": new_prominence_data_base_left,
        "prominence_data_base_right": new_prominence_data_base_right,
    }
    
#     print("random_index", random_index)
#     print(reduced_test_case)
    try:
        if still_failing(new_test_case):
            return new_test_case
        else:
            return reduced_test_case
    except ValueError as e:
        print("invalid test case")
        print(e)
        return reduced_test_case

def print_test_case(test_case):
    print("import numpy as np")
    print("from numpy import array")
    # V1
    print(f"data = {test_case}")
    print("""peak_widths(
    data["x"],
    data["peaks"],
    prominence_data=(
        data["prominence_data_value"],
        data["prominence_data_base_left"],
        data["prominence_data_base_right"],
    ),
)""")
    # V2
#     print(f"x = {repr(test_case['x'])}")
#     print(f"peaks = {repr(test_case['peaks'])}")
#     print("""peak_widths(
#     data["x"],
#     data["peaks"],
#     prominence=0,
# )""")
    


reduced_test_case = reduce_test_case_by_peak_removal()
assert still_failing(reduced_test_case)

random_removal_test = copy.deepcopy(reduced_test_case)
for i in range(200):
    print(f"len(x)={len(random_removal_test['x'])}")
    random_removal_test = reduce_test_case_by_random_removal(random_removal_test)

print("Final program")
print("\n\n\n")
print_test_case(random_removal_test)
```

</details>

Here is the reduced test case.

```
import numpy as np
from numpy import array
data = {
    'x': array([ 0, 1 , 1]),
    'peaks': array([1]),
    'prominence_data_value': array([-1.0]),
    'prominence_data_base_left': array([0]),
    'prominence_data_base_right': array([2])
}
peak_widths(
    data["x"],
    data["peaks"],
    prominence_data=(
        data["prominence_data_value"],
        data["prominence_data_base_left"],
        data["prominence_data_base_right"],
    ),
)
```

I was able to reproduce the problem without the use of `rel_height`, but I was unable to reproduce the problem without the use of `prominence_data`. In particular the prominence must be negative, and `prominence_data_base_right` must be 2.

2025-11-24 17:16 UTC, Jerry-Ma commented
Hi,

Thank you very much for picking the issue up and working on this! Great that we now have a MWE that reproduce the issue.

It is indeed only problematic when we provide prominence data, which is generated separately in a non-trivial way. This issue only raises when the input data is not of the nominal form when our readout system is not working properly (we monitor a readout circuit and the algorithm is to detect peaks in the readout).

Looking forward to see it merged in the next milestone. Let me know if I need to update the PR to make it proper.

2025-11-25 04:29 UTC, nickodell commented
> Looking forward to see it merged in the next milestone. Let me know if I need to update the PR to make it proper.

To see this merged, I would like to see two things.

1. From @Jerry-Ma, I would like to see a test case that fails on current main added to your PR. The one I just posted fails on our current main. This will protect our users if we ever accidentally break this code in the future.
2. From a scipy.signal maintainer, I would like clarification on whether using prominence_data in this manner is within the scope of our public API. Is the procedure that @Jerry-Ma described in [this comment](https://github.com/scipy/scipy/pull/20721#issuecomment-3571873247) a legal use of our public API?

   The docs do say that prominence_data must be "A tuple of three arrays matching the output of peak_prominences when called with the same arguments x and peaks. This data are calculated internally if not provided." This data matches what we expect in terms of dtype and shape, but not content.

   If not, then this bug is out of scope.

2025-12-06 02:12 UTC, tylerjereddy commented
> If not, then this bug is out of scope.

Maybe a bit more discussion still needed here--thanks for pushing on it Nick. I'll assume this won't get resolved in the next 1-2 days and bump the milestone with imminent branching.

2026-01-26 22:11 UTC, j-bowhay commented
@Jerry-Ma friendly ping, would you be able to come back here and add a regression test

2026-01-29 18:24 UTC, Jerry-Ma commented
> @Jerry-Ma friendly ping, would you be able to come back here and add a regression test

Hi, I just updated the PR with a unit test. I also did a rebase and squash. Let me know if there is any thing that needs to be done.

2026-01-29 19:04 UTC, nickodell commented
> Pull request overview

Does anyone know what triggered this? I thought we had CoPilot turned off.

2026-01-29 19:39 UTC, ev-br commented
> Does anyone know what triggered this? I thought we had CoPilot turned off.

Seconded. Please definitely let's keep if off this repository. 

If someone wants copilot reviews, please turn it on on their fork, get a review in the fork, and then send a PR to scipy/scipy.

2026-01-30 02:56 UTC, nickodell requested changes

2026-01-30 02:56 UTC, nickodell commented on scipy/signal/_peak_finding_utils.pyx
```suggestion
#cython: wraparound=False
#cython: boundscheck=False
#cython: nonecheck=False
#cython: cdivision=True

```

When cdivision is disabled, Cython generates a bunch of code to protect against division by zero, and create a Python exception.

It generates quite a lot of C code.

```
−356:                     left_ip += (height - x[i]) / (x[i + 1] - x[i])

              __pyx_t_14 = __pyx_v_i;
              __pyx_t_16 = (__pyx_v_height - (*((__pyx_t_5numpy_float64_t const  *) ( /* dim=0 */ ((char *) (((__pyx_t_5numpy_float64_t const  *) __pyx_v_x.data) + __pyx_t_14)) ))));
              __pyx_t_14 = (__pyx_v_i + 1);
              __pyx_t_15 = __pyx_v_i;
              __pyx_t_17 = ((*((__pyx_t_5numpy_float64_t const  *) ( /* dim=0 */ ((char *) (((__pyx_t_5numpy_float64_t const  *) __pyx_v_x.data) + __pyx_t_14)) ))) - (*((__pyx_t_5numpy_float64_t const  *) ( /* dim=0 */ ((char *) (((__pyx_t_5numpy_float64_t const  *) __pyx_v_x.data) + __pyx_t_15)) ))));
              if (unlikely(__pyx_t_17 == 0)) {
                PyGILState_STATE __pyx_gilstate_save = __Pyx_PyGILState_Ensure();
                PyErr_SetString(PyExc_ZeroDivisionError, "float division");
                __Pyx_PyGILState_Release(__pyx_gilstate_save);
                __PYX_ERR(0, 356, __pyx_L6_error)
              }
              __pyx_v_left_ip = (__pyx_v_left_ip + (__pyx_t_16 / __pyx_t_17));
```

However, if one turns on `cdivision`, and requests the standard floating point behavior here, about half of this code can be avoided. Since we are already protecting against division by zero, we can also enable `cdivision`.

2026-01-30 02:58 UTC, nickodell commented on scipy/signal/_peak_finding_utils.pyx
Err, for some reason my suggested change didn't come through quite right.

To turn on C division, one can change the header of this program from:

```
#cython: wraparound=False
#cython: boundscheck=False
#cython: nonecheck=False
```
to
```
#cython: wraparound=False
#cython: boundscheck=False
#cython: nonecheck=False
#cython: cdivision=True
```

2026-01-30 03:03 UTC, nickodell commented
>From a scipy.signal maintainer, I would like clarification on whether using prominence_data in this manner is within the scope of our public API.

I haven't heard from any scipy.signal maintainers on this point, so I am going to assume that this is part of our public API; it is a documented parameter, after all. Therefore, this is a valid bug. Anyone who disagrees should speak now or forever hold their peace.

2026-01-30 09:30 UTC, j-bowhay commented
Thanks for adding the test, I am happy that this reproduces the original issue:
```
In [1]: from scipy.signal import peak_widths

In [2]: x = np.array([ 0, 1 , 1])

In [3]: peak = np.array([1])

In [4]: prominence_data = (
   ...:             np.array([-1.0]),
   ...:             np.array([0]),
   ...:             np.array([2])
   ...:         )

In [5]: result = peak_widths(
   ...:                 x,
   ...:                 peak,
   ...:                 prominence_data=prominence_data
   ...:                 )
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 result = peak_widths(
      2                 x,
      3                 peak,
      4                 prominence_data=prominence_data
      5                 )

File ~/development/scipy/scipy/signal/_peak_finding.py:593, in peak_widths(x, peaks, rel_height, prominence_data, wlen)
    591     wlen = _arg_wlen_as_expected(wlen)
    592     prominence_data = _peak_prominences(x, peaks, wlen)
--> 593 return _peak_widths(x, peaks, rel_height, *prominence_data)

File _peak_finding_utils.pyx:355, in scipy.signal._peak_finding_utils._peak_widths()

ZeroDivisionError: float division
```

2026-03-13 23:03 UTC, j-bowhay commented
I have addressed @nickodell's comment over at #24817 to help get this over the line

2026-03-13 23:49 UTC, closed without merging