addition to make_lsq_bspline
scipy/scipy pull request #20818
Opened 2024-05-28 08:49 UTC by Searchingdays

#### Reference issue

#### What does this implement/fix?

#### Additional information

2024-05-28 09:11 UTC, ev-br requested changes

2024-05-28 09:11 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +def make_lsq_spline(x, y, t, k=3, w=None, axis=0, check_finite=True, bc_type:None):
this is not a legal python syntax.

2024-05-28 09:11 UTC, ev-br commented on scipy/interpolate/_bsplines.py
> +    t[-1] = deriv2
This cannot be right.

2024-05-28 09:57 UTC, lucascolley commented
Hi @Searchingdays , please can you follow the PR template and provide a description of why changes, and why you think they should be included? For API additions like this, it is generally a good idea to open an issue first, to discuss with maintainers whether it is something that would belong in SciPy. More info at https://scipy.github.io/devdocs/dev/hacking.html.

2024-06-08 16:24 UTC, ev-br commented
The sparse changes are unrelated and should be in a separate PR. The interpolate changes are not really correct. I believe it'd be easier to start from scratch, so am closing this PR. @Searchingdays please don't hesitate resubmitting a focused PR.

2024-06-08 16:24 UTC, closed without merging

2024-06-08 17:58 UTC, lucascolley commented
Please read the dev guide at http://scipy.github.io/devdocs/dev/hacking.html and reach out via https://scipy.org/community/ if you'd like any help!