DOC: Add example when using ``workers`` in ``integrate.quad_vec``
scipy/scipy pull request #20915
Opened 2024-06-06 16:19 UTC by m-maggi

#### Reference issue
An attempt to close #18879

#### What does this implement/fix?
Write a second code example where the argument ``workers`` is used.

2024-06-07 04:58 UTC, j-bowhay requested changes
Thanks @m-maggi! The doc/refguide failure looks related if you could take a look

2024-06-07 05:35 UTC, m-maggi commented
> Thanks @m-maggi! The doc/refguide failure looks related if you could take a look

thank you @j-bowhay, may I write the code block without executing it or would you have any other advice?
What I don't like so much in this way is that the plot of the first example is shown after the second example, even though the second example is just a code block without execution as far as I understand. I enclose a screenshot of how it looks like on my local machine.

The new docstring would be:

    When using the argument ``workers``, one should ensure
    the 'Safe importing of main module', for instance
    by rewriting the example above as:

    .. highlight:: python
    .. code-block:: python

        from scipy.integrate import quad_vec
        import numpy as np
        import matplotlib.pyplot as plt

        alpha = np.linspace(0.0, 2.0, num=30)
        x0, x1 = 0, 2
        def f(x):
            return x**alpha

        if __name__ == "__main__":
            y, err = quad_vec(f, x0, x1, workers=2)
            plt.plot(alpha, y)
            plt.xlabel(r"$\alpha$")
            plt.ylabel(r"$\int_{0}^{2} x^\alpha dx$")
            plt.show()

![doc_example](https://github.com/scipy/scipy/assets/124086916/f36abb31-d856-40b4-9772-96af3617015c)

2024-06-16 22:07 UTC, j-bowhay commented
> > Thanks @m-maggi! The doc/refguide failure looks related if you could take a look
> 
> thank you @j-bowhay, may I write the code block without executing it or would you have any other advice? What I don't like so much in this way is that the plot of the first example is shown after the second example, even though the second example is just a code block without execution as far as I understand. I enclose a screenshot of how it looks like on my local machine.
> 
> The new docstring would be:
> 
> ```
> When using the argument ``workers``, one should ensure
> the 'Safe importing of main module', for instance
> by rewriting the example above as:
> 
> .. highlight:: python
> .. code-block:: python
> 
>     from scipy.integrate import quad_vec
>     import numpy as np
>     import matplotlib.pyplot as plt
> 
>     alpha = np.linspace(0.0, 2.0, num=30)
>     x0, x1 = 0, 2
>     def f(x):
>         return x**alpha
> 
>     if __name__ == "__main__":
>         y, err = quad_vec(f, x0, x1, workers=2)
>         plt.plot(alpha, y)
>         plt.xlabel(r"$\alpha$")
>         plt.ylabel(r"$\int_{0}^{2} x^\alpha dx$")
>         plt.show()
> ```
> 
> ![doc_example](https://private-user-images.githubusercontent.com/124086916/337535627-f36abb31-d856-40b4-9772-96af3617015c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NzU3NjcsIm5iZiI6MTcxODU3NTQ2NywicGF0aCI6Ii8xMjQwODY5MTYvMzM3NTM1NjI3LWYzNmFiYjMxLWQ4NTYtNDBiNC05NzcyLTk2YWYzNjE3MDE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQyMjA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTM3YmY5N2I1M2QwOWEwOTlkNGVmYzcxYjhiNThlNzAwNjU0ODM2ZWUyZTdmYzNlMjBhZDY1Y2JhNmQ3ZGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IeVBhofBwaPoM0eFqo2Y6FfxkESGvS-5dhfsxZ86sKw)

I think that would work yes. I am not entirely sure about the plotting issue yet

2024-06-18 18:35 UTC, j-bowhay commented
Hmm the refguide check seems related, sorry haven't had time to long deeper than that

2024-06-18 19:23 UTC, m-maggi commented
The refguide-check fails here

> build-install/lib/python3.11/site-packages/scipy/integrate/_quad_vec.py:scipy.integrate.quad_vec:132: (ERROR/3) Unknown directive type "plot".::

This directive is needed to show the plot right after the plt.show().
I tried to import and register it there without success (I then get another error)

https://github.com/scipy/scipy/blob/c22b657faf9e8cf19167a82b3bfe65a90a2c5afb/tools/refguide_check.py#L37-L39

I now commit again without using the plot directive. The drawback is that the plot will appear at the end of the docstring and not right after the plot.show(). But the refguide-check should pass and also the example with ``workers`` should be visible.

2024-06-19 07:58 UTC, j-bowhay commented on scipy/integrate/_quad_vec.py
> +    the 'Safe importing of main module', for instance
```suggestion
    the main module is import-safe, for instance
```

2024-06-19 07:58 UTC, j-bowhay commented on scipy/integrate/_quad_vec.py
> +            plt.show()
```suggestion
```

2024-06-19 07:59 UTC, j-bowhay commented on scipy/integrate/_quad_vec.py
> +            plt.show()
Lets keep this minimal since we aren't showing a plot

2024-06-19 09:49 UTC, j-bowhay approved these changes
Thanks as ever @m-maggi! will merge if CI come back green

2024-06-19 10:42 UTC, j-bowhay commented on scipy/integrate/_quad_vec.py
> +    When using the argument ``workers``, one should ensure
Sorry missed this last time around!
```suggestion
    When using the argument `workers`, one should ensure
```

2024-06-19 10:43 UTC, merged