ENH: Better error message on sparse matmul mismatch
scipy/scipy pull request #21018
Opened 2024-06-21 18:28 UTC by larsoner

The error message I saw in https://github.com/scipy/scipy/issues/21016 was just:
```
mne/morph.py:1401: in _surf_upsampling_mat
    data = use_e @ data
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/scipy/sparse/_base.py:715: in __matmul__
    return self._matmul_dispatch(other)
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/scipy/sparse/_base.py:625: in _matmul_dispatch
    raise ValueError('dimension mismatch')
E   ValueError: dimension mismatch
```
which was not as helpful as I would have liked. This PR tries to move toward a similar message as NumPy:
```Python
>>> import numpy as np
>>> np.eye(2) @ np.ones(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)
>>> from scipy import sparse
>>> sparse.eye_array(2) @ sparse.eye_array(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/scipy/scipy/sparse/_base.py", line 725, in __matmul__
    return self._matmul_dispatch(other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/larsoner/python/scipy/scipy/sparse/_base.py", line 626, in _matmul_dispatch
    raise ValueError(
ValueError: matmul: dimension mismatch with signature (n,k),(k,m)->(n,m) (size 2 is different from 3)
>>> sparse.eye_array(2) @ np.ones(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/scipy/scipy/sparse/_base.py", line 725, in __matmul__
    return self._matmul_dispatch(other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/larsoner/python/scipy/scipy/sparse/_base.py", line 648, in _matmul_dispatch
    raise ValueError(
ValueError: matmul: dimension mismatch with signature (n,k),(k,1?)->(n,1?) (size 2 is different from 3)

```
Happy to adjust the message a bit more if people would prefer something different. My thinking was to try to be NumPy-like but simplify the language a little bit.

2024-06-23 11:16 UTC, lucascolley approved these changes
seems sensible!

2024-06-24 18:25 UTC, perimosocordiae requested changes
What do you think about making the error messages more concise by inlining the mismatching values of `k` in the signature?

2024-06-24 18:25 UTC, perimosocordiae commented on scipy/sparse/_base.py
> +                    f"(size {N} is different from {other.shape[0]})"
```suggestion
                    f"{err_prefix} (n,k={N}),(k={other.shape[0]},m)->(n,m)"
```

2024-06-24 18:25 UTC, perimosocordiae commented on scipy/sparse/_base.py
> +                    f"(size {N} is different from {other.shape[0]})"
```suggestion
                    f"{err_prefix} (n,k={N}),(k={other.shape[0]},1?)->(n,1?)"
```

2024-06-24 18:25 UTC, perimosocordiae commented on scipy/sparse/_base.py
> +                    f"(size {N} is different from {other.shape[0]})"
```suggestion
                    f"{err_prefix} (n,k={N}),(k={other.shape[0]},m)->(n,m)"
```

2024-06-24 18:29 UTC, larsoner commented
It makes them less similar to NumPy but I agree they seem more readable so I applied the changes!

2024-06-25 15:40 UTC, dschmitz89 commented
Change looks sensible. One question: In stats, we typically also test the error messages themselves. Is that common in the other subpackages as well?

2024-06-27 15:29 UTC, dschult approved these changes
This looks good!
Thanks!

2024-06-27 15:30 UTC, merged