MAINT: cleaner 0-D/scalar checks for `xp` assertions, round 2
scipy/scipy pull request #21413
Opened 2024-08-19 12:40 UTC by lucascolley

#### Reference issue
Closes gh-21044. Taking over from gh-21026.

#### What does this implement/fix?
Not yet ready for review.

#### Additional information

2024-08-20 22:52 UTC, lucascolley commented
CI looks green and I have finished the write-up - this is ready for discussion and review.

2024-08-20 23:12 UTC, lucascolley commented
@betatim @ogrisel out of interest, have you bumped into this distinction between NumPy 0-D arrays and scalars in testing scikit-learn? And do you also have custom assertion functions, or do you just use `np.testing`?

2024-08-21 00:57 UTC, fancidev commented
Could you clarify by “scalar” do you mean numpy scalar (such as `np.float64(1.0)`) or Python scalar (such as `1.0`) or both?

2024-08-21 01:16 UTC, h-vetinari commented
First off, such a discussion should be had in an issue (or the existing RFC), not hidden away in a PR.

> (3B) I think we want to avoid the regression in testing strictness, hence I didn't want to merge this solution

This is a patently false statement, because ipso facto our code does _not_ maintain the correct dimensionality (or the expected value in the assert is wrong). There's no strictness to decrease for code that _does not support_ your increased strictness requirements also for numpy.

Still, that realisation opens the door to a solution that will hopefully satisfy you
```python
xp_assert_close(actual, desired, check_0d=not is_numpy(xp))
```

2024-08-21 01:19 UTC, h-vetinari requested changes
Adding `[()]` outside of `scipy.stats` and "at scale" is a strict pessimization of our code base; see comment above for an alternative

2024-08-21 01:19 UTC, h-vetinari commented on scipy/differentiate/tests/test_differentiate.py
> +        xp_assert_close(res.df, ref[()])
Like here etc.

2024-08-21 01:19 UTC, h-vetinari commented on scipy/special/tests/test_support_alternative_backends.py
> +    ref = ref[()] if ref.ndim == 0 else ref
same here

2024-08-21 06:13 UTC, lucascolley commented
> Could you clarify by “scalar” do you mean numpy scalar (such as np.float64(1.0)) or Python scalar (such as 1.0) or both?

This is about NumPy scalars.

2024-08-21 06:15 UTC, lucascolley commented
> such a discussion should be had in an issue (or the existing RFC), not hidden away in a PR.

I'll paste the write-up in the RFC 👍

2024-08-21 06:28 UTC, lucascolley commented
> `xp_assert_close(actual, desired, check_0d=not is_numpy(xp))`

With this, both of the following pass:

1. `xp_assert_close(np_scalar, np_array, check_0d=not is_numpy(xp))`
2. `xp_assert_close(np_array, np_array, check_0d=not is_numpy(xp))`

I'm looking for a configuration such that only (1) passes, not (2). If we want to handle this via a kwarg to the assertion, I think that will look like alternative (3A) in my write-up.

2024-08-21 07:55 UTC, h-vetinari commented
> I'm looking for a configuration such that only (1) passes, not (2).

This is against the fundamental design principles laid out in the RFC; The general `xp_assert_close(np_array, np_array)` must always pass, regardless of `check_0d` or not. You have the `_no_0d` variant to suppress this case.

2024-08-21 08:08 UTC, ogrisel commented
> @betatim @ogrisel out of interest, have you bumped into this distinction between NumPy 0-D arrays and scalars in testing scikit-learn? And do you also have custom assertion functions, or do you just use np.testing?

No we do not have such testing utilities: we manually convert to numpy (with a private library-aware conversion function) and then use `np.testing`.

As far as I remember we did not encounter the 0d array vs numpy scalar discrepancy in our array API upgraded code base yet. Public scikit-learn functions that return scalars often convert to Python scalars explicitly.

Still we might want to adopt scipy's testing utils in the future (probably via a temporary backport to be able to test against older scipy versions).

2024-08-21 10:36 UTC, ev-br commented
> The general xp_assert_close(np_array, np_array) must always pass, regardless of check_0d or not.

+1

2024-08-23 17:54 UTC, mdhaber commented on scipy/special/tests/test_support_alternative_backends.py
> +    ref = ref[()] if ref.ndim == 0 else ref
Oops, forgot to remove this one.
```suggestion
```

2024-08-23 18:04 UTC, mdhaber reviewed
Thanks for letting me sit out for a while. 

It sounds like one concern with this approach was the widespread addition of `[()]` to make tests pass. At at the same time, there was hesitation to use `check_0d=False`. I thought that since all the parts of SciPy that have been converted to use `xp_assert_close` happen to consistently return scalars instead of 0d arrays, we could eliminate all the `[()]` and the `check_0d=False` added here (and then some!) if we were to just use the `_no_0d` functions. If I understood correctly, the intent was to use them for modules that consistently return scalars, and that seems to be the case for these modules.

If I misuinderstood and we don't want to use the `_no_0d` functions except in `stats`, and if it is preferable to specify `check_0d=False` or `check_0d=not is_numpy(xp)` everwhere, instead, OK. (I just thought that the intent was for the default behavior of the `xp_assert_` functions to match the typical behavior of the module. It seems that it would might get cumbersome to change the default everywhere as we do more conversions in `special`, `integrate`, etc.) We can always revert the commit, though.

2024-08-23 19:32 UTC, lucascolley commented
Thanks for helping here, Matt.

> Huh, the failure is because the ndimage functions used to return scalars, but now return 0-d arrays with SCIPY_ARRAY_API=1.

See (4) of the top post.

2024-08-24 16:08 UTC, lucascolley commented
After your changes @mdhaber , I would still like to see this merged 👍

2024-08-24 16:10 UTC, lucascolley commented
@ev-br just to sanity check - the switch from scalar to 0-D in some of the ndimage functions when `SCIPY_ARRAY_API` is set is deliberate, right? I think we may have discussed this at the time, but my memory isn't clear. Thanks!

2024-08-24 16:17 UTC, ev-br commented
Those in ndimage tests were workarounds for then-current infra, no more.

2024-08-24 16:24 UTC, lucascolley commented
Sorry, I'm talking about the public functions, not the tests - e.g.

```python
ndimage.sum_labels(input) # scalar without SCIPY_ARRAY_API, 0-D with SCIPY_ARRAY_API
```

2024-08-24 16:53 UTC, ev-br commented
Ah, right. No, not deliberate. Or I forgot, too. Good catch! 
Needs a release note at a minimum, needs checking that there's no regression for when the env var is not set, and a decision on what to do when it is set. I _think_ it's OK when it is set to return 0D arrays (given the N+0 discussion in the scipy.signal PR).

2024-08-24 17:14 UTC, lucascolley commented
Aha, at least we can all agree something fruitful came from my investigation :) agreed with your thoughts there. See my (4A) above for a suggested follow-up to actually test this (or Matt's smarter idea of having array-api-compat help us out with this sort of case).

2024-08-24 20:32 UTC, mdhaber commented
> needs checking that there's no regression for when the env var is not set,

The `_no_0d` checks were passing without the environment variable.

> I think it's OK when it is set to return 0D arrays (given the N+0 discussion in the scipy.signal PR).

Let's see what array-api-compat says. I think this would be great if they can help us make that possible throughout.

2024-09-03 10:09 UTC, ev-br commented
So what's the status here, can somebody summarize?

I tried merging this branch into https://github.com/scipy/scipy/pull/21117 and figure out how to use assertions from this PR. Still baffled, still have 40-odd failures. 
Specifically, what's the recommended way to

```
xp_assert_close(0d_array, 0d_array)
xp_assert_close(0d_array, numpy_scalar)
``` 
under numpy with SCIPY_ARRAY_API _not_ set?

2024-09-03 10:20 UTC, lucascolley commented
> Specifically, what's the recommended way to ... under numpy with SCIPY_ARRAY_API not set?

To clarify your use case: a test module expects 0-d arrays throughout, but you would like to pass `expected` as a NumPy scalar sometimes?

If so, then the recommendation is to just use `xp.asarray` on  `expected` so that we check that a 0-d array is returned. If you don't care about that check, you can use `check_0d=False`.

2024-09-03 13:58 UTC, ev-br commented
Thanks Lucas.

> To clarify your use case: a test module expects 0-d arrays throughout, but you would like to pass expected as a NumPy scalar sometimes?

In general yes, but I don't believe the distinction "0D throughout" vs "scalar throughout" is that robust vs a reality check.  Given two functions, `b(x, y)` and `i(x)` which both return 0D arrays, consider

```
xp_assert_close(b(0, 0), i(0))     # OK
xp_assert_close(b(0, 1), i(1) - i(0))     # oops, needs check_0d=False
``` 

That said, I tried merging this PR into https://github.com/scipy/scipy/pull/21117/ and after throwing around some ~50 `asarray`-s or `check_0d=False`, it finally passes.

This is definitely an improvement over the status quo, so while very much not ideal, it can IMO be declared tolerable. 
I would suggest we land this and continue dogfooding.
So, are we all happy about the state of this PR? @lucascolley @mdhaber @fancidev @h-vetinari

2024-09-03 14:18 UTC, lucascolley commented
> ```
> xp_assert_close(b(0, 0), i(0))     # OK
> xp_assert_close(b(0, 1), i(1) - i(0))     # oops, needs check_0d=False
> ```

Yeah, that is a bit annoying, and could be solved with another namespace, `*_no_scalar` to mirror `*_no_0d`. But I am happy to land this as is.

2024-09-04 07:06 UTC, ev-br commented
I would not add yet another check_ argument. If anything, I'd default to `check_0d=False` to make usage lighter and land this.

2024-09-04 14:41 UTC, mdhaber commented
In the [example](https://github.com/scipy/scipy/pull/21413#issuecomment-2326600812) above, why not just call `xp.asarray` on the reference value? That would need to be done anyway when `interpolate` gets array API support.

2024-09-05 06:37 UTC, ev-br commented
> why not just call xp.asarray on the reference value? 

Yes, that. Or check-0d=False. Some 100+ times. 

> That would need to be done anyway when interpolate gets array API support.

Why?

2024-09-05 07:36 UTC, mdhaber commented
> Why?

If `interpolate` gets array API support, it will be tested with multiple input array types and return the appropriate array type. `xp_assert_allclose` checks to make sure the actual and result array types match, so at some point the reference value needs to be converted to the appropriate array type. It depends on how the reference values are computed, but it's quite common for them to be hard-coded or calculated with NumPy and only turned into the appropriate array type just before comparison. It's not unusual to see like `xp_assert_allclose(res, xp.asarray(ref))` everywhere.

2024-09-05 10:36 UTC, lucascolley commented
> It depends on how the reference values are generated, but it's quite common for them to be hard-coded or calculated with NumPy and only turned into the appropriate array type just before comparison.

I think Evgeni is bumping into an exception to the rule here actually. E.g. generating the reference value via `an_xp_array - 5`. For all libraries this maintains the `xp` namespace, but NumPy throws us a scalar.

2024-09-05 11:14 UTC, ev-br commented
Indeed, in the OP example, both `b(x, y)` and `i(x)` functions are going to get the array api support, and will be returning `xp` 0D arrays on all backends. The annoyance is with numpy `0Darray - 0Darray -> scalar`.

I still don't understand the opposion to having `check_0d=False` as the default in `xp_assert_*` checks, but I've no energy to argue any more. I can throw in the `check_0d` flag or an extra `asarray` and move on.

Anyhow, this is tangential to the meat of the matter. As long as `xp_assert_close(0D_array, 0D_array)` does not blow up, the rest can be declared tolerable IMO. Are we all happy with this PR as is?

2024-09-05 20:08 UTC, merged

2024-09-06 02:07 UTC, h-vetinari commented
Thank you for finishing the implementation