DOC/MAINT: add references to Boost
scipy/scipy pull request #21469
Opened 2024-08-28 19:38 UTC by dschmitz89

#### What does this implement/fix?
Although many special functions used in `special` or `stats` rely on boost, we did not add the reference yet. I personally find it important to credit the authors of the code we use.

#### Additional information
There are also many referenes left to the Fortran implementations of specfun, amos and cdflib. I would alter the descriptions along "reimplementation of the methods described in .." but will leave that for discussion.

2024-08-29 02:35 UTC, steppi requested changes
Thanks @dschmitz89. This is a welcome update. I agree we should be crediting Boost here. Rather than just adding a reference, I think it would be good to also add sentences “Wrapper for the Boost Math [i]_ routine X”.  If convenient, it would be good to be more specific with the references, but I don’t think it’s necessary for you to do that here. There’s still an issue of having to link to specific versions and keeping the versions up to date, and just adding any reference is a big improvement.

2024-08-29 04:08 UTC, fancidev commented
I think it’s a very good initiative! Not only does it gives proper credit, it also helps the (curious) user to locate the source of the implementation easily without having to dig into the code. In this regard, I think the initiative equally applies to cdflib, cephes, etc.

2024-08-29 05:16 UTC, dschmitz89 commented
> > I think it’s a very good initiative! Not only does it gives proper credit, it also helps the (curious) user to locate the source of the implementation easily without having to dig into the code. In this regard, I think the initiative equally applies to cdflib, cephes, etc.
> 
> I think most special function docstrings do reference the original libraries when relevant. Boost is an exception because we’ve only started wrapping Boost relatively recently and haven’t updated the docstrings yet. 
> 
> What @dschmitz89 is talking about is changing wording like “wrapper for routine X from Zhang and Jin” to “Reimplemented based on routine X from Zhang and Jin.” Although in some cases the code has diverged from the original enough that it could be considered a new implementation. Basically every scalar kernel in `scipy.special` except those that come from Boost are being reimplemented.

Yap, let's stick to boost instead here. Too many moving parts in the rest of special. How about we use this as a reminder that when we touch a function again next time we try to keep the docstring in sync? Doc updates are easily forgotten, have been guilty of it myself.

2024-09-01 15:15 UTC, dschmitz89 commented
I cancelled unnecessary docs irrelevant jobs, thats why Github is showin all red CI.

2024-09-02 19:13 UTC, mdhaber commented on scipy/stats/_continuous_distns.py
> +    the computation of ``cdf``, ``ppf`` and ``isf`` methods. [1]_
```suggestion
    the computation of ``cdf``, ``ppf`` and ``isf`` methods. [2]_
```

2024-09-03 14:10 UTC, steppi commented on scipy/special/_add_newdocs.py
> +    This function wraps the ``ibeta_inv`` routine from the C++ Boost library [2]_.
```suggestion
    This function wraps the ``ibeta_inv`` routine from the Boost Math C++ library [2]_.
```

and similarly in the other docstrings. Boost is a set of libraries, not a single library, and the particular library used here is [Boost Math](https://github.com/boostorg/math).

2024-09-22 05:32 UTC, merged

2024-09-22 05:34 UTC, mdhaber commented
There may be a few more hairs to be split (e.g.. precise placement of citations in the distribution notes), and I think this will be challenging to keep up to date, but probably better overall to merge and make changes as the need is noticed. Thanks @dschmitz89!