DOC: improving documentation on shifted Jacobi polynomials (#18988)
scipy/scipy pull request #21480
Opened 2024-08-30 13:55 UTC by gertingold

#### Reference issue
Addresses gh-18988

#### What does this implement/fix?
Instead of entering into a discussion of naming conventions which do not seem to be universal in this case, this PR proposes the following steps to clarify the documentation:
- The explicit definition of $G^{(p,q)}_n$, which was already present for `roots_sh_jacobi` and `sh_jacobi`, is added to `eval_sh_jacobi`. In this way, it should be more obvious to the reader that here more is being done than just shifting Jacobi polynomials.
- Information on constraints for p and q added for `eval_sh_jacobi`. This should draw the user's attention to the change in parameters. In this way, the documentation is also consistent with `roots_sh_jacobi` and `sh_jacobi`.
- For `roots_sh_jacobi`, `eval_sh_jacobi` , and `sh_jacobi`, a remark is added to point out that there is a difference between shifted Jacobi polynomials and shifted Legendre and Chebyshev polynomials.

2024-08-30 14:44 UTC, lucascolley reviewed
It looks like CI wants you to add a References section to `sh_jacobi` with AS in it

2024-08-30 18:12 UTC, gertingold commented
Thanks for the hint. I thought that I had added the reference but clearly the commits prove me wrong.

2025-06-17 05:20 UTC, jorenham commented on scipy/special/_orthogonal.py
> +          = \binom{2n + p - 1}{n}^{-1}P_n^{(p - q, q - 1)}(2x - 1).
Since `p` and `q` are reals, it might be a bit confusing to use the binomial coefficient here.  Some equivalent alternatives that are defined for real `p` are

- `factorial(n) * gamma(n + p) / gamma(2 * n + p)`  (`gamma` = euler gamma function)
- `factorial(n) / poch(n + p, n)`  (`poch` = pochhammer symbol for the rising factorial)
- `n * beta(n, n + p)` (`beta` = euler beta function)

The pochhammer symbol might be a nice fit with the underlying hypergeometric function.
Either way, no need to explain what any of these three special functions are, because you could just link to the docs of their respective `scipy.special` function.

But that being said, this definition is the same as the one used in `eval_sh_jacobi`. So I can also see how you might consider this out-of-scope.

2025-06-17 05:27 UTC, jorenham commented on scipy/special/_add_newdocs.py
> +        Parameter, must have :math:`p > q - 1`.
in the `roots_sh_jacobi` docstring this is written as

> (p1 - q1) must be > -1

and since `p - q` maps to the unshifted `alpha` parameter, I can see how that form might  be easier to interpret

2025-06-25 13:28 UTC, gertingold commented on scipy/special/_orthogonal.py
> +          = \binom{2n + p - 1}{n}^{-1}P_n^{(p - q, q - 1)}(2x - 1).
Thanks for this remark. I had used the binomial for consistency in the documentation of all three functions involved here. But of course, I fully agree that the formula should be compatible with real values of p. In 53db057, I chose your first suggestion because it agrees with the expression given in AS 22.5.2. However, I am wondering whether nowadays, it would not be more appropriate to refer to the [Digital Library of Mathematical Functions](https://dlmf.nist.gov), which continues the work of A and S and is probably more accessible for most users. In DLMF, your second option is given in [http://dlmf.nist.gov/18.1.E2](https://dlmf.nist.gov/18.1.E2).

2025-06-25 13:31 UTC, gertingold commented on scipy/special/_add_newdocs.py
> +        Parameter, must have :math:`p > q - 1`.
I followed your suggestion and implemented it in 05f6480 with a correction in 278ea0e, even though I would still be slightly in favor of my original version because in a description of the parameter p, one expects a condition for this parameter and not a combination with another parameter which is only defined afterwards. However, your structural argument is of course also a good point.

2025-06-25 13:46 UTC, jorenham commented on scipy/special/_orthogonal.py
> +          = \binom{2n + p - 1}{n}^{-1}P_n^{(p - q, q - 1)}(2x - 1).
The DLMF is fantastic, but I also agree that it's best to stick with the original sources here. Because changing those would require changing it for all other ortho polys, which is out of scope here. But perhaps it might be worth doing in a follow-up.

2025-06-25 14:40 UTC, jorenham commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
Nitpick: assuming that `\hphanthom` works, we could align the terms in the fraction like this:

```suggestion
          = n! \frac{\Gamma(\hphantom{2}n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
```

2025-06-25 15:17 UTC, gertingold commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
While I can understand that in this way the difference between the arguments in the two gamma functions can be highlighted, I would consider this to be rather ugly from a typographical point of view. I would really prefer not to use `\hphantom` in this situation. Also, it makes sense to keep the factorial of n in the numerator, thereby reflecting the binomial structure of the prefactor. Unless you insist, I would thus prefer to keep the equation as it is.

2025-06-25 15:21 UTC, jorenham commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
Dealer's choice :)

2025-06-25 15:22 UTC, gertingold commented on scipy/special/_orthogonal.py
> +          = \binom{2n + p - 1}{n}^{-1}P_n^{(p - q, q - 1)}(2x - 1).
Concerning AS vs DLMF, if replacing AS references by DLMF references is considered worth doing, I might work on that once the present issue is closed. While this task will ultimately concern the whole special functions module, it probably makes sense to first concentrate on the functions related to orthogonal polynomials. In my experience, the chapter on orthogonal polynomials has changed its structure more than other chapters in the transition from AS to DLMF.

2025-06-25 15:23 UTC, jorenham commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
(you being the dealer, in case that wasn't clear)

2025-06-25 15:25 UTC, gertingold commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
I was wondering for a second, but then concluded that you meant it in the way you just confirmed :)

2025-08-22 07:07 UTC, gertingold commented
@Kai-Striega

2026-08-05 17:58 UTC, fbourgey commented
@gertingold can you please take care of the merge conflicts?

2026-08-06 07:05 UTC, gertingold commented
I have resolved the merge conflicts.

2026-08-06 14:31 UTC, fbourgey requested changes

2026-08-06 14:31 UTC, fbourgey commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
Should we not use $\Gamma(n+1)$ instead of $n!$ as $n$ can be non-integer?

2026-08-06 14:35 UTC, jorenham commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
The Beta function could also work, since Beta(a, b) = Gamma(a) Gamma(b) / Gamma(a + b), so you could write this entire fraction as Beta(n, n + p) * n

2026-08-06 14:48 UTC, gertingold commented
Thanks for your feedback, @fbourgey and @jorenham.

It is a long time that I had originally authored this PR. I guess that the reason for using the factorial at that time was that the parameter section says `n : int`. Interestingly, the next lines specify what happens when `n` is not an integer. I just tried it out and the function call indeed works for non-integer `n`. Therefore, I would propose to replace the factorial by a gamma function and specify `n : float`. Concerning the remark by @jorenham, I would be in favor of using the gamma function instead of the beta function because I would expect users to be more familiar with the gamma function than with the beta function, but in principle I am also open to use the beta function.

If I get some feedback on which changes to implement, I will amend the PR accordingly.

2026-08-06 14:50 UTC, jorenham commented
> I would be in favor of using the gamma function instead of the beta function because I would expect users to be more familiar with the gamma function than with the beta function, but in principle I am also open to use the beta function.

makes sense :ok_hand:

2026-08-06 15:04 UTC, gertingold commented on scipy/special/_add_newdocs.py
> +          = \frac{n!\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
changed to gamma function in [39c4f07](https://github.com/scipy/scipy/pull/21480/commits/39c4f070b586dd52cbc481d9480df71d915089c1) and modified the specification of parameter `n` to float in [8c87a44](https://github.com/scipy/scipy/pull/21480/commits/8c87a4462523d677166bb4ceab16f93f2addc62e)

2026-08-07 05:55 UTC, gertingold commented
The CI failures do not seem to be related to the content of this PR.

2026-08-17 18:36 UTC, fbourgey requested changes

2026-08-17 18:36 UTC, fbourgey commented on scipy/special/_add_newdocs.py
> +          = \frac{\Gamma{n+1}\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
```suggestion
          = \frac{\Gamma(n+1)\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
```

2026-08-17 18:36 UTC, fbourgey commented on scipy/special/_add_newdocs.py
> +    and `eval_sh_chebyu`, not only the argument is shifted.
Here and below, I suggest using

```suggestion
    and `eval_sh_chebyu`, more than just the argument is shifted.
```

I think it reads better.

2026-08-18 05:33 UTC, gertingold commented on scipy/special/_add_newdocs.py
> +          = \frac{\Gamma{n+1}\Gamma(n+p)}{\Gamma(2n+p)} P_n^{(p - q, q - 1)}(2x - 1),
Thanks a lot for spotting this mistake. Corrected in [bffab55](https://github.com/scipy/scipy/pull/21480/commits/bffab558ec58cf1a45978591e760c3b44cd557ad).

2026-08-18 05:34 UTC, gertingold commented on scipy/special/_add_newdocs.py
> +    and `eval_sh_chebyu`, not only the argument is shifted.
Changes made as proposed, see [40c5420](https://github.com/scipy/scipy/pull/21480/commits/40c542030ba742e671b735885bbc95f57fe29877).

2026-08-18 14:27 UTC, merged

2026-08-18 14:28 UTC, fbourgey commented
Thanks!