Update _filter_design.py
scipy/scipy pull request #21514
Opened 2024-09-07 05:45 UTC by qqwqqw689

#### Reference issue

issue about doc. [#21510](
#### What does this implement/fix?

change the fs for firwin.
#### Additional information

I didn't build the doc. So it may need some checks.

2024-09-07 13:30 UTC, DietBru commented
> I didn't build the doc. So it may need some checks.

As described in the [Contributing to the SciPy documentation], you can check a [preview] of the rendered documentation by clicking on ``Details`` on the "**Check the rendered docs here!**" entry in the CI window below. 

A more streamlined version of the example, especially with no more cut-off text, looks like this:
```python

    >>> import numpy as np
    >>> from scipy import signal
    >>> import matplotlib.pyplot as plt
    ...
    >>> taps, f_c = 80, 1.0  # number of taps and cut-off frequency
    >>> b = signal.firwin(taps, f_c, window=('kaiser', 8), fs=2*np.pi)
    >>> w, h = signal.freqz(b)
    ...
    >>> fig, ax1 = plt.subplots(tight_layout=True)
    >>> ax1.set_title(f"Frequency Response of {taps} tap FIR Filter " +
    ...               f"($f_c={f_c}$ rad/sample)")
    >>> ax1.axvline(f_c, color='black', linestyle=':', linewidth=0.8)
    >>> ax1.plot(w, 20 * np.log10(abs(h)), 'C0')
    >>> ax1.set_ylabel("Amplitude in dB", color='C0')
    >>> ax1.set(xlabel="Frequency in rad/sample", xlim=(0, np.pi))
    ...
    >>> ax2 = ax1.twinx()
    >>> angles = np.unwrap(np.angle(h))
    >>> ax2.plot(w, angles, 'C1')
    >>> ax2.set_ylabel("Angle in radians", color='C1')
    >>> ax2.grid(True)
    >>> plt.show()
```
Otherwise, LGTM.

PS: For future Pull Requests, don't forget to consult the [PR Checklist], before submitting one.

[PR Checklist]: https://docs.scipy.org/doc/scipy/dev/contributor/development_workflow.html#checklist-before-submitting-a-pr
[Contributing to the SciPy documentation]: https://docs.scipy.org/doc/scipy/dev/contributor/rendering_documentation.html#rendering-documentation
[preview]: https://output.circle-artifacts.com/output/job/42c2f18e-d6f5-4ddf-b72c-2fa4ac76da8c/artifacts/0/html/reference/generated/scipy.signal.freqz.html

2024-09-07 13:37 UTC, qqwqqw689 commented
@DietBru thanks!

2024-09-07 15:46 UTC, qqwqqw689 commented
It looks ok now.
[link](https://output.circle-artifacts.com/output/job/dd118835-f0c2-4017-a9f0-3e5ac1cab623/artifacts/0/html/reference/generated/scipy.signal.freqz.html#scipy.signal.freqz)

2024-09-07 19:27 UTC, DietBru requested changes
One small comment. Otherwise, I think it is good to go.

2024-09-07 19:27 UTC, DietBru commented on scipy/signal/_filter_design.py
> +    >>> ax1.set_title(f"Frequency Response of {taps} tap FIR Filter ($f_c={f_c}$ rad/sample)")
According to the [PEP8 and SciPy] section of the [SciPy Contributor Guide], the line length limit is _88_ characters. Please convert this line into two shorter ones.

[PEP8 and SciPy]: https://docs.scipy.org/doc/scipy/dev/contributor/pep8.html#pep8-scipy
[SciPy Contributor Guide]: https://docs.scipy.org/doc/scipy/dev/contributor/contributor_toc.html

2024-09-08 06:02 UTC, DietBru approved these changes
Looks good now. Thanks, @qqwqqw689.

2024-09-08 16:58 UTC, j-bowhay approved these changes
Thanks for your first contribution to China @qqwqqw689 and thanks @DietBru for the review

2024-09-08 16:58 UTC, merged