BUG: fix error in `optimize.minimize(..., method='L-BFGS-B', ...)` with fixed `bounds` and `callback`
scipy/scipy pull request #21538
Opened 2024-09-10 12:22 UTC by yuzie007

#### Reference issue

Closes gh-21537

#### What does this implement/fix?

As reported in the issue above, when `optimize.minimize(..., method='L-BFGS-B', ...)` is called with fixed parameters (by giving the same values as the lower and the upper `bounds`) together with `callback`, SciPy 1.14.1 raises an error.
This PR fixes it in the manner suggested in the issue.

2025-02-05 05:40 UTC, czgdp1807 reviewed
These are recommendations/suggestions. Totally upto you to apply these. I am yet to verify the fix. If other maintainers approve then feel free to merge it.

2025-02-05 05:40 UTC, czgdp1807 commented on scipy/optimize/tests/test_optimize.py
> +    @pytest.mark.parametrize('method', ['l-bfgs-b'])
Since, we are testing only for one method here, may be we don't need `method` as input argument to `test_minimize_callback_result`. We can directly pass, `l-bfgs-b` to `optimize.minimize` call below.

2025-02-05 05:40 UTC, czgdp1807 commented on scipy/optimize/tests/test_optimize.py
> +
Can we do something like,

```
assert (bounds[:, 0] <= res.x).all()
assert (bounds[:, 1] >= res.x).all()
```

Note that `bounds` is kept as a numpy array. I tried one example and it works,

```python
>>> import numpy as np
>>> bounds = [[0.0, 0.0], [-np.inf, +np.inf], [-np.inf, +np.inf]]
>>> bounds = np.array(bounds)
>>> bounds
array([[  0.,   0.],
       [-inf,  inf],
       [-inf,  inf]])
>>> x = [1, 2, 3]
>>> x = np.array([1, 2, 3])
>>> x
array([1, 2, 3])
>>> bounds[:, 0] >= x
array([False, False, False])
>>> bounds[:, 1] <= x
array([ True, False, False])
```

Suggesting to use NumPy API over using Pythonic loops. `res.x` is anyways a NumPy array and we can make `bounds` a NumPy array so we can avoid the loop easily.

2025-02-05 18:18 UTC, czgdp1807 commented on scipy/optimize/_minimize.py
> +                        callback = _remove_from_func(callback, i_fixed, x_fixed)
I read your analysis and the idea behind the fix seems correct. So other than the reviews for test I gave above, this PR seems good.

2025-02-05 20:12 UTC, andyfaff commented
I'm going to have a look at this in the next couple of days. It overlaps with a PR thatll be merged today and there will be a merge issue.

2025-02-06 01:11 UTC, andyfaff commented
This isn't a complete fix. It's ok if the callback is one of the originals, but if the callback is an `intermediate_result` the fixed variables aren't reinjected.

2025-02-06 01:15 UTC, andyfaff requested changes
This needs further work, the following code fails:

```
import numpy as np
from scipy.optimize import rosen, minimize, Bounds, OptimizeResult

def callback(intermediate_result):
    assert len(intermediate_result.x) == 3
    assert isinstance(intermediate_result, OptimizeResult)

def callback2(x):
    assert len(x) == 3

x0 = np.array([2.0, 2.0, 4.0])
bnds = Bounds([0.0, 2.0, 0.0], [10.0, 2.0, 10.0])
minimize(f, x0, bounds=bnds, callback=callback)
minimize(f, x0, bounds=bnds, callback=callback2)
```

2025-02-06 03:07 UTC, andyfaff commented on scipy/optimize/_minimize.py
> +    def __init__(self, callback, i_fixed, x_fixed, ):
```suggestion
    def __init__(self, callback, i_fixed, x_fixed):
```

2025-02-06 06:01 UTC, merged