DOC: mstats: add examples to kurtosis
scipy/scipy pull request #21655
Opened 2024-10-02 10:35 UTC by daniel-finnan

#### Reference issue
Towards 7168

#### What does this implement/fix?
Add examples to mstats kurtosis

#### Additional information
[docs only]
First PR, tried to follow contributing guidelines, but apologies in advance if I've messed up!

2024-10-03 02:29 UTC, tylerjereddy commented on scipy/stats/_mstats_basic.py
> +    In this example, we generate an array using the `scipy.stats.norm.rvs`
For the doc build failure you can see in the CI testing, I did a quick check of our previous usages of this:

`git grep -E -i "scipy.stats.norm.rvs"`

```
scipy/stats/_continuous_distns.py:    >>> data = scipy.stats.norm.rvs(size=100000, loc=0, scale=1.5,
scipy/stats/_hypotests.py:    Suppose we wish to test whether data generated by ``scipy.stats.norm.rvs``
scipy/stats/_hypotests.py:    ``scipy.stats.norm.rvs`` have the same distribution. We choose a
scipy/stats/_mstats_basic.py:    In this example, we generate an array using the `scipy.stats.norm.rvs`
```

so, it looks like an extra set of backticks may do the trick!

2024-10-03 15:25 UTC, daniel-finnan commented
Thanks for the pointers Tyler, think this should work now

2024-10-08 09:40 UTC, yuanx749 requested changes

2024-10-08 09:40 UTC, yuanx749 commented on scipy/stats/_mstats_basic.py
> +    >>>                                        False, False, False, True, False])
```suggestion
    >>> masked = np.ma.MaskedArray(data, mask=[False, True, False, False, False,
    ...                                        False, False, False, True, False])
```

2024-12-28 20:39 UTC, mdhaber commented
Thanks @daniel-finnan, but given the responses so far in gh-22194, I don't think we'll be maintaining entirely separate examples for `mstats` functions and their `stats` counterparts. I'll adjust gh-7168 accordingly.

2024-12-28 20:39 UTC, closed without merging