Remove deprecated beta distributions
scipy/scipy pull request #21773
Opened 2024-10-28 19:55 UTC by IamPhytan

#### Reference issue

Closes #21759.

#### What does this implement/fix?

Remove references to `special.btdtr` and `special.btdtri`. Scheduled to be removed in 1.14.0.

#### Additional information

2024-10-29 05:07 UTC, dschmitz89 requested changes
Thanks for the PR @IamPhytan . I think the biggest obstacle is the CircleCI timeout which is unrelated to your changes. Let's hope that the next CI run does not run in the same issue.

2024-10-29 05:07 UTC, dschmitz89 commented on scipy/special/__init__.py
>               'removed in SciPy 1.14.0.  Use scipy.special.{} instead.')
```suggestion
```

If this is not used anywhere else, let's remove it while we are at it.

2024-10-29 13:48 UTC, IamPhytan commented
Perfect!
I commited your suggested change, @dschmitz89

2024-11-02 00:04 UTC, j-bowhay approved these changes
LGTM thanks!

2024-11-02 00:06 UTC, merged