ENH: `optimize.root`: warn when inner parameters are ignored with `method='krylov'`
scipy/scipy pull request #21993
Opened 2024-12-03 12:58 UTC by SoutrikBandyopadhyay

#### Reference issue
Closes #21986 

#### What does this implement/fix?
This PR emits warnings to the user if the Krylov solver in `optimize.root` is passed with invalid `inner_*` options which don't exist for the inner solver chosen. For example if provided with `inner_atol` with `solver="minres"`, the code will emit a warning to the user as `minres` solver doesn't accept `atol` parameter. 

#### Additional information

2024-12-03 13:53 UTC, lucascolley requested changes
thanks @SoutrikBandyopadhyay ! I've suggested a tweak to the warning message.

Could you also add a test? Test that there is no warning for valid params, that there is a warning for an invalid param, and that there are no warnings when `method` is a user-provided callable.

We also need to deal with `stacklevel` - see https://docs.python.org/3/library/warnings.html#warnings.warn. Since this constructor can be called from various places in the SciPy public API (see https://github.com/scipy/scipy/issues/21296#issuecomment-2316287029), it looks like we will want to make use of `skip_file_prefixes` as described in the Python docs.

2024-12-03 13:53 UTC, lucascolley commented on scipy/optimize/_nonlin.py
> +                )
```suggestion
            option = key[6:]
            if option not in valid_inner_params:
                warnings.warn(
                    f"The option {option} is not valid for inner solver {method}, "
                    f"so it has been ignored."
                    f"Please see the solver's documentation for a list of valid"
                    f"options to append to `inner_`."
                )
```

2024-12-03 13:53 UTC, lucascolley commented on scipy/optimize/_nonlin.py
> +            if key[6:] not in valid_inner_params:
You also need to accommodate for the possibility that `method` is a user-provided callable (no need to give any warnings here)

2024-12-04 06:19 UTC, SoutrikBandyopadhyay commented
Ok, I am on it.

2024-12-29 01:23 UTC, j-bowhay commented
Friendly reminder @SoutrikBandyopadhyay this still needs a unit test

2024-12-29 05:31 UTC, SoutrikBandyopadhyay commented
> Friendly reminder @SoutrikBandyopadhyay this still needs a unit test

I am sorry, I was busy this month. I am on it today.

2024-12-31 09:23 UTC, SoutrikBandyopadhyay commented
> thanks @SoutrikBandyopadhyay ! I've suggested a tweak to the warning message.
> 
> Could you also add a test? Test that there is no warning for valid params, that there is a warning for an invalid param, and that there are no warnings when `method` is a user-provided callable.
> 
> We also need to deal with `stacklevel` - see https://docs.python.org/3/library/warnings.html#warnings.warn. Since this constructor can be called from various places in the SciPy public API (see [#21296 (comment)](https://github.com/scipy/scipy/issues/21296#issuecomment-2316287029)), it looks like we will want to make use of `skip_file_prefixes` as described in the Python docs.

@lucascolley @j-bowhay I believe the `skip_file_prefixes` in `warnings.warn()` is not available in Python 3.11 and below https://docs.python.org/3.11/library/warnings.html#warnings.warn 

It is there in Python 3.12 and above from what I see https://docs.python.org/3.12/library/warnings.html#warnings.warn
Should I use this method? If not, can you suggest a way to handle this stacklevel issue that is backwards compatible?

2024-12-31 10:17 UTC, lucascolley commented
Ah, good catch. I would suggest using a stacklevel that may be too high in some cases, and adding a comment that we can make it more precise using `skip_file_prefixes` once we drop Python 3.11. Does that sound right to you @j-bowhay ?

2025-03-23 11:10 UTC, lucascolley commented
Hi @SoutrikBandyopadhyay, would you be interested in finishing this PR?

2025-03-23 12:18 UTC, SoutrikBandyopadhyay commented
@lucascolley I am sorry I am not able to finish this PR due to some other commitments. I close this PR so that someone experienced may take over.

2025-03-23 12:19 UTC, closed without merging