BUG: immortalize uarray global strings in order to prevent negative refcounts
scipy/scipy pull request #22038
Opened 2024-12-09 16:39 UTC by andfoy

#### Reference issue

Fixes https://github.com/scipy/scipy/issues/21214
Closes https://github.com/scipy/scipy/pull/21218

#### What does this implement/fix?

This is an alternative PR based off @peterbell10 comment https://github.com/scipy/scipy/pull/21218#pullrequestreview-2466103157 on the original PR that was opened to fix some segfaults that appeared when global `uarray` strings were being released when the Python interpreter was no longer existent.

#### Additional information

2024-12-09 17:18 UTC, peterbell10 requested changes
Should be able to revert most of this PR and change a few `.` to `->` and maybe add a few `*`s.

2024-12-09 17:18 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +  py_ref(immortal<py_ref> other): obj_(other->get()) { Py_XINCREF(obj_); }
These should not be necessary. `py_ref` should only ever be created via `steal` or `ref`.

2024-12-09 17:18 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +  global_backend_options global;
Don't make the members `immortal`, make the global variable itself immortal. 
```cpp
static immortal<global_state_t> global_domain_map;
```

2024-12-09 17:18 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +    }
Sorry, I missed a few things in my earlier comment. I think this should be more complete
```suggestion
    T* get() { return reinterpret_cast<T*>(&storage); }
    const T* get() const { return reinterpret_cast<const T*>(&storage); }
    const T* get_const() const { return reinterpret_cast<const T*>(&storage); }

    const T* operator ->() const { return get(); }
    T* operator ->() { return get(); }

    T& operator*() { return *get(); }
    const T& operator*() const { return *get(); }
```

2024-12-09 17:18 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +    ua_convert = immortal<py_ref>(PyUnicode_InternFromString("__ua_convert__"));
With the `operator*` above, you should be able to do
```suggestion
    *ua_convert = py_ref::steal(PyUnicode_InternFromString("__ua_convert__"));
```

2025-01-09 19:03 UTC, peterbell10 reviewed
Looking much better now! Just one issue left.

2025-01-09 19:03 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +  }
```suggestion
  current_global_state =
      use_thread_local_globals ? &thread_local_domain_map : global_domain_map.get();
```

2025-01-09 19:03 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +thread_local immortal<global_state_t> * current_global_state = &global_domain_map;
```suggestion
thread_local global_state_t * current_global_state = &global_domain_map;
```

2025-01-09 22:54 UTC, peterbell10 approved these changes
LGTM, just a NIT

2025-01-09 22:54 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +thread_local global_state_t * current_global_state = &*global_domain_map;
Sorry, I meant this
```suggestion
thread_local global_state_t * current_global_state = global_domain_map.get();
```

2025-01-09 22:54 UTC, peterbell10 commented on scipy/_lib/_uarray/_uarray_dispatch.cxx
> +      (current_global_state != &*global_domain_map);
```suggestion
      (current_global_state != global_domain_map.get());
```

2025-01-13 20:49 UTC, rgommers commented
Can we do both in parallel please? This needs to be backported to 1.15.x still, ideally soon.

2025-01-13 20:57 UTC, merged

2025-01-14 16:27 UTC, rgommers commented
Great, thanks a lot @andfoy and @peterbell10, and @hameerabbasi for already taking care of syncing it to Uarray!