ENH: sparse: nD cleanup and docs
scipy/scipy pull request #22129
Opened 2024-12-19 04:18 UTC by dschult

Fixes #22112 

This cleanup was inspired from the stubs work in #22112 which showed that:
- CSC format could be created as an nD array.
- `tensordot` had no doc_string

While investigating I found CSR could also almost create nD...and the resulting error was not clear.
Also, the new function `dot` did not have a doc_string.  In addition, there is quite q bit of spurious whitespace from the nD PRs.  I also found and fixed an idx_dtype error in the new `_broadcast_to` method. And finally that `test_base.py` have tests for sum and mean that were copied and never changed the var names from mean to sum. So, there are a number of small changes here.  Each has it's own commit.

-remove spurious whitespace
-align exception messages for 3D input across formats (adds test too)
- fix idx_dtype error in `_broadcast_to`
- change test_base.py varnames to match quantity computed
- add doc_strings to dot and tensordot with examples.

This should be backported to the maintenance branch.

2024-12-19 05:47 UTC, perimosocordiae approved these changes

2024-12-19 20:57 UTC, dschult commented
@jorenham can you make sure this works for your stubs and the issue #22112?  
Thanks!

2024-12-19 21:07 UTC, jorenham commented
> @jorenham can you make sure this works for your stubs and the issue #22112? Thanks!

The [`csc*` stubs](https://github.com/jorenham/scipy-stubs/blob/d70087d8cbefd0cef2581e582ab84ddb17155f8b/scipy-stubs/sparse/_csc.pyi) already reject >n-D, and the [`coo_*.tensordot` method](https://github.com/jorenham/scipy-stubs/blob/d70087d8cbefd0cef2581e582ab84ddb17155f8b/scipy-stubs/sparse/_coo.pyi#L311-L328) is annotated to have `axes: int | tuple[Sequence[int], Sequence[int]]` (although I just spotted  an outdated comment there)

2024-12-19 21:14 UTC, jorenham commented
Oh and quick (semi-related) question; all sparse arrays are now annotated to be able to be of one of the following scalar-types:

```pyi
np.bool_ | np.integer | np.float32 | np.float64 | np.longdouble | np.complexfloating
```

source: https://github.com/jorenham/scipy-stubs/blob/d70087d8cbefd0cef2581e582ab84ddb17155f8b/scipy-stubs/sparse/_typing.pyi#L41-L50 

Does that right, or did I miss something?

2024-12-20 01:21 UTC, dschult commented
Thanks for that summary... I think we're good to go then.

As for what dtypes does sparray support:  line 17 of `scipy.sparse._sputils.py`
```python
supported_dtypes = [np.bool_, np.byte, np.ubyte, np.short, np.ushort, np.intc,
                    np.uintc, np_long, np_ulong, np.longlong, np.ulonglong,
                    np.float32, np.float64, np.longdouble,
                    np.complex64, np.complex128, np.clongdouble]
```
I'm not sure what is the best way to translate that into annotations.

2024-12-20 02:11 UTC, jorenham commented
> Thanks for that summary... I think we're good to go then.
> 
> As for what dtypes does sparray support: line 17 of `scipy.sparse._sputils.py`
> 
> ```python
> supported_dtypes = [np.bool_, np.byte, np.ubyte, np.short, np.ushort, np.intc,
>                     np.uintc, np_long, np_ulong, np.longlong, np.ulonglong,
>                     np.float32, np.float64, np.longdouble,
>                     np.complex64, np.complex128, np.clongdouble]
> ```
> 
> I'm not sure what is the best way to translate that into annotations.

I guess that

```pu
(
    np.byte, np.ubyte, 
    np.short, np.ushort,
    np.intc, np.uintc,
    np_long, np_ulong,
    np.longlong, np.ulonglong
)
```

(usually) covers all of the `np.integer` instances (`datetime64` and `timedelta64` aren't annotated as `np.integer` subtypes in the numpy stubs, so those aren't included), and

```py
np.complex64, np.complex128, np.clongdouble
```

(usually) covers all of the `np.complexfloating`, so I guess it's close enough then 🤷🏻

2024-12-20 02:32 UTC, j-bowhay requested changes
Thanks, a few formatting niggles/ typos

2024-12-20 02:32 UTC, j-bowhay commented on scipy/sparse/_coo.py
> +        other : array_like (dense of sparse)
```suggestion
        other : array_like (dense or sparse)
```

2024-12-20 02:32 UTC, j-bowhay commented on scipy/sparse/_coo.py
> +        just for the rows fo the first times the columns of the second. It
```suggestion
        just for the rows of the first times the columns of the second. It
```

2024-12-20 02:32 UTC, j-bowhay commented on scipy/sparse/_coo.py
> +        producs is computed just like for matrix multiplication, only not
```suggestion
        products is computed just like for matrix multiplication, only not
```

2024-12-20 02:32 UTC, j-bowhay commented on scipy/sparse/_coo.py
> +        (components) over the axes specified by``a_axes`` and ``b_axes``.
```suggestion
        (components) over the axes specified by ``a_axes`` and ``b_axes``.
```

2024-12-20 04:34 UTC, dschult commented
Wow -- thanks for finding the typos... sorry for not spell-checking. :)

Looks like the failure is unrelated.

2024-12-20 18:39 UTC, j-bowhay approved these changes
Thanks!

2024-12-20 18:43 UTC, merged