ENH: Descending order of x in PPoly
scipy/scipy pull request #6315
Opened 2016-06-26 20:50 UTC by nmayorov

Hi!

Currently `PPoly` requires `x` to be in ascending order, which is typically sufficient. But if you computed coefficients for breakpoints in descending order (say integrated ODE back it time), then it will be awkward  to recompute coefficients to the required format (it's not very difficult, but not obvious). 

On the other hand, ascending and descending orders are not different at all from a mathematical point of view. So it required only few modifications to support both.

TODO: Handle `BPoly`.

@ev-br @pv please take a look.

2016-09-17 20:39 UTC, pv commented on scipy/interpolate/interpolate.py
> +    def extend(self, c, x):
Removing keyword is backward compat break. Maybe retain it, but change the default value to `None` and emit a DeprecationWarning if the user gives a value different from `None`.

2016-09-17 20:40 UTC, pv commented on scipy/interpolate/interpolate.py
> +    def extend(self, c, x):
Same comment as above Re: removing kwargs

2016-09-17 20:49 UTC, pv requested changes
Looks ok, modulo minor comments.

It indeed is probably best to retain the same definition for descending order in PPoly, even if the coefficients need a more complicated transform than just mirroring.

2016-09-18 17:28 UTC, nmayorov commented
@pv, appreciate that you checked. 

I restored `right=None` and added warnings. I used simple `warnings.warn`, because `DeprecationWarning` is not issued by the default.  

Also I didn't keep the previous substantial description, just said that it is deprecated and not used.

Right decisions?

2016-09-18 17:48 UTC, pv commented on scipy/interpolate/interpolate.py
> +    def extend(self, c, x, right):
right=None

2016-09-18 17:49 UTC, nmayorov commented on scipy/interpolate/interpolate.py
> +    def extend(self, c, x, right):
True...

2016-09-18 19:33 UTC, nmayorov commented
All fixed now. Tests are passing, but one configuration on travis failed to wget something.

2016-09-18 19:55 UTC, person142 commented
It looks like all of gnu.org is down.

2016-10-08 22:02 UTC, pv approved these changes

2016-10-08 22:02 UTC, merged