Added Breit-Wigner distribution
scipy/scipy pull request #6419
Opened 2016-07-27 06:36 UTC by innisfree

I've added the relativistic Breit-Wigner distribution to `scipy.stats`. The `_pdf` and `_cdf` are analytic; other attributes are numerical and provided by the inherited `rv_continuous` class.

As for the other distributions, I define a `breit_wigner_gen` class, and then a `breit_wigner` instance of that class, which should be imported by a user.

2016-07-27 07:58 UTC, innisfree commented
A few issues I need to fix:

1. ERROR: objects in scipy.stats.__all__ but not in refguide:: breit_wigner
2.  print 'number of continuous distributions:', len(dist_continu)

Expected:

    number of continuous distributions: 94

Got:

    number of continuous distributions: 95

3. All my doctests are broken (though work on my system)

2016-07-27 13:47 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +        """
Nitpick: There's no need to add a full-fledged docstring to a private, computational method. A simple comment would suffice IMO (and even then, the one-line code is self-documenting enough, I'd think)

2016-07-27 13:48 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +        """
Ditto, these docstrings will not be visible unless you look at the source code. Description of the physical parameters, `mass`, `width` and explanations should go to the class docstsring.

2016-07-27 13:52 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +        return cdf_
This is a direct transcription of the output of Wolfram Alpha, is it? :-).

I'm pretty sure the formulas can be simplified for real-valued mass and width.

2016-07-27 13:59 UTC, ev-br commented
First and foremost, my question about the use case (https://github.com/scipy/scipy/issues/6414) still stands.

On a technical level, this is a very good start!
Assuming there is a use case, this needs some work. See, e.g. https://github.com/scipy/scipy/pull/6030 about several places a distribution needs to be registered with (`__init__`, `_distr_param.py` etc).

2016-07-27 14:02 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +    """
Have a look at the docstrings of other distributions, they have magic substitution keys (compare to online docs, where the keys are expanded). I probably makes sense to reuse the standard format.

2016-07-27 14:02 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +    """
The docstring also needs a See Also section with a reference to `halfcauchy`.

2019-08-19 13:02 UTC, frederikfaye commented
Any news on this? Would love this feature!

2019-08-19 16:36 UTC, rgommers commented
The unanswered question is about whether `cauchy` is enough. From gh-6414:

_And indeed, as a function of the square of the 4-momentum, E^2, Breit-Wigner formula is almost a Cauchy distribution, the only difference being that the support of the distribution is [0, \inf], so it's a halfcauchy._

_Can you sketch a use case where a distribution of E^2 is not enough and you really need a distribution in terms of E itself?_

Once that's decided, this looks close to good to go.

2019-08-19 17:27 UTC, ev-br requested changes
a few minor comments (assuming that a use case is going to materialize).

2019-08-19 17:27 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +    >>> plt.show()
Explicit example largely duplicates the autogenerated. Suggest deduplicating.

2019-08-19 17:27 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +    cdf = Integrate[pdf, m]
This comment belongs to the comment of `_cdf`, should not be in the main docstring.

2019-08-19 17:27 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +    to a Dirac function. In the m -> 0 limit, the pdf vanishes.
Dirac delta function

2019-08-19 17:27 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +    pdf = k/((m^2 - mass^2)^2 + mass^4*alpha^2)
Most other distribution have TeX formulas here.

2019-08-19 17:27 UTC, ev-br commented on scipy/stats/_continuous_distns.py
> +        shape_ = -1j * np.arctan(arg_1) / (-1j + alpha_)**0.5 - np.arctan(arg_2) / (1j + alpha_)**0.5
I'm pretty sure this formula could be simplified further to avoid complex arithmetics.

2019-08-19 19:17 UTC, frederikfaye commented
> The unanswered question is about whether `cauchy` is enough.

I think it is, see https://github.com/scipy/scipy/issues/6414#issuecomment-522715954.

2019-08-20 04:13 UTC, andrewfowlie commented
I don't have time for this, sorry, but would happy to see it make it into scipy :)

2022-01-03 16:32 UTC, closed without merging