[DOC] Correct bounds for v in RectSphereBivariateSpline
scipy/scipy pull request #6612
Opened 2016-09-22 23:45 UTC by sriki18

This is a fix for #6556 . I changed the SciPy documentation to reflect the actual functionality of fftpack.

2016-09-23 03:14 UTC, person142 commented on scipy/interpolate/fitpack2.py
> +        Coordinates must be given in radians, and must lie within (-pi, pi).
This isn't quite right--the FITPACK documentation requires that

- ``-pi <= v[0] < pi``
- ``v[i] < v[i+1]`` (the strictly ascending bit)
- ``v[-1] <= v[0] + 2*pi``.

(Changed the indexing from the documentation for python conventions.) So for example in #6556 the example
```python
>>> u = np.linspace(1, 3)
>>> v = np.linspace(np.pi - 1e-6, 6)
>>> r = np.zeros([u.size, v.size])
>>> RectSphereBivariateSpline(u, v, r)
```
works fine even though 6 is not in the interval ``(-pi, pi)``.

2016-09-23 03:14 UTC, person142 requested changes

2016-10-03 04:42 UTC, person142 commented
@sriki18 I wonder if you're planning to continue to working on this? No pressure, just don't want it to slip into the mists of time.

2016-10-03 05:38 UTC, sriki18 commented
Hi, Sorry I didn't catch your earlier comment. I am going to have a busy week and will have a go at it if I find the time. I should definitely find time by Friday. If you would prefer to work on it in the mean time, please let me know. Thanks!

2016-10-03 12:53 UTC, person142 commented
Sounds great. No rush, just wanted to make sure you were still interested.

2016-10-08 17:14 UTC, sriki18 commented
Working on this at the moment.

2016-10-08 21:50 UTC, pv commented
superceded by #6665

2016-10-08 21:50 UTC, closed without merging