some style cleanup
scipy/scipy pull request #6717
Opened 2016-10-23 19:56 UTC by mherkazandjian

pip score increaby for this module from 3.67/10 to 4.43/10

2016-10-23 20:09 UTC, rgommers commented
LGTM. What is a pip score and how do you calculate it?

2016-10-23 20:11 UTC, mherkazandjian commented
i meant pylint. got confused, sorry.

2016-10-23 22:00 UTC, perimosocordiae requested changes
Looks mostly fine, see the inline comments.

The `NotImplementedError` changes are a little suspect. Are those part of a style guide somewhere?

2016-10-23 22:00 UTC, perimosocordiae commented on scipy/interpolate/interpolate.py
> +        Anti-derivativative is also the indefinite integral of the function,
Typo here

2016-10-23 22:00 UTC, perimosocordiae commented on scipy/interpolate/interpolate.py
> +        Anti-derivativative is also the indefinite integral of the function,
Typo

2016-10-23 22:00 UTC, perimosocordiae commented on scipy/interpolate/interpolate.py
> +            raise NotImplementedError("""""")
Is this really the correct usage according to pylint?

2016-10-23 22:10 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +            raise NotImplementedError("""""")
I think it is better to raise an instance of an exception rather than raise the exception class itself.

2016-10-24 00:55 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +        Anti-derivativative is also the indefinite integral of the function,
fixed

2016-10-24 00:58 UTC, WarrenWeckesser commented on scipy/interpolate/interpolate.py
> +            first derivative. If negative, the anti-derivative is returned.
There is nothing wrong with "antiderivative".

2016-10-24 00:59 UTC, MSeifert04 commented on scipy/interpolate/interpolate.py
> +            raise NotImplementedError("""""")
I think one uses `""` instead of multi-line `""""""`comments, especially if there is no message.

2016-10-24 01:00 UTC, WarrenWeckesser commented
Thanks for the clean up!  I haven't done a complete review; I'm just jumping in to say that "antiderivative" should not be changed to "anti-derivative".

2016-10-24 01:04 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +            raise NotImplementedError("""""")
haha, ok.

2016-10-24 01:07 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +            first derivative. If negative, the anti-derivative is returned.
reverted! i thought there should have been a hyphen :S

2016-10-24 01:08 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +            raise NotImplementedError("""""")
changed to ""

2016-10-24 06:52 UTC, ev-br commented on scipy/interpolate/interpolate.py
> +                            xi[i], len(y1), xi[i+1], len(y2), orders[i]))
Nit: better separate assembling the string into a variable (mesg = "..."), then raise ValueError(mesg)

2016-10-24 06:52 UTC, ev-br commented on scipy/interpolate/interpolate.py
> +                                                         np.complexfloating)):
If (a or b) --- better use implicit string continuation within brackets

2016-10-24 16:48 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +                            xi[i], len(y1), xi[i+1], len(y2), orders[i]))
done

2016-10-24 16:48 UTC, mherkazandjian commented on scipy/interpolate/interpolate.py
> +                                                         np.complexfloating)):
done

2016-10-29 22:48 UTC, rgommers commented
Actually, I'll just make the last revert and squash/push now. The ``NotImplementedError`` question isn't that relevant, because that's all dead code anyway. Will send a follow-up PR to remove that all.

2016-10-29 22:59 UTC, rgommers commented
Merged in fed1ae5, thanks @mherkazandjian, all.

2016-10-29 22:59 UTC, closed without merging

2016-10-29 23:08 UTC, rgommers commented
follow up in gh-6741