optimized Hessian calculation
scipy/scipy pull request #6724
Opened 2016-10-25 13:07 UTC by safooray

The previous code was in line-by-line agreement with the textbook but had double redundancy in memory consumption. By applying some linear algebra simplification we are now able to optimize models twice as large using BFGS.

2016-10-25 23:14 UTC, ev-br commented
Test failures seem real: there's something very fishy going on with dtypes.

2016-10-25 23:34 UTC, nmayorov requested changes

2016-10-25 23:34 UTC, nmayorov commented on scipy/optimize/optimize.py
> +        Hk += rhok * rhok * numpy.dot(yk, Z) * sk[:, numpy.newaxis] * sk[numpy.newaxis,:]
I don't understand where `rhok * sk[:, numpy.newaxis] * sk[numpy.newaxis, :]` part gone.

As for tests error: `Hk` is an identity matrix with `int` data type initially, so you can't subtract float in-place (easy to fix).

2017-03-16 11:39 UTC, nmayorov commented
Closed in favor of #7165

2017-03-16 11:39 UTC, closed without merging