Add lanczos window to the collection of existing windows
scipy/scipy pull request #6837
Opened 2016-12-07 17:44 UTC by serazing

I have added the Lanczos window in `scipy.signal.windows` following the definition of other windows. I have added documentation, references and tests for this window. The reason why I added this window is because it is widely used among the climate research community for time and space filtering.

2017-01-03 08:31 UTC, rgommers commented
Thanks @serazing, looks like a nice addition to me. There are a few PRs for new window functions open, so I'll send a message to the scipy-dev mailing list about those (that's where we decide on adding new functions).

2017-01-03 08:33 UTC, rgommers commented on scipy/signal/windows.py
> +    ('lanczos', 'lcz'): (lanczos, True),
I'd prefer to remove this. These additional spellings are present for backwards compatibility, but they're bad style so we shouldn't add new ones.

2017-01-03 12:27 UTC, serazing commented on scipy/signal/windows.py
> +    ('lanczos', 'lcz'): (lanczos, True),
That's fair enough, I did not know it was for backwards compatibility. I have removed the spelling 'lcz' in the latest commit.

2017-01-03 16:21 UTC, larsoner reviewed
Otherwise LGTM

2017-01-03 16:21 UTC, Eric89GXL commented on scipy/signal/tests/test_windows.py
> +        assert_allclose(signal.lanczos(6, False),
Can you add a small comment about where these hard-coded values come from (hand calculations, Octave, etc.)?

2017-01-06 04:59 UTC, rgommers commented
scipy-dev thread: https://mail.scipy.org/pipermail/scipy-dev/2017-January/021639.html

2019-06-19 13:53 UTC, larsoner commented
Thread now lives at https://mail.python.org/pipermail/scipy-dev/2017-January/021654.html

@serazing any interest in reviving this with the newer `scipy/signal/windows/` structure?

2019-06-24 04:27 UTC, serazing commented
I have to admit that I forgot to finalise this pull request. The newer `scipy/signal/windows/` structure is probably a good motivation to do it.

2019-08-07 18:55 UTC, pv requested changes
Docstring needs updating vs. `scipy.signal.windows` but otherwise lgtm I think.

2019-08-07 18:55 UTC, pv commented on scipy/signal/windows/windows.py
> +    >>> window = signal.lanczos(51)
`from scipy.signal.windows import lanczos`

2019-08-07 18:55 UTC, pv commented on scipy/signal/windows/windows.py
> +    .. math::  sinc(x) = \frac{\sin(\pi x)}{\pi x}
Empty line before and after `.. math::` needed I guess.

2019-08-07 19:00 UTC, peterbell10 commented on scipy/signal/windows/windows.py
> +    >>> from scipy.fftpack import fft, fftshift
```suggestion
    >>> from scipy.fft import fft, fftshift
```

2022-07-04 11:53 UTC, AtsushiSakai commented
I am trying to revive this PR in #16533.

2022-07-05 12:43 UTC, AtsushiSakai commented
@kimstik Thank you. I agree it should be symmetric. I will try to fix it in #16533.

2022-07-28 05:39 UTC, AtsushiSakai commented
This PR revived in #16533. So closing this. Thank you for your great PR. @serazing

2022-07-28 05:39 UTC, closed without merging