io/matlab/mio.py: handle objects supporting PEP 519
scipy/scipy pull request #6855
Opened 2016-12-13 19:23 UTC by mruffalo

We don't need to specifically check for a `__fspath__` attribute here, since
part of PEP 519 is enhancing `__builtins__.open` to support path-like objects.

The logic changes are quite small: first, try to read from whatever is given to
this function. If that succeeds, it's already a file-like object, and it's
returned as-is. If it's not readable, try passing it to `open`. If that
succeeds, return the new file-like object. If it fails with an `IOError`, check
for object type, append '.mat' if appropriate, and try calling `open` again.

If the user passes something nonsensical to `_open_file`, `open` will throw a
`TypeError`, which is a perfectly sane thing to do:

"""
Python 3.6.0rc1 (default, Dec  8 2016, 17:06:38)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open(object())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected str, bytes or os.PathLike object, not object
"""

(related issue: #6854)

2016-12-21 20:55 UTC, pv requested changes
Looks ok. Should have a test though with some object with `__fspath__` --- can be made conditional on Python version, cf scipy._lib._version.NumpyVersion.

2017-07-19 18:30 UTC, mruffalo commented
I just remembered that I had left this PR in limbo after submitting a similar one to PyTables. I added some test code that exercises a few I/O functions under Python 3.6, giving `pathlib.Path` objects to `savemat`, `loadmat`, `whosmat`, `readsav`, `hb_read`, and `hb_write`.

I'm not totally sure how to test `readsav` since I've never used IDL, so I settled on passing a nonexistent `Path` object to `readsav` and verifying that it throws a `FileNotFoundError` instead of (e.g.) a `TypeError`. This feels kind of weird, so I didn't do this anywhere else, though (at a glance) it looks like the following functions already support `Path` objects:
* `scipy.io.netcdf.netcdf_file`
* `scipy.io.wavfile.read`
* `scipy.io.wavfile.write`
* `scipy.io.arff.loadarff`

2017-07-19 19:17 UTC, merged

2017-07-19 19:17 UTC, pv commented
thanks, merged

2017-07-19 19:36 UTC, pv commented
ok, went a bit too fast --- gh-6855 for followup