ENH: gaussian_kde.logpdf with logsumexp
scipy/scipy pull request #6874
Opened 2016-12-21 16:50 UTC by evgenyzhurko

Solution for issue #6869 
Updated function for computing `gaussian_kde.logpdf` based on `scipy.misc.logsumexp`

2016-12-21 20:07 UTC, pv commented on scipy/stats/kde.py
> +                result = logsumexp(-energy, b=1/self._norm_factor)
This looks wrong.

2016-12-21 20:08 UTC, pv requested changes
Needs tests, all branches are not covered.
Cf https://codecov.io/gh/scipy/scipy/compare/c992cd6fa92db803770ae7fc477b610de2099877...a3414585549d631eba210d988f7ed21c7884f540

2016-12-21 20:08 UTC, pv commented on scipy/stats/kde.py
> +                result = logsumexp(-energy, b=1/self._norm_factor)
This looks wrong.

2016-12-23 00:33 UTC, ev-br requested changes

2016-12-23 00:33 UTC, ev-br commented on scipy/stats/kde.py
> +from scipy.misc import logsumexp
Not: from sciipy.special import logsumexp

2016-12-23 00:33 UTC, ev-br commented on scipy/stats/tests/test_kdeoth.py
> +    assert_almost_equal(logpdf, logpdf2, decimal=12)
assert_almost_equal(PDF, pdf2) or rename variables

2017-01-08 17:06 UTC, ev-br approved these changes

2017-01-08 17:28 UTC, merged