ENH: initial vector in minres
scipy/scipy pull request #6887
Opened 2016-12-25 18:43 UTC by evgenyzhurko

Fix #6843 
[`make_system`](https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/sparse/linalg/isolve/minres.py#L46) checks `x0` for `None`  [(here)](https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/sparse/linalg/isolve/utils.py#L107) and return `zeros` array (`x0 is None`) or given array(`x0 is not None`)
But i'm not sure that test is correct

2016-12-27 12:18 UTC, pv requested changes
I think the required change in the algorithm is somewhat more complex --- the initial `x0` given should not affect the final result, or the effective tolerances in use.

2016-12-27 12:18 UTC, pv commented on scipy/sparse/linalg/isolve/tests/test_minres.py
> +    assert_almost_equal(x1, x2)
This looks strange to me --- I'd expect the initial value to not affect the final result.
If you replace `minres` by eg. `gmres` the assert fails.

You'd expect `abs(a.dot(x) - b) < tol` for any `x0` provided.

2016-12-27 12:18 UTC, pv commented on scipy/sparse/linalg/isolve/minres.py
> -    x = zeros(n, dtype=xtype)
This is probably not sufficient, you likely also need to other changes to the algorithm.
In principle `b = b - matvec(x)` does almost the right thing, but it messes up the tolerance computations, so the change to the algorithm is likely more complex.

2017-08-20 15:01 UTC, adeak commented
It seems to me that now there are two stalled fix attempts to this problem, #7080 is the newer one. Should only one of them be kept, or is this OK like this?

2017-08-20 15:46 UTC, pv commented
Generally, the first PR that gets at a mergeable state will get in, and if there is no progress the PRs will remain stalled. Projects are not assigned to or reserved by anyone, so it is possible for anyone to pick them up, especially if stalled. This doesn't mean that you shouldn't coordinate with other people who are interested on working at the same topic --- you should, and it is usually not productive to try to "compete" --- but you are free to use common sense, esp. with long periods of inactivity. If you substantially build on someone else's work, you generally should preserve the original commits and authorship information.

2019-08-24 13:51 UTC, rgommers commented
A more complete approach in gh-10719. Unaddressed comments here for a couple of years, so closing. Thanks @evgenyzhurko

2019-08-24 13:51 UTC, closed without merging