Fix spsolve result's dtype for complex input
scipy/scipy pull request #6908
Opened 2016-12-31 11:10 UTC by jotasi

Complex input for either the matrix A or the vector b should give a complex vector as a result. Tests are added to ensure this. The fix is done in the fashion suggested by @perimosocordiae. This fixes #6901.

2017-01-01 19:25 UTC, perimosocordiae requested changes
Looks good. I just left a few style nitpicks.

2017-01-01 19:25 UTC, perimosocordiae commented on scipy/sparse/linalg/dsolve/linsolve.py
> +    resultDType = np.promote_types(A.dtype, b.dtype)
this should probably be `result_dtype`, to match the surrounding style

2017-01-01 19:25 UTC, perimosocordiae commented on scipy/sparse/linalg/dsolve/tests/test_linsolve.py
> +        bComplex = np.array([1,1,1]) + 1j*np.array([1,1,1])
same as above, these should be `A_real`, `A_complex`, `b_real`, `b_complex`

2017-01-01 20:39 UTC, jotasi commented
@perimosocordiae Oh yes, thanks you are obviously right. It's my first time contributing and apparently I am too used to camel code. I changed the style to match the surrounding code.

2017-01-02 17:55 UTC, perimosocordiae approved these changes

2017-01-02 17:56 UTC, perimosocordiae commented
Looks good to me. I'll wait a few days to let another maintainer have a look before merging.

2017-01-03 07:26 UTC, merged

2017-01-03 07:26 UTC, rgommers commented
LGTM too, merged. Thanks @jotasi, @perimosocordiae