Add random unitary matrices
scipy/scipy pull request #7027
Opened 2017-02-11 02:48 UTC by philipdeboer

2017-02-16 07:37 UTC, rgommers commented
Thanks @philipdeboer!

@lesshaste would be much appreciated if you reviewed this

2017-02-18 15:25 UTC, pv requested changes

2017-02-18 15:25 UTC, pv commented on scipy/stats/tests/test_multivariate.py
> +        # Overall this seems to be a necessary but weak test of the distribution.
You can do a real statistical test, `res = kstest(samples, uniform(0, 2*pi).cdf); assert_(res.pvalue > 0.05)`.

2017-02-18 15:25 UTC, pv commented on scipy/stats/tests/test_multivariate.py
> +        x = np.arctan(eigs.imag/eigs.real)
`np.arctan2(eigs.imag, eigs.real)`

2017-02-18 15:25 UTC, pv commented on scipy/stats/_multivariate.py
> +    TODO Update this
TODO

2017-02-18 15:25 UTC, pv commented on scipy/stats/_multivariate.py
> +        q = q*d
`q *= d`

2017-02-18 15:25 UTC, pv commented on scipy/stats/_multivariate.py
> +        d = d/abs(d)
`d /= abs(d)`

2017-02-18 15:25 UTC, pv commented on scipy/stats/tests/test_multivariate.py
> +            assert_array_almost_equal(np.dot(x, x.conj().T),
Prefer using  assert_allclose with explicitly specified atol.

2017-02-19 22:22 UTC, lesshaste commented on scipy/stats/tests/test_multivariate.py
> +        # Overall this seems to be a necessary but weak test of the distribution.
Won't that fail one in twenty times?

2017-02-19 22:59 UTC, pv commented on scipy/stats/tests/test_multivariate.py
> +        # Overall this seems to be a necessary but weak test of the distribution.
Fixed random seed. Of course, the p-threshold can be made smaller.

2017-02-19 23:12 UTC, philipdeboer commented
Thanks for your feedback; I hope to get to this later this week.
Sent from my BlackBerry device on the Rogers Wireless Network

-----Original Message-----
From: Pauli Virtanen <notifications@github.com>
Date: Sun, 19 Feb 2017 14:59:07 
To: scipy/scipy<scipy@noreply.github.com>
Reply-To: scipy/scipy <reply@reply.github.com>
Cc: philipdeboer<philip.deboer@gmail.com>; Mention<mention@noreply.github.com>
Subject: Re: [scipy/scipy] Add random unitary matrices (#7027)

pv commented on this pull request.



> +        # the complex plane, are uncorrelated.
+
+        # Generate samples
+        dim = 2
+        samples = 10000  # Not too many, or the test takes too long
+        np.random.seed(514)  # Note that the test is sensitive to seed too
+        xs = unitary_group.rvs(dim, size=samples)
+
+        eigs = np.vstack(scipy.linalg.eigvals(x) for x in xs)
+        x = np.arctan(eigs.imag/eigs.real)
+
+        h = np.histogram(x.flatten())[0]
+
+        # The angles "x" of the eigenvalues should be uniformly distributed
+        # We are not checking that the range is correct; maybe we should?
+        # Overall this seems to be a necessary but weak test of the distribution.

Fixed random seed. Of course, the p-threshold can be made smaller.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/scipy/scipy/pull/7027#discussion_r101931563

2017-02-25 01:16 UTC, philipdeboer commented
The uniform cdf confused me for a bit. I expected to be able to use uniform(-pi, pi).cdf, but that did not work. Is that a bug in uniform that I should fix? I had to "manually" shift the range to match my data. I guess I could have shifted my data...ah well.

2017-02-25 23:35 UTC, rkern commented
You want a uniform distribution over the range `[-pi, +pi]`? The right syntax is `uniform(-pi, 2*pi)`. Like all of the distributions, `uniform()` takes a `loc` and `scale` parameter, so that's `uniform(loc=-pi, scale=2*pi)`. The two arguments are not the endpoints of the support.

2017-02-26 12:47 UTC, pv commented on scipy/stats/tests/test_multivariate.py
> +        assert_(res.pvalue > 0.8)
This maybe should be smaller threshold, `0.05` is one false rejection in 1/20, `0.01` 1/100, etc.
Although the larger value works for the particular seed above, the value probably should be smaller.

2017-03-26 12:09 UTC, merged