Improved doc string for hyp2f1
scipy/scipy pull request #7033
Opened 2017-02-12 07:36 UTC by ashwinpathak20

I have changed the doc string of hyp2f1 function and included all the necessary details. Issue #6966

2017-02-12 15:08 UTC, person142 requested changes
Note that you need to run `generate_ufuncs.py` for these changes to actually show up in the published docs (as was mentioned in the mailing list, run it and commit the changes in a separate commit).

2017-02-12 15:08 UTC, person142 commented on scipy/special/add_newdocs.py
>      Gauss hypergeometric function 2F1(a, b; c; z).
Format here should be a short definition (that part is fine) followed by a longer definition. The series definition in the notes should be moved here to be the longer definition. See e.g. https://scipy.github.io/devdocs/generated/scipy.special.eval_jacobi.html#scipy.special.eval_jacobi.

2017-02-12 15:08 UTC, person142 commented on scipy/special/add_newdocs.py
> +        y being the solution to the second-order linear ordinary differential equation.
You haven't told the user that this function satisfies a second-order linear equation, so this isn't a good way to go. Just say something like "values of the Gaussian hypergeometric function".

2017-02-12 15:08 UTC, person142 commented on scipy/special/add_newdocs.py
> +        \mathrm{hyp2f1}(a, b, c, z) = 1 + \sum_{k=0}^inf. \frac {{{a+k}\choose{a}} {{b+k}}\choose{b}}}{{c+k}\choose{c}} z^(k+1).
Move to above, as noted in earlier comment.

2017-02-12 15:08 UTC, person142 commented on scipy/special/add_newdocs.py
> +    hyp1f1 , hyp0f1.
Format needs to be different here; see `eval_jacobi` example linked above.

2017-02-12 15:09 UTC, person142 commented on scipy/special/add_newdocs.py
> +    Cases addressed are
While I am pro discussing the algorithm in the notes, you need more description here for the user to be able to understand what's happening. In particular links to the DLMF (http://dlmf.nist.gov/) are very helpful. Also this appears to only discuss what happens for the real case.

2017-02-12 16:39 UTC, ashwinpathak20 commented on scipy/signal/_peak_finding.py
> +        Default is widths[0].
i am really sorry, i didn't realise that this was also included.

2017-02-12 16:45 UTC, ashwinpathak20 commented on scipy/signal/_peak_finding.py
> +        Default is widths[0].
Also, how do I know that I have run generate_ufuncs.py correctly?

2017-02-12 19:09 UTC, person142 commented on scipy/special/add_newdocs.py
> +    hyp0f1 : confluent hypergeometric function.
`hyp0f1` is the confluent hypergeometric *limit* function.

2017-02-12 19:10 UTC, person142 commented on scipy/special/add_newdocs.py
> +      a,b,c or z can take up complex values too.
`a`, `b`, and `c` cannot take complex values, only `z` can.

2017-02-12 19:11 UTC, person142 commented on scipy/special/add_newdocs.py
> +    Gaussian function is defined on the disk |z|<1, and by analytic continuation elsewhere.
The Gaussian function is `e^(-x**2)`. Should be Gaussian hypergeometric function.

2017-02-12 19:11 UTC, person142 commented on scipy/special/add_newdocs.py
> +        y being the values of the gaussian hypergeometric function.
Just "values of the Gaussian hypergeometric function"

2017-02-12 19:12 UTC, person142 commented on scipy/special/add_newdocs.py
> +      a,b,c or z can take up complex values too.
Also what can or cannot take complex values should be specified in the parameters section.

2017-02-12 19:14 UTC, person142 commented on scipy/special/add_newdocs.py
> +    \mathrm{hyp2f1}(a, b, c, z) = 1 + \sum_{k=0}^inf. \frac {{{a+k}\choose{a}} {{b+k}}\choose{b}}}{{c+k}\choose{c}} z^(k+1).
Make this a complete sentence. Something like "The Gaussian hypergeometric function is defined as...". Also I wouldn't use binomial coefficients here, the Pochhammer symbol is more appropriate.

2017-02-12 19:14 UTC, person142 commented on scipy/special/add_newdocs.py
> +    z : array_like
"real or complex array_like", similar for the others.

2017-02-12 19:14 UTC, person142 commented on scipy/special/add_newdocs.py
> +        Parameter
This is the argument, not a parameter.

2017-02-12 19:15 UTC, person142 commented on scipy/special/add_newdocs.py
> +    \mathrm{hyp2f1}(a, b, c, z) = 1 + \sum_{k=0}^inf. \frac {{{a+k}\choose{a}} {{b+k}}\choose{b}}}{{c+k}\choose{c}} z^(k+1).
Also you want to mention the analytic continuation and branch cut here as they are part of the definition of the function.

2017-02-12 19:20 UTC, person142 commented
Changes in `_ufuncs_cxx.pxd ` etc. shouldn't be here. Guessing it's because of the merge commits; instead of merging in the master branch you should rebase on it.

2017-02-13 16:14 UTC, ashwinpathak20 commented
@person142  I am not able to understand why my code is not able to pass the checks , can you please help me out here?

2017-02-13 16:59 UTC, ev-br commented
You can click through the CI status to see the test log: *Docstring contains a non-printable character '\x0c'! Maybe forgot r"""?*

2017-02-13 20:05 UTC, ashwinpathak20 commented
I did include r at the starting , after defining the function in add_newdocs.py but still the same result.

2017-02-13 21:09 UTC, person142 commented
There are at least a couple more errors, e.g. not all of the math is in math mode.

2017-02-13 21:21 UTC, ashwinpathak20 commented
Is that the reason of not passing the checks or the math code is incorrect according to the hyp2f1?

2017-02-16 01:20 UTC, person142 commented
Let's try to get this sorted out. The erroneous +13,737 LOC and large number of commits is making review a bit of a pain, so we'll start there. Some things for the future:

- It looks like you did your development on master; it's better to do it on a topic branch.
- Don't merge the master branch to resolve conflicts--instead rebase on master (`git rebase`).

Probably the easiest way to fix this now is to:

- Rename this branch to something else (`git branch -m <oldbranch> <newbranch>`). Let's call it `hyp2f1-doc` for concreteness.
- Grab a new copy of the master branch from the main SciPy repo so that you have a clean master again.
- Rebase `hyp2f1-doc` on the clean master with `git rebase -i master hyp2f1-doc`. Drop every commit that isn't modifying `add_newdocs.py`, and squash all of the commits modifying `add_newdocs.py`. Also modify the commit message to be formatted according to https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message.
- There should now be one commit that only modifies `add_newdocs.py`. Go run `generate_ufuncs.py` and commit the changes with the message `GEN: run generate_ufuncs.py`.
- Push the changes, force pushing (`git push -f`) is fine.

2017-02-16 14:30 UTC, ashwinpathak20 commented
When i did rebasing of the branch , in the interactive mode, there was noop present rather then the commits, so I was not able to squash the commits.

2017-02-16 14:57 UTC, person142 commented
Please don't push more changes until this is sorted out; it is making the situation worse.

> When i did rebasing of the branch , in the interactive mode, there was noop present rather then the commits

I am not sure what you mean here. When you run `git rebase -i` it opens a text editor which shows the commits you have added since your topic branch diverged from master. Did you create a new topic branch as instructed?

2017-02-16 15:10 UTC, ashwinpathak20 commented
yes i followed the same steps.... can i make a new pull request instead?

2017-02-16 18:43 UTC, person142 commented
> can i make a new pull request instead?

Sure. Just be careful of the points mentioned above.

2017-02-16 21:22 UTC, ashwinpathak20 commented
I am really sorry for the last commits , please ignore them

2017-02-16 21:24 UTC, closed without merging