ENH: sparse: allow subclasses to override specific math operations
scipy/scipy pull request #7079
Opened 2017-02-21 20:46 UTC by perimosocordiae

New methods `_(add/sub)_sparse` and `_(add/sub/rsub)_dense` allow spmatrix to handle the boilerplate delegation code of `__add__` and `__sub__`, and make it easy for subclasses to provide optimized implementations.

As an example, `coo_matrix._add_dense` can avoid densification, which results in a reasonably large speedup (depending on matrix size and density). The old situation for `coo + dense` was especially bad because it expanded to `coo -> csr -> coo -> dense`.

2017-02-26 14:36 UTC, pv requested changes
I guess it's mostly fine, but needs to decide where to put broadcasting/shape compatibility checks, and then put them there. E.g. does `_binopt` do them?

2017-02-26 14:36 UTC, pv commented on scipy/sparse/coo.py
> +                    result.ravel('A'), fortran)
Does this do bounds checks?

2017-02-26 14:36 UTC, pv commented on scipy/sparse/coo.py
> +        result = np.array(other, dtype=dtype, copy=True)
This needs a shape compatibility check.

2017-02-26 14:36 UTC, pv commented on scipy/sparse/base.py
> +            return self._rsub_dense(other)
Does it need to do a shape check here? Do we support broadcasting anywhere?

2017-02-27 21:05 UTC, perimosocordiae commented
I've added checks for shape compatibility, along with tests to make sure we can do simple broadcasting.

2017-03-12 10:54 UTC, pv approved these changes

2017-03-12 10:54 UTC, merged