DOC: stats: Added tutorial documentation for the generalized normal distribution. #7171
scipy/scipy pull request #7200
Opened 2017-03-19 20:38 UTC by DominicAntonacci

This is my first pull request, so let me know if there's anything that needs to be improved/fixed.

2017-03-26 15:33 UTC, WarrenWeckesser requested changes
This is great, thanks!  I requested one change in-line.

The only other suggestion is that you follow the conventions for commit messages used by scipy and numpy described in https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message (admittedly, that can be hard to find for a new contributor).  Specifically, commit messages that are updates to the documentation (e.g. docstrings and tutorials) should have the prefix `DOC:`, just like the heading of this pull request.

2017-03-26 15:33 UTC, WarrenWeckesser commented on doc/source/tutorial/stats/continuous_gennorm.rst
> +    \mu_2 & = &  \mu_2  =  \frac{\Gamma\left(3/\beta\right)}{\gamma\left(1/\beta\right)} \\
You have `\mu_2` twice.  This should be just `\mu_2 & = & \frac{\Gamma ...`

2017-03-27 20:35 UTC, WarrenWeckesser commented on doc/source/tutorial/stats/continuous_gennorm.rst
> +    \begin{eqnarray*} f\left(x\right) & = &\frac{\beta}{2\Gamma(1/\beta)} e^{-\left|x\right|^{\beta}} \end{eqnarray*}
Here and elsewhere: the convention for specifying the funtion arguments is to include the parameter, separated from x with a semicolon.  E.g. `f\left(x; \beta \right) & = & ...`.

2017-03-27 20:36 UTC, WarrenWeckesser commented
I just commented in-line about one more detail that should be fixed.

2017-04-04 23:45 UTC, DominicAntonacci commented
Sorry about the delay on that! Should be ready to go.

2017-04-19 15:20 UTC, merged

2017-04-19 15:20 UTC, WarrenWeckesser commented
Thanks, Dominic.  Merged.