FIX 7262: ckdtree crashes in query_knn.
scipy/scipy pull request #7266
Opened 2017-04-05 22:29 UTC by rainwoodman

This was because a loosen check on j >= 0 in the branches. The loop
was not carefully written. It has been replaced with a version that
is easier to understand.

Also added the docstring warning that if k is not sorted the result
is undefined. We can worry about adding a sorting wrapper in cython
later if there is a demand.

This fixes #7262

2017-04-05 22:57 UTC, sturlamolden commented
I am not sure I understand the purpose of all these checks. In the original code that @aarchiba  and I wrote we had this:
```C++
/* fill output arrays with sorted neighbors */
    for (i=neighbors.n-1; i>=0; --i) {
        neighbor = neighbors.pop();
        result_indices[i] = neighbor.contents.intdata;
        if (NPY_LIKELY(p == 2.0))
            result_distances[i] = std::sqrt(-neighbor.priority);
        else if ((p == 1.) || (p == infinity))
            result_distances[i] = -neighbor.priority;
        else
            result_distances[i] = std::pow((-neighbor.priority),(1./p));
    }
```
The heap is already sorted, so we just needed to pop them off. What has changed?

2017-04-05 23:43 UTC, sturlamolden commented
Why not do something like this? 

It should also avoid undefined results if the list ```k``` of neighbor indices is unsorted.

```C++
    /* heapsort */
    std::vector<heapitem> sorted_neighbors(kmax);
    npy_intp j = 0; 
    for(i = neighbors.n - 1; i >=0; --i) {
        sorted_neighbors[j++] = neighbors.pop();
    }
    
    /* fill output arrays with sorted neighbors */
    for (i = 0; i < nk; ++i) {
        neighbor = sorted_neighbors[k[i] - 1];
        result_indices[i] = neighbor.contents.intdata;
        if (NPY_LIKELY(p == 2.0))
            result_distances[i] = std::sqrt(-neighbor.priority);
        else if ((p == 1.) || (ckdtree_isinf(p)))
            result_distances[i] = -neighbor.priority;
        else
            result_distances[i] = std::pow((-neighbor.priority),(1./p));
    }
```

2017-04-06 00:04 UTC, rainwoodman commented
Yes. It is cleaner. We still want to check if `k[i]` is greater than `neighbours.n`. The current undefined values are defined in cython. Shall we move them here?

2017-04-06 00:38 UTC, rainwoodman commented
Shall I run valgrind on the entire test suite?

2017-04-06 00:39 UTC, sturlamolden commented
Something like this?
```
    /* heapsort */
    std::vector<heapitem> sorted_neighbors;
    sorted_neighbors.reserve(kmax)
    for(i = neighbors.n - 1; i >=0; --i) {
        sorted_neighbors.push_back(neighbors.pop());
    }
    
    /* fill output arrays with sorted neighbors */
    for (i = 0; i < nk; ++i) {
        const npy_intp j = k[i];
        if (j > sorted_neighbors.size()) continue; /* missing neighbor */
        neighbor = sorted_neighbors[j - 1];
        result_indices[i] = neighbor.contents.intdata;
        if (NPY_LIKELY(p == 2.0))
            result_distances[i] = std::sqrt(-neighbor.priority);
        else if ((p == 1.) || (ckdtree_isinf(p)))
            result_distances[i] = -neighbor.priority;
        else
            result_distances[i] = std::pow((-neighbor.priority),(1./p));
    }
```

2017-04-06 00:45 UTC, sturlamolden commented
The "missing neighbor" values are prefilled in Cython, so we can just ignore them in C++ I guess.

2017-04-08 21:48 UTC, rainwoodman commented
Well I moved the handling to C++, since we have to do a branching there anyways.

2017-04-18 10:03 UTC, rgommers commented
Wasn't clear to me from reading gh-7262 if this needs a backport to 0.19.x?

2017-04-18 10:39 UTC, sturlamolden commented
Judging from the code, the bug is in 0.19.x as well. It was the introduction of a list of ```k``` values that did this.

@rainwoodman needs to address my two comments before this can be merged. I.e. remove the typo line from the docstring and add an ``NPY_UNLIKELY``` at the final branch.

2017-04-18 10:41 UTC, sturlamolden commented
@rgommers Change the label to defect. This is a bug.

2017-04-18 10:59 UTC, sturlamolden requested changes

2017-04-18 10:59 UTC, sturlamolden commented on scipy/spatial/ckdtree/src/query.cxx
> +        if(k[i] - 1 >= nnb) {
@rainwoodman can you add this please?

2017-04-18 20:21 UTC, sturlamolden commented
Looks good. Time to merge and backport?

2017-04-18 22:31 UTC, rainwoodman commented
Yes. I am all in to get this bug fixed sooner than later since I introduced it. 

Valgrind was green on my computer. 

Is it possible set up a valgrind test on travis to catch this sort of bugs? We can focus on the modules that are mostly written in C/C++ to speed it up.

2017-04-19 11:32 UTC, rgommers commented
> Looks good. Time to merge and backport?

Allright, in it goes. Thanks @rainwoodman, @sturlamolden 

> Change the label to defect. This is a bug.

This is the regular labeling - the issue gets labelled "defect" and the PR "maintenance".

Added the backport label as well. Will get onto that soon.

2017-04-19 11:32 UTC, merged