DOC: Add example to stats.normaltest
scipy/scipy pull request #7275
Opened 2017-04-07 10:22 UTC by MartinThoma

2017-04-17 20:49 UTC, WarrenWeckesser requested changes
Thanks for the example!  I've made some suggestions in-line.

2017-04-17 20:49 UTC, WarrenWeckesser commented on scipy/stats/stats.py
> +    >>> import scipy.stats as stats
`from scipy import stats` is simpler. (["Don't repeat yourself"](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself); why write `stats` twice?)

2017-04-17 20:49 UTC, WarrenWeckesser commented on scipy/stats/stats.py
> +    >>> a = np.random.multivariate_normal([0], [[1]], size=pts)
This uses `np.random.multivariate_normal()`, but it generates a one-dimensional sample, so you might as well use `np.random.normal(0, 1, size=pts)` instead.  (The same comment applies to the next line.)

2017-04-17 20:49 UTC, WarrenWeckesser commented on scipy/stats/stats.py
> +    >>> alpha = 10**-3
It would be more conventional to write this as `alpha = 1e-3`.

2017-04-17 20:49 UTC, WarrenWeckesser commented on scipy/stats/stats.py
> +    >>> k2, p = stats.normaltest(x)
In addition to the test below, I'd like to see the p-value.  How about adding `print(p)` after this?

2017-04-17 20:54 UTC, MartinThoma commented on scipy/stats/stats.py
> +    >>> k2, p = stats.normaltest(x)
`print(p)` is a problem due to doctests as the value differs between runs

2017-04-17 21:00 UTC, WarrenWeckesser commented on scipy/stats/stats.py
> +    >>> k2, p = stats.normaltest(x)
One way to avoid that is to set the random seed with, say, `np.random.seed(123)` before generating the random samples.

2017-04-17 21:59 UTC, WarrenWeckesser commented on scipy/stats/stats.py
> +    >>> k2, p = stats.normaltest(x)
I see that you added a call to set the seed.  Were you also going to add `print(p)`?

2017-04-17 22:05 UTC, MartinThoma commented
I print p in line 1408

On Apr 18, 2017 00:00, "Warren Weckesser" <notifications@github.com> wrote:

> *@WarrenWeckesser* commented on this pull request.
> ------------------------------
>
> In scipy/stats/stats.py
> <https://github.com/scipy/scipy/pull/7275#discussion_r111831624>:
>
> > @@ -1394,6 +1394,20 @@ def normaltest(a, axis=0, nan_policy='propagate'):
>      .. [2] D'Agostino, R. and Pearson, E. S. (1973), "Tests for departure from
>             normality", Biometrika, 60, 613-622
>
> +    Examples
> +    --------
> +    >>> import scipy.stats as stats
> +    >>> pts = 1000
> +    >>> a = np.random.multivariate_normal([0], [[1]], size=pts)
> +    >>> b = np.random.multivariate_normal([2], [[1]], size=pts)
> +    >>> x = np.concatenate((a, b))
> +    >>> k2, p = stats.normaltest(x)
>
> I see that you added a call to set the seed. Were you also going to add
> print(p)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy/scipy/pull/7275#discussion_r111831624>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABlNBV_Rj8mTNSfdnPWvAREG1w2DsiWsks5rw-DigaJpZM4M2uP_>
> .
>

2017-04-17 22:19 UTC, WarrenWeckesser commented
> I print p in line 1408

Ah, sorry I missed that.  But that only shows `p` in one of the cases, and with that formatting, it shows all zeros.  As an example of `normaltest()`, I think it would be (slightly!) better to show the actual value of `p` in either case.  How about `print("p = {:g}".format(p))` or `print("p = %g" % p)` before the `if` statement?

2017-04-18 14:08 UTC, WarrenWeckesser approved these changes

2017-04-18 14:36 UTC, merged

2017-04-18 14:37 UTC, WarrenWeckesser commented
Thanks @MartinThoma, merged.