ENH: add n-dimensional DCT and IDCT to fftpack
scipy/scipy pull request #7337
Opened 2017-04-25 19:53 UTC by grlee77

I recently needed an n-dimensional `dct` and `idct`.  This PR adds these.  

The implementation is trivial, as the existing 1D routines already had `axis` support, but I thought it may still be worth providing.

Unlike for the n-dimensional FFT routines, there is no underlying n-d implementation in the `fftpack` Fortran code.  This does not seem to be a big problem in terms of performance.  As is, it is similar or faster than `fftn` for real-valued inputs and a bit slower for complex-valued ones:

potential updates:

- [ ] add `dstn` and `idstn` as well?
- [ ] raise an error if duplicate axes are provided?

results from some quick speed tests in IPython:

```python
for shape in [(16, 16), (256, 256, 256)]:
    for dtype in np.float32, np.complex64:
        r = np.ones(shape, dtype)
        print("\n---------------------------")
        print("dctn for dtype {}, shape {}".format(dtype, shape))
        %timeit scipy.fftpack.dctn(r)
        print("\nfftn for dtype {}, shape {}".format(dtype, shape))
        %timeit scipy.fftpack.fftn(r)
```

```
---------------------------
dctn for dtype <class 'numpy.float32'>, shape (16, 16)
The slowest run took 4.43 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 60.2 µs per loop

fftn for dtype <class 'numpy.float32'>, shape (16, 16)
The slowest run took 9.49 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 69.5 µs per loop

---------------------------
dctn for dtype <class 'numpy.complex64'>, shape (16, 16)
10000 loops, best of 3: 131 µs per loop

fftn for dtype <class 'numpy.complex64'>, shape (16, 16)
10000 loops, best of 3: 67.3 µs per loop

---------------------------
dctn for dtype <class 'numpy.float32'>, shape (256, 256, 256)
1 loop, best of 3: 841 ms per loop

fftn for dtype <class 'numpy.float32'>, shape (256, 256, 256)
1 loop, best of 3: 1.43 s per loop

---------------------------
dctn for dtype <class 'numpy.complex64'>, shape (256, 256, 256)
1 loop, best of 3: 2.13 s per loop

fftn for dtype <class 'numpy.complex64'>, shape (256, 256, 256)
1 loop, best of 3: 1.49 s per loop
```

2017-05-03 19:03 UTC, grlee77 commented
Reduced the precision slightly in the tests to fix the Travis test failures.

2017-08-20 08:07 UTC, rgommers commented
@grlee77 thanks! This fell through the review cracks, but would be good to get it merged in the near future. Would you mind rebasing?

For your potential updates I'd say yes 2x.

2017-08-22 10:36 UTC, rgommers requested changes
This all looks good to me, only a couple of minor comments.

2017-08-22 10:36 UTC, rgommers commented on scipy/fftpack/__init__.py
> +   idctn - n-dimensional Inverse discrete cosine transform
missing ``dstn``, ``idstn`` here and in ``__all__.extend`` below

2017-08-22 10:36 UTC, rgommers commented on scipy/fftpack/realtransforms.py
> +    Return multidimensional Discrete Cosine Transform of x along the specified
maybe remove "of x" and make this fit on one line

2017-08-22 10:36 UTC, rgommers commented on scipy/fftpack/realtransforms.py
> +    Return multidimensional Discrete Cosine Transform of x along the specified
applies to all added functions

2017-08-22 10:36 UTC, rgommers commented on scipy/fftpack/tests/test_real_transforms.py
> +                           assert_raises)
This is just being fixed in gh-7777, so better ``from pytest import raises as assert_raises``

2017-08-22 14:53 UTC, grlee77 commented
Thanks for the review @rgommers.  let me know if you want me to squash the commits

2017-08-22 19:02 UTC, rgommers commented on scipy/fftpack/realtransforms.py
> +    >>> np.allclose(y, idstn(dctn(y, norm='ortho'), norm='ortho'))
Here ``dctn`` should be ``dstn``. That will fix the doctest failure.

2017-08-22 19:03 UTC, rgommers commented
you can squash if you prefer, but 12 commits is not excessive from my point of view

2017-08-23 03:09 UTC, grlee77 commented
okay, should be good to go now

2017-08-23 04:39 UTC, rgommers approved these changes

2017-08-23 04:40 UTC, merged

2017-08-23 04:40 UTC, rgommers commented
In it goes, thanks @grlee77!