BUG: fixed norm in optimize.root
scipy/scipy pull request #7385
Opened 2017-05-06 22:24 UTC by tyler-abbot

Previously when calling `optimize.root` and using the `disp` and `tol_norm` options, the displayed norm was not the same as the actual norm being used. The below code produces the desired error:

```
import numpy as np
from scipy.optimize import root

def f(x):
    return (x - np.array((-1.0, 2.0)))**3

x = np.linspace(-3, 3, 100)
x = np.outer(x, np.ones((2)))

res = root(f, np.array((1.0, 1.0)), method='krylov',
           options={'disp': True, 'ftol': 0.1, 'tol_norm': lambda x: np.absolute(x).min()})
```

This resolves #7384.

2017-05-07 13:32 UTC, pv requested changes
This adds a bunch of miscellaneous files that should not be added. 
Also, this changes the inexact newton tolerance control norm, which probably is not correct, as the intent apparently is only to change what is printed.

2017-05-07 13:32 UTC, pv commented on scipy/optimize/nonlin.py
> +        norm = maxnorm
This looks wrong, iirc 2-norm should be used for newton step length choice.

2017-05-07 13:32 UTC, pv commented on _configtest.o.d
> +commandline: -I/home/tmabbot/anaconda3/include/python3.5m -c-I/home/tmabbot/anaconda3/include/python3.5m
All these miscellaneous files should not be added.

2017-05-07 14:01 UTC, pv commented on _configtest.o.d
> +commandline: -I/home/tmabbot/anaconda3/include/python3.5m -c-I/home/tmabbot/anaconda3/include/python3.5m
I don't know what sort of development setup you use, but I'd guess this is not the usual way to do it, so I can't offer advice. In any case, you shouldn't include these files in the PR.

2017-06-05 21:16 UTC, cdouglass commented on _configtest.o.d
> +commandline: -I/home/tmabbot/anaconda3/include/python3.5m -c-I/home/tmabbot/anaconda3/include/python3.5m
@tyler-abbot You can configure Git to ignore certain files or directories by name. If you add the line `scipy_env/` in your global gitignore file (which you might need to create), Git will pretend the directory `scipy_env`, and everything in it, does not exist. It's really common to do this for files that are automatically generated or that may vary between systems, such as Python environment stuff or compiled code.

Instructions: http://islegend.com/development/setting-global-gitignore-mac-windows/
Official documentation for this feature (way more info than you need): https://git-scm.com/docs/gitignore

To get these files out of your PR without changing your environment, you can use `git rm --cached` on the directory and then amend your original commit: https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

2018-07-14 18:57 UTC, vyasr commented
@rgommers This pull request has identified a problem but the fix isn't quite right. Currently it's changing the behavior of the line search itself, but we should only be changing the norm for the tolerance check. In addition to the original bug reported, the current value printed for the "tol" is also not meaningful. I will make a separate PR to fix both of these, and you can close this PR.

2018-07-14 20:56 UTC, rgommers commented
Great, thanks @vyasr. And thanks @tyler-abbot for pointing out that there's a problem here.

2018-07-14 20:56 UTC, closed without merging