Fix docs of the minimize function
scipy/scipy pull request #7412
Opened 2017-05-17 10:30 UTC by killthekitten

To avoid confusion when using with objective functions of more than one variable.

2017-05-17 13:11 UTC, larsoner reviewed
Can you make the changes PEP8 compliant (< 80 char)?

2017-05-17 13:11 UTC, Eric89GXL commented on scipy/optimize/_minimize.py
> +        Objective function. Takes a vector of variables as it's only argument, i.e. it is going to be a vector
it's -> its

2017-05-17 13:11 UTC, Eric89GXL commented on scipy/optimize/_minimize.py
> +        of size 2 if the objective function takes 2 arguments. You can find the examples below.
Usually we just say "See examples below."

2017-05-17 13:25 UTC, killthekitten commented
@Eric89GXL 👍 done.

2017-05-17 18:50 UTC, Eric89GXL commented
LGTM but I'll let one of the optimize folks merge

2017-05-17 23:44 UTC, andyfaff requested changes

2017-05-17 23:44 UTC, andyfaff commented on scipy/optimize/_minimize.py
> +        Objective function. Takes a vector of variables as its only argument,
My version is more precise. Also, `fun` accepts additional arguments, specified by `args`.

2017-05-17 23:44 UTC, andyfaff commented on scipy/optimize/_minimize.py
> +        Initial guess. Number of items in `x0` corresponds to the number of
Initial guess. ``len(x0)`` is the dimensionality of the minimization problem.

2017-05-18 10:32 UTC, killthekitten commented
@andyfaff this way looks much better, thank you.

2017-05-18 21:58 UTC, andyfaff commented
@killthekitten it would be great if you could modify your PR to include the changes I suggested.

2017-05-18 22:29 UTC, killthekitten commented
@andyfaff but I've included them already :)

2017-05-19 08:09 UTC, andyfaff commented
Test failure is unrelated to this PR (sparse matrices). Restarted build to see if the tests pass this time.

2017-05-19 16:53 UTC, killthekitten commented
@andyfaff didn't help. I've rebased it from master, let's see again.

2017-05-26 11:57 UTC, killthekitten commented
@andyfaff seems safe to merge.

2017-05-26 12:28 UTC, andyfaff approved these changes

2017-05-26 12:29 UTC, merged