Fix several issues in sparse.load_npz, save_npz
scipy/scipy pull request #7419
Opened 2017-05-19 19:30 UTC by pv

Fix several issues in sparse.load_npz, save_npz:

- Make loading files from unknown origin safe (for new enough numpy), disallowing pickle.
- Close the opened files properly in `load_npz` (don't rely on gc).
- Fix up bytes vs. unicode confusion on Python 3, and make the files Python 2 to 3 portable

Fixes gh-7418 (we don't rely any more on Numpy's formatting of bytes scalars in unicode strings)

2017-05-19 19:44 UTC, eric-wieser commented on scipy/sparse/_matrix_io.py
> +            matrix_format = matrix_format.decode('ascii')
Doesn't this call `unicode.decode` (aka `bytes.decode(unicode.encode(...))` on python 2? `u'café'.decode('ascii')` causes a `UnicodeEncoderError`, which doesn't seem sensible.

What case is this trying to cover?

2017-05-19 19:45 UTC, eric-wieser commented on scipy/sparse/_matrix_io.py
> +        matrix_format = matrix_format.item()
I'd argue that this line shouldn't be necessary, and actually is a regression in numpy master

2017-05-19 19:47 UTC, eric-wieser commented on scipy/sparse/_matrix_io.py
> +        matrix_format = matrix_format.item()
Never mind, numpy can't handle the unicodeness for you.

Is this guaranteed to not be a normal python scalar?

2017-05-19 19:55 UTC, pv commented on scipy/sparse/_matrix_io.py
> +            matrix_format = matrix_format.decode('ascii')
Loading files saved on Python 3 on previous versions. Previously, you could have bytes or unicode here depending on Python version.

Calling unicode.decode is allowed on Python 2.

2017-05-19 19:57 UTC, pv commented on scipy/sparse/_matrix_io.py
> +        matrix_format = matrix_format.item()
It's guaranteed to be a Python scalar: https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.ndarray.item.html

2017-05-19 19:57 UTC, eric-wieser commented on scipy/sparse/_matrix_io.py
> +        matrix_format = matrix_format.item()
No, I mean is `matrix_format` guaranteed to be an `ndarray` in the first place, and not a raw string?

2017-05-19 19:59 UTC, eric-wieser commented on scipy/sparse/_matrix_io.py
> +            matrix_format = matrix_format.decode('ascii')
> Calling unicode.decode is allowed on Python 2.

Right, but it's harmful - AFAICT, for unicode objects, this line means "throw an error if the string isn't ascii"

2017-05-19 19:59 UTC, pv commented on scipy/sparse/_matrix_io.py
> +            matrix_format = matrix_format.decode('ascii')
The string here is guaranteed to be ascii-only for any file saved by `save_npz`.

2017-05-19 20:07 UTC, pv commented on scipy/sparse/_matrix_io.py
> +        matrix_format = matrix_format.item()
Yes, stuff coming from `np.load()` always has type ndarray.

2017-05-19 23:51 UTC, perimosocordiae requested changes

2017-05-19 23:51 UTC, perimosocordiae commented on scipy/sparse/tests/test_matrix_io.py
> +    b = load_npz(os.path.join(DATA_DIR, 'csc_py2.npz'))
One of these should be `'csc_py3.npz'`.

2017-05-19 23:51 UTC, perimosocordiae commented on scipy/sparse/tests/test_matrix_io.py
> +@dec.skipif(NumpyVersion(np.__version__) < '1.10.0', 'feature requires numpy >= 1.10.0')
It would be nice if the message said what feature we're requiring here, like "disabling unpickling requires numpy >= 1.10.0" (or similar).

2017-05-20 14:03 UTC, pv commented
Updated.

2017-05-20 14:31 UTC, perimosocordiae approved these changes

2017-05-20 14:47 UTC, merged

2017-05-20 14:47 UTC, perimosocordiae commented
Merged, thanks Pauli!