ENH: optimize: more complete callback signature
scipy/scipy pull request #7425
Opened 2017-05-21 17:54 UTC by antonior92

I have implemented a more complete signature to the callback function used in ``optimize``.
The default  signature  ``callback(xk)`` is still available for all solvers, but a more complete
list of parameters is also allowed:

- ``callback(xk, fk, nfev, nit)`` is the alternative signature for the methods "Powell" and "Nelder-Mead";
- ``callback(xk, fk, nfev, gk, njev, nit)``, for the methods "CG" and "BFGS";
- ``callback(xk, fk, nfev, gk, njev, nhev, nit)``, for the methods "Newton-CG", "trust-ncg", "trust-exact" and "dogleg".

The idea for this PR follows from the discussion with @mdhaber in Issue #7306

2017-05-21 18:40 UTC, pv requested changes
Using plain `except:` will catch all exceptions, also those unrelated to the number of arguments. That probably leads to confusing error behavior.

I wonder what is the best way to specify the callback signature. Some options:

1. Use `inspect` to get the signature
2. Tell the user to set some special attribute to get the bigger signature, e.g. `callback.signature = "(xk, fk, nfev, gk, njev, nhev, nit)"`
3. Try to call and catch the specific argument number exception.

You probably should detect which callback signature to use immediately at the entry to the function, so that it does not need to be done on each iteration.

The same solution as used here can then be used to clean up the callback mess in `scipy.sparse.linalg`.

2017-05-22 00:06 UTC, andyfaff commented
Sorry for not contributing here earlier. I think a callback interface with the same signature for all minimizers is needed here. I think the following would be cleaner in a user callback function. The user stops a minimization by raising an `Exception`.

    def callback(x, OptResObj=None):
        # OptResObj is an intermediate OptimizeResult instance
        # It'd contain the normal OptimizeResult attributes like nit, nfev, x, etc.
        # Extra attributes can be set dependent on the minimizer, e.g. njev. Those attributes
        # would be listed for each minimizer.
        
        # To stop the minimizer the callback function raises an Exception
        if time.time() > boredom_threshold:
            raise Exception("The minimizer was running for too long")

This Exception would then be caught by the calling code. The `try/except` block that catches the Exception could then do one of two things. 

1. It could return an `OptimizeResult`, with the error message that was given by the callback function, with the Exception object also included in the `OptimizeResult`.
2. It could propagate the `Exception`, with the `Exception` having the `OptimizeResult` as an extra attribute.

If it weren't for back compatibility issues the  following signature would be best:

    def callback(OptResObj):
         # OptResObj is an intermediate OptimizeResult

I'm not sure how those backcompat issues could be addressed.

2017-05-22 02:30 UTC, antonior92 commented
Your suggestion is pretty good @andyfaff ... What do you think of providing two alternative signatures:

- ``callback(xk)`` 
- ``callback(xk, OptResObj)``

@pv I am thinking of continue to use a try-catch structure but I will modify it so it only catches the exception related to the number of parameters. What do you think?

2017-05-22 03:36 UTC, andyfaff commented
THere are a few minimizers that have callbacks with more than one argument. `differential_evolution` and `basinhopping` are among them. How about:

    def callback(xk, state=None)

where `state` is an `OptimizeResult`.  This form will make it easier to use because one can use introspection to see if the `state` keyword is present in the keyword arguments, or if the callback function accepts `**kwds`. We may be able to have a single piece of shim code that all the minimizers call - this shim function would be responsible for assembling all the required attributes, performing the introspection of the callback, then calling the callback. The introspection would only be run once during the whole minimization run.

2017-05-23 02:41 UTC, andyfaff commented
It'll be better that the `callback(xk, state=None)` raises an `Exception`, somewhere up the chain the calling code catches that `Exception`, adds the intermediate `OptimizeResult` as another attribute, then propagates the `Exception`.
The reason for this is because the provider of the callback function was raising the Exception, so they shouldn't be surprised to receive the same Exception back.

2017-05-23 11:24 UTC, antonior92 commented
```
def callback(xk, state=None)
```
sounds good to me. Furthermore, the way you suggested to handle the exception also seems a good idea. It would be a way to forcefully interrupt the execution of the algorithm without loosing the information (solving another problem we have discussed in #7306).

2017-05-23 11:46 UTC, pv commented
Should the extra metadata be added to all exceptions or only to a 
specific exception type?

2017-05-23 12:28 UTC, antonior92 commented
My idea was to add the metadata to all exceptions raised inside the callback function. What do you think? Even if the exception was not intended to happen I think information about the solver state would be useful for the user.

2017-05-24 01:50 UTC, andyfaff commented
I was thinking:

    # in minimizer code somewhere
    # truth of has_state_keyword determined via introspection of callback
    if has_state_keyword:
        # construct OptimizeResult with intermediate results, e.g. best x, nit, nfev
        or = OptimizeResult()
        try:
            callback(xk, state=or)
        except Exception as e:
            e.optimize_result = or
            raise e
    else:
        callback(xk)

and

    # the users callback
    def callback(xk, state=None):
        if (time.time() > boredom_threshold) and (state is not None) and (state.nfev > 10):
            raise RuntimeError("I'm bored")

With this approach I think we can use callbacks of old and new signatures. If this were a clean sheet implementation we'd do it differently, with the only parameter to `callback` being an intermediate `OptimizeResult`.

2017-05-24 11:34 UTC, antonior92 commented
Nice suggestion! It was in the line of what I was thinking. I will modify my implementation accordingly...

2018-02-22 08:10 UTC, andyfaff commented
#8414 will go a long way to addressing this, if it gets merged.

2022-12-16 07:14 UTC, tupui commented
Closing this as superseded by #17486

2022-12-16 07:14 UTC, closed without merging