Doc: Added tutorial documentation for stats distributions ksone and kstwobign
scipy/scipy pull request #7461
Opened 2017-06-04 15:17 UTC by pvanmulbregt

The stats tutorial pages in the doc for these two KS distributions existed but were empty. This adds a body for each of them.

2017-06-25 12:05 UTC, rgommers requested changes
Thanks @pvanmulbregt! Had a few minor comments only so far. ``ksone`` seems right to me, ``kstwobign`` is hard to check - not in the Birnbaum paper. Did you have another reference for that?

2017-06-26 15:38 UTC, pvanmulbregt commented on doc/source/tutorial/stats/continuous_ksone.rst
> +One shape parameter
Requested changes now made.
I had cloned the style from the beta distribution doc, tutorial/stats/continuous_beta.html.  Is there a preferred template one should use?

2017-06-27 11:59 UTC, rgommers commented on doc/source/tutorial/stats/continuous_ksone.rst
> +One shape parameter
Not really I think. Most of these have been converted to Sphinx from LaTeX a long time ago, that's why the format looks fairly uniform. But I'm not sure I can point to a template or one function as the preferred one.

2017-06-27 12:07 UTC, rgommers commented
https://2976-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/tutorial/stats/continuous_ksone.html

https://2976-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/tutorial/stats/continuous_kstwobign.html

both look good. change to ``target`` and ``empirical`` made it clearer

2017-06-27 12:07 UTC, merged

2017-06-27 12:07 UTC, rgommers commented
Merged, thanks @pvanmulbregt