ENH: support any order >=0 in ndimage.gaussian_filter
scipy/scipy pull request #7485
Opened 2017-06-11 23:38 UTC by jaimefrio

Probably more important than supporting higher order derivatives is the fact that the kernel generation is vectorized and doesn't rely on hard-coded formulas, but is instead automatically generated using NumPy's `Polynomial.deriv()`.

2017-06-26 12:08 UTC, rgommers requested changes
The changes look good apart from my minor comments. Test coverage is a bit thin though, it wouldn't catch some errors I suspect - mostly the ``gaussian_filter`` tests are for internal consistency (like between modes) and with simple inputs for which exact errors are known. Did you test with a realistic input or just random numbers for any changes in results? I'd expect they should be there, but only at the 1e-13 level or so.

2017-06-26 19:57 UTC, jaimefrio commented on scipy/ndimage/filters.py
> +        raise ValueError('order must be non-hegative')
Done.

2017-06-26 19:57 UTC, jaimefrio commented on scipy/ndimage/filters.py
> +    p = numpy.polynomial.polynomial.Polynomial([0, 0, -0.5 / (sigma * sigma)])
It can be, have changed both occurrences.

2017-06-26 19:58 UTC, jaimefrio commented on scipy/ndimage/filters.py
> +    # this perhaps be phi /= sigma * sqrt(2 * pi) instead?
I guess it does, and we couldn't break backwards compatibility either, so why even worry?

2017-06-27 06:06 UTC, rgommers commented
Test error was a timeout only. LGTM now, so in it goes. Thanks @jaimefrio

2017-06-27 06:06 UTC, merged