Informative exception when passing a sparse matrix
scipy/scipy pull request #7566
Opened 2017-07-05 22:51 UTC by urigoren

Proposed solution to
https://github.com/scipy/scipy/issues/7565

2017-07-06 20:31 UTC, perimosocordiae commented on scipy/spatial/distance.py
> +         raise NotImplementedError("pdist does not support sparse matrices, use skearn's pairwise_distances\nhttp://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.pairwise_distanc
The [docs](https://docs.python.org/3/library/exceptions.html#NotImplementedError) indicate that `NotImplementedError` should be used for abstract methods or in-progress methods. I don't think there's a plan to support sparse inputs here, so `TypeError` might be more appropriate.

Also, I'd like a shorter message. Maybe something like: "pdist doesn't support sparse matrix inputs, use sklearn.metrics.pairwise_distances instead."

2017-07-07 08:22 UTC, urigoren commented on scipy/spatial/distance.py
> +         raise NotImplementedError("pdist does not support sparse matrices, use skearn's pairwise_distances\nhttp://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.pairwise_distanc
Thank you, Done...

2017-07-07 13:18 UTC, perimosocordiae requested changes

2017-07-07 13:18 UTC, perimosocordiae commented on scipy/spatial/distance.py
> +         raise TypeError("pdist does not support sparse matrix input, use skearn's pairwise_distances instead")
typo: skearn -> sklearn

Also wrap the string to fit in 80 columns, please.

2017-07-07 13:18 UTC, perimosocordiae commented on scipy/spatial/distance.py
> +    if scipy.sparse.issparse(X):
`scipy.sparse` needs to be imported before use.

2017-07-07 19:20 UTC, urigoren commented on scipy/spatial/distance.py
> +         raise TypeError("pdist does not support sparse matrix input, use skearn's pairwise_distances instead")
Thanks, Done !

2017-07-08 17:25 UTC, urigoren commented
@perimosocordiae , please re-review

2017-07-08 18:41 UTC, perimosocordiae approved these changes
Looks good, thanks @urigoren!

My final concern is that this will cause `scipy.spatial` to depend on importing `scipy.sparse`, which will slightly increase the time it takes to run `import scipy.spatial` the first time. I don't expect this to be a big slowdown, though, so I'm +1 to merge.

2017-07-10 09:25 UTC, rgommers commented
This doesn't look quite right to me:

- ``_copy_array_if_base_present`` is called from other functions than ``pdist`` (e.g. ``squareform``), so is not the right place to put this check
- adding coupling between scipy submodules just for an exception message is slightly questionable. there are many types of inputs that aren't accepted.......

2017-07-10 09:30 UTC, rgommers commented
Looks like a documentation change is a better way to go about this. And perhaps it would make sense to move the scikit-learn distance metrics into ``scipy.spatial``?

2017-07-10 10:41 UTC, urigoren commented
@rgommers , So what do you suggest to do next?  Move this check to `_copy_array_if_base_present` or copy the code from sklearn's code ?

2017-07-10 13:43 UTC, perimosocordiae commented
For now, let's just add a warning not to use sparse matrix inputs to the docstring of `pdist` and `cdist`, perhaps in the "Notes" section.

I do think that eventually `scipy.spatial` should grow sparse matrix support similar to what scikit-learn provides, but that will be a large effort that needs to be designed carefully.

2017-07-10 14:49 UTC, urigoren commented
What are the downsides of merging this PR, only the possible increase in loading time ?
Correct me if I'm wrong, but that can be tested with a simple `%timeit` call, right ?

I agree with @perimosocordiae , that we definitely want `pdist` and `cdist` to support sparse matrices in the future, 
but until that happens, what's the harm of having an informative exception ?

2017-07-11 09:50 UTC, rgommers commented
> What are the downsides of merging this PR, only the possible increase in loading time ?
Correct me if I'm wrong, but that can be tested with a simple %timeit call, right ?

No you can't. Measuring import time is quite tricky to get right (after the first import it's a lookup in globals so much faster) - we had some discussion on that on the numpy-discussion list last year.

Either way, import time is not the main issue. The issues are the two I listed in https://github.com/scipy/scipy/pull/7566#issuecomment-314053350.

2017-07-11 09:52 UTC, rgommers commented
> I do think that eventually scipy.spatial should grow sparse matrix support similar to what scikit-learn provides, but that will be a large effort that needs to be designed carefully.

Agreed

> For now, let's just add a warning not to use sparse matrix inputs to the docstring of pdist and cdist, perhaps in the "Notes" section.

+1

2017-07-22 12:33 UTC, ev-br commented
Just noting that there's a similar utility function instead of a direct use of `issparse`, used e.g. in scipy.linalg IIRC: https://github.com/scipy/scipy/blob/master/scipy/_lib/_util.py#L192

2018-02-21 15:58 UTC, urigoren commented
@rgommers , @ev-br , I fixed the sparsity check as you suggested.

The test seem to pass (despite what the CI says), it's an accuracy issue on python 3.5 - please have a look at the logs.

Could you please merge ?

2018-04-08 16:41 UTC, merged