DOC: Add examples to scipy.optimize
scipy/scipy pull request #7587
Opened 2017-07-11 12:22 UTC by adivijaykumar

I have currently added examples to `fminbound` and `bisect` methods.

I plan on adding to `newton`, `golden`, `fmin`, `brenth`, `brentq` and some others too.

Are examples similar to `brent` (#7299) enough for `brenth` and `brentq`?

2017-07-12 09:05 UTC, rgommers commented
@adivijaykumar one test failure that is real

2017-07-12 09:10 UTC, rgommers requested changes
Overall examples are suitable and useful to add, thanks. A few small things to fix.

2017-07-12 09:10 UTC, rgommers commented on scipy/optimize/optimize.py
> +    >>> minimum = optimize.fminbound(f,-1,2)
pep8 nitpick: spaces after commas please

2017-07-12 09:10 UTC, rgommers commented on scipy/optimize/optimize.py
> +    >>> minimum = optimize.fminbound(f,1,2)
same here, spaces

2017-07-12 09:10 UTC, rgommers commented on scipy/optimize/zeros.py
> +    The bisection algorithm fails if `f(a)` and `f(b)` have the same sign.
If you're formatting code snippets, those should have double rather than single backticks.

2017-07-12 09:10 UTC, rgommers commented on scipy/optimize/zeros.py
> +    >>> root = optimize.bisect(f,0,2)
more spaces

2017-07-12 09:10 UTC, rgommers commented on scipy/optimize/zeros.py
> +    >>> root = optimize.bisect(f,-2,2)
and even more spaces

2017-07-12 09:10 UTC, rgommers commented on scipy/optimize/zeros.py
> +    ValueError: f(a) and f(b) must have different signs
This won't work. Our doctest checkers runs test code to verify it doesn't raise exceptions, so this test will fail. I suggest to just leave this out

2017-07-12 09:10 UTC, rgommers commented
> Are examples similar to brent (#7299) enough for brenth and brentq?

That's enough. Thanks for working on this @adivijaykumar

2017-07-12 09:23 UTC, adivijaykumar commented on scipy/optimize/optimize.py
> +    >>> minimum = optimize.fminbound(f,-1,2)
Will take care. But then I do notice a lot of places in the files (other than what I am working on) seem to not obey this pep8 guideline.

2017-07-13 12:05 UTC, rgommers commented on scipy/optimize/optimize.py
> +    >>> minimum = optimize.fminbound(f,-1,2)
Yeah, there's a lot of very old code that was not written in a very nice style that we haven't changed. It's a bit of a trade-off between messing up the history by touching lots of code, and living with ``a,b`` type code. We're trying to be better about new code though.

2017-07-13 17:54 UTC, person142 commented on scipy/optimize/zeros.py
> +    >>> # fprime and fprime2 not provided, use secant method
It would probably be nicer to write this line before the interpreter section rather than include it as a code comment.

2017-07-13 21:50 UTC, rgommers commented
@adivijaykumar if you can, it would be better to push multiple commits at once rather than one by one, in order to not trigger the continuous integration on each commit.

2017-07-14 05:20 UTC, adivijaykumar commented
Sure! That's okay.


Thanks and Regards,
Aditya V

Sent from a Phone, kindly forgive brevity and spelling/grammatical errors

On Jul 14, 2017 3:20 AM, "Ralf Gommers" <notifications@github.com> wrote:

> @adivijaykumar <https://github.com/adivijaykumar> if you can, it would be
> better to push multiple commits at once rather than one by one, in order to
> not trigger the continuous integration on each commit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy/scipy/pull/7587#issuecomment-315212097>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ALOPWwq6oLmiCRM7v-SYrMHt9waVjeMoks5sNpErgaJpZM4OUJyi>
> .
>

2017-07-14 06:06 UTC, adivijaykumar commented on scipy/optimize/zeros.py
> +    >>> root = optimize.newton(f, 1.5, fprime=lambda x: 3 * x**2, fprime2=lambda x: 6 * x)
The Travis build had failed here in the previous build, saying that end of line was detected. Now after correcting it, there's a PEP8 nit (more than 80 chars). What shall I do?

2017-07-14 07:55 UTC, rgommers commented on scipy/optimize/zeros.py
> +    >>> root = optimize.newton(f, 1.5, fprime=lambda x: 3 * x**2, fprime2=lambda x: 6 * x)
You can break lines like so (note the ``...``):

    >>> root = optimize.newton(f, 1.5, fprime=lambda x: 3 * x**2,
    ...                        fprime2=lambda x: 6 * x)

2017-07-14 08:38 UTC, adivijaykumar commented
That's it from my side! Let me know if there are any changes to be made.

2017-07-16 01:57 UTC, rgommers requested changes
Looks good overall, a few minor changes left to make.

For future commits, it would be useful to format the commit messages as described in http://docs.scipy.org/doc/numpy-dev/dev/gitwash/development_workflow.html#writing-the-commit-message

2017-07-16 01:57 UTC, rgommers commented on scipy/optimize/optimize.py
> +    not necessarily lie in the range (xa,xb).
formatting: in the above two lines, change ``(xa,xb)`` to ` ``(xa, xb)`` `.

2017-07-16 01:57 UTC, rgommers commented on scipy/optimize/optimize.py
> +    >>> minimum = optimize.golden(f,brack=(1,2))
pep8: spaces after commas

2017-07-16 01:57 UTC, rgommers commented on scipy/optimize/optimize.py
> +    >>> minimum = optimize.golden(f,brack=(-1,0.5,2))
more spaces

2017-07-16 01:57 UTC, rgommers commented on scipy/optimize/zeros.py
> +    Halley's method
These comments are now duplicate with the first paragraph of the docstring. May be useful to keep, but then split this up and put each method right above the example demonstrating it.

2017-07-17 10:02 UTC, adivijaykumar commented
@rgommers should be ok now.

2017-07-17 11:06 UTC, rgommers approved these changes

2017-07-17 11:08 UTC, merged

2017-07-17 11:08 UTC, rgommers commented
Thanks @adivijaykumar, merged.

2017-07-17 11:38 UTC, adivijaykumar commented
Fixes a part of #7168