Add out parameter to pdist and cdist.py
scipy/scipy pull request #7637
Opened 2017-07-20 19:20 UTC by dezmondgoff

To reduce memory load of repeated calls to pdist/cdist. I don't think `out` it needs to be set to zero, does it?

2017-07-22 21:00 UTC, apbard requested changes
It is for sure a nice addition. 
There are some easy-to-fix indentation issues.
You should also add tests to check that out is correctly used and filled.

2017-07-22 21:00 UTC, apbard commented on scipy/spatial/distance.py
> +      dm = out
You have to use 4 spaces to correctly indent.

2017-07-22 21:00 UTC, apbard commented on scipy/spatial/distance.py
> +      dm = np.zeros((m * (m - 1)) // 2, dtype=np.double)
It should be safe also to change this to  `dm = np.empty((m * (m - 1)) // 2, dtype=np.double)`

2017-07-23 06:14 UTC, dezmondgoff commented
Sorry, I'm new to github. Is there any special way to add tests, or do I just add a test script to the patch branch?

2017-07-23 11:59 UTC, ilayn commented
If you install `pep8` package, you can test for pep8 issues via `pep8 myfile.py` on the terminal which will tell you problems if there is any. Or you can use an editor that can automatically perform the checks periodically.

Also if you are not on Windows (which is very tedious to set things up), you can simply call `python runtests.py -s <module name>` to run tests of that module.  Currently you have an error that says esp is not known because in the test you have a typo of `esp` instead of `eps` local checks will reduce the effort of committing and waiting for Travis CI to check (no worries I was there too). 

I'm mainly a Windows user but what I did is to setup a Oracle VM VirtualBox and installed different Linux machines there. Then whenever I feel like ready I switch to those machines and perform builds and testruns on those machines to check for problems. Then I commit to here.

2017-07-23 13:04 UTC, apbard commented on scipy/spatial/distance.py
> +        if out.shape != (mA, mB):
This is not needed for pdist

2017-07-23 13:04 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +        out1 = np.empty((10, 20), dtype=np.double)
To improve readability, what about change the order so to group together the different aspects you are testing? You may also add a line of comment saying what are you testing  (E.g. C-contiguous, wrong shape..)

2017-07-23 13:04 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +        Y1 = cdist(X1, X2, u('euclidean'), out=out1)
Here you are testing just the euclidean metric. We could check instead against all metrics by adding a for cycle like `for metric in _METRICS_NAMES:`

2017-07-23 13:04 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +        assert_raises(ValueError, cdist, X1, X2, u('euclidean'), out=out2)
Is there a reason for using the conversion to unicode?

2017-07-23 13:28 UTC, apbard commented
Don't worry if you are new, there is always a first time ;)
[Here](https://github.com/scipy/scipy/blob/master/HACKING.rst.txt) you can find some useful info about scipy policies, how to run test or a script, the naming conventions for commits and PR, etc.
As @ilayn has suggested, using an editor with pylint and pep8 packages can help you spot errors right away while editing ;)
P.s. I tipically use Atom or VisualStudio Code as editors and the are availlable both for Linux and Windows.

2017-07-23 21:12 UTC, dezmondgoff commented
@apbard Thanks for the links and I apologize for the ill-formatted commit messages. I'm currently using Eclipse for Python and C, and Atom for everything else. Have used Spyder and RStudio also. Eclipse has pep8.

2017-07-23 21:38 UTC, ilayn commented
You can do it on Spyder too. see Realtime code analysis part with pep8 setting
![image](https://user-images.githubusercontent.com/1303842/28503091-f47c4514-6fff-11e7-94fc-0156d9aeb9c0.png)

2017-07-24 12:33 UTC, apbard commented on scipy/spatial/distance.py
> +        dm = np.zeros((m * (m - 1)) // 2, dtype=np.double)
I would change also this to `np.empty`

2017-07-24 12:33 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +            Y2 = cdist(X1, X2, metric, **kwargs)
You can use `Y2 = cdist(X1, X2, metric, out=out1, **kwargs)`

2017-07-24 12:33 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +            # test is distance matrix Y1 and out1 are the same object
You probably forgot to copy back the updated comments used in `cdist`

2017-07-24 12:33 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +            for rnd_eo_name in self.rnd_eo_names:
I think it should be enough to check against `X = eo['cdist-X1']` ...it is small and it will speed-up tests.

2017-07-24 18:58 UTC, dezmondgoff commented on scipy/spatial/tests/test_distance.py
> +            # test is distance matrix Y1 and out1 are the same object
Fixed for next commit

2017-07-24 18:58 UTC, dezmondgoff commented on scipy/spatial/tests/test_distance.py
> +            Y2 = cdist(X1, X2, metric, **kwargs)
Fixed for next commit

2017-07-24 18:59 UTC, dezmondgoff commented on scipy/spatial/distance.py
> +        dm = np.zeros((m * (m - 1)) // 2, dtype=np.double)
Changed for next commit

2017-07-24 18:59 UTC, dezmondgoff commented on scipy/spatial/tests/test_distance.py
> +            for rnd_eo_name in self.rnd_eo_names:
Just tried, and unfortunately, `eo['cdist-X1']` has too few observations for mahalanobis distance. I might have to make a new data set, 10 x 9 or something like that.

2017-07-24 21:08 UTC, apbard commented on scipy/spatial/tests/test_distance.py
> +            for rnd_eo_name in self.rnd_eo_names:
You can just discard some columns e.g., `eo['cdist-X1'][: , ::2]`... the actual result of the xdist is not so important for this specific test.

2017-08-21 10:13 UTC, rgommers commented
@dezmondgoff did you maybe forget to push that next commit that you mention in a couple of replies above?

Also would be good if you could rebase this PR (let us know if you're not sure how to do that), there's a merge conflict now.

2017-09-10 11:40 UTC, rgommers commented
@dezmondgoff ping. Looks like this PR is close to the finish line. We're branching the next release in a week, if you want this to be included then would be good to come back to this very soon.

2017-09-14 09:21 UTC, apbard commented
@rgommers would you like me to take this over and try to have it finished by the 16th? 
If yes, how should I proceed? 
Clone his branch, squash everything (keeping his authorship) and then add another commit with the final changes? Or change directly the squashed commit? open a new pr? or else?

2017-09-14 09:28 UTC, rgommers commented
@apbard yes good idea, please do! 

> Clone his branch, squash everything (keeping his authorship) and then add another commit with the final changes? 

Yes that sounds right.

2017-09-15 10:00 UTC, rgommers commented
Finished and merged in gh-7637, so closing this.

2017-09-15 10:00 UTC, closed without merging