Fixes #7735: Prevent integer overflow in concatenated index pointer
scipy/scipy pull request #7736
Opened 2017-08-15 16:19 UTC by aerval

This determines the best data type of the new index pointer and applies it.

This does not have a unittest, but I am not sure whether this makes sense here as one would need to either generate a ~30 Gb sparse matrix for it to appear or use int8 (or similar) pointers on purpose.

I have also not checked whether similar issues appear when concatenating other sparse matrix types

2017-08-15 16:32 UTC, pv requested changes
You can add a unit test along the lines of 
```
import pytest
from scipy._lib._testutils import check_free_memory
...
@pytest.mark.slow
def test_concatenate_int32_overflow():
    check_free_memory(<a priori upper bound for memory needed, in MB>)
    use dtype=np.int8 arrays for data (but not indices), to minimize
    the amount of memory needed
```

2017-08-15 16:32 UTC, pv commented on scipy/sparse/construct.py
> -        indptr.append(b.indptr[:-1] + last_indptr)
Use `np.asarray(..., dtype=idx_dtype)` instead of astype, to avoid unnecessary copies.

2017-08-15 16:32 UTC, pv commented on scipy/sparse/construct.py
>      indices = np.concatenate([b.indices for b in blocks])
It's necessary to ensure that the dtype of `indices` is also `idx_dtype`.

2017-08-16 07:39 UTC, aerval commented on scipy/sparse/construct.py
> -        indptr.append(b.indptr[:-1] + last_indptr)
I see, that is a good point. However, this also changes the dtype in the original matrices. If, as you write above, indices and indptr have to be the same dtype, those original matrices may become damaged (i.e do we have to change the dtype in the input matrices as well?).

2017-08-16 09:23 UTC, aerval commented on scipy/sparse/construct.py
> -        indptr.append(b.indptr[:-1] + last_indptr)
Ah I see, sorry, my mistake

2017-08-16 11:45 UTC, aerval commented
Unfortunately, my local python needs about 30G of RAM to execute this test scenario. Also, tests 2 and 3 pass by default as the types of indices and indptr are converted automatically due to `last_indptr` being concatenated at the end.

2017-08-16 13:39 UTC, perimosocordiae commented on scipy/sparse/tests/test_construct.py
> +        A = csr_matrix(np.ones((n, n)), dtype=bool))
Syntax error here (extra ')').

2017-08-16 13:48 UTC, pv commented
I think the `_compressed_sparse_stack` should be written in a more memory-efficient way, cutting memory usage by a factor of 2 or more --- basically, `np.concatenate` should not be used, but instead the `indptr` and `indices` arrays should be allocated beforehand and the pieces be assigned to them. Incrementing the indptr `c = a + b` should be written as `c[:] = a; c += b` to avoid temporary arrays.

2017-08-16 14:12 UTC, perimosocordiae commented
Internally, `np.concatenate` does the allocation all at once, so it wouldn't be any faster to build `indices` without it: https://github.com/numpy/numpy/blob/8ed1770a8ca968388eacd5d96b8068b272fb47b7/numpy/core/src/multiarray/multiarraymodule.c#L355

I agree that it would help to allocate `indptr` up-front as you suggested, though.

2017-08-16 14:19 UTC, perimosocordiae requested changes

2017-08-16 14:19 UTC, perimosocordiae commented on scipy/sparse/construct.py
> +                              for b in blocks])
As you mentioned, the `asarray` calls here aren't needed as the sparse matrix constructor will handle conversion if needed.

2017-08-16 14:19 UTC, perimosocordiae commented on scipy/sparse/tests/test_construct.py
> +        C = construct._compressed_sparse_stack((A,B), 0)
Call `vstack` here instead.

2017-08-16 14:19 UTC, perimosocordiae commented on scipy/sparse/tests/test_construct.py
> +
Another test that makes sure we aren't promoting to int64 if we don't need to would be great (and won't require huge RAM to test).

2017-08-16 15:31 UTC, aerval commented on scipy/sparse/tests/test_construct.py
> +        C = construct._compressed_sparse_stack((A,B), 0)
I was using `_compressed_sparse_stack` on purpose as the bug is not in `vstack` (and may also appear in `hstack`)

2017-08-16 17:27 UTC, perimosocordiae commented on scipy/sparse/tests/test_construct.py
> +    def test_concatenate_int32_overflow():
Needs `self` argument.

2017-08-17 09:04 UTC, aerval commented
This should address @pv's suggestions with a pre-allocated indptr. As we assume that the matrix is initialized de-novo in the end, I think `concatenate` can be used for the joined `indices`?!

2017-08-17 09:19 UTC, pv reviewed
Using np.concatenate for indices rather than preallocating will still result in a temporary array. The matrix constructor will ensure the correct type, but it has to create a copy of the array because the type conversion cannot be done in-place.

2017-08-17 09:19 UTC, pv commented on scipy/sparse/construct.py
> +        indptr[sum_dim:sum_dim+b.shape[axis]] = b.indptr[:-1] + last_indptr
The temporary array on the RHS can be avoided via
```
idxs = slice(sum_dim, sum_dim + b.shape[axis])
indptr[idxs] = b.indptr[:-1]
indptr[idxs] += last_indptr
```

2017-08-17 09:22 UTC, pv commented on scipy/sparse/construct.py
> +    last_indptr = idx_dtype(0)
This can be `last_indptr = 0` --- using a numpy dtype scalar here is not necessary, as the type of the scalar does not matter in additions.

2017-08-17 09:46 UTC, aerval commented on scipy/sparse/construct.py
> +        indptr[sum_dim:sum_dim+b.shape[axis]] = b.indptr[:-1] + last_indptr
Oh, I did not think of that, thanks for catching that :)

2017-08-17 10:53 UTC, pv commented on scipy/sparse/construct.py
> +                                maxval=data.size)
The `arrays` should also list the `indices`.
It's possible to imagine very sparse matrices of sizes > 2**32 so also `indices` can overflow.

2017-08-17 11:58 UTC, aerval commented on scipy/sparse/construct.py
> +                                maxval=data.size)
yes, though there `constant_dim` would be the better limit

2017-08-17 15:52 UTC, pv approved these changes

2017-08-17 21:48 UTC, perimosocordiae commented on scipy/sparse/construct.py
> +    indptr = np.empty(np.sum([b.shape[axis] for b in blocks])+1,
Why not `sum(b.shape[axis] for b in blocks) + 1` here?

2017-08-17 21:49 UTC, perimosocordiae commented on scipy/sparse/tests/test_construct.py
> +        assert_equal(construct.vstack([A.tocsr(),B.tocsr()],
nitpick: space after commas

2017-08-18 06:28 UTC, aerval commented on scipy/sparse/tests/test_construct.py
> +        assert_equal(construct.vstack([A.tocsr(),B.tocsr()],
pardon, where? The matrix lists in the document all have no space after comma so I am not sure which one you mean.

2017-08-18 06:29 UTC, aerval commented on scipy/sparse/construct.py
> +    indptr = np.empty(np.sum([b.shape[axis] for b in blocks])+1,
good point, had not thought of that

2017-08-18 13:15 UTC, pv commented on scipy/sparse/construct.py
> +    last_indptr = 0
One final thing --- I was wrong that `last_indptr = idx_dtype(0)` is not necessary, it is necessary.

The Python integer is cast to the default integer size, but on win64 that's 32-bit even when the address space is 64-bit.

2017-08-18 13:37 UTC, aerval commented on scipy/sparse/construct.py
> +    last_indptr = 0
ah okay, but only in Python2, right?

2017-08-18 13:41 UTC, pv commented on scipy/sparse/construct.py
> +    last_indptr = 0
No, I think this is a numpy thing, so it's regardless of Python version.

2017-08-18 13:50 UTC, pv commented
Looks good, so I'll merge once CI finishes.

2017-08-18 14:16 UTC, perimosocordiae commented on scipy/sparse/tests/test_construct.py
> +        assert_equal(construct.vstack([A.tocsr(),B.tocsr()],
The recommendation is to have one space after a comma. (Sorry for not being clear!)

2017-08-18 14:16 UTC, perimosocordiae approved these changes

2017-08-18 15:17 UTC, merged

2017-08-18 15:18 UTC, pv commented
Merged, thanks a lot @aerval!

2017-08-18 15:19 UTC, pv commented
What the... Github's "Squash and merge" threw the authorship information away from the commit :/

2017-08-18 15:21 UTC, pv commented
Ah nope, it actually did an ordinary merge, so it's fine.