ENH: sparse: Add 64-bit integer to sparsetools
scipy/scipy pull request #7871
Opened 2017-09-16 20:58 UTC by perimosocordiae

This supersedes gh-7435 and fixes gh-7230, by allowing sparsetools functions to accept 64-bit integers even when the index dtype is 32-bit.

It's a little tricky to verify that this works without gobs of RAM, but here's one way to do it:
```python
import numpy as np
import scipy.sparse
from scipy.sparse._sparsetools import coo_todense

a = scipy.sparse.rand(5, 4, density=0.5)  # produces coo_matrix with index dtype = int32
out = np.zeros_like(a.toarray())
nnz = 2**32
coo_todense(5, 4, nnz, a.row, a.col, a.data, out.ravel('A'), 0)
```

Without this PR, the sparsetools machinery tries to cast `nnz` to int32, fails, and raises an error.

With this PR, we are able to pass `nnz` as a 64-bit integer and `coo_todense` promptly segfaults (as expected).

2017-09-23 18:07 UTC, pv commented on scipy/sparse/sparsetools/sparsetools.cxx
>                  *(npy_int64*)arg_list[j] = (npy_int64)value;
The `else if` clause following this should start with `else if (*p == 'i' && PyArray_EquivTypenums(I_typenum, NPY_INT32) ...`

2017-09-23 18:12 UTC, pv requested changes
Probably also need to add `case 'l':` to the `switch (ret_spec)` on line 376?

Also, `'l'` needs to be handled in the cleanup around line 449.

2017-09-29 21:31 UTC, perimosocordiae commented
Comments addressed. I'm not positive that I've used the right API call for converting an int64 to a Python int, though. I know that some platforms don't satisfy `long == int64`, but I didn't see a more explicit conversion function.

2017-09-30 12:54 UTC, pv commented
Can you add a test? Try to golf it down to minimum memory requirement, then estimate how much is needed, and then do as here:
https://github.com/scipy/scipy/blob/676da8f65d38cd62c89799aec7444df227424e04/scipy/sparse/tests/test_sparsetools.py#L251

2017-09-30 12:55 UTC, pv commented on scipy/sparse/sparsetools/sparsetools.cxx
> +        return_value = PyInt_FromLong(ret);
This is not the right one I think, will fail on windows.
FromLongLong is safe, since that's always at least 64-bit.

2017-09-30 13:01 UTC, pv commented on scipy/sparse/sparsetools/sparsetools.cxx
> +        return_value = PyInt_FromLong(ret);
TBH, also the call above it should be FromLongLong because `'i'` can be 64-bit. Can you fix that at the same time?

2017-10-01 01:08 UTC, perimosocordiae commented
I changed `ret` to be a `long long`, which means that the `'l'` and `'i'` cases are now the same for the return value conversion code.

The test will come next, but first: why is the `test_csr_matmat_int64_overflow` test unconditionally skipped? I know it's unlikely that any machine will have 155GB of available RAM, but the skip message seems wrong.

2017-10-01 01:33 UTC, perimosocordiae commented
I added the test, but I don't have a machine with the 20GB available to actually run it.

2017-10-01 01:50 UTC, person142 commented
@perimosocordiae ran the test on a machine with 32GB; it passed.

2017-10-01 02:05 UTC, perimosocordiae commented
@person142 thanks! Could you try running the same test against master to make sure it fails?

2017-10-01 02:42 UTC, person142 commented
On master I get:
```
============================================ FAILURES =============================================
________________________________________ test_nnz_overflow ________________________________________

    def test_nnz_overflow():
        # Regression test for gh-7230 / gh-7871, checking that coo_todense
        # with nnz > int32max doesn't overflow.
        nnz = np.iinfo(np.int32).max + 1
        # Ensure ~20 GB of RAM is free to run this test.
        check_free_memory((4 + 4 + 1) * nnz / 1e6 + 0.5)

        # Use nnz duplicate entries to keep the dense version small.
        row = np.zeros(nnz, dtype=np.int32)
        col = np.zeros(nnz, dtype=np.int32)
        data = np.zeros(nnz, dtype=np.int8)
        data[-1] = 4
        s = coo_matrix((data, (row, col)), shape=(1, 1), copy=False)
        # Sums nnz duplicates to produce a 1x1 array containing 4.
>       d = s.toarray()

../test_sparsetools.py:79:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <1x1 sparse matrix of type '<class 'numpy.int8'>'
	with 2147483648 stored elements in COOrdinate format>
order = None, out = None

    def toarray(self, order=None, out=None):
        """See the docstring for `spmatrix.toarray`."""
        B = self._process_toarray_args(order, out)
        fortran = int(B.flags.f_contiguous)
        if not fortran and not B.flags.c_contiguous:
            raise ValueError("Output array must be C or F contiguous")
        M,N = self.shape
        coo_todense(M, N, self.nnz, self.row, self.col, self.data,
>                   B.ravel('A'), fortran)
E       ValueError: could not convert integer scalar
```

2017-10-01 12:31 UTC, merged

2017-10-01 12:32 UTC, pv commented
I don't recally why that one test is unconditionally skipped.
It may be it was added in some early stage of the 64-bit support and was not fixed up later on.

2018-02-19 04:20 UTC, pasudyan commented
Hello, 

I am still having this exact same problem even after including the trick above. Any thoughts?
Here is the error:
ValueError                                Traceback (most recent call last)
<ipython-input-98-128ba715d74a> in <module>()
----> 1 coo_todense(5, 4, nnz, a.row, a.col, a.data, out.ravel('A'), 0)

ValueError: could not convert integer scalar