DOC: Completed "Examples" sections of all linalg funcs
scipy/scipy pull request #8200
Opened 2017-12-04 01:32 UTC by ilayn

MAINT: Touched `lu_factor` -> LinAlgWarning and stacklevel
MAINT: Touched `qr_multiply` -> Cleaned up the code and fixed an ndim bug
MAINT: Touched `rsf2csf` -> Cleaned up code

It is mostly documentation additions so in case docstring test passes the review load is minor. The parts that need attention are items above.

2017-12-04 03:26 UTC, ilayn commented
Does anyone know what

    ValueError: >>> from scipy.linalg import eigvals is not a item name

means in CircleCI error? I can't replicate it locally.

2017-12-04 03:43 UTC, person142 commented
First guess would be it's the lack of a blank line between the end of the `See Also` section and the `Examples` section for `eigvals`.

2017-12-04 03:45 UTC, ilayn commented
Argh.... *facepalm*

2017-12-06 16:22 UTC, ilayn commented
All green and I think this is ready for review.

2018-01-14 12:10 UTC, ev-br commented on scipy/linalg/_procrustes.py
> +    that most closely maps A to B using the algorithm given in [1]_.
FWIW, I think the original comment was useful.

2018-01-14 12:12 UTC, ev-br commented on scipy/linalg/_procrustes.py
> +    that most closely maps A to B using the algorithm given in [1]_.
Scratch that, I see now that the comment is moved to the Notes section.

2018-01-14 22:42 UTC, ilayn commented
Link for the rendered versions of the docstrings  https://5060-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/linalg.html

2018-01-16 10:29 UTC, rgommers requested changes
Overall LGTM, missing test for the bugfix is my only nontrivial comment.

For the record: ``@`` is not yet valid syntax for all supported Python versions, but I approve of it in these examples:)

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/_decomp_qz.py
> +    >>> # since we have sorted for left half plane eig, negatives come first
Style nitpick: *blank line - sentence - blank line* would look better than as a comment

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/_procrustes.py
> +    >>> # Flip the order of cols and check for the anti-diagonal mapping
same here, sentence > comment

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp.py
> +    >>> from numpy import allclose, zeros, ones, diag
better to remove these imports and just use ``np.``

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp.py
> +    >>> d, e = 3*ones(4), -1*ones(3)
clearer to put on two separate lines

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp.py
> +    >>> from numpy import allclose, zeros
use ``np.`` instead

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp_cholesky.py
> +    >>> from numpy import allclose, zeros, triu
use ``np.`` instead

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp_cholesky.py
> +    >>> from numpy import allclose, zeros, triu
same in more places, won't comment on it again

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp_lu.py
> +    >>> # piv is [2, 2, 3, 3]
evaluate `piv` instead?

2018-01-16 10:29 UTC, rgommers commented on scipy/linalg/decomp_schur.py
> +            c, s = mu[0] / r, T[m, m-1] / r
better to keep this on separate lines

2018-01-16 14:42 UTC, ilayn commented
Rebased and squashed

2018-01-17 20:13 UTC, rgommers approved these changes

2018-01-17 20:15 UTC, merged

2018-01-17 20:15 UTC, rgommers commented
LGTM now, merged. Thanks @ilayn!