Fixes Numpy datatype compatibility issues
scipy/scipy pull request #8215
Opened 2017-12-13 18:29 UTC by saurabhkgp21

Fixes #8207 
Taking input as float16 datatype will give segmentation fault, since there are no corresponding types for it in C language. Here I am taking input as float64 type to avoid datatype incompatibility.

2017-12-13 19:07 UTC, pv commented
This is not the right fix. The check for float16 needs to be done in the C code of ndimage.

2017-12-13 19:14 UTC, saurabhkgp21 commented
@pv I will update this PR with float16 check in C code

2017-12-14 12:15 UTC, saurabhkgp21 commented
@pv please look at the changes and see if changes are required or not.

2017-12-14 16:45 UTC, xoviat commented
IMO adding a test for this is trivial:

```
from scipy.ndimage.filters import gaussian_filter
import numpy as np
gaussian_filter(np.array([1],dtype=np.float16), 1)
```

2017-12-15 02:09 UTC, saurabhkgp21 commented
Okay, I will add test cases for this one

2017-12-16 07:48 UTC, saurabhkgp21 commented
@pv @xoviat  I had added corresponding test cases, please check if everything is fine or not.

2017-12-18 04:56 UTC, ghost requested changes

2017-12-18 04:56 UTC, xoviat commented on scipy/ndimage/tests/test_filters.py
> +		sndi.gaussian_filter(data,sigma)
Nit: indent with four spaces instead of a tab.

2017-12-18 06:37 UTC, saurabhkgp21 commented
ping @xoviat

2017-12-21 21:28 UTC, ghost approved these changes

2017-12-31 05:13 UTC, saurabhkgp21 commented
@xoviat is this PR ready to be merged or some more work is needed?

2018-02-03 13:09 UTC, pv commented
I rebased this and replaced the [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) `array_type > 12` with an explicit list of types.

2018-02-03 14:27 UTC, merged

2018-02-03 14:27 UTC, pv commented
thanks, merged