added accept_rate (target acceptance rate) as an optional keyword
scipy/scipy pull request #8775
Opened 2018-04-25 19:53 UTC by rocapp

Added accept_rate as an optional keyword argument to the `optimize.basinhopping` method.

2018-04-25 19:57 UTC, ilayn commented on scipy/optimize/_basinhopping.py
> +                 niter_success=None, seed=None):
new keywords need to appear at the end of the signature for backwards compatibility.

2018-07-13 16:45 UTC, rgommers requested changes
Thanks @rocapp. This looks like a reasonable addition to me. Just a few minor comments.

2018-07-13 16:45 UTC, rgommers commented on scipy/optimize/_basinhopping.py
> +    accept_rate : float, optional
This description needs to be at the end of the parameters list.

2018-07-13 16:45 UTC, rgommers commented on scipy/optimize/_basinhopping.py
> +        is increased. Otherwise, the stepsize is decreased.
minor: can you add "Default is 0.5."?

2021-11-10 05:47 UTC, andyfaff commented
Would be superseded by #14941. Thank you for creating this PR though.

2021-11-10 05:47 UTC, closed without merging