DOC: fix definition of optional `disp` parameter
scipy/scipy pull request #8788
Opened 2018-04-30 16:12 UTC by sciunto

I discovered a mistake in the documentation of _minimize_lbfgsb which is visible [here](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb).

2018-05-01 03:39 UTC, andyfaff requested changes
@sciunto thanks for noticing this and submitting a PR. The comments I made were purely based on what the code does at the moment. I don't know why the function accepts both `iprint` and `disp` when a single parameter would do (possibly back compatibility).

2018-05-01 03:39 UTC, andyfaff commented on scipy/optimize/lbfgsb.py
> +    disp : int
None or int

2018-05-01 03:39 UTC, andyfaff commented on scipy/optimize/lbfgsb.py
> +        If zero, then no output.  If a positive number, then this over-rides
If `disp is None` (the default), then the supplied version of `iprint` is used. If `disp is not None`, then it overrides the supplied version of `iprint` with the behaviour you outlined.

2018-05-02 07:10 UTC, sciunto commented
@andyfaff Thanks for helping. It's fixed and squashed.

2018-06-04 04:06 UTC, merged

2018-06-04 04:06 UTC, rgommers commented
LGTM now, merged. Thanks @sciunto, @mdhaber