Better imresize deprecation warning
scipy/scipy pull request #8971
Opened 2018-06-25 15:27 UTC by Atcold

Better deprecation warning, which tells the user how to recover the **same exact output data** when `imresize` will be taken out.

2018-06-25 15:31 UTC, Atcold commented
Damn, I messed up, and I cannot force push.

2018-06-25 15:36 UTC, Atcold commented
One second, I'm trying to fix this mess.

2018-06-28 07:57 UTC, rgommers requested changes
Thanks @Atcold, that is a better recommendation.

2018-06-28 07:57 UTC, rgommers commented on scipy/misc/pilutil.py
> +                         "Combine Pillow and Numpy as in ``numpy.array(Image.fromarray(arr).imresize())``.")
I'd suggest a slight tweak: "use Pillow directly instead: ``np.array(Image.fromarray(arr).imresize())``".

2018-06-28 07:57 UTC, rgommers commented
CircleCI test failures can be ignored, unrelated.

2018-07-01 11:42 UTC, ev-br commented
The deprecation message says it's slate for removal in scipy 1.2.0, which is the current master. So ISTM we either live by the deprecation message and remove it altogether instead, or adjust the message further.

2018-07-02 00:00 UTC, rgommers commented
I'm fine with leaving it in till 1.3.0

2018-07-05 14:13 UTC, Atcold commented
Fixed, @rgommers.

2018-07-05 19:04 UTC, rgommers commented
@Atcold that didn't adjust the message to say `1.3.0` instead of `1.2.0`, could you please do that?

2018-07-07 11:20 UTC, Atcold commented
Done.

2018-07-07 15:36 UTC, merged

2018-07-07 15:36 UTC, rgommers commented
Merged, thanks @Atcold