DOC add sections to overview in scipy.stats
scipy/scipy pull request #9062
Opened 2018-07-20 19:18 UTC by chrisb83

The overview of the module `scipy.stats` is hard to read in my view: https://docs.scipy.org/doc/scipy/reference/stats.html. 

I tried to group the functions to give a better overview. This is an initial proposal, probably there are a lot of other ways to structure it, feedback welcome.

2018-07-20 23:20 UTC, rgommers requested changes
Good idea. Just a few minor comments

2018-07-20 23:20 UTC, rgommers commented on scipy/stats/__init__.py
> +scipy.stats.mstats which work for masked arrays.
single backticks around `scipy.stats.mstats` should turn that into a link

2018-07-20 23:20 UTC, rgommers commented on scipy/stats/__init__.py
> +In the sequel, an overview of statistical functions is given.
"In the sequel" sounds a bit odd to me, maybe just "Below"?

2018-07-23 21:57 UTC, chrisb83 commented
@rgommers done, i addressed your comments.

2018-07-24 01:18 UTC, rgommers approved these changes

2018-07-24 01:18 UTC, merged

2018-07-24 01:18 UTC, rgommers commented
Merged, thanks @chrisb83