FIX: AIX compilation issue with NAN and INFINITY
scipy/scipy pull request #9374
Opened 2018-10-12 08:52 UTC by ayappanec

The definition of NAN and INFINITY in AIX doesn't make it qualify as constant literals.
After the preprocessing step, the definitions are

NAN ---> (*((float )(&_SQNAN)))
INFINITY ----> (((float *)(&_SINFINITY)))

Because of this, the compilation fails
scipy/special/cephes/dd_real.c:70:40: error: initializer element is not constant
     const double2 DD_C_NAN = _DD_REAL_INIT(NAN, NAN);
                                                                             ^
    scipy/special/cephes/dd_real.c:33:32: note: in definition of macro '_DD_REAL_INIT'
     #define _DD_REAL_INIT(A, B)  {{A, B}}
                                                       ^
scipy/special/cephes/dd_real.c:71:40: error: initializer element is not constant
     const double2 DD_C_INF = _DD_REAL_INIT(INFINITY, INFINITY);
                                                                           ^
    scipy/special/cephes/dd_real.c:33:32: note: in definition of macro '_DD_REAL_INIT'
     #define _DD_REAL_INIT(A, B)  {{A, B}}
                                                       ^

2018-10-15 11:42 UTC, ayappanec commented
The Travis CI build failure is unrelated to this.

2018-10-16 06:29 UTC, ayappanec commented
Anybody watching this ? Can someone look into this ?

2018-10-17 22:52 UTC, pvanmulbregt commented
@ayappanec Is the definition of `NAN ---> (*((float )(&_SQNAN)))` specific to one compiler on AIX or all versions of all compilers on AIX?

2018-10-18 06:17 UTC, ayappanec commented
Both GCC & XLC has this issue. 
NAN/INFINITY definition comes from one of the standard header /usr/include/math.h in AIX. So no matter what compiler we use ,this is going to get picked up.

2018-10-18 11:57 UTC, pvanmulbregt requested changes
Can you add a one line comment to the h file to record why AIX is special here? E.g. Something like
NAN not const in AIX's math.h

2018-10-18 12:36 UTC, ayappanec commented
Thanks. I just added the comment.

2018-10-18 12:46 UTC, pvanmulbregt approved these changes
Thanks for the quick change.

2018-10-18 15:01 UTC, ayappanec commented
The CI failures are not related to this PR

2018-10-20 21:20 UTC, merged

2018-10-22 06:29 UTC, ayappanec commented
Thanks @pvanmulbregt for the support.