ENH: Add Fiedler and fiedler companion to special matrices
scipy/scipy pull request #9522
Opened 2018-11-22 22:40 UTC by ilayn

These are in my opinion both interesting enough due to their properties and also once in a while useful to have. Especially the companion is better conditioned than the regular Frobenius companion which we might use for root finding when used with `matrix_balance` (which is also an active research area).

2019-01-27 12:01 UTC, ilayn commented
In case there are no objections, I would like to merge this in a few days.

2019-02-07 17:56 UTC, ilayn commented
@larsoner Can you help me understand what the problem is with the error here? After See Also is it tripping because it sees the first dot as a second reference ?

2019-03-01 07:56 UTC, rgommers requested changes
looks good, just some minor things to fix

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +    """Returns a symmetric Fiedler matrix ``F[i, j] = np.abs(a[i] - a[j])``
Better to move the math to the next paragraph. I'm not sure this works.

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +
remove extra blank line

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +    .. versionadded:: 1.13.0
This belongs under `Notes`, that will be the issue you were seeing with the doc build

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +        leading coefficient. For N < 2, an empty array is returned.
maybe put double backticks around `N < 2`

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +    Similar to `scipy.linalg.companion` the leading coefficient should be
don't need `scipy.linalg`, `companion` will resolve

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +
same here, missing `Notes` header

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +    .. versionadded:: 1.13.0
1.3.0 not 1.13.0

2019-03-01 07:56 UTC, rgommers commented on scipy/linalg/special_matrices.py
> +    .. versionadded:: 1.13.0
and 1.3.0 not 1.13.0

2019-03-10 00:55 UTC, rgommers approved these changes

2019-03-10 01:04 UTC, merged

2019-03-10 01:04 UTC, rgommers commented
Allright, all green and no more comments, in it goes. Thanks @ilayn