MAINT: Allow None tolerances in least_squares
scipy/scipy pull request #9796
Opened 2019-02-09 16:25 UTC by nmayorov

Fixes #7632

The tolerance logic was changes as follows:

1. `None` is accepted and it is converted to 0.
2. Tolerances are not bounded by `EPS`. But a warning is issued when it is less that `EPS`, unless `None` was passed (we consider this as a clear intent and don't warn about disabled tolerance check).

2019-02-22 01:32 UTC, rgommers requested changes
Looks like a good improvement to me. Would be nice to have a basic smoke test at least for each of the tolerances being None

2019-02-22 01:32 UTC, rgommers commented on scipy/optimize/_lsq/least_squares.py
> +                 "disables the corresponding termination condtion."
typo: condtion

2019-02-24 12:02 UTC, nmayorov commented
@rgommers --- thanks, the test was added.

2019-02-28 21:42 UTC, rgommers approved these changes

2019-02-28 21:44 UTC, rgommers commented
the test is failing because of `RuntimeWarning: invalid value encountered in true_divide`

2019-03-01 00:00 UTC, nmayorov commented
I tried to fix the problem, but I'm not very happy with the solution. There was a good reason to require each tolerance to be higher than `EPS`. Considering that the tests are strong I think my changes are safe and disabling 1 or 2 tolerances will work as expected.

2019-03-01 00:02 UTC, nmayorov commented
I tried to fix the problem, but I'm not very happy with the solution. There was a good reason to require each tolerance to be higher than `EPS`. Considering that the tests are strong I think my changes are safe and disabling 1 or 2 tolerances will work as expected. However, disabling all 3 creates potentially too many pathological situations and I'm quite certain it's best not to allow it.

2019-03-01 00:12 UTC, rgommers commented
> However, disabling all 3 creates potentially too many pathological situations and I'm quite certain it's best not to allow it.

Yes that makes sense. Optimization completely without any tolerances is a bit too weird.

2019-03-01 05:31 UTC, rgommers commented
Almost there, one docstring related failure:
```
/home/travis/build/scipy/scipy/tools/../doc/source/tutorial/optimize.rst
------------------------------------------------------------------------
File "doc/source/tutorial/optimize.rst", line 797, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/optimize.rst
Failed example:
    res = least_squares(fun, x0, jac=jac, bounds=(0, 100), args=(u, y), verbose=1)
Expected:
    `ftol` termination condition is satisfied.
    Function evaluations 130, initial cost 4.4383e+00, final cost 1.5375e-04, first-order optimality 4.92e-08.
Got:
    `ftol` termination condition is satisfied.
    Function evaluations 131, initial cost 4.4383e+00, final cost 1.5375e-04, first-order optimality 4.52e-08.
```
the PyPy failure is unrelated

2019-03-01 05:48 UTC, ev-br commented
The refguide-check failure shows that the verbose=True output is meant for a human user, hence a bit too brittle for the automated checking.

I suggest to just add a `# may vary` comment to disable that particular check.

2019-03-02 07:22 UTC, rgommers commented
okay all happy with the `#may vary` except for the unrelated PyPy failure, merging. thanks @nmayorov, @ev-br

2019-03-02 07:22 UTC, merged

2019-03-03 09:25 UTC, nmayorov commented
@rgommers @ev-br thanks for helping to finish this.