Doc integrate tutorial solve ivp
scipy/scipy pull request #9847
Opened 2019-02-19 19:57 UTC by jakobjakobson18

Can you guys take a look at it? Especially regarding the length and beginner friendliness of the changes. That would be great. Thanks.

2019-02-24 20:22 UTC, StanczakDominik requested changes
I think I caught a hitch in the proposed changes:

2019-02-24 20:22 UTC, StanczakDominik commented on doc/source/tutorial/integrate.rst
> +intervall. The initial conditions are therefore given in the first output row.
```suggestion
function defining the derivative, *fprime*, the time span `[t_start, t_end]`
and the initial conditions vector, *y0*. :obj:`solve_ivp` outputs an object
whose *y* field is an array with consecutive solution values as columns.
The initial conditions are therefore given in the first output column.
```

Re: rows vs columns, this at least seems to be what https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html currently suggests!

2019-02-26 14:45 UTC, MatthewFlamm commented
Should the tutorial be comprehensive in showcasing the major features of `solve_ivp` like event handling and dense output?  The event functionality is already handled in the docstring of solve_ivp, but you could consider how to add a short example for `dense_output=True`, which is only touched on briefly in the examples in the docstring.

One suggestion is to introduce `t_eval` before the new method with specified Jacobian.  You could then provide an alternative method for evaluating at those times (or a specific time) by using `dense_output=True`.

2019-02-26 21:03 UTC, jakobjakobson18 commented
> Should the tutorial be comprehensive in showcasing the major features of `solve_ivp` like event handling and dense output? The event functionality is already handled in the docstring of solve_ivp, but you could consider how to add a short example for `dense_output=True`, which is only touched on briefly in the examples in the docstring.
> 
> One suggestion is to introduce `t_eval` before the new method with specified Jacobian. You could then provide an alternative method for evaluating at those times (or a specific time) by using `dense_output=True`.

Personally I would see the purpose of the tutorial as a description of a problem and a possible solution. The problem was and is still given and a possible solution is the `solve_ivp` function. If the user recognizes her problem to be similar as the given one and understands that she can use solve_ivp to solve it, the tutorial would be well written for me. But that's up to discussion.

If the `dense_output=True` is only touched briefly in the docstrings, I guess the docstring of the function would be a better place to give explicit examples.

2019-02-26 22:49 UTC, rgommers commented
>  If the user recognizes her problem to be similar as the given one and understands that she can use solve_ivp to solve it, the tutorial would be well written for me. But that's up to discussion.

Yes, the tutorial does not need to be comprehensive, that's for the docstrings (which get turned into the "reference guide" API docs). I have no strong opinion in this case, but the point of the tutorials is to give a good overview of the capabilities to especially the newer users, typically with longer worked examples of common use cases.

It's also true of course that there are many important functions that aren't discussed at all in the tutorial - we'd like to grow the tutorial, but it's a lot of work and it's not a hard requirement to add tutorial content for new features (although it's appreciated of course).

2019-03-01 21:06 UTC, jakobjakobson18 commented
> > If the user recognizes her problem to be similar as the given one and understands that she can use solve_ivp to solve it, the tutorial would be well written for me. But that's up to discussion.
> 
> Yes, the tutorial does not need to be comprehensive, that's for the docstrings (which get turned into the "reference guide" API docs). I have no strong opinion in this case, but the point of the tutorials is to give a good overview of the capabilities to especially the newer users, typically with longer worked examples of common use cases.
> 
> It's also true of course that there are many important functions that aren't discussed at all in the tutorial - we'd like to grow the tutorial, but it's a lot of work and it's not a hard requirement to add tutorial content for new features (although it's appreciated of course).

All right, I'll try to get it done tomorrow. But I actually got a question first. In the following tutorial example the `dense_output` did not make any difference (tested on SciPy 1.2.1).

```python3
from scipy.integrate import solve_ivp
from scipy.special import gamma, airy
y1_0 = +1 / 3**(2/3) / gamma(2/3)
y0_0 = -1 / 3**(1/3) / gamma(1/3)
y0 = [y0_0, y1_0]
def func(t, y):
    return [t*y[1],y[0]]
t_span = [0, 4]
sol1 = solve_ivp(func, t_span, y0, dense_output = True)
sol2 = solve_ivp(func, t_span, y0, dense_output = False)
```

The solutions are given below:
```bash
>>> sol1.y
array([[-0.2588194 , -0.25709812, -0.15275702, -0.06318633, -0.02763101,
        -0.01110407, -0.00215684,  0.00411502],
       [ 0.35502805,  0.328952  ,  0.12801343,  0.04296455,  0.01710117,
         0.00714538,  0.00371189,  0.00410178]])
>>> sol2.y
array([[-0.2588194 , -0.25709812, -0.15275702, -0.06318633, -0.02763101,
        -0.01110407, -0.00215684,  0.00411502],
       [ 0.35502805,  0.328952  ,  0.12801343,  0.04296455,  0.01710117,
         0.00714538,  0.00371189,  0.00410178]])
```

Did I miss again something?

Regards

2019-03-02 11:10 UTC, MatthewFlamm commented
Using `dense_output=True` returns the `sol` attribute which lets you evaluate the solution at arbitrary times.  In your example, you can do `sol1.sol(2)` to evaluate at t=2.

2019-03-06 20:56 UTC, StanczakDominik reviewed
A few minor text suggestions!

2019-03-06 20:56 UTC, StanczakDominik commented on doc/source/tutorial/integrate.rst
> +any arbitrary time point within the time span can be calculated.
```suggestion
any arbitrary time point within the time span can be calculated via interpolation.
```

2019-03-06 20:56 UTC, StanczakDominik commented on doc/source/tutorial/integrate.rst
> +If the jacobian matrix of function is known it can can of passed to the `solve_ivp`
```suggestion
If the jacobian matrix of function is known, it can be passed to the `solve_ivp`
```

2019-03-06 20:56 UTC, StanczakDominik commented on doc/source/tutorial/integrate.rst
> +to the airy function. To minimize this deviation relative and absolute
```suggestion
to the airy function. To minimize this deviation, relative and absolute
```

2019-03-06 20:56 UTC, StanczakDominik commented on doc/source/tutorial/integrate.rst
> +offers two possibilites that can also be used complementary. By passing the `t_eval`
```suggestion
offers two possibilites that can also be used complementarily. By passing the `t_eval`
```

2019-06-15 09:40 UTC, drhagen commented
This looks great to me. I support merging this.

2019-06-15 10:03 UTC, rgommers commented
thanks for the review @drhagen!

looks like this was good to go for a while when we ran out of reviewer time. there's some unhappy CI, I'll have a look at that.

> @jakobjakobson13 wants to merge 19 commits into `scipy:master` from `unknown repository`

weird, I think this PR came from @jakobjakobson13's fork of this repo (which still exists) but the branch it came from was deleted

2019-06-15 10:06 UTC, rgommers commented
some of the failures are real:
```
=========================================================================
/home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
=========================================================================
/home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
-------------------------------------------------------------------------
File "doc/source/tutorial/integrate.rst", line 461, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    print("sol1.t:    {}".format(sol1.t))
Expected:
    sol.t:          [0.         0.10097672 1.04643602 1.86341289 2.45798743 2.99814154
     3.54800133 4.        ]
Got:
    sol1.t:    [0.         0.10097672 1.04643602 1.86341289 2.45798743 2.99814154
     3.54800133 4.        ]
File "doc/source/tutorial/integrate.rst", line 469, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    print("sol1.y[1]: {}".format(sol1.y[1]))
Expected nothing
Got:
    sol1.y[1]: [0.35502805 0.328952   0.12801343 0.04296455 0.01710117 0.00714538
     0.00371189 0.00410178]
File "doc/source/tutorial/integrate.rst", line 470, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    print("airy(sol.t):  {}".format(airy(sol1.t))
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst[64]>", line 1
        print("airy(sol.t):  {}".format(airy(sol1.t))
                                                    ^
    SyntaxError: unexpected EOF while parsing
File "doc/source/tutorial/integrate.rst", line 482, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    print("sol2.y[1]: {}".format(sol2.y[1]))
Expected nothing
Got:
    sol2.y[1]: [0.35502805 0.351446   0.31791417 0.28514662 0.25295646 0.22162462
     0.19133491 0.16203676 0.13363647 0.11127801 0.09180607 0.07705457
     0.06422892 0.05321708 0.04383569 0.03590249 0.02924155 0.02368706
     0.01908572 0.01529826 0.01219994 0.00968053 0.00764377 0.00600652
     0.00469766 0.0036477  0.0028018  0.00212681 0.00159352 0.00117685
     0.00095159]
File "doc/source/tutorial/integrate.rst", line 483, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    print("airy(sol2.t)[0]: {}".format(airy(sol2.t)[0]))
Expected:
    sol2.y[1]:      [0.35502805 0.22162462 0.09180607 0.03590249 0.01219994 0.0036477
     0.00095159]
    airy(sol2.t)[0]: [0.35502805 0.22162462 0.09180606 0.03590248 0.01219993 0.00364769
     0.00095156]
Got:
    airy(sol2.t)[0]: [0.35502805 0.351446   0.31791417 0.28514662 0.25295646 0.22162462
     0.19133491 0.16203675 0.13363647 0.111278   0.09180606 0.07705456
     0.06422892 0.05321708 0.04383569 0.03590248 0.02924155 0.02368705
     0.01908572 0.01529826 0.01219993 0.00968052 0.00764377 0.00600651
     0.00469765 0.00364769 0.00280179 0.00212679 0.0015935  0.00117682
     0.00095156]
File "doc/source/tutorial/integrate.rst", line 495, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    t = np.linspace(t_start, t_end, 50)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst[70]>", line 1, in <module>
        t = np.linspace(t_start, t_end, 50)
    NameError: name 't_start' is not defined
File "doc/source/tutorial/integrate.rst", line 496, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    sol3 = solve_ivp(func, t_span, y0, t_eval=t)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst[71]>", line 1, in <module>
        sol3 = solve_ivp(func, t_span, y0, t_eval=t)
    NameError: name 't' is not defined
/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/integrate/_ivp/common.py:41: UserWarning: The following arguments have no effect for a chosen solver: `dense_ouput`.
  .format(", ".join("`{}`".format(x) for x in extraneous)))
File "doc/source/tutorial/integrate.rst", line 504, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    print("sol4.sol(2)[1]: {}".format(sol4.sol(2)[1])
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst[73]>", line 1
        print("sol4.sol(2)[1]: {}".format(sol4.sol(2)[1])
                                                        ^
    SyntaxError: unexpected EOF while parsing
File "doc/source/tutorial/integrate.rst", line 515, in /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst
Failed example:
    sol5 = solve_ivp(func, [t_start, t_end], y0, method='Radau', jac=gradient)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest /home/travis/build/scipy/scipy/tools/../doc/source/tutorial/integrate.rst[75]>", line 1, in <module>
        sol5 = solve_ivp(func, [t_start, t_end], y0, method='Radau', jac=gradient)
    NameError: name 't_start' is not defined
```

@jakobjakobson13 would you be able to restore your branch and fix the errors? I promise to review and merge quickly:)

2019-06-17 08:23 UTC, jakobjakobson13 commented
See #10315

2019-08-04 11:49 UTC, pv commented
Superceded by #10315

2019-08-04 11:49 UTC, closed without merging